Repository replicatedhq/kots, pull requests merged in 2021-11, with the labels that each got.

#2288 38977: Fix analysis filtering
  web/src/components/troubleshoot/AnalyzerInsights.jsx
Labels: type::enhancement, team::day2

#2296 Include weave logs in support bundle
  pkg/supportbundle/defaultspec/spec.yaml
Labels: type::chore

#2310 include a security context for the restore-db container in kotsadm
  pkg/kotsadm/objects/kotsadm_objects.go
Labels: type::bug

#2313 increase readiness probe timeout to 5s to match liveness probe
  pkg/kotsadm/objects/postgres_objects.go
Labels: type::bug, bug::normal

#2351 fix: make strict security contexts optional
  cmd/kots/cli/admin-console-upgrade.go
  cmd/kots/cli/install.go
  pkg/kotsadm/main.go
  pkg/kotsadm/objects/distribution_objects.go
  pkg/kotsadm/objects/kotsadm_objects.go
  pkg/kotsadm/objects/minio_objects.go
  pkg/kotsadm/objects/postgres_objects.go
  pkg/kotsadm/objects/shared_object_config.go
  pkg/kotsadm/types/deployoptions.go
  pkg/kotsadm/types/upgradeoptions.go
Labels: type::bug

#2354 add chart yaml for empty sub charts
  pkg/base/helm.go
Labels: type::bug, bug::normal

#2367 Remove the usage of the temporary regression branch and start using m…
  .github/workflows/regression.yaml
Labels: type::chore

#2372 Fix for constant re-rending page whenever there was a ping. This was…
  .github/workflows/regression.yaml
  web/src/Root.jsx
  web/src/components/gitops/GitOpsRepoDetails.jsx
Labels: type::feature

#2373 Fixing recursive merge
  pkg/base/replicated.go
Labels: @actions/safe-to-test
