Repository replicatedhq/kots, pull requests merged in 2021-12, with the labels that each got.

#2378 Copy original base before writing midstream
  pkg/pull/pull.go
Labels: type::bug, bug::normal

#2368 config export command
  cmd/kots/cli/get-apps.go
  cmd/kots/cli/get-backups.go
  cmd/kots/cli/get-config.go
  cmd/kots/cli/get-restores.go
  cmd/kots/cli/get.go
Labels: type::feature

#2384 Add multi-namespace-yeti-redis-registry secret to redis-test namespace
  .github/workflows/build-test.yaml
Labels: type::chore

#2386 centralize encryption key management
  kotskinds/apis/kots/v1beta1/identityconfig_types.go
  pkg/airgap/airgap.go
  pkg/airgap/update.go
  pkg/apiserver/bootstrap.go
  pkg/base/templates.go
  pkg/config/config.go
  pkg/crypto/aes.go
  pkg/gitops/gitops.go
  pkg/handlers/config.go
  pkg/handlers/identity.go
  pkg/identity/deploy.go
  pkg/identity/deploy/deploy.go
  pkg/identity/deploy/dex.go
  pkg/identity/deploy/postgres.go
  pkg/kotsadm/secrets.go
  pkg/kotsadmidentity/identityconfig.go
  pkg/kotsadmupstream/upstream.go
  pkg/kotsutil/kots.go
  pkg/midstream/identity.go
  pkg/midstream/write.go
  pkg/online/online.go
  pkg/pull/pull.go
  pkg/render/render.go
  pkg/rewrite/rewrite.go
  pkg/store/kotsstore/registry_store.go
  pkg/template/builder.go
  pkg/template/config_context.go
  pkg/template/config_context_test.go
  pkg/template/identity_context.go
  pkg/template/identity_context_test.go
  pkg/upstream/fetch.go
  pkg/upstream/replicated.go
  pkg/upstream/replicated_test.go
  pkg/upstream/write.go
Labels: type::chore

#2394 Branch rename master -> main
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/alpha.yaml
  .github/workflows/codespaces.yaml
  .github/workflows/nightly.yaml
  CONTRIBUTING.md
  README.md
  design/docs/installing/README.md
  design/docs/proposals/object-store.md
  pkg/template/license_context.go
  pkg/template/static_context.go
Labels: type::chore

#2395 explicitly do not decrypt passwords shown on the config page
  pkg/base/replicated.go
  pkg/base/templates.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/crypto/aes_test.go
  pkg/handlers/config.go
  pkg/kotsadmconfig/config.go
  pkg/render/render.go
  pkg/template/builder.go
  pkg/template/config_context.go
  pkg/template/config_context_test.go
  pkg/upstream/replicated.go
Labels: type::chore

#2397 Validate kots pull fix
  .github/workflows/alpha.yaml
  .github/workflows/build-test.yaml
  .github/workflows/release.yaml
  pkg/image/builder.go
  pkg/pull/pull.go
Labels: type::bug, bug::normal

#2398 More fixes for master branch renaming to main
  .github/workflows/build-test.yaml
Labels: type::chore

#2399 Skaffold profile to enable delve
  Makefile.build
  hack/CONTRIBUTING.md
  hack/dev/Dockerfile.skaffold
  hack/dev/entrypoint.sh
  skaffold.yaml
Labels: type::chore

#2400 Pin testim cli to 3.206.0 to fix flakey tests
  .github/workflows/build-test.yaml
Labels: type::chore

#2406 add a '--decrypt' flag to 'kubectl kots get config'
  cmd/kots/cli/get-config.go
Labels: type::feature

#2405 Write helm midstream with HelmChart namespace
  pkg/base/base.go
  pkg/base/base_test.go
  pkg/base/helm.go
  pkg/base/helm_test.go
  pkg/base/replicated.go
  pkg/pull/pull.go
  pkg/rewrite/rewrite.go
  pkg/tests/pull/cases/configcontext/testcase.yaml
  pkg/tests/pull/cases/configcontext/wantResults/overlays/midstream/charts/test-chart/secret.yaml
  pkg/tests/pull/cases/configcontext/wantResults/overlays/midstream/secret.yaml
  pkg/tests/pull/cases/simple/testcase.yaml
  pkg/tests/pull/cases/subcharts/testcase.yaml
  pkg/tests/pull/cases/subcharts/wantResults/overlays/midstream/charts/chart/charts/subchart-1/secret.yaml
  pkg/tests/pull/cases/subcharts/wantResults/overlays/midstream/charts/chart/charts/subchart-2/charts/subsubchart/secret.yaml
  pkg/tests/pull/cases/subcharts/wantResults/overlays/midstream/charts/chart/charts/subchart-2/secret.yaml
  pkg/tests/pull/cases/subcharts/wantResults/overlays/midstream/charts/chart/secret.yaml
  pkg/tests/pull/cases/subcharts/wantResults/overlays/midstream/secret.yaml
  pkg/tests/pull/pull_test.go
Labels: type::bug, bug::normal

#2413 chore: update go to 1.17
  .devcontainer/devcontainer.json
  .github/workflows/alpha.yaml
  .github/workflows/build-test.yaml
  .github/workflows/nightly.yaml
  .github/workflows/release.yaml
  actions/copy-assets/Dockerfile
  actions/copy-assets/go.mod
  go.mod
  hack/dev/Dockerfile.skaffoldcache
  kurl_proxy/Dockerfile.skaffold
  kurl_proxy/go.mod
Labels: type::chore
