Repository replicatedhq/kots, pull requests merged in 2021-10, with the labels that each got.

#2177 Automated Kots Image Dependency Tag Update
  .image.env
  pkg/image/constants.go
Labels: automated-pr, images

#2228 fix: auto-deploy app when there's no config and preflights are skipped
  pkg/airgap/airgap.go
  pkg/online/online.go
Labels: kind/bug

#2230 Delete old support bundle spec
  support-bundle.yaml
Labels: kind/chore

#2282 Update styles of support bundle rows
  pkg/handlers/troubleshoot.go
  web/src/components/troubleshoot/SupportBundleList.jsx
  web/src/components/troubleshoot/SupportBundleRow.jsx
  web/src/images/main_spritesheet.svg
  web/src/scss/utilities/icons.scss
Labels: type::enhancement

#2281 Don't fail weave report if no files collected
  go.mod
  go.sum
  pkg/supportbundle/defaultspec/spec.yaml
Labels: bug::normal, team::day2
