Repository replicatedhq/kots, pull requests merged in 2021-09, with the labels that each got.

#1753 Run tests on forks
  .github/workflows/build-test.yaml
  CONTRIBUTING.md
Labels: @actions/safe-to-test

#2146 Replaced hard coded image tags in kotsadm
  cmd/imagedeps/main.go
  cmd/imagedeps/testdata/basic/constants.go
  cmd/imagedeps/testdata/filter-github/constants.go
  cmd/imagedeps/testdata/postgres/constants.go
  cmd/imagedeps/testdata/with-overrides/constants.go
  pkg/image/image.go
  pkg/image/image_test.go
  pkg/kotsadm/objects/images.go
  pkg/kotsadm/objects/postgres_objects.go
Labels: wip

#2158 Automated Kots Image Dependency Tag Update
  .image.env
  pkg/image/constants.go
Labels: automated-pr, images

#2185 chore: add slack notifications for nightly regression tests
  .github/workflows/release.yaml
Labels: kind/chore

#2162 Pull Request Guidelines
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: kind/documentation

#2216 fix: append additional files correctly for sub charts
  pkg/base/helm.go
Labels: kind/bug

#2219 Explain usage of github pat in action
  .github/workflows/nightly.yaml
Labels: kind/chore

#2218 Clean up actions
  .github/dependabot.yml
  actions/containers/Dockerfile
  actions/containers/action.yml
  actions/containers/entrypoint.sh
Labels: kind/chore

#2217 Build Dex image from dockerfile
  Makefile
  deploy/Dockerfile.dex
Labels: kind/chore

#2213 Unify troubleshoot specs
  pkg/supportbundle/analyze.go
  pkg/supportbundle/defaultspec/embed.go
  pkg/supportbundle/defaultspec/spec.yaml
  pkg/supportbundle/spec.go
  pkg/supportbundle/spec_test.go
  pkg/supportbundle/supportbundle.go
Labels: kind/chore
