Repository replicatedhq/kots, pull requests merged in 2022-08, with the labels that each got.

#3014 fix: remove specific namespaces from backup if wildcard is specified
  pkg/kotsadmsnapshot/backup.go
  pkg/kotsadmsnapshot/backup_test.go
Labels: type::bug, bug::normal

#3021 check is-helm-managed after login
  web/src/Root.jsx
  web/src/components/SecureAdminConsole.jsx
Labels: type::bug, bug::normal, team::orange

#3023 E2E deps should fail on error
  e2e/hack/deps.sh
Labels: type::chore

#3024 Implement HTTPS_PROXY template function
  pkg/template/static_context.go
  pkg/template/static_context_test.go
Labels: type::feature, team::orange

#3020 Version history page in helm mode fixes
  pkg/api/downstream/types/types.go
  pkg/api/downstream/types/types_test.go
  pkg/handlers/app.go
  pkg/helm/cache.go
  pkg/helm/updates.go
  pkg/store/kotsstore/downstream_store.go
  pkg/store/kotsstore/version_store.go
  web/src/components/apps/AppVersionHistory.jsx
  web/src/components/apps/AppVersionHistoryRow.jsx
  web/src/components/apps/DashboardVersionCard.jsx
Labels: type::bug, bug::normal

#3018 render help text if it exists for ConfigFileInput
  web/src/components/config_render/ConfigFileInput.jsx
  web/src/scss/components/config-render/config-base-styles.scss
Labels: type::bug, bug::normal

#3029 use port 10250 when a certificate is available for mTLS
  pkg/kurl/kurl_nodes.go
Labels: type::bug, bug::regression

#3026 Add default kots collectors and analyzers when running support bundle from UI
  pkg/airgap/airgap.go
  pkg/app/types/app.go
  pkg/app/types/helm_app.go
  pkg/app/types/types.go
  pkg/handlers/app.go
  pkg/handlers/helm.go
  pkg/handlers/preflight.go
  pkg/handlers/troubleshoot.go
  pkg/helm/cache.go
  pkg/helm/charts.go
  pkg/kotsutil/kots.go
  pkg/online/online.go
  pkg/operator/client/client.go
  pkg/operator/operator.go
  pkg/preflight/preflight.go
  pkg/redact/app.go
  pkg/render/helper/appfile.go
  pkg/supportbundle/helm.go
  pkg/supportbundle/spec.go
  pkg/supportbundle/supportbundle.go
Labels: type::feature

#3031 only merge repl tmpl values on config change in helm managed mode
  kotskinds/apis/kots/v1beta1/helmchart_types.go
  kotskinds/apis/kots/v1beta1/helmchart_types_test.go
  pkg/handlers/config.go
  web/src/components/shared/modals/HelmDeployModal.jsx
Labels: type::bug, bug::normal

#3004 Copy the kurl kotsadm addon files into kots
  .github/actions/kurl-addon-kots-publisher/.gitignore
  .github/actions/kurl-addon-kots-publisher/action.yml
  .github/actions/kurl-addon-kots-publisher/dist/index.js
  .github/actions/kurl-addon-kots-publisher/index.js
  .github/actions/kurl-addon-kots-publisher/package-lock.json
  .github/actions/kurl-addon-kots-publisher/package.json
  .github/workflows/kurl-addon-kots-publish.yaml
  .github/workflows/release.yaml
  deploy/kurl/kotsadm/categories.json
  deploy/kurl/kotsadm/template/base/Manifest
  deploy/kurl/kotsadm/template/base/deployment/kotsadm-airgap.yaml
  deploy/kurl/kotsadm/template/base/deployment/kotsadm-deployment.yaml
  deploy/kurl/kotsadm/template/base/deployment/patches/api-prometheus.yaml
  deploy/kurl/kotsadm/template/base/deployment/tmpl-kotsadm-cacerts.yaml
  deploy/kurl/kotsadm/template/base/deployment/tmpl-kotsadm-installation-id.yaml
  deploy/kurl/kotsadm/template/base/deployment/tmpl-kotsadm-proxy.yaml
  deploy/kurl/kotsadm/template/base/host-preflight.yaml
  deploy/kurl/kotsadm/template/base/install.sh
  deploy/kurl/kotsadm/template/base/join-rbac.yaml
  deploy/kurl/kotsadm/template/base/kotsadm-postgres-rename-pvc.yaml
  deploy/kurl/kotsadm/template/base/kotsadm.yaml
  deploy/kurl/kotsadm/template/base/kurl-proxy/kustomization.yaml
  deploy/kurl/kotsadm/template/base/kurl-proxy/rbac.yaml
  deploy/kurl/kotsadm/template/base/kurl-proxy/tmpl-deployment.yaml
  deploy/kurl/kotsadm/template/base/kurl-proxy/tmpl-service.yaml
  deploy/kurl/kotsadm/template/base/kustomization.yaml
  deploy/kurl/kotsadm/template/base/postgres.yaml
  deploy/kurl/kotsadm/template/base/statefulset/kotsadm-airgap.yaml
  deploy/kurl/kotsadm/template/base/statefulset/kotsadm-statefulset.yaml
  deploy/kurl/kotsadm/template/base/statefulset/patches/api-prometheus.yaml
  deploy/kurl/kotsadm/template/base/statefulset/patches/s3-migration.yaml
  deploy/kurl/kotsadm/template/base/statefulset/tmpl-kotsadm-cacerts.yaml
  deploy/kurl/kotsadm/template/base/statefulset/tmpl-kotsadm-installation-id.yaml
  deploy/kurl/kotsadm/template/base/statefulset/tmpl-kotsadm-proxy.yaml
  deploy/kurl/kotsadm/template/base/tmpl-secret-api-encryption.yaml
  deploy/kurl/kotsadm/template/base/tmpl-secret-authstring.yaml
  deploy/kurl/kotsadm/template/base/tmpl-secret-cluster-token.yaml
  deploy/kurl/kotsadm/template/base/tmpl-secret-dex-postgres.yaml
  deploy/kurl/kotsadm/template/base/tmpl-secret-password.yaml
  deploy/kurl/kotsadm/template/base/tmpl-secret-postgres.yaml
  deploy/kurl/kotsadm/template/base/tmpl-secret-s3.yaml
  deploy/kurl/kotsadm/template/base/tmpl-secret-session.yaml
  deploy/kurl/kotsadm/template/base/tmpl-start-kotsadm-web.sh
  deploy/kurl/kotsadm/template/generate.sh
  deploy/kurl/kotsadm/template/testgrid/k8s-docker.yaml
Labels: type::feature

#3036 Use defaul collectors and analyzers, if support bundle spec cannot be downloaded
  pkg/supportbundle/supportbundle.go
Labels: type::bug, bug::normal

#3037 Show password rules
  web/src/components/modals/ChangePasswordModal/ChangePasswordForm.jsx
  web/src/components/shared/forms/InputField.jsx
  web/src/scss/components/shared/forms/InputField.scss
Labels: type::feature

#3040 Store Helm config values in ConfigValues kind
  kotskinds/apis/kots/v1beta1/helmchart_types.go
  kotskinds/apis/kots/v1beta1/helmchart_types_test.go
  pkg/app/types/helm_app.go
  pkg/handlers/config.go
  pkg/handlers/config_test.go
  pkg/handlers/helm.go
  pkg/helm/cache.go
  pkg/helm/charts.go
  pkg/helm/config_values.go
  pkg/helm/helm.go
  pkg/helm/helm_test.go
  pkg/kotsutil/kots.go
  pkg/reporting/app.go
Labels: type::bug, bug::normal

#3025 feat: add support for alias field in helm chart dependencies
  pkg/base/helm.go
  pkg/base/helm_test.go
  pkg/tests/pull/cases/subchart-alias/upstream/chart-0.1.0.tgz
  pkg/tests/pull/cases/subchart-alias/wantResults/base/charts/chart/Chart.yaml
  pkg/tests/pull/cases/subchart-alias/wantResults/base/charts/chart/charts/subchart-3/Chart.yaml
  pkg/tests/pull/cases/subchart-alias/wantResults/base/charts/chart/helm-charts/subchart-1/kustomization.yaml
  pkg/tests/pull/cases/subchart-alias/wantResults/overlays/midstream/charts/chart/helm-charts/subchart-1/backup-label-transformer.yaml
  pkg/tests/pull/cases/subchart-alias/wantResults/overlays/midstream/charts/chart/helm-charts/subchart-1/kustomization.yaml
  pkg/tests/pull/cases/subchart-alias/wantResults/overlays/midstream/charts/chart/helm-charts/subchart-1/secret.yaml
  pkg/tests/pull/cases/subchart-alias/wantResults/upstream/chart-0.1.0.tgz
Labels: type::feature

#3049 Node join commands should fail on network issues early to match console output
  pkg/kurl/node_join.go
Labels: bug::normal

#3038 feat: add support for images with tag and digest
  pkg/base/images.go
  pkg/docker/registry/images.go
  pkg/docker/registry/images_test.go
  pkg/image/builder.go
Labels: type::feature

#3051 chore: add validate tag and digest to build-test
  .github/workflows/build-test.yaml
Labels: type::tests

#3047 Miawong/sc 48390/kots edit config layout overlaps left menu
  web/src/Root.jsx
  web/src/components/apps/AppDetailPage.jsx
  web/src/components/apps/Dashboard.jsx
  web/src/components/apps/styles/paragraphs.js
  web/src/components/apps/styles/theme.js
  web/src/features/AppConfig/components/AppConfig.jsx
  web/src/features/AppConfig/components/ConfigInfo.jsx
  web/src/features/AppConfig/styles/index.js
  web/src/scss/components/watches/WatchConfig.scss
  web/src/styles/colors.js
  web/src/styles/common.js
Labels: type::bug, bug::regression

#3057 Require PR labels
  .github/workflows/require-pr-labels.yaml
Labels: type::chore, team::orange

#3056 fix: don't enable gitops until the deploy key is added
  pkg/version/version.go
  web/src/components/apps/AppLicense.jsx
  web/src/components/apps/AppVersionHistory.jsx
  web/src/components/apps/Dashboard.jsx
  web/src/components/apps/DashboardLicenseCard.jsx
  web/src/components/apps/DashboardVersionCard.jsx
  web/src/components/modals/AutomaticUpdatesModal.jsx
  web/src/components/shared/SubNavBar/SubNavBar.jsx
  web/src/components/watches/WatchSidebarItem/KotsSidebarItem.jsx
  web/src/features/AppConfig/components/AppConfig.jsx
  web/src/features/AppConfig/components/ConfigInfo.jsx
  web/src/features/AppVersionHistory/AppVersionHistoryRow.jsx
Labels: type::bug, bug::normal

#3053 add clipboard check to copy command rendering check
  web/src/components/shared/CodeSnippet.jsx
Labels: type::bug, bug::normal, team::orange

#3054 refactor fetchRenderedApplicationTree to use promise.all
  web/src/components/watches/DownstreamWatchVersionDiff.jsx
Labels: type::chore, team::orange

#3041 Default to Helm v3
  pkg/base/helm.go
  pkg/base/helm_test.go
Labels: type::feature

#3055 Trigger kotadm addon generate as part of the kots release process
  .github/workflows/kurl-addon-kots-publish.yaml
Labels: type::feature

#3062 fix: fixes date parsing issue when starting snapshots in firefox
  web/src/components/snapshots/AppSnapshots.jsx
  web/src/components/snapshots/Snapshots.jsx
Labels: type::bug, bug::normal

#3060 Release trigger was using the wrong event type. Switched it from crea…
  .github/workflows/kurl-addon-kots-publish.yaml
Labels: type::feature

#3052 Support images names formatted as docker.io/image:tag
  go.mod
  go.sum
  pkg/base/images.go
  pkg/base/replicated_test.go
  pkg/base/write_images_test.go
  pkg/image/image.go
  pkg/image/image_test.go
  pkg/k8sutil/kustomization.go
  pkg/tests/pull/cases/configcontext/wantResults/overlays/midstream/charts/test-chart/kustomization.yaml
  pkg/tests/pull/cases/configcontext/wantResults/overlays/midstream/kustomization.yaml
  pkg/tests/pull/cases/samechartvariations/wantResults/overlays/midstream/charts/test-chart-release-1/kustomization.yaml
  pkg/tests/pull/cases/samechartvariations/wantResults/overlays/midstream/charts/test-chart-release-2/kustomization.yaml
  pkg/tests/pull/cases/samechartvariations/wantResults/overlays/midstream/charts/test-chart-variation-0/kustomization.yaml
  pkg/tests/pull/cases/samechartvariations/wantResults/overlays/midstream/kustomization.yaml
  pkg/tests/pull/cases/subchart-alias/wantResults/overlays/midstream/charts/chart/charts/subchart-1/kustomization.yaml
  pkg/tests/pull/cases/subchart-alias/wantResults/overlays/midstream/charts/chart/charts/subchart-2/charts/subsubchart/kustomization.yaml
  pkg/tests/pull/cases/subchart-alias/wantResults/overlays/midstream/charts/chart/charts/subchart-2/kustomization.yaml
  pkg/tests/pull/cases/subchart-alias/wantResults/overlays/midstream/charts/chart/charts/subchart-3/kustomization.yaml
  pkg/tests/pull/cases/subchart-alias/wantResults/overlays/midstream/charts/chart/kustomization.yaml
  pkg/tests/pull/cases/subchart-alias/wantResults/overlays/midstream/kustomization.yaml
  pkg/tests/pull/cases/subcharts/wantResults/base/charts/fluent-bit/charts/fluent-bit/templates/clusterrolebinding.yaml
  pkg/tests/pull/cases/subcharts/wantResults/overlays/midstream/charts/chart/charts/subchart-1/kustomization.yaml
  pkg/tests/pull/cases/subcharts/wantResults/overlays/midstream/charts/chart/charts/subchart-2/charts/subsubchart/kustomization.yaml
  pkg/tests/pull/cases/subcharts/wantResults/overlays/midstream/charts/chart/charts/subchart-2/kustomization.yaml
  pkg/tests/pull/cases/subcharts/wantResults/overlays/midstream/charts/chart/kustomization.yaml
  pkg/tests/pull/cases/subcharts/wantResults/overlays/midstream/charts/fluent-bit/charts/fluent-bit/kustomization.yaml
  pkg/tests/pull/cases/subcharts/wantResults/overlays/midstream/charts/fluent-bit/kustomization.yaml
  pkg/tests/pull/cases/subcharts/wantResults/overlays/midstream/kustomization.yaml
  pkg/tests/pull/pull_test.go
  pkg/upstream/push_images.go
  pkg/util/tests.go
Labels: type::bug, bug::normal

#3034 implement deploy logs view for helm managed mode
  pkg/handlers/downstream.go
  pkg/helm/cache.go
  pkg/helm/charts.go
  web/src/components/UploadAirgapBundle.jsx
  web/src/components/apps/AppVersionHistory.jsx
  web/src/components/snapshots/SnapshotDetails.jsx
  web/src/features/AppVersionHistory/AppVersionHistoryRow.jsx
Labels: type::feature

#3063 fix: update helm to resolve CVE-2022-21698 and CVE-2022-27191
  deploy/Dockerfile
  deploy/okteto/okteto-v2.Dockerfile
  deploy/okteto/okteto.Dockerfile
  hack/dev/skaffold.Dockerfile
Labels: type::security

#3066 fix: resolve CVE-2021-44716 in kurl_proxy
  actions/copy-assets/go.mod
  actions/copy-assets/go.sum
  kurl_proxy/go.mod
  kurl_proxy/go.sum
Labels: type::security

#3065 copy updates
  web/src/components/UploadAirgapBundle.jsx
  web/src/components/apps/AppVersionHistory.jsx
  web/src/components/apps/DashboardVersionCard.jsx
  web/src/components/shared/SubNavBar/SubNavBar.jsx
  web/src/components/snapshots/SnapshotDetails.jsx
  web/src/features/AppConfig/components/AppConfig.jsx
  web/src/features/AppVersionHistory/AppVersionHistoryRow.jsx
Labels: type::feature, team::orange

#3067 remove componentWillMount from AppConfig
  web/src/features/AppConfig/components/AppConfig.jsx
Labels: type::chore, team::orange

#3070 fix failing fetch
  web/src/components/apps/Dashboard.jsx
  web/src/features/AppConfig/components/AppConfig.jsx
Labels: type::chore, team::orange

#3073 Create separate workflow for releasing helm chart based on release st…
  .github/workflows/release.yaml
  .github/workflows/tag-helm-chart.yaml
Labels: type::bug, bug::normal

#3064 Include config values in deployment values file
  pkg/app/types/helm_app.go
  pkg/handlers/config.go
  pkg/handlers/helm.go
  pkg/handlers/license.go
  pkg/handlers/update.go
  pkg/helm/cache.go
  pkg/helm/charts.go
  pkg/helm/config_values.go
  pkg/helm/helm.go
  pkg/supportbundle/spec.go
  pkg/supportbundle/supportbundle.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: type::feature

#3079 fix: add isSnapshotSupported to LicenseFieldValue template function
  pkg/template/license_context.go
  pkg/template/license_context_test.go
Labels: type::bug, bug::normal

#3077 refactor Dashboard into SFC
  web/src/components/apps/Dashboard.jsx
Labels: type::chore, team::orange

#3087 Rianfowler/sc 52399/upgrade kots to react 18 9
  web/src/components/apps/Dashboard.jsx
  web/src/features/Dashboard/api/getDashboard.jsx
  web/src/features/Dashboard/api/getDashboard.test.jsx
  web/src/features/Dashboard/index.js
Labels: type::chore, team::orange

#3091 chore: update local-volume-provider image to resolve CVEs
  .image.env
  Makefile
  pkg/image/constants.go
Labels: type::security

#3069 Miawong/sc 55403/improve the gitops ux
  web/src/components/apps/AppGitops.jsx
  web/src/components/apps/DashboardGitOpsCard.jsx
  web/src/components/gitops/GitOpsDeploymentManager.jsx
  web/src/components/gitops/GitOpsRepoDetails.jsx
  web/src/components/gitops/SetupProvider.jsx
  web/src/components/gitops/modals/ConnectionModal.jsx
  web/src/components/gitops/modals/DisableModal.jsx
  web/src/config-ui/subNavConfig.js
  web/src/images/enabled.svg
  web/src/images/not_enabled.svg
  web/src/images/warning.svg
  web/src/scss/components/gitops/GitOpsDeploymentManager.scss
  web/src/scss/components/gitops/GitOpsSettings.scss
  web/src/scss/components/gitops/GitopsPrism.scss
  web/src/scss/utilities/forms.scss
  web/src/scss/utilities/icons.scss
  web/src/scss/utilities/modals.scss
  web/src/styles/common.js
Labels: type::feature

#3095 Revert "Rianfowler/sc 52399/upgrade kots to react 18 9"
  web/src/components/apps/Dashboard.jsx
  web/src/features/Dashboard/api/getDashboard.jsx
  web/src/features/Dashboard/api/getDashboard.test.jsx
  web/src/features/Dashboard/index.js
Labels: type::chore, team::orange

#3096 Revert "refactor Dashboard into SFC"
  web/src/components/apps/Dashboard.jsx
Labels: type::chore, team::orange

#3076 Ability to use image digests in airgap mode
  .github/workflows/build-test.yaml
  cmd/kots/cli/admin-console-push-images.go
  cmd/kots/cli/docker-registry.go
  cmd/kots/cli/root.go
  deploy/okteto/okteto-v2.Dockerfile
  deploy/okteto/okteto.Dockerfile
  e2e/e2e_test.go
  e2e/testim/inventory/inventory.go
  go.mod
  go.sum
  hack/dev/skaffold.Dockerfile
  hack/dev/skaffoldcache.Dockerfile
  integration/docker/registry/assets/manifests.yaml
  integration/docker/registry/registry_server.go
  integration/docker/registry/temp_registry_test.go
  kotskinds/apis/kots/v1beta1/airgap_types.go
  kotskinds/apis/kots/v1beta1/zz_generated.deepcopy.go
  kotskinds/config/crds/kots.io_airgaps.yaml
  kotskinds/schemas/airgap-kots-v1beta1.json
  pkg/airgap/airgap.go
  pkg/airgap/update.go
  pkg/automation/automation.go
  pkg/base/images.go
  pkg/base/testdata/base-specs/pod.yaml
  pkg/base/write_images.go
  pkg/base/write_images_test.go
  pkg/docker/archive/docker_archive.go
  pkg/docker/registry/assets/temp-registry-config.yml
  pkg/docker/registry/auth.go
  pkg/docker/registry/images_test.go
  pkg/docker/registry/temp_registry.go
  pkg/docker/registry/temp_registry_test.go
  pkg/docker/registry/types/types.go
  pkg/docker/types/types.go
  pkg/handlers/registry.go
  pkg/image/builder.go
  pkg/image/builder_test.go
  pkg/image/image.go
  pkg/image/image_test.go
  pkg/image/types/types.go
  pkg/k8sutil/kustomization.go
  pkg/kotsadm/copy_images.go
  pkg/kotsadm/main.go
  pkg/kotsadm/push_images.go
  pkg/kotsadm/types/pushkotsadmoptions.go
  pkg/kotsadm/version/kotsadm_version.go
  pkg/kotsutil/kots.go
  pkg/pull/pull.go
  pkg/registry/images.go
  pkg/registry/registry.go
  pkg/rewrite/rewrite.go
  pkg/template/builder.go
  pkg/template/config_context.go
  pkg/template/config_context_test.go
  pkg/tests/pull/cases/simple/wantResults/overlays/midstream/kustomization.yaml
  pkg/tests/pull/cases/simple/wantResults/overlays/midstream/secret.yaml
  pkg/upload/upload.go
  pkg/upstream/push_images.go
  pkg/upstream/upgrade.go
Labels: type::feature

#3100 Fix error when no config values provided for helm
  pkg/helm/charts.go
  pkg/license/license.go
Labels: type::bug, bug::normal

#3107 Fix being able to type in the 'path' field for other s3-compatible storage destination
  web/src/components/snapshots/SnapshotStorageDestination.jsx
Labels: type::bug, bug::regression

#3102 Allow square and circular app logos
  web/src/components/apps/AppGitops.jsx
  web/src/components/gitops/SetupProvider.jsx
  web/src/scss/components/apps/AppVersionHistory.scss
  web/src/scss/components/shared/NavBar.scss
  web/src/scss/components/shared/SideBar.scss
  web/src/scss/components/watches/Dashboard.scss
Labels: type::feature

#3084 Destroy test instance before retry to ensure clean environment
  .github/workflows/regression.yaml
Labels: type::chore

#3113 consolidate ci for creating prod and staging tags for helm chart
  .github/workflows/tag-helm-chart.yaml
Labels: type::bug, bug::normal

#3114 When redeploying or updating config, pin helm command to the correct chart version
  pkg/handlers/app.go
  pkg/handlers/config.go
  pkg/helm/charts.go
  web/src/components/shared/modals/HelmDeployModal.jsx
  web/src/features/AppConfig/components/AppConfig.jsx
Labels: type::bug, bug::normal

#3115 Include namespace in helm upgrade commands
  pkg/api/handlers/types/types.go
  pkg/handlers/app.go
  web/src/components/apps/AppVersionHistory.jsx
  web/src/components/apps/DashboardVersionCard.jsx
  web/src/components/shared/modals/HelmDeployModal.jsx
  web/src/features/AppConfig/components/AppConfig.jsx
Labels: type::bug, bug::normal

#3110 upgrade kots to react 18
  web/package.json
  web/src/components/apps/AppDetailPage.jsx
  web/src/components/hooks/useDownloadValues.js
  web/src/features/AppConfig/components/AppConfig.jsx
  web/src/index.jsx
  web/yarn.lock
Labels: type::chore, team::orange

#3119 No automatic deploys when Helm managed
  README.md
  pkg/updatechecker/updatechecker.go
  web/src/components/apps/AppVersionHistory.jsx
  web/src/components/apps/Dashboard.jsx
  web/src/components/modals/AutomaticUpdatesModal.jsx
Labels: type::bug, bug::normal

#3109 Don't validate JWT tokens when checking registry access
  pkg/docker/registry/auth.go
  pkg/docker/registry/token.go
  pkg/handlers/registry.go
Labels: type::bug, bug::normal

#3120 Live-render config in Helm mode
  pkg/app/types/app.go
  pkg/app/types/helm_app.go
  pkg/app/types/types.go
  pkg/handlers/config.go
Labels: type::bug, bug::normal

#3121 generate release notes on tag
  .github/workflows/release.yaml
  .github/workflows/require-pr-labels.yaml
Labels: type::chore

#3122 fix: trigger target/min/range/kgrid tests on merge
  .github/workflows/release.yaml
Labels: type::chore

#3126 out-of-order steps on infra turn-up
  .github/workflows/regression.yaml
Labels: type::chore

#3118 Update Registry Settings UI
  web/src/components/apps/AppRegistrySettings.jsx
  web/src/components/shared/AirgapRegistrySettings.jsx
  web/src/scss/components/watches/WatchDetailPage.scss
Labels: type::chore

#3130 update to not read from passwordB64 for testim test
  e2e/e2e_test.go
  e2e/testim/inventory/inventory.go
Labels: type::chore

#3117 feat: allow custom branding of the admin console
  kotskinds/apis/kots/v1beta1/application_types.go
  kotskinds/config/crds/kots.io_applications.yaml
  kotskinds/schemas/application-kots-v1beta1.json
  pkg/handlers/metadata.go
  web/src/Root.jsx
Labels: type::feature

#3134 remove console log
  web/src/components/apps/AppDetailPage.jsx
Labels: type::chore, team::orange

#3127 Rianfowler/sc 56973/add typechecking to kots web
  web/.babelrc
  web/.eslintrc
  web/.gitignore
  web/.prettierrc.js
  web/.prettierrc.json
  web/babel.config.js
  web/eslint-dist.yml
  web/package.json
  web/src/Root.jsx
  web/src/components/apps/AppVersionHistory.jsx
  web/src/components/hooks/useDownloadValues.js
  web/src/components/modals/AutomaticUpdatesModal.jsx
  web/src/components/shared/modals/HelmDeployModal.tsx
  web/src/components/snapshots/SnapshotStorageDestination.tsx
  web/tsconfig.json
  web/webpack.config.dev.js
  web/webpack.config.js
  web/yarn.lock
Labels: type::chore, team::orange

#3139 get body before setting error state
  web/src/components/apps/Dashboard.jsx
Labels: type::bug, bug::normal, team::orange
