Repository replicatedhq/kots, pull requests merged in 2022-12, with the labels that each got.

#3461 pin velero version and remove k3s permutation from regression tests
  .github/workflows/regression.yaml
  e2e/hack/deps.sh
Labels: type::chore, type::tests

#3454 Fail gracefully in Helm mode on initial login
  pkg/handlers/app.go
Labels: type::bug, bug::normal

#3449 add replicatedRegistryDomain and proxyRegistryDomain fields to App Spec
  kotskinds/Makefile
  kotskinds/apis/kots/v1beta1/application_types.go
  kotskinds/client/kotsclientset/fake/register.go
  kotskinds/client/kotsclientset/scheme/register.go
  kotskinds/config/crds/kots.io_applications.yaml
  kotskinds/schemas/application-kots-v1beta1.json
Labels: type::feature

#3479 bump lvp to resolve snapshot permission issue
  .image.env
  Makefile
  pkg/image/constants.go
Labels: type::bug, bug::normal

#3452 Allow required values in helm charts
  pkg/base/helm_v2.go
  pkg/base/helm_v3.go
  pkg/handlers/config.go
  pkg/kotsadmupstream/upstream.go
  pkg/online/online.go
  pkg/pull/pull.go
  pkg/store/kotsstore/version_store.go
Labels: type::bug, bug::normal

#3464 add show release notes
  web/src/features/Dashboard/components/DashboardVersionCard.tsx
Labels: type::bug, bug::regression

#3459 update initial tab selection
  web/src/components/apps/AppVersionHistory.tsx
  web/src/features/Dashboard/components/DashboardVersionCard.tsx
Labels: type::bug, bug::normal

#3422 TLS configuration page improvements
  kurl_proxy/assets/tls-custom.css
  kurl_proxy/assets/tls.html
  kurl_proxy/assets/tls.js
Labels: type::chore

#3466 add kotsadm debugger for okteto v2
  Makefile
  README.md
  deploy/okteto/okteto-v2.Dockerfile
  okteto-v2.yml
Labels: type::chore

#3463 Fix an issue where enabling/disabling image garbage collection is broken
  pkg/kotsutil/kots.go
Labels: type::bug, bug::regression

#3447 Read `proxyRegistryDomain` from kots application manifest and rewrite images
  kotskinds/client/kotsclientset/fake/clientset_generated.go
  pkg/docker/registry/registry.go
  pkg/docker/registry/registry_test.go
  pkg/preflight/preflight.go
  pkg/pull/pull.go
  pkg/registry/registry.go
  pkg/registry/troubleshoot.go
  pkg/registry/troubleshoot_test.go
  pkg/render/render.go
  pkg/rewrite/rewrite.go
  pkg/supportbundle/spec.go
  pkg/template/config_context.go
Labels: type::feature

#3460 Fix: Dockerhub credentials provided to KOTS via the 'kots docker ensure-secret' CLI command do not increase the rate limit
  pkg/image/builder.go
  pkg/pull/pull.go
Labels: type::bug, bug::regression

#3473 Show meaningful errors when running kots upload command
  pkg/handlers/errors.go
  pkg/handlers/gitops.go
  pkg/handlers/identity.go
  pkg/handlers/login.go
  pkg/handlers/password_change.go
  pkg/handlers/registry.go
  pkg/handlers/session.go
  pkg/handlers/snapshots.go
  pkg/handlers/types/errors.go
  pkg/handlers/upload.go
  pkg/upload/upload.go
  pkg/util/util.go
Labels: type::bug, bug::normal

#3381 adds firefox as a testrunner for regression tests
  e2e/testim/client.go
  e2e/testim/inventory/inventory.go
  e2e/testim/inventory/test.go
  web/src/components/modals/ViewSnapshotLogsModal.jsx
  web/src/components/snapshots/AppSnapshots.jsx
  web/src/components/snapshots/SnapshotSchedule.jsx
  web/src/components/snapshots/Snapshots.jsx
Labels: type::chore

#3481 Keep untagged images for 24 hours instead of 12
  .github/actions/kots-e2e/action.yml
  .github/workflows/build-test.yaml
  Makefile
  deploy/kurl/kotsadm/hack/Makefile
  e2e/README.md
  hack/build-ttl.sh
  kurl_proxy/Makefile
  migrations/build-ttl.sh
Labels: type::chore

#3482 Disable kgrid until it's fixed
  .github/workflows/release.yaml
Labels: type::chore

#3469 defer close pipe to fix leaking goroutine issue
  pkg/kotsadmupstream/upstream.go
Labels: type::bug, bug::normal

#3450 Fix size of command boxes
  web/src/scss/utilities/prism.scss
Labels: type::bug, bug::regression

#3486 Increase rqlite memory limit to 1Gi
  deploy/kurl/kotsadm/template/base/rqlite.yaml
  migrations/kustomize/overlays/dev/rqlite.yaml
  migrations/kustomize/overlays/okteto/rqlite.yaml
  pkg/kotsadm/objects/rqlite_objects.go
  pkg/kotsadm/rqlite.go
Labels: type::bug, bug::normal

#3453 Update support bundle insight message after completing
  web/src/components/troubleshoot/SupportBundleList.tsx
Labels: type::bug, bug::regression

#3471 exclude kURL specific collectors from support bundle if not running in kURL
  pkg/supportbundle/spec.go
  pkg/supportbundle/supportbundle.go
Labels: type::bug, bug::normal

#3468 add e2e readme details
  e2e/README.md
Labels: type::chore

#3490 Revert "Allow required values in helm charts"
  pkg/base/helm_v2.go
  pkg/base/helm_v3.go
  pkg/handlers/config.go
  pkg/kotsadmupstream/upstream.go
  pkg/online/online.go
  pkg/pull/pull.go
  pkg/store/kotsstore/version_store.go
Labels: type::bug, bug::regression

#3492 Support registry and proxy from okteto envs
  pkg/docker/registry/registry.go
  pkg/docker/registry/registry_test.go
Labels: type::chore

#3472 Remove head requests that were not necessary
  pkg/replicatedapp/api.go
  pkg/upstream/fetch.go
  pkg/upstream/git.go
  pkg/upstream/helm.go
  pkg/upstream/helm_test.go
  pkg/upstream/http.go
  pkg/upstream/peek.go
  pkg/upstream/replicated.go
Labels: type::chore

#3475 Disable image garbage collection when an external registry is enabled
  pkg/registry/images.go
  pkg/registry/images_test.go
Labels: type::bug, bug::normal

#3497 Read replicatedRegistryDomain from kots application manifest and rewrite images
  pkg/base/images.go
  pkg/base/testdata/replicated-registry/pod.yaml
  pkg/base/write_images_test.go
  pkg/docker/registry/registry.go
  pkg/docker/registry/registry_test.go
  pkg/docker/registry/types/types.go
  pkg/pull/pull.go
  pkg/rewrite/rewrite.go
Labels: type::feature

#3448 use registry fields for LicenseDockerCfg template func
  pkg/template/builder.go
  pkg/template/config_context.go
  pkg/template/license_context.go
  pkg/template/license_context_test.go
Labels: type::feature

#3503 Expose k8s version info as template functions
  pkg/template/static_context.go
  pkg/template/static_context_test.go
Labels: type::feature

#3507 fix a bug where rqlite headless service manifest is not generated
  pkg/kotsadm/rqlite.go
  pkg/kotsadm/rqlite_test.go
Labels: type::bug, bug::regression

#3502 filter label type from side nav
  web/src/features/AppConfig/components/AppConfig.tsx
Labels: type::bug, bug::normal

#3509 Make config nav fixed / scroll independently of config form
  web/src/features/AppConfig/components/AppConfig.tsx
  web/src/scss/components/watches/WatchConfig.scss
Labels: type::feature

#3499 use decrypt flag
  cmd/kots/cli/get-config.go
  cmd/kots/cli/get-config_test.go
  pkg/crypto/aes.go
Labels: type::bug, bug::normal

#3510 Add commit SHA to regression tests slack notification
  .github/workflows/regression.yaml
Labels: type::chore

#3504 add storybook to kots
  web/.storybook/main.js
  web/.storybook/preview.js
  web/babel.config.js
  web/package.json
  web/src/stories/CodeSnippet.stories.tsx
  web/src/stories/ErrorModal.stories.tsx
  web/yarn.lock
Labels: type::chore

#3512 Fix 'undefined' commit SHA in regression tests slack notification
  .github/workflows/regression.yaml
Labels: type::chore

#3513 Add how much each test took to run in regression tests slack notification
  .github/workflows/regression.yaml
Labels: type::chore

#3515 'took' field is per job not step, remove it for now
  .github/workflows/regression.yaml
Labels: type::chore

#3514 return valid semver when a k8s version is not detected
  pkg/template/static_context.go
Labels: type::chore

#3508 add airgap smoke test to e2e suite
  .github/actions/kots-e2e/action.yml
  .github/workflows/build-test.yaml
  e2e/Makefile
  e2e/e2e_test.go
  e2e/kots/kots.go
  e2e/testim/inventory/inventory.go
Labels: type::chore

#3517 set max memory for testim cli
  e2e/testim/client.go
Labels: type::chore

#3523 Increase client-go k8s config QPS and burst for better performance
  pkg/k8sutil/clientset.go
Labels: type::feature, type::improvement

#3520 rename airgap smoke test
  .github/workflows/build-test.yaml
  e2e/testim/inventory/inventory.go
Labels: type::chore

#3516 update kubectl version for CVEs
  deploy/Dockerfile
Labels: type::security

#3525 fix: airgap releases with required config items
  cmd/kots/cli/pull.go
  pkg/airgap/airgap.go
  pkg/airgap/update.go
  pkg/base/helm_v2.go
  pkg/base/helm_v3.go
  pkg/base/replicated.go
  pkg/base/templates.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/handlers/config.go
  pkg/kotsadmconfig/config.go
  pkg/kotsadmupstream/upstream.go
  pkg/midstream/write.go
  pkg/online/online.go
  pkg/pull/archive.go
  pkg/pull/pull.go
  pkg/registry/registry.go
  pkg/registry/types/types.go
  pkg/render/render.go
  pkg/rewrite/rewrite.go
  pkg/store/kotsstore/registry_store.go
  pkg/store/kotsstore/version_store.go
  pkg/template/builder.go
  pkg/template/config_context.go
  pkg/template/config_context_test.go
  pkg/tests/pull/cases/configcontext/testcase.yaml
  pkg/tests/pull/cases/samechartvariations/testcase.yaml
  pkg/tests/pull/cases/subchart-alias/testcase.yaml
  pkg/tests/pull/cases/subcharts/testcase.yaml
  pkg/upstream/replicated.go
  pkg/upstream/replicated_test.go
  pkg/upstream/types/types.go
Labels: type::bug, bug::regression

#3528 bump lvp to resolve CVE-2021-46848
  .image.env
  Makefile
  pkg/image/constants.go
Labels: type::security

#3529 Data reporting improvements
  pkg/api/reporting/types/types.go
  pkg/operator/operator.go
  pkg/operator/operator_test.go
  pkg/preflight/preflight.go
  pkg/reporting/app.go
  pkg/reporting/preflight.go
  pkg/reporting/util.go
  pkg/supportbundle/spec.go
Labels: type::chore

#3530 update helm go module
  go.mod
  go.sum
Labels: type::security
