Repository replicatedhq/kots, pull requests merged in 2022-04, with the labels that each got.

#2687 clear previous snapshot schedule confirm message timeout
  web/src/components/snapshots/SnapshotSchedule.jsx
Labels: type::tests

#2686 Add pagination to the version history page and improve api performance
  cmd/kots/cli/get-apps.go
  cmd/kots/cli/get-versions.go
  kustomize/overlays/dev/deployment.yaml
  pkg/airgap/update.go
  pkg/airgap/update_test.go
  pkg/api/downstream/types/types.go
  pkg/api/handlers/types/types.go
  pkg/apiserver/bootstrap.go
  pkg/handlers/app.go
  pkg/handlers/config.go
  pkg/handlers/download.go
  pkg/handlers/identity.go
  pkg/handlers/ports.go
  pkg/handlers/registry.go
  pkg/handlers/troubleshoot.go
  pkg/kotsadmlicense/license.go
  pkg/operator/operator.go
  pkg/registry/images.go
  pkg/render/helper/appfile.go
  pkg/store/kotsstore/app_store.go
  pkg/store/kotsstore/downstream_store.go
  pkg/store/kotsstore/downstream_store_test.go
  pkg/store/kotsstore/preflight_store.go
  pkg/store/kotsstore/version_store.go
  pkg/store/mock/mock.go
  pkg/store/ocistore/downstream_store.go
  pkg/store/ocistore/version_store.go
  pkg/store/store_interface.go
  pkg/supportbundle/spec.go
  pkg/supportbundle/supportbundle.go
  pkg/updatechecker/updatechecker.go
  web/package.json
  web/src/components/apps/AppConfig.jsx
  web/src/components/apps/AppDetailPage.jsx
  web/src/components/apps/AppGitops.jsx
  web/src/components/apps/AppLicense.jsx
  web/src/components/apps/AppStatus.jsx
  web/src/components/apps/AppVersionHistory.jsx
  web/src/components/apps/AppVersionHistoryRow.jsx
  web/src/components/apps/Dashboard.jsx
  web/src/components/apps/DashboardLicenseCard.jsx
  web/src/components/apps/DashboardVersionCard.jsx
  web/src/components/gitops/GitOpsDeploymentManager.jsx
  web/src/components/modals/ShowDetailsModal.jsx
  web/src/components/shared/Pager.jsx
  web/src/components/shared/SubNavBar/SubNavBar.jsx
  web/src/components/troubleshoot/GenerateSupportBundle.jsx
  web/src/components/troubleshoot/SupportBundleList.jsx
  web/src/components/watches/WatchSidebarItem/KotsSidebarItem.jsx
  web/src/config-ui/subNavConfig.js
  web/src/images/main_spritesheet.svg
  web/src/scss/components/shared/Pager.scss
  web/src/scss/utilities/icons.scss
  web/src/scss/utilities/utilities.scss
  web/src/utilities/utilities.js
  web/yarn.lock
Labels: type::feature, team::orange

#2689 move version action button tooltip outside of the button
  web/src/components/apps/AppVersionHistoryRow.jsx
Labels: type::tests

#2665 aws instance role snapshot settings
  pkg/snapshot/store.go
Labels: type::bug, bug::regression, team::orange

#2690 Fix refreshing app data after checking for updates or doing other actions in the version history page
  web/src/components/apps/AppDetailPage.jsx
Labels: type::bug

#2691 Don't include the latest version in the total count of other available versions
  web/src/components/apps/AppVersionHistory.jsx
Labels: type::bug

#2684 Update app when new docker hub credentials are create/updated
  .github/workflows/build-test.yaml
  cmd/kots/cli/docker.go
  integration/replicated/tests/kitchen-sink/expected/overlays/midstream/pullsecrets.yaml
  integration/replicated/tests/kitchen-sink/expected/overlays/midstream/secret.yaml
  pkg/docker/registry/registry.go
  pkg/handlers/config.go
  pkg/handlers/handlers.go
  pkg/handlers/handlers_test.go
  pkg/handlers/interface.go
  pkg/handlers/mock/mock.go
  pkg/handlers/registry.go
  pkg/image/builder.go
  pkg/kotsadm/version/kotsadm_version.go
  pkg/logger/clilogger.go
  pkg/midstream/midstream.go
  pkg/midstream/write.go
  pkg/pull/pull.go
  pkg/rewrite/rewrite.go
Labels: type::bug, bug::normal, team::orange

#2692 Add test for validating the version history pagination
  .github/workflows/build-test.yaml
Labels: type::tests, team::orange

#2688 Adds the ability to switch from a community license to a different license from the same application
  pkg/handlers/handlers.go
  pkg/handlers/handlers_test.go
  pkg/handlers/interface.go
  pkg/handlers/license.go
  pkg/handlers/mock/mock.go
  pkg/kotsadmlicense/license.go
  web/src/components/apps/AppDetailPage.jsx
  web/src/components/apps/AppLicense.jsx
  web/src/components/apps/AppVersionHistory.jsx
  web/src/scss/components/apps/AppLicense.scss
Labels: type::feature, team::orange

#2696 Add change license test
  .github/workflows/build-test.yaml
Labels: type::tests, team::orange

#2683 Add ability to upload CA certificates to trust snapshot storage endpoints
  pkg/handlers/snapshots.go
  web/src/components/snapshots/ConfigureSnapshots.jsx
  web/src/components/snapshots/SnapshotStorageDestination.data.jsx
  web/src/components/snapshots/SnapshotStorageDestination.jsx
  web/src/components/snapshots/UploadCACertificate.jsx
  web/src/scss/components/shared/SnapshotForm.scss
  web/src/scss/utilities/icons.scss
Labels: type::feature, team::blue

#2700 put all support bundle files in kots/admin_console not kots/admin-console
  pkg/supportbundle/spec.go
Labels: type::chore, team::blue

#2701 Increase snapshot settings success message timeout
  web/src/components/snapshots/SnapshotSchedule.jsx
  web/src/components/snapshots/SnapshotSettings.jsx
Labels: type::tests

#2703 set KOTS JWT session timeout to 12 hours and validate expired sessions
  pkg/handlers/login.go
  pkg/handlers/session.go
Labels: type::bug, bug::regression, team::blue

#2702 Generate minio and nominio kotsadm bundles
  .github/workflows/release.yaml
Labels: type::feature, team::blue

#2695 fix: ensure registry image pull secrets are preset in additional namespaces for minimal RBAC installations
  .github/workflows/build-test.yaml
  pkg/operator/client/client.go
  pkg/operator/client/deploy.go
  pkg/operator/client/namespaces.go
Labels: type::bug, bug::normal

#2705 Releases promoted while updates are being processed will be missed if semantic versioning is enabled
  pkg/app/app.go
  pkg/updatechecker/updatechecker.go
Labels: type::bug, bug::normal, team::orange

#2709 fix: "Select a different file" link for file uploads
  web/src/components/config_render/FileInput.jsx
Labels: type::bug, bug::regression, team::orange

#2708 only poll snapshot settings after the update request succeeds
  web/src/components/snapshots/SnapshotSettings.jsx
Labels: type::tests, team::orange

#2711 fix: extend active user session by an hour if session expiryAt is less than one hour of session timeout
  pkg/handlers/handlers_test.go
  pkg/handlers/login.go
  pkg/handlers/session.go
  pkg/handlers/session_test.go
  pkg/store/kotsstore/session_store.go
  pkg/store/mock/mock.go
  pkg/store/ocistore/session_store.go
  pkg/store/store_interface.go
Labels: type::bug, bug::normal, team::blue

#2712 Improve Okteto build size/time
  okteto.Dockerfile
Labels: type::chore

#2713 feature: add a cron job to purge expired sessions
  pkg/apiserver/server.go
  pkg/handlers/session.go
  pkg/session/expired_session.go
  pkg/store/kotsstore/session_store.go
  pkg/store/mock/mock.go
  pkg/store/ocistore/session_store.go
  pkg/store/store_interface.go
Labels: type::feature, team::blue

#2714 remove now-unused ocistore backend
  cmd/kots/cli/admin-console-upgrade.go
  cmd/kots/cli/install.go
  pkg/kotsadm/distribution.go
  pkg/kotsadm/main.go
  pkg/kotsadm/objects/kotsadm_objects.go
  pkg/kotsadm/types/deployoptions.go
  pkg/kotsadm/types/upgradeoptions.go
  pkg/store/ocistore/README.md
  pkg/store/ocistore/airgap_store.go
  pkg/store/ocistore/app_store.go
  pkg/store/ocistore/appstatus_store.go
  pkg/store/ocistore/cluster_store.go
  pkg/store/ocistore/downstream_store.go
  pkg/store/ocistore/embedded_store.go
  pkg/store/ocistore/installation_store.go
  pkg/store/ocistore/kotsadm_params_store.go
  pkg/store/ocistore/license_store.go
  pkg/store/ocistore/migrations.go
  pkg/store/ocistore/oci_store.go
  pkg/store/ocistore/preflight_store.go
  pkg/store/ocistore/prometheus_address.go
  pkg/store/ocistore/registry_store.go
  pkg/store/ocistore/session_store.go
  pkg/store/ocistore/snapshot_store.go
  pkg/store/ocistore/supportbundle_store.go
  pkg/store/ocistore/task_store.go
  pkg/store/ocistore/user_store.go
  pkg/store/ocistore/version_store.go
  pkg/store/ocistore/version_store_test.go
  pkg/store/store.go
Labels: type::chore, team::blue

#2715 template sig-apps application object
  pkg/kotsutil/kots.go
  pkg/store/kotsstore/version_store.go
Labels: type::bug, bug::regression, team::blue

#2718 add a unit test that relies on a mock sql client
  go.mod
  pkg/persistence/persistence.go
  pkg/store/kotsstore/registry_store_test.go
Labels: type::chore, team::blue

#2716 when user ignores preflights during installation, deploy the application
  web/src/components/PreflightResultPage.jsx
  web/src/components/apps/AppDetailPage.jsx
  web/src/components/apps/Dashboard.jsx
  web/src/components/shared/modals/SkipPreflightsModal.jsx
Labels: type::feature, team::orange

#2720 Revert "when user ignores preflights during installation, deploy the application"
  web/src/components/PreflightResultPage.jsx
  web/src/components/apps/AppDetailPage.jsx
  web/src/components/apps/Dashboard.jsx
  web/src/components/shared/modals/SkipPreflightsModal.jsx
Labels: type::bug, team::orange

#2721 set the 'last checked for updates at' time even when no updates are available
  pkg/updatechecker/updatechecker.go
Labels: type::bug, bug::normal, team::support

#2723 add some unit tests
  pkg/docker/registry/images_test.go
  pkg/docker/registry/registry_test.go
Labels: type::chore, team::orange

#2724 Show default monitoring graphs before first version is deployed
  deploy/Dockerfile
  hack/dev/skaffold.Dockerfile
  pkg/version/metrics.go
Labels: type::feature

#2722 update local-volume-provider to v0.3.1
  Makefile
  pkg/print/fs-lvp-velero-config.go
Labels: type::chore, team::support

#2725 combine build-kots and build-kotsadm ci steps
  .github/workflows/build-test.yaml
Labels: type::chore, team::blue

#2728 Add CODEOWNERS
  CODEOWNERS
Labels: type::chore, team::orange

#2732 Return number of skipped and remaining versions
  pkg/api/downstream/types/types.go
  pkg/handlers/app.go
  pkg/handlers/mock/mock.go
  pkg/store/kotsstore/downstream_store.go
  pkg/store/mock/mock.go
  pkg/store/store_interface.go
Labels: type::feature, team::orange

#2731 Build metrics
  .github/workflows/metrics.yml
  kurl_proxy/okteto.Dockerfile
  migrations/okteto.Dockerfile
  okteto.Dockerfile
  web/okteto.Dockerfile
Labels: type::feature

#2726 ux improvements to pagination on version history page
  cmd/kots/cli/get-versions.go
  pkg/api/downstream/types/types.go
  pkg/handlers/app.go
  pkg/handlers/handlers.go
  pkg/handlers/handlers_test.go
  pkg/handlers/interface.go
  pkg/handlers/mock/mock.go
  pkg/store/kotsstore/downstream_store.go
  pkg/store/mock/mock.go
  pkg/store/store_interface.go
  web/src/components/apps/AppVersionHistory.jsx
  web/src/components/apps/DashboardVersionCard.jsx
  web/src/components/shared/Pager.jsx
Labels: type::feature, team::orange

#2733 ignore preflights and deploy application
  web/src/components/PreflightResultPage.jsx
  web/src/components/apps/AppDetailPage.jsx
  web/src/components/apps/Dashboard.jsx
  web/src/components/shared/modals/SkipPreflightsModal.jsx
Labels: type::feature, team::orange

#2741 Images garbage collection should be limited to the application's registry namespace
  pkg/registry/images.go
Labels: type::bug, bug::normal, team::orange

#2739 add an API to allow changing password (if the current password is known) while logged into kotsadm
  cmd/kots/cli/reset-password.go
  pkg/handlers/handlers.go
  pkg/handlers/handlers_test.go
  pkg/handlers/interface.go
  pkg/handlers/mock/mock.go
  pkg/handlers/password_change.go
  pkg/handlers/session.go
  pkg/handlers/session_test.go
  pkg/password/password.go
  pkg/password/password_test.go
  pkg/policy/policies.go
  pkg/store/kotsstore/user_store.go
  pkg/store/mock/mock.go
  pkg/store/store_interface.go
  pkg/util/namespace.go
Labels: type::feature, team::blue

#2748 get logs from correct namespace
  .github/workflows/build-test.yaml
Labels: type::chore, team::blue

#2744 fix broken monitoring graph legend, fix broken date templating to show localized date instead of LLL
  web/src/components/apps/DashboardGraphsCard.jsx
  web/webpack.config.js
Labels: type::bug, bug::regression, team::orange

#2751 Adding the ability to dev on migrations in Okteto
  README.md
  migrations/README.md
  migrations/okteto.yml
  migrations/tables/.stignore
Labels: type::feature

#2747 Don't deploy only if it's the currently deployed version
  pkg/handlers/deploy.go
Labels: type::bug, bug::normal, team::orange

#2719 fix: propagate automated install errors from kotsadm to cli
  cmd/kots/cli/cli_suite_test.go
  cmd/kots/cli/install.go
  cmd/kots/cli/install_test.go
  go.mod
  go.sum
  pkg/automation/automation.go
  pkg/handlers/app.go
  pkg/handlers/handlers.go
  pkg/handlers/handlers_test.go
  pkg/handlers/interface.go
  pkg/handlers/mock/mock.go
  pkg/handlers/preflight.go
  pkg/kotsadm/types/deployoptions.go
  pkg/preflight/execute.go
  pkg/store/kotsstore/kots_store.go
  pkg/store/kotsstore/task_store.go
Labels: type::bug, bug::normal, team::orange

#2717 Allow anntating the kurl proxy TLS secret using kots CLI
  cmd/kots/cli/reset-tls.go
Labels: type::feature, team::orange

#2749 Re-download newer versions if an older one was updated
  pkg/store/kotsstore/version_store.go
Labels: bug::regression, bug::normal, team::orange

#2754 update error messages for kots change pw api
  pkg/password/password.go
Labels: type::chore, team::blue

#2757 disable 'prebuild codespace' job on merge to main
  .github/workflows/codespaces.yaml
Labels: type::chore, team::blue

#2753 Fix: use networking.k8s.io/v1 api version for ingress instead of extensions/v1beta1
  pkg/appstate/ingress.go
  pkg/identity/deploy/deploy.go
  pkg/identity/deploy/undeploy.go
  pkg/ingress/deploy.go
  pkg/ingress/ingress_config.go
  pkg/kotsadm/ingress.go
  pkg/kotsadm/objects/kotsadm_objects.go
Labels: type::bug, bug::normal, team::orange

#2755 feature: add change password modal to footer
  web/src/components/modals/ChangePasswordModal/ChangePasswordForm.jsx
  web/src/components/modals/ChangePasswordModal/ChangePasswordModal.jsx
  web/src/components/shared/ChangePassword.jsx
  web/src/components/shared/Footer.jsx
  web/src/components/shared/Warning.jsx
  web/src/components/shared/forms/InputField.jsx
  web/src/components/snapshots/SnapshotStorageDestination.jsx
  web/src/images/main_spritesheet.svg
  web/src/scss/components/modals/ChangePasswordModal/ChangePasswordForm.scss
  web/src/scss/components/modals/ChangePasswordModal/ChangePasswordModal.scss
  web/src/scss/components/shared/Footer.scss
  web/src/scss/components/shared/Warning.scss
  web/src/scss/components/shared/forms/InputField.scss
  web/src/scss/utilities/icons.scss
Labels: type::feature, team::blue

#2761 return nil instead of default time when kotsadm password updated is nil
  pkg/handlers/handlers_test.go
  pkg/handlers/session.go
  pkg/handlers/session_test.go
  pkg/store/kotsstore/user_store.go
Labels: type::bug, bug::regression

#2743 helmchart apply ordering
  kotskinds/apis/kots/v1beta1/helmchart_types.go
  kotskinds/config/crds/kots.io_helmcharts.yaml
  kotskinds/schemas/helmchart-kots-v1beta1.json
  pkg/base/replicated_test.go
  pkg/base/testdata/postgresql-10.13.8.tgz
  pkg/operator/client/client.go
  pkg/operator/client/deploy.go
  pkg/operator/client/deploy_test.go
  pkg/operator/operator.go
  pkg/operator/types/types.go
Labels: type::feature, team::blue

#2740 downloadable file in kots config
  pkg/handlers/config.go
  pkg/handlers/handlers.go
  pkg/handlers/handlers_test.go
  pkg/handlers/interface.go
  pkg/handlers/mock/mock.go
  web/src/components/AppConfigRenderer.jsx
  web/src/components/apps/AppConfig.jsx
  web/src/components/config_render/ConfigFileInput.jsx
  web/src/components/config_render/ConfigGroup.jsx
  web/src/components/config_render/ConfigGroups.jsx
  web/src/components/config_render/ConfigRender.jsx
  web/src/components/config_render/FileInput.jsx
  web/src/images/main_spritesheet.svg
  web/src/scss/utilities/icons.scss
Labels: type::feature, team::orange

#2764 changes to workflow in pr should run in ci
  .github/workflows/build-test.yaml
Labels: type::chore

#2767 Add 'Steps to reproduce' section to the pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type::chore

#2768 Actions cache go modules
  .github/workflows/alpha.yaml
  .github/workflows/build-test.yaml
  .github/workflows/release.yaml
Labels: type::chore

#2770 improve error logs for validate-kots-pull
  .github/workflows/build-test.yaml
Labels: type::chore, type::tests, team::blue

#2773 change all workflows to use an ubuntu 20.04 base image instead of a mix of 18.04 and 20.04
  .github/workflows/alpha.yaml
  .github/workflows/nightly.yaml
  .github/workflows/release.yaml
Labels: type::chore, team::blue

#2763 refactor AutomateAirgapInstall to use task logic
  cmd/kots/cli/install.go
  cmd/kots/cli/install_test.go
  pkg/apiserver/server.go
  pkg/automation/automation.go
  pkg/handlers/airgap.go
  pkg/logger/clilogger.go
Labels: type::bug, bug::normal, team::orange

#2774 Separate go caches
  .github/workflows/alpha.yaml
  .github/workflows/build-test.yaml
  .github/workflows/release.yaml
Labels: type::chore

#2775 add checkout action to goreleaser step
  .github/workflows/release.yaml
Labels: type::chore, team::blue

#2776 add schemahero entrypoint
  migrations/deploy/Dockerfile
Labels: type::chore, team::blue

#2778 no longer install btrfs-tools for goreleaser
  .github/workflows/release.yaml
Labels: type::chore, team::blue

#2769 add a test to validate helm install weights are respected
  .github/workflows/build-test.yaml
Labels: type::feature, type::tests, team::blue

#2779 add package libbtrfs-dev to goreleaser build
  .github/workflows/release.yaml
Labels: type::chore, team::blue

#2780 add on-pr test for yamlescape
  .github/workflows/build-test.yaml
Labels: type::feature, type::tests, team::blue
