Repository replicatedhq/kots, pull requests merged in 2022-02, with the labels that each got.

#2474 add modal when specified KOTS version does not match current version
  web/src/components/apps/AppConfig.jsx
  web/src/components/apps/AppDetailPage.jsx
  web/src/components/apps/AppVersionHistory.jsx
  web/src/components/apps/AppVersionHistoryClassic.jsx
  web/src/components/apps/Dashboard.jsx
  web/src/components/apps/DashboardCard.jsx
  web/src/components/apps/DashboardClassic.jsx
  web/src/components/apps/DashboardVersionCard.jsx
Labels: type::feature, team::orange

#2499 Use proper serializer for license file in support bundle
  pkg/supportbundle/spec.go
Labels: type::bug, bug::regression, team::orange

#2500 details link for app resource modal
  web/src/components/apps/AppStatus.jsx
  web/src/components/apps/Dashboard.jsx
Labels: type::bug, bug::regression, team::orange

#2502 return an error when there is no cipher loaded but decryption is attempted
  pkg/crypto/aes.go
  pkg/crypto/aes_test.go
Labels: type::bug, bug::regression

#2511 do not return error until bug is fixed
  pkg/handlers/snapshots.go
Labels: type::bug, team::orange

#2508 Kiraboyle/sc 40359/kubectl kots get config should use sane defaults
  cmd/kots/cli/get-config.go
Labels: team::orange

#2492 fix: 'Diff versions' button changes to 'Diff releases' after you click it the first time
  web/src/components/apps/AppVersionHistory.jsx
  web/src/components/apps/AppVersionHistoryClassic.jsx
Labels: bug::normal

#2509 Add dev mode kotsadm
  .dockerignore
  .stignore
  Makefile
  hack/dev/Dockerfile.okteto
  okteto.yml
Labels: type::chore

#2516 Add testing for Okteto
  .github/workflows/build-test.yaml
  .gitignore
Labels: type::feature

#2515 Update troubleshoot to v0.28.1
  go.mod
  go.sum
Labels: type::chore, team::orange

#2527 detect minio image based on the kurl or existing instance
  pkg/image/minio.go
  pkg/snapshot/filesystem.go
Labels: team::blue

#2532 chore(ci): update testim version to latest
  .github/workflows/build-test.yaml
  .github/workflows/release.yaml
Labels: type::chore, team::orange

#2520 Add k3s and rke tests
  .github/workflows/regression.yaml
Labels: type::tests, team::orange

#2534 fix: client-side dry run to support legacy operators
  pkg/operator/applier/kubectl.go
Labels: type::bug, bug::regression, team::orange

#2529 update okteto debug configurations
  .vscode/launch.json
  Makefile
  hack/dev/Dockerfile.okteto
  okteto.yml
Labels: type::chore, team::blue

#2535 feat: new UI permanently enabled
  .gitignore
  kotskinds/apis/kots/v1beta1/license_types.go
  kotskinds/config/crds/kots.io_licenses.yaml
  kotskinds/schemas/license-kots-v1beta1.json
  pkg/api/handlers/types/types.go
  pkg/handlers/app.go
  pkg/pull/signature.go
  web/src/components/apps/AppDetailPage.jsx
  web/src/components/apps/AppVersionHistoryClassic.jsx
  web/src/components/apps/AppVersionHistoryRowClassic.jsx
  web/src/components/apps/DashboardClassic.jsx
  web/src/scss/components/watches/DashboardCardClassic.scss
Labels: type::feature, team::orange

#2540 Rename dockerfiles to be consistent
  Makefile
  deploy/dex.Dockerfile
  hack/dev/okteto.Dockerfile
  hack/dev/skaffold.Dockerfile
  hack/dev/skaffoldcache.Dockerfile
  kurl_proxy/okteto.Dockerfile
  kurl_proxy/skaffold.Dockerfile
  migrations/.dockerignore
  migrations/okteto.Dockerfile
  migrations/skaffold.Dockerfile
  okteto-pipeline.yml
  skaffold.yaml
  web/.dockerignore
  web/okteto.Dockerfile
  web/okteto.yml
  web/skaffold.Dockerfile
Labels: type::chore

#2545 reinclude the preflight status endpoint used by cli preflights
  pkg/apiserver/server.go
Labels: type::bug, bug::regression, team::blue

#2543 feat: cli will attempt to reconnect port-forward if disconnected
  cmd/kots/cli/admin-console.go
  cmd/kots/cli/app-status.go
  cmd/kots/cli/garbage-collect-images.go
  cmd/kots/cli/get-apps.go
  cmd/kots/cli/get-config.go
  cmd/kots/cli/get-versions.go
  cmd/kots/cli/install.go
  cmd/kots/cli/remove.go
  cmd/kots/cli/set-config.go
  pkg/download/download.go
  pkg/k8sutil/portforward.go
  pkg/snapshot/backup.go
  pkg/snapshot/restore.go
  pkg/upload/port-forward.go
  pkg/upload/upload_license.go
Labels: type::feature, team::orange

#2546 Add kots binary to kotsadm image
  .github/workflows/build-test.yaml
  .github/workflows/release.yaml
  deploy/Dockerfile
Labels: type::chore, team::orange

#2547 add a test to ensure the preflight status endpoint is not removed
  pkg/apiserver/server.go
  pkg/handlers/handlers.go
  pkg/handlers/handlers_test.go
Labels: type::chore, team::blue

#2541 Rename make targets to standardize across projects
  .github/workflows/alpha.yaml
  .github/workflows/build-test.yaml
  .github/workflows/release.yaml
  Makefile
  README.md
Labels: type::chore

#2551 Create failed updates as pending download versions that can be downloaded later
  cmd/kots/cli/upstream-download.go
  cmd/kots/cli/upstream.go
  pkg/airgap/update.go
  pkg/api/downstream/types/types.go
  pkg/api/handlers/types/types.go
  pkg/apiserver/bootstrap.go
  pkg/handlers/app.go
  pkg/handlers/config.go
  pkg/handlers/contents.go
  pkg/handlers/deploy.go
  pkg/handlers/download.go
  pkg/handlers/gitops.go
  pkg/handlers/handlers.go
  pkg/handlers/handlers_test.go
  pkg/handlers/identity.go
  pkg/handlers/interface.go
  pkg/handlers/mock/mock.go
  pkg/handlers/ports.go
  pkg/handlers/preflight.go
  pkg/handlers/registry.go
  pkg/handlers/rendered_contents.go
  pkg/handlers/status.go
  pkg/kotsadmlicense/license.go
  pkg/kotsadmupstream/upstream.go
  pkg/kotsutil/kots.go
  pkg/registry/images.go
  pkg/registry/registry.go
  pkg/render/helper/appfile.go
  pkg/store/kotsstore/app_store.go
  pkg/store/kotsstore/downstream_store.go
  pkg/store/kotsstore/version_store.go
  pkg/store/mock/mock.go
  pkg/store/ocistore/downstream_store.go
  pkg/store/ocistore/version_store.go
  pkg/store/store_interface.go
  pkg/store/types/constants.go
  pkg/supportbundle/spec.go
  pkg/supportbundle/supportbundle.go
  pkg/updatechecker/updatechecker.go
  pkg/upstream/replicated.go
  pkg/upstream/types/types.go
  web/src/components/apps/AppConfig.jsx
  web/src/components/apps/AppDetailPage.jsx
  web/src/components/apps/AppVersionHistory.jsx
  web/src/components/apps/AppVersionHistoryHeader.jsx
  web/src/components/apps/AppVersionHistoryRow.jsx
  web/src/components/apps/Dashboard.jsx
  web/src/components/apps/DashboardCard.jsx
  web/src/components/apps/DashboardGraphsCard.jsx
  web/src/components/apps/DashboardSnapshotsCard.jsx
  web/src/components/apps/DashboardVersionCard.jsx
  web/src/components/watches/WatchSidebarItem/KotsSidebarItem.jsx
  web/src/scss/components/apps/AppVersionHistory.scss
  web/src/scss/components/watches/DashboardCard.scss
Labels: type::feature, team::orange

#2550 feat: cli will warn user if version does not match api
  cmd/kots/cli/check-version.go
  cmd/kots/cli/root.go
  pkg/handlers/healthz.go
Labels: type::feature, team::orange

#2557 Fix make commands
  hack/CONTRIBUTING.md
  hack/build-ttl.sh
  hack/dev/okteto.Dockerfile
  hack/dev/skaffold.Dockerfile
Labels: type::bug, bug::regression, team::orange

#2559 bug: added --no-port-forward flag for install command
  .github/workflows/build-test.yaml
  .github/workflows/release.yaml
  cmd/kots/cli/install.go
Labels: type::bug, bug::normal, team::orange
