Repository replicatedhq/kots, pull requests merged in 2022-09, with the labels that each got.

#3133 Revert TF env change pending workflow refactor
  .github/workflows/regression.yaml
Labels: type::chore

#3131 Add kotsadm label to sessions sectret; there is one on all other secrets
  pkg/password/password.go
  pkg/store/kotsstore/session_store.go
Labels: type::bug, bug::normal

#3144 Ability to edit config for pending upgrades
  pkg/handlers/config.go
  pkg/handlers/helm.go
  pkg/helm/charts.go
  pkg/helm/updates.go
  pkg/util/tar.go
  web/src/components/apps/DashboardVersionCard.jsx
  web/src/components/shared/modals/HelmDeployModal.tsx
  web/src/features/AppConfig/components/AppConfig.jsx
  web/src/features/AppVersionHistory/AppVersionHistoryRow.jsx
Labels: type::feature

#3142 start status informers when operator starts
  pkg/apiserver/server.go
  pkg/operator/operator.go
  pkg/operator/operator_test.go
Labels: type::bug, bug::regression

#3094 Automated Kots Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#3146 refactor operator to improve unit testing
  pkg/apiserver/server.go
  pkg/operator/operator.go
  pkg/operator/operator_test.go
  pkg/version/version.go
Labels: type::chore

#3147 resolve CVE-2020-28483 in kurl_proxy image
  kurl_proxy/go.mod
  kurl_proxy/go.sum
Labels: type::security

#3148 Redirect to apps when user already authenticated
  web/src/components/SecureAdminConsole.jsx
Labels: type::bug, bug::normal

#3149 Fix: kots fails to render helm charts that have subcharts referenced as local file repositories
  pkg/base/helm.go
  pkg/base/helm_test.go
Labels: type::bug, bug::regression

#3150 Update SchemaHero to v0.13.2 to resolve CVE-2022-21698
  .github/workflows/alpha.yaml
  .github/workflows/release.yaml
  .image.env
  migrations/Makefile
  migrations/fixtures/Makefile
  migrations/skaffold.Dockerfile
  pkg/image/constants.go
Labels: type::security

#3154 feat: add support for custom fonts in the admin console
  kotskinds/apis/kots/v1beta1/application_types.go
  kotskinds/apis/kots/v1beta1/zz_generated.deepcopy.go
  kotskinds/client/kotsclientset/fake/clientset_generated.go
  kotskinds/config/crds/kots.io_applications.yaml
  kotskinds/schemas/application-kots-v1beta1.json
  pkg/handlers/metadata.go
  pkg/handlers/metadata_test.go
  web/src/Root.jsx
  web/src/components/apps/AppDetailPage.jsx
Labels: type::feature

#3156 fix app restore in progress error message
  pkg/operator/operator.go
Labels: type::chore

#3153 remove border radius and box shadow from app logo
  web/src/scss/components/Login.scss
Labels: type::bug, bug::normal

#3158 narrow types on SnapshotStorageDestination.tsx
  web/src/components/snapshots/SnapshotStorageDestination.tsx
Labels: type::chore, team::orange

#3161 Rianfowler/sc 53446/in helm managed mode user is prompted to
  web/src/Root.jsx
  web/src/features/AddNewApp/components/InstallWithHelm.jsx
Labels: type::feature, team::orange

#3155 auto update checks for helm charts
  pkg/airgap/types/types.go
  pkg/app/types/helm_app.go
  pkg/handlers/app.go
  pkg/handlers/helm.go
  pkg/handlers/update.go
  pkg/handlers/update_checker_spec.go
  pkg/helm/helm.go
  pkg/online/online.go
  pkg/online/types/types.go
  pkg/store/kotsstore/app_store.go
  pkg/store/kotsstore/kots_store.go
  pkg/store/kotsstore/task_store.go
  pkg/store/mock/mock.go
  pkg/store/store_interface.go
  pkg/updatechecker/updatechecker.go
  web/src/components/modals/AutomaticUpdatesModal.jsx
Labels: type::feature

#3168 fix: kots image garbage collection deletes images that are still in use by application
  pkg/image/image.go
  pkg/image/image_test.go
  pkg/upstream/push_images.go
  pkg/upstream/push_images_test.go
  web/src/components/modals/AutomaticUpdatesModal.jsx
Labels: type::bug, bug::regression

#3166 fix: bump minio memory limit to 512Mi
  pkg/kotsadm/objects/minio_objects.go
Labels: type::bug, bug::normal

#3165 Miawong/sc 55710/redesign how we display custom license fields
  web/src/components/apps/AppLicense.jsx
  web/src/components/apps/DashboardLicenseCard.jsx
  web/src/components/apps/LicenseFields.tsx
Labels: type::bug, bug::normal

#3170 fix assignment to nil map
  pkg/handlers/update_checker_spec.go
Labels: type::bug, bug::regression

#3157 Automated Kots Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#3169 fix: Headless/unattended install hangs in embedded clusters with recent kubernetes versions
  pkg/k8sutil/portforward.go
  pkg/k8sutil/portforward_test.go
Labels: type::bug, bug::regression

#3175 Use values from currently deployed version to display on config for pending version
  pkg/handlers/config.go
  pkg/helm/updates.go
Labels: type::bug, bug::normal

#3171 make root a functional component
  web/package.json
  web/src/Root.jsx
  web/src/Root.tsx
  web/src/index.jsx
  web/src/routes/RootRoutes.tsx
  web/src/utilities/fetchWithTimeout.js
  web/src/utilities/fetchWithTimeout.ts
  web/src/utilities/utilities.js
  web/tsconfig.json
  web/yarn.lock
Labels: type::feature, team::orange

#3174 add types to app hook
  web/README.md
  web/package.json
  web/src/features/App/api/getApps.test.jsx
  web/src/features/App/api/getApps.tsx
  web/src/features/App/index.ts
  web/src/features/AppVersionHistory/hooks/useCurrentApp.tsx
  web/tsconfig.json
Labels: type::feature, team::orange

#3173 move new helm screen into typescript file;
  web/src/Root.tsx
  web/src/features/AddNewApp/components/InstallWithHelm.tsx
  web/src/features/AddNewApp/index.ts
Labels: type::feature, team::orange

#3177 move some auth stuff around and add types to secureadminconsole
  web/src/Root.tsx
  web/src/features/App/api/getApps.tsx
  web/src/features/Auth/components/SecureAdminConsole.tsx
  web/src/features/Auth/index.ts
Labels: type::feature, team::orange

#3182 fix check for snapshot settings changed
  web/src/components/snapshots/SnapshotStorageDestination.tsx
Labels: type::chore

#3181 Propagate pending_config status to UI when config is needed
  pkg/airgap/update.go
  pkg/handlers/app.go
  pkg/handlers/config.go
  pkg/handlers/status.go
  pkg/handlers/update.go
  pkg/helm/helm.go
  pkg/helm/updates.go
  pkg/kotsadmupstream/upstream.go
  pkg/tasks/tasks.go
  pkg/updatechecker/updatechecker.go
  web/src/components/apps/DashboardVersionCard.jsx
  web/src/features/AppVersionHistory/AppVersionHistoryRow.jsx
Labels: type::feature

#3179 Miawong/sc 57193/fix checkbox alignment on config page
  web/src/components/config_render/ConfigCheckbox.jsx
  web/src/components/config_render/ConfigCheckbox.tsx
Labels: type::bug, bug::normal

#3183 Show error when required config is missing
  web/src/components/apps/AppDetailPage.jsx
  web/src/features/AppConfig/components/AppConfig.jsx
Labels: type::bug, bug::normal

#3184 update github.com/open-policy-agent/opa to resolve CVE-2022-36085
  go.mod
  go.sum
Labels: type::security

#3187 Don't show Revision text on pending Helm releases
  web/src/features/AppVersionHistory/AppVersionHistoryRow.jsx
Labels: type::bug, bug::regression

#3176 Automated Kots Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#3191 chore: resume status informers in goroutine
  pkg/operator/operator.go
  pkg/operator/operator_test.go
Labels: type::chore

#3192 fix message alignment when strict preflight check fails
  web/src/components/PreflightRenderer.jsx
Labels: type::bug, bug::normal

#3195 Use correct sequence/semver when downloading values.yaml file
  pkg/handlers/handlers.go
  pkg/handlers/handlers_test.go
  pkg/handlers/helm.go
  pkg/helm/charts.go
  pkg/helm/updates.go
  web/src/components/hooks/useDownloadValues.js
  web/src/components/hooks/useDownloadValues.test.jsx
  web/src/features/AppConfig/components/AppConfig.jsx
Labels: type::bug, bug::normal

#3199 Sync license before checking for updates in Helm mode
  pkg/automation/automation.go
  pkg/handlers/config.go
  pkg/handlers/helm.go
  pkg/handlers/license.go
  pkg/helm/charts.go
  pkg/helm/license.go
  pkg/helm/updates.go
  pkg/kotsadmlicense/license.go
  pkg/license/license.go
  pkg/pull/pull.go
  pkg/replicatedapp/api.go
  pkg/replicatedapp/api_test.go
  pkg/replicatedapp/cursor.go
  pkg/replicatedapp/upstream.go
  pkg/replicatedapp/upstream_test.go
  pkg/updatechecker/updatechecker.go
  pkg/upstream/fetch.go
  pkg/upstream/replicated.go
  pkg/upstream/replicated_test.go
  web/src/components/apps/Dashboard.jsx
Labels: type::bug, bug::normal

#3201 Use values from currently deployed version to check if pending_config
  pkg/updatechecker/updatechecker.go
Labels: type::bug, bug::normal

#3200 Rianfowler/sc 58965/add typechecking to AppConfig
  web/.new-eslintrc
  web/package.json
  web/src/Root.tsx
  web/src/components/hooks/useDownloadValues.js
  web/src/features/App/api/getApps.tsx
  web/src/features/App/index.ts
  web/src/features/AppConfig/components/AppConfig.tsx
  web/src/features/AppVersionHistory/hooks/useCurrentApp.tsx
  web/src/features/Auth/components/SecureAdminConsole.tsx
  web/src/types/index.ts
  web/tsconfig.json
  web/webpack.config.js
Labels: type::chore, team::orange

#3202 Don't try to show updates until they are downloaded
  web/src/components/apps/AppVersionHistory.jsx
Labels: type::bug, bug::normal

#3204 Miawong/license entitlement fixes
  web/src/components/apps/AppLicense.jsx
  web/src/components/apps/DashboardLicenseCard.jsx
  web/src/components/apps/LicenseFields.tsx
Labels: type::feature

#3194 fix styling in helm install modal
  web/src/components/shared/modals/HelmDeployModal.tsx
  web/src/components/shared/modals/styles/HelmDeployModal.scss
Labels: type::bug, bug::regression, team::orange

#3205 Rianfowler/sc 58965/adding typechecking to top level routes routes troubleshoot
  web/src/components/troubleshoot/TroubleshootContainer.tsx
  web/yarn.lock
Labels: type::chore, team::orange

#3203 fix: Update error log message
  pkg/operator/operator.go
Labels: type::chore

#3207 Rianfowler/sc 58965/adding typechecking KotsApplicationTree
  web/src/components/tree/KotsApplicationTree.tsx
Labels: type::chore, team::orange

#3212 Rianfowler/sc 58965/adding typechecking to dashboard component
  web/src/components/apps/Dashboard.tsx
  web/src/types/index.ts
Labels: type::chore, team::orange

#3220 fix arrow icon rotation
  web/src/features/AppConfig/components/AppConfig.tsx
  web/src/features/AppConfig/styles/index.js
Labels: type::bug, bug::normal

#3222 Recalculate config_pending when new version is deployed
  e2e/hack/deps.sh
  pkg/helm/cache.go
  web/src/components/apps/AppVersionHistory.jsx
  web/src/components/apps/DashboardVersionCard.jsx
  web/src/components/hooks/useDownloadValues.js
  web/src/components/hooks/useDownloadValues.test.jsx
  web/src/components/hooks/useIsHelmManaged.test.jsx
  web/src/components/hooks/useSaveConfig.test.jsx
  web/src/features/App/api/getApps.test.jsx
  web/src/features/AppConfig/components/AppConfig.tsx
  web/src/features/AppVersionHistory/api/getVersions.test.jsx
Labels: type::bug, bug::normal

#3206 Use semver tag for all binaries
  .github/workflows/alpha.yaml
  .github/workflows/build-test.yaml
  .github/workflows/release.yaml
  Makefile
  e2e/e2e_test.go
  e2e/kots/kots.go
  e2e/testim/inventory/inventory.go
  e2e/testim/inventory/test.go
  pkg/handlers/app.go
  pkg/handlers/download.go
  pkg/k8sutil/portforward.go
  pkg/kotsadmupstream/upstream.go
  pkg/pull/peek.go
  pkg/pull/pull.go
  pkg/updatechecker/updatechecker.go
  web/Makefile
  web/src/components/shared/SubNavBar/SubNavBar.jsx
Labels: type::bug, bug::normal

#3225 Fix githib actions yaml
  .github/workflows/alpha.yaml
Labels: type::chore

#3221 Improved support for generating, testing and releasing the kurl package
  .github/actions/kurl-addon-kots-publisher/action.yml
  .github/actions/kurl-addon-kots-publisher/index.js
  .github/workflows/kurl-addon-kots-generate.yaml
  .github/workflows/kurl-addon-kots-publish.yaml
  .github/workflows/kurl-addon-kots-test.yaml
  deploy/kurl/kotsadm/template/generate.sh
Labels: type::chore

#3226 KOTS kURL add-on release testgrid run priority 1
  .github/workflows/kurl-addon-kots-publish.yaml
  .github/workflows/kurl-addon-kots-test.yaml
Labels: type::chore

#3227 Use workflow context inputs over env
  .github/workflows/kurl-addon-kots-generate.yaml
  .github/workflows/kurl-addon-kots-publish.yaml
  .github/workflows/kurl-addon-kots-test.yaml
Labels: type::chore

#3229 add classname to config elements
  web/src/components/config_render/ConfigGroup.jsx
  web/src/features/AppConfig/components/AppConfig.tsx
  web/src/scss/components/watches/WatchConfig.scss
Labels: type::chore

#3214 Miawong/sc 58965/adding typechecking to license
  web/src/components/apps/AppLicense.tsx
  web/src/components/apps/LicenseFields.tsx
  web/src/types/index.ts
Labels: type::chore, team::orange

#3228 Fix kurl-addon-publish-action
  .github/actions/kurl-addon-kots-publisher/.babelrc
  .github/actions/kurl-addon-kots-publisher/dist/index.js
  .github/actions/kurl-addon-kots-publisher/index.js
  .github/actions/kurl-addon-kots-publisher/package-lock.json
  .github/actions/kurl-addon-kots-publisher/package.json
  .github/actions/kurl-addon-kots-publisher/publisher.js
  .github/actions/kurl-addon-kots-publisher/test/publisher.js
  .github/workflows/kurl-addon-kots-generate.yaml
  .github/workflows/kurl-addon-kots-publish.yaml
Labels: type::chore

#3233 Fixes to kurl add-on workflows
  .github/workflows/kurl-addon-kots-publish.yaml
  .github/workflows/kurl-addon-kots-test.yaml
Labels: type::chore

#3213 add filter for helm managed tabs
  web/src/components/apps/AppVersionHistory.jsx
  web/src/components/apps/DashboardVersionCard.jsx
Labels: type::feature, team::orange

#3235 Fix kurl-addon-kots-publisher action call
  .github/actions/kurl-addon-kots-publisher/dist/index.js
  .github/actions/kurl-addon-kots-publisher/index.js
  .github/workflows/kurl-addon-kots-publish.yaml
  deploy/kurl/kotsadm/template/base/install.sh
  deploy/kurl/kotsadm/template/base/postgres.yaml
  deploy/kurl/kotsadm/template/testgrid/k8s-docker.yaml
Labels: type::chore

#3234 Fix: automatic update checks panic when interval is too short for pending updates to be fetched
  pkg/updatechecker/updatechecker.go
Labels: type::bug, bug::normal

#3232 Show automatic update check config that was previously saved
  pkg/handlers/handlers.go
  pkg/handlers/handlers_test.go
  pkg/handlers/interface.go
  pkg/handlers/mock/mock.go
  pkg/handlers/update_checker_spec.go
  pkg/helm/updates.go
  pkg/online/online.go
  pkg/store/kotsstore/app_store.go
  pkg/store/kotsstore/kots_store.go
  pkg/store/kotsstore/task_store.go
  pkg/store/mock/mock.go
  pkg/store/store_interface.go
  pkg/updatechecker/updatechecker.go
  web/src/components/modals/AutomaticUpdatesModal.jsx
Labels: type::bug, bug::regression

#3237 add optional chaining
  web/src/features/Auth/components/SecureAdminConsole.tsx
Labels: type::bug, bug::normal

#3238 Show license expired message on Version History page
  pkg/updatechecker/updatechecker.go
  web/src/components/apps/AppVersionHistory.jsx
  web/src/components/apps/Dashboard.tsx
  web/src/components/apps/DashboardVersionCard.jsx
Labels: type::bug, bug::normal

#3230 Miawong/sc 58965/adding typechecking to registry
  web/src/components/shared/AirgapRegistrySettings.tsx
Labels: type::chore

#3236 Rianfowler/sc 54435/support bundle page name is wrong - standardize titles
  web/package.json
  web/src/components/BackupRestore.jsx
  web/src/components/Head/KotsPageTitle.tsx
  web/src/components/Head/index.ts
  web/src/components/PreflightResultPage.jsx
  web/src/components/UploadAirgapBundle.jsx
  web/src/components/UploadLicenseFile.jsx
  web/src/components/apps/AppDetailPage.jsx
  web/src/components/apps/AppIdentityServiceSettings.jsx
  web/src/components/apps/AppLicense.tsx
  web/src/components/apps/AppRegistrySettings.jsx
  web/src/components/apps/AppVersionHistory.jsx
  web/src/components/apps/ClusterNodes.jsx
  web/src/components/apps/Dashboard.tsx
  web/src/components/clusters/GitOps.jsx
  web/src/components/identity/Access.jsx
  web/src/components/identity/ConfigureIngress.jsx
  web/src/components/identity/IdentityProviders.jsx
  web/src/components/redactors/EditRedactor.jsx
  web/src/components/redactors/Redactors.jsx
  web/src/components/snapshots/AppSnapshotRestore.jsx
  web/src/components/snapshots/AppSnapshots.jsx
  web/src/components/snapshots/SnapshotRestore.jsx
  web/src/components/snapshots/SnapshotSettings.jsx
  web/src/components/snapshots/Snapshots.jsx
  web/src/components/snapshots/SnapshotsWrapper.jsx
  web/src/components/tree/KotsApplicationTree.tsx
  web/src/components/troubleshoot/GenerateSupportBundle.jsx
  web/src/components/troubleshoot/SupportBundleAnalysis.jsx
  web/src/components/troubleshoot/SupportBundleList.jsx
  web/src/features/AppConfig/components/AppConfig.tsx
  web/src/features/Auth/components/SecureAdminConsole.tsx
  web/src/features/Gitops/components/AppGitops.jsx
  web/src/features/Gitops/components/SetupProvider.jsx
  web/tsconfig.json
  web/webpack.config.js
  web/yarn.lock
Labels: type::bug, bug::normal, team::orange

#3240 fix icon sizing for firefox
  web/src/components/apps/AppVersionHistory.jsx
  web/src/components/apps/DashboardGitOpsCard.jsx
  web/src/components/snapshots/AppSnapshots.jsx
  web/src/components/snapshots/SnapshotRow.jsx
  web/src/components/snapshots/Snapshots.jsx
  web/src/components/troubleshoot/AnalyzerFileTree.jsx
  web/src/components/troubleshoot/AnalyzerRedactorReportRow.jsx
  web/src/components/troubleshoot/GenerateSupportBundle.jsx
  web/src/components/troubleshoot/SupportBundleAnalysis.jsx
  web/src/components/troubleshoot/SupportBundleRow.jsx
  web/src/components/watches/DownstreamWatchVersionDiff.jsx
  web/src/components/watches/WatchSidebarItem/HelmChartSidebarItem.jsx
  web/src/features/AppConfig/components/AppConfig.tsx
  web/src/features/AppVersionHistory/AppVersionHistoryRow.jsx
Labels: type::bug, bug::normal

#3242 Fix constructing the path to the configured registry
  pkg/kotsadm/version/kotsadm_version.go
  pkg/kotsadm/version/kotsadm_version_test.go
Labels: type::bug, bug::normal

#3245 Fix flakey temp registry integration test
  integration/docker/registry/registry_server.go
  integration/docker/registry/temp_registry_test.go
Labels: type::tests

#3239 store branding archive in database
  cmd/kots/cli/install.go
  go.mod
  go.sum
  kotskinds/apis/kots/v1beta1/application_types.go
  kotskinds/apis/kots/v1beta1/zz_generated.deepcopy.go
  kotskinds/config/crds/kots.io_applications.yaml
  kotskinds/schemas/application-kots-v1beta1.json
  migrations/tables/app_version.yaml
  migrations/tables/initial_branding.yaml
  pkg/apiserver/server.go
  pkg/handlers/branding.go
  pkg/handlers/handlers.go
  pkg/handlers/handlers_test.go
  pkg/handlers/metadata.go
  pkg/handlers/metadata_test.go
  pkg/kotsutil/kots.go
  pkg/kotsutil/kots_test.go
  pkg/pull/pull.go
  pkg/replicatedapp/api.go
  pkg/store/kotsstore/branding_store.go
  pkg/store/kotsstore/version_store.go
  pkg/store/mock/mock.go
  pkg/store/store_interface.go
  web/src/Root.tsx
Labels: type::bug, bug::normal
