Repository replicatedhq/kots, pull requests merged in 2022-01, with the labels that each got.

#2419 fix(snapshots): display internal for disableS3 in kURL
  pkg/snapshot/store.go
Labels: type::bug

#2425 feat(cli): build universal M1 binary
  .github/workflows/release.yaml
  Makefile
  deploy/.goreleaser.yaml
Labels: type::feature

#2429 Dashboard style cleanup
  web/src/components/AirgapUploadProgress.jsx
  web/src/components/apps/AppVersionHistory.jsx
  web/src/components/apps/AppVersionHistoryRowClassic.jsx
  web/src/components/apps/DashboardCard.jsx
  web/src/components/apps/DashboardClassic.jsx
  web/src/components/apps/DashboardVersionCard.jsx
  web/src/scss/components/AirgapUploadProgress.scss
  web/src/scss/components/apps/AppVersionHistory.scss
Labels: type::chore

#2427 improve the helm chart deployment method changed logic
  pkg/pull/pull.go
Labels: type::bug, bug::normal

#2434 version history dashboard css cleanup
  pkg/store/kotsstore/license_store.go
  web/src/components/apps/DashboardLicenseCard.jsx
Labels: type::chore

#2437 redeploy button on dashboard current version
  web/src/components/apps/DashboardVersionCard.jsx
Labels: type::chore

#2439 chore: update dry-run commands for k8s 1.23
  pkg/operator/applier/kubectl.go
Labels: type::chore

#2441 show airgap upload progress on version history page
  web/src/components/apps/AppVersionHistory.jsx
Labels: type::chore

#2442 Update web to use nginx in Okteto when not in dev mode.
  .gitignore
  migrations/kustomize/overlays/okteto/migrations.yaml
  okteto-pipeline.yml
  web/.stignore
  web/Dockerfile.okteto
  web/Dockerfile.skaffold
  web/Makefile
  web/deploy/nginx.conf
  web/dist/README.md
  web/env/enterprise.js
  web/env/okteto.js
  web/env/okteto.tmpl.js
  web/env/skaffold.js
  web/kustomize/overlays/dev/deployment.yaml
  web/kustomize/overlays/dev/service.yaml
  web/okteto.yml
  web/src/components/PreflightResultPage.jsx
  web/src/components/UploadLicenseFile.jsx
  web/src/components/apps/AppConfig.jsx
  web/src/components/apps/AppVersionHistory.jsx
  web/src/components/apps/AppVersionHistoryClassic.jsx
  web/src/components/apps/AppVersionHistoryRow.jsx
  web/src/components/apps/AppVersionHistoryRowClassic.jsx
  web/src/components/apps/DashboardVersionCard.jsx
  web/src/components/apps/NodeRow.jsx
  web/src/components/config_render/ConfigGroup.jsx
  web/src/components/config_render/ConfigInput.jsx
  web/src/components/config_render/ConfigSelectOne.jsx
  web/src/components/config_render/FileInput.jsx
  web/src/components/gitops/GitOpsFlowIllustration.jsx
  web/src/components/modals/ShowLogsModal.jsx
  web/src/components/modals/ViewSnapshotLogsModal.jsx
  web/src/components/shared/ClickOutsideAction.jsx
  web/src/components/snapshots/AppSnapshots.jsx
  web/src/components/snapshots/SnapshotDetails.jsx
  web/src/components/snapshots/SnapshotStorageDestination.jsx
  web/src/components/troubleshoot/PodAnalyzerDetails.jsx
  web/src/components/troubleshoot/SupportBundleRow.jsx
  web/src/components/watches/WatchSidebarItem/HelmChartSidebarItem.jsx
  web/src/components/watches/WatchSidebarItem/KotsSidebarItem.jsx
  web/src/utilities/utilities.js
  web/webpack.config.dev.js
  web/webpack.config.dist.js
  web/webpack.config.js
Labels: type::chore

#2443 snapshot card on dashboard shows correct snapshot destination
  web/src/components/apps/DashboardSnapshotsCard.jsx
Labels: type::bug

#2447 Fix skaffold deployment issue
  hack/dev/Dockerfile.skaffold
  hack/dev/Dockerfile.skaffoldcache
  pkg/apiserver/server.go
  web/Dockerfile.skaffold
Labels: type::bug, bug::normal

#2449 Grayson/version history dashboard udpates
  web/src/components/apps/Dashboard.jsx
Labels: type::bug, bug::normal

#2451 Okteto fix
  hack/dev/Dockerfile.okteto
Labels: type::bug, bug::normal

#2453 Revert "test sbom"
  .github/workflows/build-test.yaml
Labels: type::chore

#2454 Run raw commands that sbom generator uses for debugging
  .github/workflows/release.yaml
Labels: type::chore

#2455 Download artifact needed to build sbom
  .github/workflows/release.yaml
Labels: type::chore

#2456 Fix dependencies for tagged build
  .github/workflows/release.yaml
Labels: type::chore

#2450 feat: add k8s 1.22 support
  .github/workflows/build-test.yaml
  deploy/Dockerfile
  hack/dev/Dockerfile.okteto
  hack/dev/Dockerfile.skaffold
Labels: type::chore

#2458 fix k8s versions
  .github/workflows/build-test.yaml
Labels: type::chore

#2457 Wait for regression hosts to come up before running tests
  .github/workflows/regression.yaml
Labels: type::chore

#2460 chore(ci): fix velero for legacy tests on 1.22
  .github/workflows/build-test.yaml
Labels: type::chore

#2463 Bump minio and postgres versions
  .image.env
  Makefile
  migrations/Makefile
  migrations/fixtures/Makefile
  migrations/fixtures/deploy/Dockerfile
  migrations/kustomize/overlays/dev/postgres.yaml
  migrations/kustomize/overlays/okteto/postgres.yaml
  pkg/image/constants.go
Labels: type::chore, type::security

#2465 Don't push airgap images multiple times when installing
  pkg/pull/pull.go
  pkg/rewrite/rewrite.go
  pkg/upstream/push_images.go
Labels: type::bug, bug::normal

#2472 debianmaster/actions-k3s action was pinned to master and dependabot s…
  .github/workflows/build-test.yaml
Labels: type::bug, bug::normal

#2475 don't show edit current config message on initial install
  web/src/components/apps/AppConfig.jsx
Labels: type::bug, bug::normal

#2478 Migrating off of debianmaster/actions-k3s and on to an internal fork …
  .github/workflows/build-test.yaml
Labels: type::bug, bug::normal

#2464 kots cli get versions
  cmd/kots/cli/get-versions.go
  cmd/kots/cli/get.go
  pkg/print/versions.go
Labels: type::feature

#2488 Fixing some problems
  web/package.json
  web/src/components/apps/AppConfig.jsx
  web/webpack.config.dist.js
  web/webpack.config.js
  web/yarn.lock
Labels: type::bug, bug::normal

#2487 add support for Kubernetes 1.23.x
  .github/workflows/build-test.yaml
  deploy/Dockerfile
  hack/dev/Dockerfile.okteto
  hack/dev/Dockerfile.skaffold
Labels: type::feature, team::orange
