Repository replicatedhq/kots, pull requests merged in 2022-05, with the labels that each got.

#2766 updated GitOps UI for dashboard and version history
  web/src/components/apps/AppConfig.jsx
  web/src/components/apps/AppVersionHistory.jsx
  web/src/components/apps/AppVersionHistoryRow.jsx
  web/src/components/apps/DashboardGitOpsCard.jsx
  web/src/components/apps/DashboardVersionCard.jsx
  web/src/components/modals/AutomaticUpdatesModal.jsx
  web/src/components/shared/SubNavBar/SubNavBar.jsx
  web/src/scss/components/apps/AppVersionHistory.scss
  web/src/scss/components/watches/DashboardCard.scss
  web/src/scss/variables.scss
  web/src/utilities/utilities.js
Labels: type::feature, team::orange

#2772 Bump dexidp version
  .image.env
  Makefile
  cmd/imagedeps/README.md
  cmd/imagedeps/image-spec
  migrations/Makefile
  pkg/image/constants.go
Labels: type::chore, team::blue

#2783 Update gzip and liblzma5 packages to patch CVEs
  kurl_proxy/deploy/Dockerfile
  migrations/deploy/Dockerfile
Labels: type::chore, team::blue

#2787 remove second nightly
  .github/workflows/nightly.yaml
Labels: type::tests, team::orange

#2788 update kots install wait-duration flag to have the proper description
  cmd/kots/cli/install.go
Labels: bug::regression, team::orange

#2794 Update troubleshoot dep
  go.mod
  go.sum
Labels: type::feature

#2795 Ensure secrets when only Helm is used with no other specs
  pkg/operator/helm.go
  pkg/operator/operator.go
Labels: type::bug, bug::normal, team::orange

#2785 Kiraboyle/sc 46647/initial gitops commit does not translate all labeled secrets to sealed secrets
  pkg/handlers/config.go
  pkg/secrets/sealed_secrets.go
  pkg/secrets/secrets.go
  pkg/secrets/secrets_suite_test.go
  pkg/secrets/secrets_test.go
  pkg/store/kotsstore/version_store.go
Labels: bug::normal, team::orange

#2799 improve no-redeploy-on-restart test
  .github/workflows/build-test.yaml
Labels: type::tests, team::orange

#2798 Prevent multiple support bundles being generated, show in progress support bundle
  web/src/components/troubleshoot/GenerateSupportBundle.jsx
Labels: type::feature, team::blue

#2800 only mark the version as deployed upon restore instead of actually redeploying it
  pkg/operator/operator.go
Labels: type::bug, bug::normal, team::orange

#2796 always show cron input. auto switch to custom when typing in the box
  web/src/components/snapshots/SnapshotSchedule.jsx
Labels: type::feature, team::orange

#2801 Fix initial version source message when updating the config
  pkg/handlers/config.go
  pkg/store/kotsstore/downstream_store.go
  pkg/store/mock/mock.go
  pkg/store/store_interface.go
Labels: type::bug, bug::normal, team::orange

#2804 mark as current version and deployed after partial restore
  pkg/operator/operator.go
  pkg/store/kotsstore/downstream_store.go
  pkg/store/mock/mock.go
  pkg/store/store_interface.go
Labels: type::bug, bug::normal, team::orange

#2803 Fix broken favicon on TLS pages in Chrome and Safari
  kurl_proxy/assets/insecure.html
  kurl_proxy/cmd/main.go
Labels: type::bug, bug::regression, team::blue

#2805 Surface Minio FS errors better in UI and support bundles
  pkg/handlers/snapshots.go
  pkg/k8sutil/pod.go
  pkg/s3/s3.go
  pkg/snapshot/filesystem.go
  pkg/supportbundle/spec.go
Labels: type::bug, bug::normal, team::orange

#2807 Seanrester/sc 48070/kots metrics pipeline failing after the introduction
  .github/workflows/metrics.yml
Labels: type::bug, bug::regression

#2809 Fixes critical and high CVEs found in go binaries
  .trivyignore
  Makefile
  actions/copy-assets/go.mod
  actions/copy-assets/go.sum
  go.mod
  go.sum
  kurl_proxy/go.mod
  kurl_proxy/go.sum
  pkg/store/kotsstore/preflight_store_test.go
Labels: type::security, team::blue

#2819 Seanrester/sc 48130/change kots release nightly testing to be
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/build-test.yaml
  .github/workflows/nightly.yaml
  .github/workflows/release.yaml
  .github/workflows/trigger-regression-test.yaml
  actions/version-tag/index.js
Labels: type::feature

#2821 fix airgap bundle upload hanging at 0%
  web/src/utilities/utilities.js
Labels: type::bug, bug::regression, team::orange

#2822 any airgap version can be installed initially
  pkg/handlers/app.go
Labels: type::bug, bug::normal, team::orange

#2823 Fix regression test not triggering
  .github/workflows/trigger-regression-test.yaml
Labels: bug::normal

#2810 update imported images using imagedeps
  .image.env
  Makefile
  migrations/Makefile
  migrations/fixtures/Makefile
  migrations/fixtures/deploy/Dockerfile
  migrations/kustomize/overlays/dev/postgres.yaml
  migrations/kustomize/overlays/okteto/postgres.yaml
  pkg/image/constants.go
Labels: type::chore, team::blue

#2811 Miawong/sc 47472/admin console loads some resources from the internet
  web/package.json
  web/src/assets/deployment-status.svg
  web/src/components/apps/DashboardGraphsCard.jsx
  web/src/components/modals/ShowLogsModal.jsx
  web/src/utilities/utilities.js
  web/webpack.config.js
  web/yarn.lock
Labels: type::chore, team::orange

#2820 show installed helm charts in web when running in helm managed mode
  README.md
  pkg/handlers/app.go
  pkg/handlers/dashboard.go
  pkg/handlers/handlers.go
  pkg/handlers/handlers_test.go
  pkg/handlers/helm_managed.go
  pkg/handlers/interface.go
  pkg/handlers/mock/mock.go
  pkg/policy/policies.go
  web/src/components/apps/AppDetailPage.jsx
  web/src/components/apps/Dashboard.jsx
  web/src/components/apps/DashboardGraphsCard.jsx
  web/src/components/apps/DashboardVersionCard.jsx
Labels: type::feature, team::orange

#2808 upgrade to helm v3.8.2
  deploy/Dockerfile
  deploy/okteto/okteto-v2.Dockerfile
  deploy/okteto/okteto.Dockerfile
  hack/dev/skaffold.Dockerfile
Labels: type::chore, team::blue

#2826 No longer fmt and vet in make kots command
  .github/workflows/alpha.yaml
  .github/workflows/build-test.yaml
  .github/workflows/release.yaml
  Makefile
Labels: type::chore

#2830 Upgrade troubleshoot to v0.34.0
  go.mod
  go.sum
Labels: type::bug, bug::normal

#2833 Automated Kots Image Dependency Tag Update
  .image.env
  pkg/image/constants.go
Labels: automated-pr, images, type::chore

#2834 Seanrester/sc 47238/investigate dependency simplification in
  Makefile
  cmd/kots/cli/experimental-off.go
  cmd/kots/cli/experimental-on.go
  cmd/kots/cli/root.go
  cmd/kots/cli/run.go
  deploy/.goreleaser.yaml
  go.mod
  go.sum
  pkg/apiserver/server.go
  pkg/binaries/kubectl.go
  pkg/binaries/kustomize.go
  pkg/cluster/antrea.go
  pkg/cluster/antrea.yaml
  pkg/cluster/apiserver.go
  pkg/cluster/authnz.go
  pkg/cluster/cluster.go
  pkg/cluster/containerd.go
  pkg/cluster/controller.go
  pkg/cluster/cri.go
  pkg/cluster/etcd.go
  pkg/cluster/init.go
  pkg/cluster/kubelet.go
  pkg/cluster/runc.go
  pkg/cluster/scheduler.go
  pkg/cluster/util.go
  pkg/identity/deploy.go
  pkg/identity/deploy/dex.go
  pkg/k8sutil/kotsadm.go
  pkg/k8sutil/portforward.go
  pkg/kotsadm/secrets.go
  pkg/kotsadmidentity/store/store.go
  pkg/kurl/kurl_nodes.go
  pkg/persistence/mock_db.go
  pkg/persistence/persistence.go
  pkg/persistence/pg.go
  pkg/persistence/sqlite.go
  pkg/persistence/sqlite_schema.go
  pkg/store/kotsstore/registry_store_test.go
  pkg/store/kotsstore/user_store.go
Labels: type::chore

#2829 Seanrester/sc 48196/update serial regression tests to run in
  .github/workflows/regression-test-cleanup.yaml
  .github/workflows/regression.yaml
  .github/workflows/release.yaml
  .github/workflows/trigger-regression-test.yaml
  Makefile.build.mk
  actions/clean-up/.gitignore
  actions/clean-up/action.yml
  actions/clean-up/dist/index.js
  actions/clean-up/index.js
  actions/clean-up/package-lock.json
  actions/clean-up/package.json
Labels: type::feature

#2846 Add branch trigger for release workflow
  .github/workflows/release.yaml
Labels: type::bug, bug::normal

#2847 Fixing workspace cleanup being attempted on non-empty workspace
  .github/workflows/regression-test-cleanup.yaml
  actions/regression-test-cleanup/.gitignore
  actions/regression-test-cleanup/action.yml
  actions/regression-test-cleanup/dist/index.js
  actions/regression-test-cleanup/index.js
  actions/regression-test-cleanup/package-lock.json
  actions/regression-test-cleanup/package.json
Labels: type::bug, bug::normal

#2844 Add support to do existing install on k8s 1.24.0
  pkg/kurl/join_cert.go
  pkg/kurl/kurl_nodes.go
Labels: type::feature, team::blue
