Repository replicatedhq/kots, pull requests merged in 2022-11, with the labels that each got.

#3380 fix license expiration check in UI
  web/src/utilities/utilities.js
  web/src/utilities/utilities.test.js
Labels: type::bug, bug::normal

#3374 Allow removing registry settings
  pkg/handlers/registry.go
  web/src/components/shared/AirgapRegistrySettings.tsx
Labels: type::feature

#3382 resolve CVE-2022-32149 in kurl_proxy
  kurl_proxy/go.mod
  kurl_proxy/go.sum
Labels: type::security

#3383 add poll for apps in helm install component
  web/src/features/AddNewApp/components/InstallWithHelm.tsx
  web/src/features/App/api/useLicense.ts
  web/src/features/Dashboard/api/useNextAppVersion.ts
  web/src/features/Dashboard/api/useSelectedAppClusterDashboard.ts
  web/src/features/Gitops/hooks/useApps.js
Labels: type::bug, bug::normal, team::orange

#3355 Add multi-app-tests to e2e test runner
  .github/workflows/build-test.yaml
  e2e/README.md
  e2e/e2e_test.go
  e2e/testim/inventory/inventory.go
  e2e/testim/inventory/test.go
Labels: type::chore, team::orange

#3387 Increase rqlite connector/client timeout to 60 seconds
  deploy/kurl/kotsadm/template/base/tmpl-secret-rqlite.yaml
  migrations/kustomize/overlays/dev/rqlite.yaml
  migrations/kustomize/overlays/okteto/rqlite.yaml
  pkg/kotsadm/objects/secrets_objects.go
Labels: type::bug, bug::normal

#3388 include values.yaml in helm base files
  pkg/base/helm.go
  pkg/base/helm_test.go
  pkg/base/helm_v2.go
  pkg/base/helm_v3.go
  pkg/base/replicated_test.go
  pkg/tests/base/cases/configcontext/base/charts/test-chart-2/values.yaml
  pkg/tests/base/render_test.go
  pkg/tests/pull/cases/configcontext/wantResults/base/charts/test-chart-2/values.yaml
  pkg/tests/pull/cases/configcontext/wantResults/base/charts/test-chart/values.yaml
  pkg/tests/pull/cases/samechartvariations/wantResults/base/charts/test-chart-release-1/values.yaml
  pkg/tests/pull/cases/samechartvariations/wantResults/base/charts/test-chart-release-2/values.yaml
  pkg/tests/pull/cases/samechartvariations/wantResults/base/charts/test-chart-variation-0/values.yaml
  pkg/tests/pull/cases/subchart-alias/wantResults/base/charts/chart/values.yaml
  pkg/tests/pull/cases/subcharts/wantResults/base/charts/chart/values.yaml
  pkg/tests/pull/cases/subcharts/wantResults/base/charts/fluent-bit/values.yaml
Labels: type::feature, type::improvement

#3313 run status informers for charts when in helm managed mode
  pkg/app/types/helm_app.go
  pkg/handlers/dashboard.go
  pkg/handlers/metadata.go
  pkg/helm/cache.go
  pkg/helm/charts.go
  pkg/helm/informers.go
  pkg/kotsutil/kots.go
Labels: type::feature

#3358 Miawong/sc 60457/standardize the look of the troubleshoot
  web/src/components/Icon.tsx
  web/src/components/redactors/RedactorRow.jsx
  web/src/components/redactors/Redactors.jsx
  web/src/components/selection.json
  web/src/components/troubleshoot/AnalyzerInsights.jsx
  web/src/components/troubleshoot/AnalyzerRedactorReport.jsx
  web/src/components/troubleshoot/GenerateSupportBundle.jsx
  web/src/components/troubleshoot/SupportBundleAnalysis.jsx
  web/src/components/troubleshoot/SupportBundleList.jsx
  web/src/components/troubleshoot/SupportBundleRow.jsx
  web/src/components/troubleshoot/TroubleshootContainer.tsx
  web/src/scss/components/AirgapUploadProgress.scss
  web/src/scss/components/redactors/Redactor.scss
  web/src/scss/components/shared/Toggle.scss
  web/src/scss/components/troubleshoot/GenerateSupportBundle.scss
  web/src/scss/components/troubleshoot/SupportBundleAnalysis.scss
  web/src/scss/components/troubleshoot/SupportBundleList.scss
  web/src/scss/utilities/base.scss
  web/src/scss/utilities/utilities.scss
Labels: type::feature

#3391 remove code for deprecated 'kots pull helm' command
  cmd/kots/cli/pull.go
  pkg/pull/pull.go
  pkg/upstream/fetch.go
  pkg/upstream/helm.go
  pkg/upstream/types/types.go
Labels: type::chore

#3393 Transition FOSSA to centrally-managed action
  .github/workflows/pr-license-scan.yaml
Labels: type::chore

#3392 Miawong/sc 61292/standardize the look of the config page
  web/src/components/config_render/ConfigGroup.jsx
  web/src/features/AppConfig/components/AppConfig.tsx
  web/src/features/AppConfig/styles/index.js
  web/src/scss/components/watches/WatchConfig.scss
Labels: type::feature

#3399 Deprecate enable-ha cli command
  cmd/kots/cli/enable-ha.go
Labels: type::chore

#3385 Remove withRouter from UploadAirgapBundle
  web/src/components/UploadAirgapBundle.jsx
  web/src/components/UploadAirgapBundle.tsx
Labels: type::chore, team::orange

#3386 Rianfowler/sc 59398/remove withRouter from UploadLicenseFile
  web/package.json
  web/src/Root.tsx
  web/src/components/UploadLicenseFile.jsx
  web/src/components/UploadLicenseFile.tsx
  web/src/components/apps/AppLicense.tsx
  web/src/features/Dashboard/components/DashboardLicenseCard.tsx
  web/yarn.lock
Labels: type::chore, team::orange

#3401 correct checked out ref for FOSSA tests
  .github/workflows/pr-license-scan.yaml
Labels: type::chore

#3398 (ci/fix): allow prs done from bots OR from forks be executed ONLY when they have the label @actions/safe-to-test'
  .github/dependabot.yml
  .github/workflows/build-test.yaml
Labels: type::chore

#3362 :book: add supportability info into README (only linux/amd64)
  README.md
Labels: type::chore

#3411 shows password complexity rules for resetting kotsadm password
  cmd/kots/cli/reset-password.go
  pkg/kotsadm/main.go
  pkg/kotsadm/secrets.go
  pkg/upstream/admin-console.go
  pkg/util/password_prompt.go
Labels: type::chore

#3420 use debian bullseye base image
  deploy/Dockerfile
  deploy/okteto/okteto.Dockerfile
  hack/dev/skaffold.Dockerfile
Labels: type::security

#3407 Fix logout redirect 2
  web/src/components/snapshots/AppSnapshotRestore.jsx
  web/src/components/snapshots/SnapshotRestore.jsx
  web/src/utilities/utilities.js
Labels: type::bug, bug::normal, team::orange

#3423 Revert "Remove withRouter from UploadAirgapBundle"
  web/src/components/UploadAirgapBundle.jsx
  web/src/components/UploadAirgapBundle.tsx
Labels: type::chore, team::orange

#3421 resolve CVE-2022-32149 in schemahero
  .image.env
  migrations/Makefile
  pkg/image/constants.go
Labels: type::security

#3424 Bump github.com/containers/image to v5.23.1
  go.mod
  go.sum
Labels: type::bug, bug::normal

#3426 use debian bullseye base image for kotsadm-migrations
  migrations/deploy/Dockerfile
Labels: type::security

#3425 use debian bullseye base image for kurl-proxy
  kurl_proxy/deploy/Dockerfile
Labels: type::security

#3429 fix medium cve-2019-10743 by update github.com/mholt/archiver mod to v3.5.1
  Makefile
  go.mod
  go.sum
  integration/replicated/generate.go
  integration/replicated/pull_test.go
  integration/upload/generate.go
  pkg/download/download.go
  pkg/handlers/download.go
  pkg/kotsadm/push_images.go
  pkg/kustomize/helm.go
  pkg/kustomize/helm_test.go
  pkg/operator/client/client.go
  pkg/pull/archive.go
  pkg/store/kotsstore/version_store.go
  pkg/supportbundle/backup.go
  pkg/supportbundle/filetree.go
  pkg/supportbundle/supportbundle.go
  pkg/upload/archive.go
  pkg/version/archive.go
Labels: type::security

#3431 resolve CVE-2022-29458 in local-volume-provider
  .image.env
  Makefile
  pkg/image/constants.go
Labels: type::security

#3432 Fix configuring snapshot schedule in firefox
  web/src/components/snapshots/SnapshotSchedule.jsx
Labels: type::bug, bug::normal

#3427 Updated react-router 5.0->5.3
  web/package.json
  web/src/components/PreflightResultPage.jsx
  web/src/components/UploadAirgapBundle.jsx
  web/src/components/apps/AppDetailPage.tsx
  web/src/components/apps/AppVersionHistory.tsx
  web/src/components/redactors/Redactors.jsx
  web/src/components/shared/AirgapRegistrySettings.tsx
  web/src/components/shared/NavBar.jsx
  web/src/components/snapshots/AppSnapshotRestore.jsx
  web/src/components/snapshots/AppSnapshots.jsx
  web/src/components/snapshots/SnapshotDetails.jsx
  web/src/components/snapshots/SnapshotRestore.jsx
  web/src/components/snapshots/SnapshotSchedule.jsx
  web/src/components/snapshots/SnapshotSettings.jsx
  web/src/components/snapshots/Snapshots.jsx
  web/src/components/snapshots/SnapshotsWrapper.jsx
  web/src/components/tree/KotsApplicationTree.tsx
  web/src/components/troubleshoot/AnalyzerFileTree.jsx
  web/src/components/troubleshoot/AnalyzerRedactorReport.jsx
  web/src/components/troubleshoot/GenerateSupportBundle.jsx
  web/src/components/troubleshoot/SupportBundleAnalysis.jsx
  web/src/components/troubleshoot/SupportBundleList.jsx
  web/src/components/troubleshoot/SupportBundleRow.jsx
  web/src/components/watches/DownstreamWatchVersionDiff.jsx
  web/src/features/AppConfig/components/AppConfig.tsx
  web/src/features/Dashboard/components/AirgapUploadProgress.jsx
  web/src/features/Dashboard/components/DashboardSnapshotsCard.tsx
  web/src/utilities/react-router-utilities.tsx
  web/yarn.lock
Labels: type::chore, team::orange

#3436 add intermediate step to validate pr tests
  .github/workflows/build-test.yaml
Labels: type::chore

#3434 updates rqlite statefulset's cpu for gke autopilot
  cmd/kots/cli/install.go
  pkg/k8sutil/gke.go
  pkg/k8sutil/gke_test.go
  pkg/kotsadm/main.go
  pkg/kotsadm/objects/rqlite_objects.go
  pkg/kotsadm/types/deployoptions.go
Labels: type::bug, bug::normal

#3441 Fix Kots existing cluster snapshot onboarding flow for LVP plugin
  pkg/handlers/snapshot_logs.go
  pkg/kotsadm/minio.go
  pkg/kotsadmsnapshot/backup.go
  pkg/kotsadmsnapshot/restore.go
  pkg/print/fs-lvp-velero-config.go
  pkg/snapshot/filesystem.go
  pkg/snapshot/filesystem_lvp.go
  pkg/snapshot/filesystem_minio.go
  pkg/snapshot/store.go
Labels: type::bug, bug::normal

#3418 add typechecks to SupportBundleRow
  web/package.json
  web/src/components/troubleshoot/SupportBundleAnalysis.jsx
  web/src/components/troubleshoot/SupportBundleRow.tsx
  web/src/components/troubleshoot/TroubleshootContainer.tsx
  web/src/types/index.ts
  web/src/utilities/react-router-utilities.tsx
  web/yarn.lock
Labels: type::chore

#3378 Miawong/sc 60461/standardize the look of the snapshots page
  web/src/components/modals/ViewSnapshotLogsModal.jsx
  web/src/components/snapshots/AppSnapshots.jsx
  web/src/components/snapshots/GettingStartedSnapshots.jsx
  web/src/components/snapshots/SnapshotDetails.jsx
  web/src/components/snapshots/SnapshotRow.jsx
  web/src/components/snapshots/SnapshotSchedule.jsx
  web/src/components/snapshots/SnapshotStorageDestination.tsx
  web/src/components/snapshots/Snapshots.jsx
  web/src/scss/components/snapshots/AppSnapshots.scss
Labels: type::feature

#3443 update lint and test-unit commands in makefile
  .github/workflows/build-test.yaml
  web/Makefile
Labels: type::chore

#3417 add typechecks to DownstreamWatchVersionDiff component
  web/src/components/watches/DownstreamWatchVersionDiff.tsx
Labels: type::chore

#3445 Add typechecking preflight result page
  web/src/components/PreflightResultErrors.tsx
  web/src/components/PreflightResultPage.tsx
  web/src/types/index.ts
Labels: type::chore
