Repository replicatedhq/kots, pull requests merged in 2022-06, with the labels that each got.

#2852 graysonnull/sc-48421 fix redeploy/deploy logic on dashboard card
  web/src/components/apps/DashboardVersionCard.jsx
Labels: type::bug, bug::regression, team::orange

#2855 remove tz 'guess' when writing the date format to eliminate issue whe…
  web/src/utilities/utilities.js
Labels: bug::normal, team::orange

#2827 hide more stuff for helm managed charts
  web/src/components/apps/AppDetailPage.jsx
  web/src/components/apps/AppVersionHistory.jsx
  web/src/components/apps/DashboardVersionCard.jsx
  web/src/components/shared/SubNavBar/SubNavBar.jsx
  web/src/components/tree/KotsApplicationTree.jsx
  web/src/config-ui/subNavConfig.js
  web/src/scss/utilities/base.scss
Labels: type::feature, team::orange

#2861 Testim failure message
  e2e/kots/kots.go
  e2e/testim/client.go
Labels: type::chore

#2862 show deployed chart version and icon for helm charts in UI
  go.mod
  pkg/handlers/app.go
  pkg/handlers/status.go
Labels: type::feature, team::orange

#2866 Don't fail regression if workspace already exists
  .github/workflows/regression.yaml
Labels: type::feature

#2864 Set user agent on outbound http requests
  pkg/buildversion/buildversion.go
  pkg/docker/registry/auth.go
  pkg/download/download.go
  pkg/handlers/redact.go
  pkg/handlers/troubleshoot.go
  pkg/handlers/update.go
  pkg/kotsadmlicense/platform_license.go
  pkg/license/license.go
  pkg/metrics/install.go
  pkg/reporting/app.go
  pkg/reporting/preflight.go
  pkg/upstream/replicated.go
  pkg/upstream/upgrade.go
  pkg/util/request.go
  pkg/version/metrics.go
Labels: type::bug, bug::normal

#2865 Add kubeconfig to testim env
  .github/workflows/build-test.yaml
  e2e/README.md
  e2e/cluster/k3d.go
  e2e/e2e_test.go
  e2e/helm/cli.go
  e2e/kots/kots.go
  e2e/kubectl/command.go
  e2e/testim/client.go
  e2e/util/util.go
  e2e/velero/cli.go
Labels: type::chore

#2868 Add dropdown to NavBar
  web/src/Root.jsx
  web/src/components/modals/ChangePasswordModal/ChangePasswordForm.jsx
  web/src/components/shared/ChangePassword.jsx
  web/src/components/shared/Footer.jsx
  web/src/components/shared/NavBar.jsx
  web/src/components/shared/NavBarDropdown.jsx
  web/src/components/shared/forms/InputField.jsx
  web/src/components/snapshots/SnapshotRow.jsx
  web/src/scss/components/shared/NavBar.scss
  web/src/scss/utilities/icons.scss
Labels: type::feature, team::blue

#2871 fix: fix bug where create new application button wasn't working
  web/src/components/shared/NavBarDropdown.jsx
Labels: type::bug, team::blue

#2870 update error message if license is expired
  web/src/components/apps/Dashboard.jsx
Labels: type::bug, bug::normal, team::orange

#2874 Fix issue with regressoin test runs where workspace wouldn't be selec…
  .github/workflows/regression.yaml
Labels: type::bug, bug::normal

#2876 Fix regression test bug
  .github/workflows/regression.yaml
Labels: type::bug, bug::normal

#2875 Wait longer for testim tests, use minimal rbac, create registry creds…
  e2e/kots/kots.go
  e2e/nightly_test.go
  e2e/testim/client.go
  e2e/testim/inventory/inventory.go
  e2e/testim/inventory/test.go
Labels: type::chore

#2873 Disk usage graph missing for prometheus with kubernetes-service-endpoints job enabled
  pkg/version/metrics.go
Labels: type::bug, bug::normal

#2881 E2e in docker
  e2e/Makefile
  e2e/e2e_test.go
  e2e/hack/Dockerfile
  e2e/hack/deps.sh
Labels: type::chore

#2880 Update minio image to latest upstream tag to resolve CVEs
  cmd/imagedeps/main_test.go
  cmd/imagedeps/testdata/basic/.image.env
  cmd/imagedeps/testdata/basic/constants.go
  cmd/imagedeps/testdata/with-overrides/.image.env
  cmd/imagedeps/testdata/with-overrides/constants.go
Labels: type::security, team::orange

#2835 Automated Kots Image Dependency Tag Update
  .image.env
  pkg/image/constants.go
Labels: automated-pr, images

#2889 update local-volume-provider image tag to resolve CVE-2022-1664
  .image.env
  Makefile
  pkg/image/constants.go
Labels: type::security, team::orange

#2891 Do not check snapshots datasize for nightly e2e test
  e2e/Makefile
  e2e/testim/client.go
Labels: type::chore

#2890 Fixing registry tests failing in the e2e tests
  e2e/Makefile
  e2e/e2e_test.go
  e2e/hack/Dockerfile
  e2e/kots/kots.go
  e2e/nightly_test.go
  e2e/registry/commands.go
  e2e/testim/client.go
  e2e/testim/inventory/inventory.go
  e2e/testim/inventory/test.go
  e2e/util/util.go
Labels: type::feature

#2895 "d" is not a valid time duration unit
  .github/actions/kots-e2e/action.yml
  .github/workflows/build-test.yaml
  integration/replicated/tests/kitchen-sink/expected/upstream/manifests/support-bundle.yaml
  integration/upload/tests/kitchen-sink/expected-archive/upstream/manifests/support-bundle.yaml
  integration/upload/tests/kitchen-sink/input/upstream/manifests/support-bundle.yaml
  migrations/fixtures/fixtures/kots-downstream-history-no-notes.yaml
Labels: type::chore

#2879 exclude kurl kinds from base
  pkg/base/base.go
Labels: type::bug, bug::normal, team::orange

#2894 Set ttl.sh image expiry to 12h from 2h
  .github/actions/kots-e2e/action.yml
  .github/workflows/build-test.yaml
Labels: type::chore

#2885 updating ux of how application updates are shown on version history
  web/src/components/apps/AppVersionHistory.jsx
  web/src/scss/utilities/colors.scss
  web/src/scss/utilities/utilities.scss
  web/src/scss/variables.scss
Labels: type::feature, team::orange

#2899 Don't run preflights if there are no analyzers to apply
  go.mod
  go.sum
  pkg/preflight/preflight.go
  pkg/store/kotsstore/app_store.go
Labels: bug::normal, team::orange

#2898 Emosbaugh/e2e nightly in pr
  .github/workflows/build-test.yaml
  e2e/Makefile
  e2e/README.md
  e2e/cluster/k3d.go
  e2e/e2e_test.go
  e2e/hack/Dockerfile
  e2e/hack/deps.sh
  e2e/kots/kots.go
  e2e/kubectl/command.go
  e2e/minio/install.go
  e2e/nightly_test.go
  e2e/prometheus/install.go
  e2e/registry/commands.go
  e2e/testim/client.go
  e2e/testim/client_test.go
  e2e/testim/inventory/inventory.go
  e2e/testim/inventory/test.go
  e2e/testim/run.go
  e2e/util/util.go
Labels: type::feature

#2897 Seanrester/sc 49260/remove the need for a GitHub release for
  .github/workflows/regression.yaml
  .github/workflows/release.yaml
  README.md
  actions/regression-test-cleanup/index.js
Labels: type::feature

#2904 fix typo in readme
  README.md
Labels: type::chore, team::orange

#2906 fix multiple apps in helm response when running in gke/eks
  pkg/handlers/app.go
Labels: type::bug, bug::normal, team::orange

#2907 Troubleshoot v1.36.0
  go.mod
  go.sum
  pkg/preflight/preflight.go
  pkg/store/kotsstore/app_store.go
Labels: echoes/effort: S, team::orange

#2893 Add a regression test to the build-test workflow
  .github/actions/kots-e2e/action.yml
  .github/workflows/build-test.yaml
  e2e/e2e_test.go
  e2e/nightly_test.go
  e2e/testim/inventory/inventory.go
  e2e/velero/cli.go
Labels: type::feature

#2905 Add installer to kots kinds
  pkg/kotsutil/kots.go
Labels: type::chore, team::orange

#2909 Don't fail e2e suite on debug output
  e2e/e2e_test.go
  e2e/kubectl/command.go
  e2e/nightly_test.go
Labels: type::chore

#2915 Regression test does not need velero
  .github/workflows/build-test.yaml
  e2e/testim/inventory/inventory.go
  e2e/velero/cli.go
Labels: type::chore

#2917 Migrate e2e tests to new go framework
  .github/actions/kots-e2e/action.yml
  .github/workflows/build-test.yaml
  e2e/Makefile
  e2e/e2e_test.go
  e2e/nightly_test.go
  e2e/registry/commands.go
  e2e/testim/inventory/inventory.go
  e2e/testim/inventory/test.go
Labels: type::chore

#2918 Migrate rest of e2e tests to new go framework
  .github/actions/generate-support-bundle/action.yml
  .github/actions/kots-e2e/action.yml
  .github/workflows/build-test.yaml
  e2e/e2e_test.go
  e2e/testim/inventory/inventory.go
Labels: type::chore

#2916 remove preflight icon if app has does not have preflight spec
  web/src/components/apps/AppVersionHistory.jsx
  web/src/components/apps/AppVersionHistoryRow.jsx
  web/src/components/apps/DashboardVersionCard.jsx
Labels: type::bug, bug::normal, team::orange

#2919 Simplify Velero download logs
  e2e/kots/kots.go
  pkg/handlers/snapshot_logs.go
  pkg/kotsadm/main.go
  pkg/kotsadm/postgres.go
  pkg/kotsadmsnapshot/backup.go
  pkg/kotsadmsnapshot/download.go
  pkg/kotsadmsnapshot/restore.go
  pkg/snapshot/velero.go
Labels: type::bug, bug::normal

#2921 Use minio deployment to find minio image instead of node status
  pkg/image/minio.go
  pkg/image/minio_test.go
Labels: type::bug, bug::normal, team::orange

#2925 feat: kubernetes installer preflight
  pkg/installers/installers.go
  pkg/preflight/preflight.go
  pkg/preflight/preflight_test.go
Labels: type::feature, team::orange

#2928 Prevent panic nil map
  pkg/base/replicated.go
Labels: type::bug, bug::normal

#2931 Input CLEANUP_INTERVAL_HOURS for regression-test-cleanup workflow
  .github/workflows/regression-test-cleanup.yaml
  actions/regression-test-cleanup/action.yml
  actions/regression-test-cleanup/dist/index.js
  actions/regression-test-cleanup/index.js
Labels: type::chore

#2932 Set default CLEANUP_INTERVAL_HOURS for scheduled workflow
  .github/workflows/regression-test-cleanup.yaml
Labels: type::chore

#2930 Use chart path instead of name as a map key
  pkg/base/helm.go
  pkg/base/images.go
  pkg/image/builder.go
  pkg/operator/helm.go
  pkg/pull/pull.go
  pkg/rewrite/rewrite.go
  pkg/tests/pull/cases/subcharts/upstream/fluent-bit-0.20.2.tgz
  pkg/tests/pull/cases/subcharts/upstream/fluent-bit.yaml
  pkg/tests/pull/cases/subcharts/wantResults/base/charts/fluent-bit/Chart.lock
  pkg/tests/pull/cases/subcharts/wantResults/base/charts/fluent-bit/Chart.yaml
  pkg/tests/pull/cases/subcharts/wantResults/base/charts/fluent-bit/charts/fluent-bit/Chart.yaml
  pkg/tests/pull/cases/subcharts/wantResults/base/charts/fluent-bit/charts/fluent-bit/kustomization.yaml
  pkg/tests/pull/cases/subcharts/wantResults/base/charts/fluent-bit/charts/fluent-bit/templates/clusterrole.yaml
  pkg/tests/pull/cases/subcharts/wantResults/base/charts/fluent-bit/charts/fluent-bit/templates/clusterrolebinding.yaml
  pkg/tests/pull/cases/subcharts/wantResults/base/charts/fluent-bit/charts/fluent-bit/templates/configmap.yaml
  pkg/tests/pull/cases/subcharts/wantResults/base/charts/fluent-bit/charts/fluent-bit/templates/daemonset.yaml
  pkg/tests/pull/cases/subcharts/wantResults/base/charts/fluent-bit/charts/fluent-bit/templates/service.yaml
  pkg/tests/pull/cases/subcharts/wantResults/base/charts/fluent-bit/charts/fluent-bit/templates/serviceaccount.yaml
  pkg/tests/pull/cases/subcharts/wantResults/base/charts/fluent-bit/charts/fluent-bit/templates/tests/test-connection.yaml
  pkg/tests/pull/cases/subcharts/wantResults/base/charts/fluent-bit/kustomization.yaml
  pkg/tests/pull/cases/subcharts/wantResults/overlays/midstream/charts/fluent-bit/backup-label-transformer.yaml
  pkg/tests/pull/cases/subcharts/wantResults/overlays/midstream/charts/fluent-bit/charts/fluent-bit/backup-label-transformer.yaml
  pkg/tests/pull/cases/subcharts/wantResults/overlays/midstream/charts/fluent-bit/charts/fluent-bit/kustomization.yaml
  pkg/tests/pull/cases/subcharts/wantResults/overlays/midstream/charts/fluent-bit/charts/fluent-bit/pullsecrets.yaml
  pkg/tests/pull/cases/subcharts/wantResults/overlays/midstream/charts/fluent-bit/charts/fluent-bit/secret.yaml
  pkg/tests/pull/cases/subcharts/wantResults/overlays/midstream/charts/fluent-bit/kustomization.yaml
  pkg/tests/pull/cases/subcharts/wantResults/overlays/midstream/charts/fluent-bit/secret.yaml
  pkg/tests/pull/cases/subcharts/wantResults/overlays/midstream/kustomization.yaml
  pkg/tests/pull/cases/subcharts/wantResults/upstream/fluent-bit-0.20.2.tgz
  pkg/tests/pull/cases/subcharts/wantResults/upstream/fluent-bit.yaml
Labels: type::bug, bug::regression, team::orange

#2934 Upgrade go lib github.com/dexidp/dex
  go.mod
  go.sum
  pkg/handlers/identity.go
  web/src/components/identity/IdentityProviders.jsx
Labels: type::chore
