Repository replicatedhq/kots, pull requests merged in 2022-07, with the labels that each got.

#2935 Resolve CVEs in go-getter (imported via troubleshoot)
  go.mod
  go.sum
Labels: type::security, team::orange

#2939 Never fail if registry credentials cannot be loaded for any reason
  .github/workflows/build-test.yaml
  cmd/kots/cli/admin-console-push-images.go
Labels: type::bug, bug::normal, team::orange

#2940 Update okteto hostname for kots/web
  web/env/okteto.js
Labels: type::chore, team::orange

#2944 Rewrite application spec service links to the hostname used in the browser
  web/src/components/apps/AppStatus.jsx
  web/src/scss/components/shared/InlineDropdown.scss
Labels: type::bug, bug::regression, team::orange

#2946 display license info for helm app installations
  pkg/handlers/helm.go
  pkg/handlers/license.go
  web/src/components/apps/Dashboard.jsx
  web/src/components/apps/DashboardLicenseCard.jsx
Labels: type::feature, team::orange

#2952 Rewrite images in all collectors that use images
  go.mod
  go.sum
  integration/replicated/pull_test.go
  pkg/base/images.go
  pkg/base/testdata/base-specs/pod.yaml
  pkg/base/write_images.go
  pkg/base/write_images_test.go
  pkg/image/builder.go
  pkg/k8sdoc/types.go
  pkg/kotsutil/kots.go
  pkg/pull/pull.go
  pkg/registry/troubleshoot.go
  pkg/registry/troubleshoot_test.go
  pkg/rewrite/rewrite.go
Labels: type::bug, bug::normal, team::orange

#2969 Lock Minio version in E2E suite to prevent auto updating
  e2e/minio/install.go
Labels: type::feature

#2970 Lock Minio version in E2E suite to prevent auto updating
  e2e/minio/install.go
Labels: type::feature

#2967 Check for updates works from Dashboard in Helm mode
  pkg/handlers/app.go
  pkg/handlers/status.go
  pkg/handlers/update.go
  pkg/helm/updates.go
  web/src/components/apps/DashboardVersionCard.jsx
Labels: type::feature, team::orange

#2960 chore: automate kubectl version pr
  .github/workflows/update-kubectl.yaml
  Makefile
  actions/kubectl-versions/.gitignore
  actions/kubectl-versions/index.js
  actions/kubectl-versions/package-lock.json
  actions/kubectl-versions/package.json
  deploy/Dockerfile
Labels: type::chore, team::orange

#2973 fix kubectl-versions github action
  Makefile
  actions/kubectl-versions/action.yml
  actions/kubectl-versions/dist/index.js
  actions/kubectl-versions/package-lock.json
  actions/kubectl-versions/package.json
Labels: type::chore, team::orange

#2974 Add sequences, previous releases, and release status on Version History page
  pkg/handlers/app.go
  pkg/helm/charts.go
  pkg/helm/helm.go
Labels: type::feature, team::orange

#2977 Rianfowler/sc 50832/show the helm upgrade command when saving
  web/okteto.yml
  web/src/components/apps/AppConfig.jsx
  web/src/components/apps/DashboardVersionCard.jsx
  web/src/components/shared/modals/HelmDeployModal.jsx
Labels: type::feature, team::orange

#2978 resolve minimist version
  web/package.json
  web/yarn.lock
Labels: type::chore

#2979 Fix loading license when deployed
  README.md
  pkg/handlers/app.go
  pkg/handlers/handlers.go
  pkg/handlers/helm.go
  pkg/handlers/platform_license.go
  pkg/helm/cache.go
Labels: type::bug, bug::normal

#2981 The config secret should always be there, so check if key exists in the map
  pkg/helm/cache.go
Labels: type::bug, bug::normal

#2982 Don't use current dir as temp storage
  pkg/helm/cache.go
Labels: type::bug, bug::normal

#2983 Don't list namespaces in limited RBAC mode
  pkg/apiserver/server.go
  pkg/helm/cache.go
Labels: type::bug, bug::normal

#2989 Sync license now works in Helm mode
  pkg/handlers/app.go
  pkg/handlers/config.go
  pkg/handlers/handlers.go
  pkg/handlers/helm.go
  pkg/handlers/license.go
  pkg/handlers/platform_license.go
  pkg/handlers/update.go
  pkg/helm/cache.go
  pkg/helm/charts.go
  pkg/helm/updates.go
  pkg/license/license.go
  pkg/util/util.go
Labels: type::feature

#2988 tag helm chart on release
  .github/workflows/release.yaml
Labels: type::feature, team::orange

#2992 Fixes for Version History page in Helm mode
  Makefile
  README.md
  pkg/handlers/app.go
  pkg/handlers/update.go
  pkg/helm/cache.go
  pkg/helm/updates.go
Labels: type::bug, bug::normal

#2993 Miawong/sc 51241/labels on the cluster management tab are incorrect
  web/src/components/apps/NodeRow.jsx
  web/src/components/apps/NodeRow.test.js
Labels: type::bug, bug::normal

#2991 Report kURL node total and ready counts
  cmd/kots/cli/install.go
  cmd/kots/cli/upstream-upgrade.go
  cmd/kots/cli/velero.go
  pkg/api/reporting/types/types.go
  pkg/handlers/garbage_collect_images.go
  pkg/handlers/snapshots.go
  pkg/handlers/update.go
  pkg/identity/deploy.go
  pkg/image/minio.go
  pkg/installers/installers.go
  pkg/kotsadm/main.go
  pkg/kotsadm/metadata.go
  pkg/kotsadmsnapshot/backup.go
  pkg/kotsutil/kots.go
  pkg/kotsutil/kurl.go
  pkg/kurl/configmap.go
  pkg/kurl/kurl_nodes.go
  pkg/kurl/types/types.go
  pkg/registry/images.go
  pkg/reporting/app.go
  pkg/reporting/util.go
  pkg/s3/s3.go
  pkg/snapshot/filesystem.go
  pkg/snapshot/restore.go
  pkg/snapshot/store.go
  pkg/supportbundle/spec.go
  pkg/template/static_context.go
Labels: type::feature

#2994 Fix errors on troubleshoot page in Helm managed mode
  pkg/handlers/troubleshoot.go
  web/src/components/troubleshoot/GenerateSupportBundle.jsx
Labels: type::bug, bug::normal

#2995 Update cache of available updates when chart versions are installed/removed
  pkg/helm/cache.go
  pkg/helm/updates.go
Labels: type::bug, bug::normal

#2996 expands pvc size from 2Gi
  web/okteto.yml
Labels: type::chore

#2998 Temp values directory needs execute permission
  pkg/helm/cache.go
Labels: type::bug, bug::regression

#2999 missing dollar sign in env var read
  .github/workflows/release.yaml
Labels: type::bug, bug::normal

#2997 Rianfowler/sc 49673/show when there s an update to the helm chart 2
  web/src/components/UploadAirgapBundle.jsx
  web/src/components/apps/AppConfig.jsx
  web/src/components/apps/AppVersionHistory.jsx
  web/src/components/apps/AppVersionHistoryRow.jsx
  web/src/components/apps/DashboardVersionCard.jsx
  web/src/components/apps/NodeRow.test.js
  web/src/components/hooks/index.js
  web/src/components/hooks/useDownloadValues.js
  web/src/components/shared/modals/HelmDeployModal.jsx
  web/src/components/snapshots/SnapshotDetails.jsx
  web/src/components/troubleshoot/GenerateSupportBundle.jsx
Labels: type::feature, team::orange

#3003 Miawong/sc 51243/resource status empty empty empty by default
  web/package.json
  web/src/components/apps/AppStatus.jsx
  web/src/components/apps/Dashboard.jsx
  web/src/components/apps/Dashboard.test.js
  web/src/components/apps/styles/paragraphs.js
  web/src/components/apps/styles/theme.js
  web/yarn.lock
Labels: type::bug, bug::normal

#2971 Upgrade Postgres from 10.21 to 14.4
  .github/workflows/alpha.yaml
  .github/workflows/build-test.yaml
  .image.env
  Makefile
  cmd/imagedeps/README.md
  cmd/imagedeps/image-spec
  cmd/imagedeps/main.go
  cmd/imagedeps/main_test.go
  cmd/imagedeps/tag-finder.go
  cmd/imagedeps/testdata/postgres/.image.env
  cmd/imagedeps/testdata/postgres/constants.go
  cmd/imagedeps/testdata/postgres/input-spec
  cmd/imagedeps/testdata/with-overrides/.image.env
  cmd/imagedeps/testdata/with-overrides/constants.go
  cmd/imagedeps/testdata/with-overrides/input-spec
  cmd/imagedeps/testdata/with-overrides/replacers/expected/test.Dockerfile
  cmd/imagedeps/testdata/with-overrides/replacers/expected/test.mk
  cmd/imagedeps/testdata/with-overrides/replacers/input/test.Dockerfile
  cmd/imagedeps/testdata/with-overrides/replacers/input/test.mk
  cmd/kots/cli/admin-console-upgrade.go
  deploy/Dockerfile
  deploy/okteto/okteto-v2.Dockerfile
  deploy/okteto/okteto.Dockerfile
  hack/dev/skaffold.Dockerfile
  kurl_proxy/okteto.Dockerfile
  kurl_proxy/skaffold.Dockerfile
  migrations/Makefile
  migrations/fixtures/Makefile
  migrations/fixtures/deploy/Dockerfile
  migrations/kustomize/overlays/dev/postgres.yaml
  migrations/kustomize/overlays/okteto/postgres.yaml
  pkg/identity/deploy_test.go
  pkg/image/constants.go
  pkg/k8sutil/util.go
  pkg/kotsadm/configmaps.go
  pkg/kotsadm/objects/configmaps_objects.go
  pkg/kotsadm/objects/images.go
  pkg/kotsadm/objects/kotsadm_objects.go
  pkg/kotsadm/objects/postgres_objects.go
  pkg/kotsadm/objects/scripts/copy-postgres-10.sh
  pkg/kotsadm/objects/scripts/upgrade-postgres.sh
  pkg/kotsadm/postgres.go
  pkg/kotsadm/version/kotsadm_version.go
  pkg/upstream/admin-console.go
Labels: type::feature, team::orange

#3005 Analyze application button works in Helm managed mode
  README.md
  cmd/kots/cli/upload.go
  cmd/kots/cli/util.go
  cmd/kots/cli/util_test.go
  go.mod
  go.sum
  pkg/apiserver/server.go
  pkg/filestore/blob_store.go
  pkg/handlers/app.go
  pkg/handlers/config.go
  pkg/handlers/dashboard.go
  pkg/handlers/handlers.go
  pkg/handlers/handlers_test.go
  pkg/handlers/helm.go
  pkg/handlers/interface.go
  pkg/handlers/license.go
  pkg/handlers/mock/mock.go
  pkg/handlers/status.go
  pkg/handlers/troubleshoot.go
  pkg/handlers/update.go
  pkg/helm/helm.go
  pkg/policy/getters.go
  pkg/store/kotsstore/supportbundle_store.go
  pkg/supportbundle/execute.go
  pkg/supportbundle/helm.go
  pkg/supportbundle/supportbundle.go
  pkg/supportbundle/types/types.go
  pkg/util/util.go
  web/src/components/troubleshoot/GenerateSupportBundle.jsx
Labels: type::feature

#3007 Don't use Minio and Postgres in Helm managed mode
  pkg/apiserver/bootstrap.go
  pkg/apiserver/server.go
  pkg/handlers/handlers.go
  pkg/handlers/ports.go
  pkg/reporting/app.go
  pkg/store/kotsstore/registry_store.go
  pkg/store/kotsstore/supportbundle_store.go
  web/src/components/apps/AppDetailPage.jsx
  web/src/components/hooks/useIsHelmManaged.js
  web/src/components/hooks/useIsHelmManaged.test.jsx
Labels: type::feature

#3008 Miawong/sc 33592/the affix option does not align text
  web/src/components/apps/AppStatus.jsx
  web/src/components/apps/Dashboard.jsx
  web/src/components/config_render/ConfigCheckbox.jsx
  web/src/components/config_render/ConfigComponents.js
  web/src/components/config_render/ConfigGroup.jsx
  web/src/components/config_render/ConfigInput.jsx
  web/src/components/config_render/ConfigItemTitle.jsx
  web/src/components/config_render/ConfigSelectOne.jsx
  web/src/components/config_render/ConfigTextarea.jsx
  web/src/components/config_render/ConfigUtil.js
Labels: type::bug, bug::normal

#3010 Fix: update customer when user changes app
  web/src/components/apps/Dashboard.jsx
Labels: type::bug, bug::normal
