Repository replicatedhq/kots, pull requests merged in 2022-03, with the labels that each got.

#2569 added second nightly build
  .github/workflows/nightly.yaml
  actions/version-tag/index.js
Labels: type::tests, team::orange

#2571 Update troubleshoot to v0.30.0 to fix viewing pod details
  go.mod
  go.sum
Labels: type::bug, bug::regression, team::orange

#2562 feat: store cli flags in configmap for autoupgrade
  cmd/kots/cli/install.go
  pkg/kotsadm/objects/configmaps_objects.go
  pkg/kotsadm/types/deployoptions.go
Labels: type::feature, team::orange

#2563 Automatic admin console updates
  cmd/kotsadm/cli/api.go
  go.mod
  go.sum
  pkg/api/downstream/types/types.go
  pkg/handlers/deploy.go
  pkg/handlers/handlers.go
  pkg/handlers/handlers_test.go
  pkg/handlers/interface.go
  pkg/handlers/mock/mock.go
  pkg/handlers/update.go
  pkg/handlers/update_test.go
  pkg/kotsadm/updates.go
  pkg/kotsadmupstream/upstream.go
  pkg/kotsutil/kots.go
  pkg/store/kotsstore/downstream_store.go
  pkg/store/kotsstore/version_store.go
  pkg/store/mock/mock.go
  pkg/store/ocistore/version_store.go
  pkg/store/store_interface.go
  pkg/upstream/replicated.go
  web/src/components/apps/AppDetailPage.jsx
  web/src/components/apps/AppVersionHistory.jsx
  web/src/components/apps/AppVersionHistoryRow.jsx
  web/src/components/apps/DashboardVersionCard.jsx
Labels: type::feature, team::orange

#2579 CLI to copy Admin Console images to private registry
  cmd/kots/cli/admin-console-push-images.go
  pkg/image/builder.go
  pkg/kotsadm/copy_images.go
  pkg/kotsadm/objects/images.go
  pkg/kotsadm/push_images.go
Labels: type::feature, team::orange

#2578 Remove noisy log
  pkg/kotsutil/kots.go
Labels: type::chore, team::orange

#2584 New state file for k3s test
  .github/workflows/regression.yaml
Labels: type::tests, team::orange

#2586 Copy kots images to private registry if one is configured during self-updates
  cmd/kots/cli/admin-console-push-images.go
  deploy/Dockerfile
  deploy/kots-upgrade.sh
  pkg/kotsadm/updates.go
  web/src/components/apps/AppVersionHistory.jsx
  web/src/components/apps/DashboardVersionCard.jsx
Labels: type::feature, team::orange

#2577 allow reupload of license if app is not installed
  pkg/automation/automation.go
  pkg/handlers/license.go
  pkg/handlers/mock/mock.go
  pkg/license/license.go
  pkg/store/kotsstore/app_store.go
  pkg/store/mock/mock.go
  pkg/store/ocistore/app_store.go
  pkg/store/store_interface.go
Labels: type::bug, bug::normal, team::orange

#2589 feat: add sequence-based auto-updates non-semver apps
  pkg/api/handlers/types/types.go
  pkg/app/types/types.go
  pkg/handlers/app.go
  pkg/handlers/deploy.go
  pkg/handlers/license.go
  pkg/handlers/update_checker_spec.go
  pkg/store/kotsstore/app_store.go
  pkg/store/mock/mock.go
  pkg/store/ocistore/app_store.go
  pkg/store/store_interface.go
  pkg/updatechecker/updatechecker.go
  web/src/components/apps/AppVersionHistory.jsx
  web/src/components/apps/Dashboard.jsx
  web/src/components/modals/AutomaticUpdatesModal.jsx
Labels: type::feature, team::orange

#2593 favicon on TLS pages
  kurl_proxy/assets/insecure.html
  kurl_proxy/assets/tls.html
Labels: type::bug, bug::normal, team::blue

#2596 Add resource limits for kotsadm
  okteto.yml
Labels: type::chore

#2595 parse installation parameters and pass to upgrade script
  deploy/kots-upgrade.sh
  pkg/kotsadm/updates.go
  pkg/kotsutil/kots.go
Labels: type::feature, team::orange

#2601 Only load the license for an app version if it's valid
  pkg/store/kotsstore/version_store.go
Labels: type::bug, bug::regression, team::orange

#2602 Kiraboyle/sc 43176/when installed with kurl the cluster management
  pkg/handlers/metadata.go
  web/src/Root.jsx
Labels: type::bug, team::orange

#2594 chore(ci): remove kots.io PR generation
  .github/workflows/release.yaml
Labels: type::chore, team::orange

#2598 Fix ngrok failures
  .github/workflows/build-test.yaml
  .gitignore
  Makefile.build
  deploy/build-test-pipeline/selenium-standalone.yaml
  kustomize/overlays/okteto/deployment.yaml
  migrations/deploy/Dockerfile
  web/.gitignore
  web/dist/README.md
  web/okteto.Dockerfile
  web/okteto.yml
Labels: type::bug, bug::normal

#2544 Block deployments when `strict` preflights fail
  .github/workflows/build-test.yaml
  go.sum
  kotskinds/multitype/boolstring.go
  kotskinds/multitype/boolstring_test.go
  pkg/airgap/airgap.go
  pkg/airgap/update.go
  pkg/api/downstream/types/types.go
  pkg/handlers/config.go
  pkg/handlers/identity.go
  pkg/handlers/mock/mock.go
  pkg/handlers/registry.go
  pkg/handlers/upload.go
  pkg/kotsadmupstream/upstream.go
  pkg/kotsutil/kots.go
  pkg/kotsutil/kots_test.go
  pkg/logger/logger.go
  pkg/online/online.go
  pkg/preflight/execute.go
  pkg/preflight/types/types.go
  pkg/store/kotsstore/downstream_store.go
  pkg/store/kotsstore/license_store.go
  pkg/store/kotsstore/preflight_store.go
  pkg/store/kotsstore/preflight_store_test.go
  pkg/store/kotsstore/version_store.go
  pkg/store/mock/mock.go
  pkg/store/ocistore/version_store.go
  pkg/store/store_interface.go
  pkg/upload/upload.go
  pkg/version/version.go
  web/src/components/PreflightRenderer.jsx
  web/src/components/PreflightResultPage.jsx
  web/src/components/apps/AppDetailPage.jsx
  web/src/components/apps/AppVersionHistory.jsx
  web/src/components/apps/AppVersionHistoryRow.jsx
  web/src/components/apps/DashboardVersionCard.jsx
  web/src/scss/components/PreflightCheckPage.scss
  web/src/scss/utilities/base.scss
  web/src/scss/utilities/colors.scss
  web/src/scss/utilities/icons.scss
Labels: type::feature, team::blue

#2611 Trigger preflights after configuring the version
  pkg/airgap/airgap.go
  pkg/online/online.go
Labels: type::bug, bug::regression, team::orange

#2608 Allow specifying version label at initial install
  cmd/kots/cli/install.go
  pkg/airgap/airgap.go
  pkg/automation/automation.go
  pkg/handlers/license.go
  pkg/kotsadm/objects/configmaps_objects.go
  pkg/kotsadm/types/deployoptions.go
  pkg/kotsutil/kots.go
  pkg/online/online.go
  pkg/online/types/types.go
  pkg/pull/pull.go
  pkg/upstream/fetch.go
  pkg/upstream/replicated.go
  pkg/upstream/replicated_test.go
  pkg/upstream/types/types.go
Labels: type::feature, team::orange

#2619 Respect semver ordering when garbage collecting images
  pkg/api/downstream/types/types.go
  pkg/registry/images.go
  pkg/store/kotsstore/downstream_store.go
  pkg/store/kotsstore/version_store.go
  pkg/store/mock/mock.go
  pkg/store/ocistore/version_store.go
  pkg/store/store_interface.go
Labels: type::bug, bug::normal, team::orange

#2621 Test for app-version-label cli flag
  .github/workflows/build-test.yaml
Labels: type::tests, team::orange

#2622 Improve status informers to detect updates
  pkg/appstate/deployments.go
  pkg/appstate/statefulsets.go
  pkg/appstate/types/types.go
  pkg/appstate/types/types_test.go
  web/src/components/apps/AppStatus.jsx
  web/src/components/apps/Dashboard.jsx
  web/src/scss/components/watches/Dashboard.scss
Labels: type::feature, team::orange

#2618 Updated the Readme links from kots.io to docs.replicated.com
  README.md
Labels: type::docs

#2623 Fix k3s regession test
  .github/workflows/regression.yaml
Labels: type::bug, bug::normal

#2638 log every time that an app version is deployed
  pkg/version/version.go
Labels: type::feature, team::support

#2607 Better error messages for restores
  pkg/operator/operator.go
Labels: type::chore, team::orange

#2636 fix nil pointer panic for NFS snapshots
  pkg/handlers/snapshots.go
Labels: type::bug, bug::regression, team::orange

#2643 Upload support bundle to s3 when testim tests fail
  .github/workflows/build-test.yaml
Labels: type::chore, team::blue

#2640 make fetchSnapshotSettings wait for response
  web/src/components/snapshots/SnapshotSettings.jsx
Labels: type::bug, bug::regression, team::orange

#2648 Pull version specific metadata if specified when installing app
  cmd/kots/cli/install.go
  pkg/pull/pull.go
  pkg/upstream/replicated.go
Labels: type::bug, bug::normal, team::orange

#2645 Allow overriding requireMinimalRBAC during install time
  cmd/kots/cli/install.go
  kotskinds/apis/kots/v1beta1/application_types.go
  kotskinds/config/crds/kots.io_airgaps.yaml
  kotskinds/config/crds/kots.io_applications.yaml
  kotskinds/config/crds/kots.io_configs.yaml
  kotskinds/config/crds/kots.io_configvalues.yaml
  kotskinds/config/crds/kots.io_helmcharts.yaml
  kotskinds/config/crds/kots.io_identities.yaml
  kotskinds/config/crds/kots.io_identityconfigs.yaml
  kotskinds/config/crds/kots.io_ingressconfigs.yaml
  kotskinds/config/crds/kots.io_installations.yaml
  kotskinds/config/crds/kots.io_licenses.yaml
  kotskinds/schemas/application-kots-v1beta1.json
  kotskinds/schemas/config-kots-v1beta1.json
  kotskinds/schemas/helmchart-kots-v1beta1.json
  kotskinds/schemas/identity-kots-v1beta1.json
  kotskinds/schemas/license-kots-v1beta1.json
  pkg/kotsadm/api.go
  pkg/kotsadm/kotsadm.go
  pkg/kotsadm/kotsadm_test.go
  pkg/kotsadm/main.go
  pkg/kotsadm/objects/configmaps_objects.go
  pkg/kotsadm/types/deployoptions.go
  pkg/kotsutil/kots.go
Labels: type::feature, team::orange

#2664 Test for minimal RBAC command line override
  .github/workflows/build-test.yaml
Labels: type::tests, team::orange

#2668 add validate-minimal-rbac-override to validate-success step
  .github/workflows/build-test.yaml
Labels: type::tests, team::orange

#2667 add a lock when updating the support bundle secret during generation
  pkg/store/kotsstore/supportbundle_store.go
Labels: type::bug, bug::normal, team::orange

#2669 --kotsadm 2h instead of 12h for e2e tests
  .github/workflows/build-test.yaml
Labels: team::orange

#2674 fix: addresses snapshot UI bugs indicating velero is not installed
  pkg/handlers/snapshots.go
  web/src/components/snapshots/SnapshotSchedule.jsx
  web/src/components/snapshots/SnapshotStorageDestination.jsx
Labels: type::bug, bug::regression, team::orange

#2662 handle css in grid of graphs better when scaling beyond three graphs
  web/src/components/apps/DashboardGraphsCard.jsx
  web/src/scss/components/watches/DashboardCard.scss
Labels: type::bug, bug::regression, team::blue

#2676 better offset for clicking to config elements
  web/src/scss/utilities/base.scss
Labels: type::chore, team::blue

#2675 add a contour-specific pod health check
  go.mod
  go.sum
  pkg/supportbundle/defaultspec/spec.yaml
Labels: type::feature, team::support

#2614 Ability to make a KOTS application version required and blocking
  kotskinds/apis/kots/v1beta1/airgap_types.go
  kotskinds/apis/kots/v1beta1/installation_types.go
  kotskinds/config/crds/kots.io_installations.yaml
  kotskinds/schemas/installation-kots-v1beta1.json
  migrations/tables/app_version.yaml
  pkg/airgap/update.go
  pkg/airgap/update_test.go
  pkg/api/downstream/types/types.go
  pkg/api/downstream/types/types_test.go
  pkg/api/version/types/types.go
  pkg/base/templates.go
  pkg/config/config_test.go
  pkg/cursor/cursor.go
  pkg/handlers/app.go
  pkg/handlers/config.go
  pkg/handlers/deploy.go
  pkg/handlers/download.go
  pkg/handlers/gitops.go
  pkg/handlers/handlers.go
  pkg/handlers/handlers_test.go
  pkg/handlers/interface.go
  pkg/handlers/mock/mock.go
  pkg/kotsadmupstream/upstream.go
  pkg/persistence/sqlite_schema.go
  pkg/pull/peek.go
  pkg/registry/images.go
  pkg/rewrite/rewrite.go
  pkg/store/kotsstore/downstream_store.go
  pkg/store/kotsstore/downstream_store_test.go
  pkg/store/kotsstore/version_store.go
  pkg/store/mock/mock.go
  pkg/store/ocistore/downstream_store.go
  pkg/store/ocistore/version_store.go
  pkg/store/store_interface.go
  pkg/template/version_context.go
  pkg/template/version_context_test.go
  pkg/updatechecker/updatechecker.go
  pkg/updatechecker/updatechecker_test.go
  pkg/upstream/fetch.go
  pkg/upstream/fetch_test.go
  pkg/upstream/replicated.go
  pkg/upstream/types/types.go
  pkg/upstream/write.go
  pkg/version/version.go
  web/src/components/apps/AppConfig.jsx
  web/src/components/apps/AppDetailPage.jsx
  web/src/components/apps/AppVersionHistory.jsx
  web/src/components/apps/AppVersionHistoryRow.jsx
  web/src/components/apps/Dashboard.jsx
  web/src/components/apps/DashboardVersionCard.jsx
  web/src/scss/utilities/base.scss
  web/src/utilities/airgapUploader.js
  web/src/utilities/utilities.js
Labels: type::feature, team::orange

#2678 Update kotskinds
  kotskinds/apis/kots/v1beta1/zz_generated.deepcopy.go
  kotskinds/config/crds/kots.io_airgaps.yaml
  kotskinds/schemas/airgap-kots-v1beta1.json
Labels: type::chore, team::orange

#2633 fix: update community license className and remove unused classes
  web/src/components/apps/DashboardLicenseCard.jsx
  web/src/scss/components/apps/AppLicense.scss
  web/src/scss/components/watches/DashboardCard.scss
Labels: type::bug, bug::normal, team::blue

#2680 Grayson/automatic updates weird behavior
  web/src/components/apps/AppVersionHistory.jsx
  web/src/components/apps/Dashboard.jsx
Labels: type::bug, bug::regression, team::blue

#2681 Make sure version status is "pending" before deploying
  go.sum
  pkg/airgap/airgap.go
  pkg/handlers/config.go
  pkg/online/online.go
  pkg/operator/operator.go
  pkg/preflight/preflight.go
  pkg/store/kotsstore/downstream_store.go
  pkg/store/mock/mock.go
  pkg/store/ocistore/downstream_store.go
  pkg/store/store_interface.go
Labels: type::bug, bug::normal, team::orange

#2682 move version action button tooltip outside of the button
  web/src/components/apps/AppVersionHistoryRow.jsx
  web/src/components/apps/DashboardVersionCard.jsx
Labels: type::tests
