Repository replicatedhq/kots, pull requests merged in 2022-10, with the labels that each got.

#3241 Validate kurl add-on changes on pull request
  .github/actions/kurl-addon-kots-generate/action.yml
  .github/actions/kurl-addon-kots-test/action.yml
  .github/workflows/build-test.yaml
  .github/workflows/kurl-addon-kots-generate.yaml
  .github/workflows/kurl-addon-kots-publish.yaml
  .github/workflows/kurl-addon-kots-test.yaml
  deploy/kurl/kotsadm/template/base/Manifest
  deploy/kurl/kotsadm/template/base/deployment/kotsadm-deployment.yaml
  deploy/kurl/kotsadm/template/base/install.sh
  deploy/kurl/kotsadm/template/base/kotsadm-postgres-rename-pvc.yaml
  deploy/kurl/kotsadm/template/base/kurl-proxy/tmpl-deployment.yaml
  deploy/kurl/kotsadm/template/base/statefulset/kotsadm-statefulset.yaml
  deploy/kurl/kotsadm/template/base/statefulset/patches/s3-migration.yaml
  deploy/kurl/kotsadm/template/generate.sh
Labels: type::chore

#3248 Pass in custom testgrid os spec to validate kurl add-on
  .github/actions/kurl-addon-kots-test/action.yml
  deploy/kurl/kotsadm/testgrid-os-spec.yaml
Labels: type::chore

#3249 Test kURL add-on on merge and release
  .github/actions/kurl-addon-kots-publish/action.yml
  .github/workflows/kurl-addon-kots-publish.yaml
  .github/workflows/release.yaml
Labels: type::chore

#3251 Conditionally test kurl addon on merge to main if changes to deploy/kurl
  .github/workflows/release.yaml
Labels: type::chore

#3247 Rianfowler/sc 59400/add typechecks to dashboard child components app status
  web/src/components/apps/AppStatus.tsx
  web/src/types/index.ts
Labels: type::chore, team::orange

#3253 Use kURL kotsadm add-on package for release regression tests
  .github/workflows/regression.yaml
  .github/workflows/release.yaml
Labels: type::chore

#3243 Rianfowler/sc 50084/fix multi app ux
  web/src/Root.tsx
  web/src/components/apps/AppDetailPage.tsx
  web/src/components/apps/AppStatus.tsx
  web/src/components/shared/SubNavBar/SubNavBar.jsx
  web/src/types/index.ts
Labels: type::bug, bug::normal, team::orange

#3257 Fix identity service login
  web/src/features/Auth/components/SecureAdminConsole.tsx
Labels: type::bug, bug::regression, team::orange

#3252 Rianfowler/sc 59400/add typechecks to dashboard child components dashboard version card
  web/src/components/Icon.tsx
  web/src/components/apps/DashboardVersionCard.tsx
  web/src/components/shared/modals/HelmDeployModal.tsx
  web/src/types/index.ts
Labels: type::chore, team::orange

#3259 KOTS add-on kURL dev environment
  .github/workflows/build-test.yaml
  .github/workflows/release.yaml
  deploy/kurl/kotsadm/.gitignore
  deploy/kurl/kotsadm/hack/.gitignore
  deploy/kurl/kotsadm/hack/Makefile
  deploy/kurl/kotsadm/hack/README.md
  deploy/kurl/kotsadm/hack/installer.yaml
Labels: type::chore

#3258 add cleanup to useEffect
  web/src/Root.tsx
Labels: type::bug, bug::regression, team::orange

#3254 Rianfowler/sc 50084/fix multi app ux 2
  web/src/Root.tsx
  web/src/components/apps/AppDetailPage.tsx
  web/src/components/context/withTheme.jsx
  web/src/features/App/hooks/useCurrentApp.test.jsx
  web/src/features/App/hooks/useCurrentApp.tsx
  web/src/features/App/index.ts
  web/src/features/AppVersionHistory/api/getVersions.jsx
Labels: type::chore, team::orange

#3267 Miawong/add typecheck version history
  web/src/components/Icon.tsx
  web/src/components/apps/AppVersionHistory.tsx
  web/src/components/shared/modals/HelmDeployModal.tsx
  web/src/types/index.ts
Labels: type::chore

#3268 Release regression tests not running because of kurl add-on changes
  .github/workflows/release.yaml
Labels: type::chore

#3270 No kots binary in dev env
  deploy/kurl/kotsadm/hack/Makefile
  deploy/kurl/kotsadm/template/base/install.sh
Labels: type::chore

#3271 Add kots binary to the kurl add-on dev environment
  deploy/kurl/kotsadm/hack/Makefile
Labels: type::chore

#3198 Add GVK for LintConfig
  kotskinds/Makefile
  kotskinds/apis/kots/v1beta1/lintconfig_types.go
  kotskinds/apis/kots/v1beta1/zz_generated.deepcopy.go
  kotskinds/client/kotsclientset/typed/kots/v1beta1/fake/fake_kots_client.go
  kotskinds/client/kotsclientset/typed/kots/v1beta1/fake/fake_lintconfig.go
  kotskinds/client/kotsclientset/typed/kots/v1beta1/generated_expansion.go
  kotskinds/client/kotsclientset/typed/kots/v1beta1/kots_client.go
  kotskinds/client/kotsclientset/typed/kots/v1beta1/lintconfig.go
  kotskinds/config/crds/kots.io_lintconfigs.yaml
  kotskinds/schemagen/cli/root.go
  kotskinds/schemas/lintconfigs-kots-v1beta1.json
Labels: type::feature

#3272 Cleanup kurl addon github actions
  .github/actions/kurl-addon-kots-publish/action.yml
  .github/actions/kurl-addon-kots-test/action.yml
  .github/workflows/build-test.yaml
  .github/workflows/kurl-addon-kots-test.yaml
  .github/workflows/release.yaml
Labels: type::chore

#3276 Miawong/typecheck dashboard license card
  web/src/components/apps/AppLicense.tsx
  web/src/components/apps/Dashboard.tsx
  web/src/components/apps/DashboardLicenseCard.tsx
  web/src/types/index.ts
Labels: type::chore

#3277 do not filter tabs in kots managed
  web/src/components/apps/AppVersionHistory.tsx
  web/src/components/apps/DashboardVersionCard.tsx
Labels: type::bug, bug::regression, team::orange

#3269 Use custom resources for the identity service (Dex) instead of Postgres
  cmd/kotsadm/cli/api.go
  deploy/kurl/kotsadm/template/base/deployment/kotsadm-deployment.yaml
  deploy/kurl/kotsadm/template/base/install.sh
  deploy/kurl/kotsadm/template/base/statefulset/kotsadm-statefulset.yaml
  deploy/kurl/kotsadm/template/base/tmpl-secret-dex-postgres.yaml
  go.mod
  go.sum
  kotskinds/apis/kots/v1beta1/identityconfig_types.go
  kotskinds/apis/kots/v1beta1/zz_generated.deepcopy.go
  kotskinds/config/crds/kots.io_identityconfigs.yaml
  kotskinds/schemas/identityconfigs-kots-v1beta1.json
  kustomize/overlays/dev/configmap-init-dex-db.yaml
  kustomize/overlays/dev/deployment.yaml
  kustomize/overlays/dev/dex-postgres-secret.yaml
  kustomize/overlays/dev/kustomization.yaml
  kustomize/overlays/okteto/configmap-init-dex-db.yaml
  kustomize/overlays/okteto/deployment.yaml
  kustomize/overlays/okteto/dex-postgres-secret.yaml
  kustomize/overlays/okteto/kustomization.yaml
  pkg/airgap/airgap.go
  pkg/airgap/update.go
  pkg/apiserver/bootstrap.go
  pkg/apiserver/server.go
  pkg/handlers/identity.go
  pkg/identity/config.go
  pkg/identity/deploy.go
  pkg/identity/deploy/client_secret.go
  pkg/identity/deploy/deploy.go
  pkg/identity/deploy/dex.go
  pkg/identity/deploy/postgres.go
  pkg/identity/deploy/render.go
  pkg/identity/deploy/theme.go
  pkg/identity/migrate/migrate.go
  pkg/identity/types/dex/sql.go
  pkg/identity/types/types.go
  pkg/ingress/ingress_config.go
  pkg/kotsadm/main.go
  pkg/kotsadm/objects/kotsadm_objects.go
  pkg/kotsadm/secrets.go
  pkg/kotsadmidentity/identityconfig.go
  pkg/kotsadmidentity/postgres.go
  pkg/kotsadmidentity/store/interface.go
  pkg/kotsadmidentity/store/k8s.go
  pkg/kotsadmidentity/store/postgres.go
  pkg/kotsadmidentity/store/store.go
  pkg/kotsadmupstream/upstream.go
  pkg/midstream/identity.go
  pkg/online/online.go
  pkg/pull/pull.go
  pkg/tests/pull/cases/samechartvariations/upstream/userdata/identityconfig.yaml
  pkg/tests/pull/cases/samechartvariations/wantResults/upstream/userdata/identityconfig.yaml
  pkg/upstream/types/types.go
  pkg/upstream/write.go
Labels: type::feature

#3282 Don't light up version rows every time Version History page is opened
  pkg/handlers/app.go
  pkg/helm/charts.go
  pkg/helm/helm.go
  pkg/helm/updates.go
  pkg/updatechecker/updatechecker.go
Labels: type::bug, bug::normal

#3283 NO_PROXY env value invalid yaml with starts with comma
  deploy/kurl/kotsadm/template/base/deployment/tmpl-kotsadm-proxy.yaml
  deploy/kurl/kotsadm/template/base/install.sh
  deploy/kurl/kotsadm/template/base/statefulset/tmpl-kotsadm-proxy.yaml
Labels: type::bug, bug::normal

#3278 add typechecks to dashboard snapshots card
  web/src/components/apps/DashboardSnapshotsCard.tsx
Labels: type::chore

#3274 Support Ed25519 for GitOps authentication
  go.mod
  go.sum
  pkg/gitops/gitops.go
  pkg/gitops/gitops_test.go
Labels: type::feature

#3287 Fix OIDC login
  web/src/Root.tsx
Labels: type::bug, bug::regression, team::orange

#3285 Miawong/typecheck dashboard graphs
  web/src/components/apps/DashboardGraphsCard.tsx
  web/src/types/index.ts
Labels: type::chore

#3288 Timeout abandoned running bundles
  pkg/store/kotsstore/supportbundle_store.go
  pkg/store/kotsstore/supportbundle_store_test.go
  pkg/supportbundle/execute.go
  web/src/components/troubleshoot/GenerateSupportBundle.jsx
Labels: type::bug, bug::normal

#3284 allow custom graphs to be templated
  .github/workflows/require-pr-labels.yaml
  pkg/handlers/dashboard.go
  pkg/version/metrics.go
  pkg/version/metrics_test.go
Labels: type::feature, type::improvement

#3085 Automated Kubectl version update
  deploy/Dockerfile
Labels: automated-pr, type::chore, kubectl

#3290 Adds typechecking to AutomaticUpdatesModal
  web/src/components/modals/AutomaticUpdatesModal.tsx
  web/src/types/index.ts
Labels: type::chore

#3296 use resource.Value() to compute pod capacity
  pkg/kurl/kurl_nodes.go
  pkg/kurl/kurl_nodes_test.go
Labels: type::bug, bug::normal

#3297 init plugin command with preflight stub
  cmd/kots/cli/plugin.go
  cmd/kots/cli/preflight.go
  cmd/kots/cli/root.go
Labels: type::chore

#3292 Rianfowler/sc 50084/fix multi app ux 5
  web/src/Root.tsx
  web/src/components/apps/AppDetailPage.tsx
  web/src/components/apps/AppVersionHistory.tsx
  web/src/components/shared/NavBar.jsx
  web/src/features/App/api/getApps.tsx
  web/src/features/App/hooks/useCurrentApp.tsx
  web/src/features/App/hooks/useSelectedApp.test.jsx
  web/src/features/App/hooks/useSelectedApp.tsx
  web/src/features/App/index.ts
  web/src/features/AppVersionHistory/api/getVersions.jsx
  web/src/features/AppVersionHistory/api/getVersions.test.jsx
Labels: type::chore, team::orange

#3216 Automated Kots Image Dependency Tag Update
  .image.env
  Makefile
  migrations/Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#3302 style GitHub and GitOps in pascal calse
  .github/dependabot.yml
  cmd/imagedeps/README.md
  pkg/handlers/handlers.go
  pkg/policy/policies.go
  web/src/components/Head/KotsPageTitle.tsx
  web/src/components/apps/AppVersionHistory.tsx
  web/src/components/apps/DashboardVersionCard.tsx
  web/src/components/gitops/GitOpsFlowIllustration.jsx
  web/src/features/Gitops/components/SetupProvider.jsx
Labels: type::bug, bug::normal

#3301 convert applicense into functional component
  web/src/components/apps/AppLicense.tsx
Labels: type::chore

#3307 use fetch state instead of loading state to trigger redirect and remo…
  web/src/components/apps/AppDetailPage.tsx
  web/src/components/apps/DashboardGraphsCard.tsx
  web/src/components/shared/ConfigureGraphs.tsx
Labels: type::bug, bug::regression, team::orange

#3300 make dashboard version card a functional component
  web/src/components/apps/Dashboard.tsx
  web/src/components/apps/DashboardVersionCard.tsx
Labels: type::chore

#3306 Miawong/add slow loader state to license api
  web/package.json
  web/src/components/apps/Dashboard.tsx
  web/src/components/apps/DashboardLicenseCard.tsx
  web/src/components/apps/LicenseTester.jsx
  web/src/features/App/api/getLicense.ts
  web/src/features/App/api/useLicense.ts
  web/webpack.config.js
  web/yarn.lock
Labels: type::bug, bug::regression

#3314 update LVP to v0.3.9 to resolve CVE-2022-37434
  .image.env
  Makefile
  pkg/image/constants.go
Labels: type::security

#3308 Miawong/sc 60191/standardize the look of the gitops page
  web/src/features/Gitops/components/AppGitops.jsx
  web/src/features/Gitops/components/AppSelector.jsx
  web/src/features/Gitops/components/GitOpsProviderSelector.jsx
  web/src/features/Gitops/components/GitOpsRepoDetails.jsx
  web/src/features/Gitops/components/SetupProvider.jsx
  web/src/features/Gitops/constants.js
  web/src/features/Gitops/utils.js
  web/src/scss/components/gitops/GitOpsDeploymentManager.scss
  web/src/scss/components/gitops/GitOpsSettings.scss
  web/src/scss/utilities/base.scss
Labels: type::feature

#3317 Rianfowler/add next-app-version hook and integrate into DashboardVersionCard
  web/src/components/UploadAirgapBundle.jsx
  web/src/components/apps/AppDetailPage.tsx
  web/src/components/apps/AppLicense.tsx
  web/src/components/apps/AppVersionHistory.tsx
  web/src/features/Dashboard/api/getNextAppVersion.ts
  web/src/features/Dashboard/api/useNextAppVersion.ts
  web/src/features/Dashboard/components/AirgapUploadProgress.jsx
  web/src/features/Dashboard/components/AppStatus.tsx
  web/src/features/Dashboard/components/Dashboard.tsx
  web/src/features/Dashboard/components/DashboardGitOpsCard.jsx
  web/src/features/Dashboard/components/DashboardGraphsCard.tsx
  web/src/features/Dashboard/components/DashboardLicenseCard.tsx
  web/src/features/Dashboard/components/DashboardSnapshotsCard.tsx
  web/src/features/Dashboard/components/DashboardVersionCard.tsx
  web/src/features/Dashboard/components/LicenseFields.tsx
  web/src/features/Dashboard/index.ts
  web/webpack.config.js
Labels: type::chore, team::orange

#3321 update schemahero to v0.13.5 to resolve CVE-2022-27664
  .image.env
  migrations/Makefile
  pkg/image/constants.go
Labels: type::security

#3304 diamonwiggins/troubleshoot-collect-interface
  .github/workflows/alpha.yaml
  .github/workflows/build-test.yaml
  .github/workflows/release.yaml
  deploy/okteto/okteto-v2.Dockerfile
  deploy/okteto/okteto.Dockerfile
  go.mod
  go.sum
  pkg/preflight/execute.go
  pkg/supportbundle/backup.go
Labels: type::chore

#3325 update skaffold cache dockerfile for go 1.19
  hack/dev/skaffoldcache.Dockerfile
Labels: type::chore

#3323 Rianfowler/sc 50084/convert Dashboard into functional component
  web/src/components/apps/AppDetailPage.tsx
  web/src/features/Dashboard/components/Dashboard.tsx
  web/src/features/Dashboard/index.ts
Labels: type::chore, team::orange

#3328 add license hook to applicense component
  web/src/components/apps/AppLicense.tsx
  web/src/features/App/api/getLicense.ts
  web/src/features/App/api/useLicense.ts
  web/src/features/App/index.ts
  web/src/features/AppVersionHistory/api/getVersions.test.jsx
  web/src/types/index.ts
Labels: type::chore, team::orange

#3329 convert DashboardLicenseCard into functional component
  web/src/features/Dashboard/components/DashboardLicenseCard.tsx
Labels: type::chore, team::orange

#3326 Rianfowler/sc 50084/ add and integrate /dashboard hook
  web/src/features/App/api/getApps.tsx
  web/src/features/Dashboard/api/getSelectedAppClusterDashboard.ts
  web/src/features/Dashboard/api/useSelectedAppClusterDashboard.ts
  web/src/features/Dashboard/components/Dashboard.tsx
  web/src/features/Dashboard/components/DashboardGraphsCard.tsx
Labels: type::chore, team::orange

#3331 Allow upgrading chart after license is synced
  web/src/components/apps/AppDetailPage.tsx
  web/src/components/apps/AppLicense.tsx
Labels: type::feature

#3334 fetch metadata before login
  web/src/Root.tsx
Labels: type::bug, bug::regression, team::orange

#3332 Revert "init plugin command with preflight stub"
  cmd/kots/cli/plugin.go
  cmd/kots/cli/preflight.go
  cmd/kots/cli/root.go
Labels: type::chore

#3263 Nickmeyer/sc 53201/fossa pr license check
  .fossa.yml
  .github/workflows/pr-license-scan.yaml
  README.md
  web/package.json
  web/yarn.lock
Labels: type::chore

#3327 update lvp and minio image deps
  .image.env
  Makefile
  pkg/image/constants.go
Labels: type::security

#3330 Use release timestamps from chart instead of current time
  pkg/api/downstream/types/types.go
  pkg/handlers/app.go
  pkg/helm/charts.go
  pkg/helm/helm.go
  pkg/helm/updates.go
  pkg/updatechecker/updatechecker.go
  web/src/features/AppVersionHistory/AppVersionHistoryRow.jsx
Labels: type::bug, bug::normal

#3336 fix airgap uploader
  web/src/features/Dashboard/components/Dashboard.tsx
Labels: type::bug, bug::regression

#3338 Match created_at path with where the timestamp actually is
  pkg/helm/charts.go
Labels: type::bug, bug::normal

#3337 Troubleshoot flannel collectors and analyzers
  pkg/supportbundle/defaultspec/spec.yaml
Labels: type::feature

#3340 remove withRouter from BackupRestore
  web/src/components/BackupRestore.jsx
Labels: type::chore, team::orange

#3339 remove unneccessary withRouter calls
  web/src/components/AirgapUploadProgress.jsx
  web/src/components/LicenseUploadProgress.jsx
  web/src/components/apps/AppDetailPage.tsx
  web/src/components/apps/AppIdentityServiceSettings.jsx
  web/src/components/apps/ClusterNodes.jsx
  web/src/components/clusters/GitOps.jsx
  web/src/components/identity/ConfigureIngress.jsx
  web/src/components/identity/IdentityProviders.jsx
  web/src/components/shared/Footer.jsx
  web/src/components/snapshots/SnapshotStorageDestination.tsx
  web/src/components/troubleshoot/PodAnalyzerDetails.jsx
  web/src/components/troubleshoot/TroubleshootContainer.tsx
  web/src/features/Dashboard/components/AirgapUploadProgress.jsx
  web/src/features/Gitops/GitOpsDeploymentManager.jsx
Labels: type::chore, team::orange

#3341 fix some type errors, remove withRouter from PreflightResultErrors
  web/src/components/PreflightResultErrors.jsx
  web/src/components/PreflightResultErrors.tsx
Labels: type::chore, team::orange

#3333 Rianfowler/sc 50084/add license hook and show loading when apis are responding slowly
  web/src/features/App/api/getLicense.ts
  web/src/features/App/api/useLicense.ts
  web/src/features/Dashboard/api/getNextAppVersion.ts
  web/src/features/Dashboard/api/useNextAppVersion.ts
  web/src/features/Dashboard/api/useSelectedAppClusterDashboard.ts
  web/src/features/Dashboard/components/Dashboard.tsx
  web/src/features/Dashboard/components/DashboardLicenseCard.tsx
  web/src/features/Dashboard/components/DashboardVersionCard.tsx
Labels: type::chore, team::orange

#3286 collect namespace from flag or kubeconfig context
  .github/workflows/build-test.yaml
  cmd/kots/cli/admin-console-generate-manifests.go
  cmd/kots/cli/admin-console-push-images.go
  cmd/kots/cli/admin-console-upgrade.go
  cmd/kots/cli/admin-console.go
  cmd/kots/cli/app-status.go
  cmd/kots/cli/backup.go
  cmd/kots/cli/check-version.go
  cmd/kots/cli/docker.go
  cmd/kots/cli/download.go
  cmd/kots/cli/garbage-collect-images.go
  cmd/kots/cli/get-apps.go
  cmd/kots/cli/get-backups.go
  cmd/kots/cli/get-config.go
  cmd/kots/cli/get-restores.go
  cmd/kots/cli/get-versions.go
  cmd/kots/cli/identity.go
  cmd/kots/cli/ingress.go
  cmd/kots/cli/namespace.go
  cmd/kots/cli/pull.go
  cmd/kots/cli/remove.go
  cmd/kots/cli/reset-password.go
  cmd/kots/cli/reset-tls.go
  cmd/kots/cli/restore.go
  cmd/kots/cli/set-config.go
  cmd/kots/cli/upload.go
  cmd/kots/cli/upstream-download.go
  cmd/kots/cli/upstream-upgrade.go
  cmd/kots/cli/velero.go
Labels: type::bug, bug::normal

#3347 fix: installing/updating/configuring applications that have many kots kinds images hangs or takes a really long time
  pkg/image/builder.go
Labels: type::bug, bug::regression

#3346 remove withRouter from Access component
  web/src/Root.tsx
  web/src/components/identity/Access.tsx
Labels: type::chore, team::orange

#3351 replace env vars and iniit containers instead of merging
  pkg/k8sutil/util.go
  pkg/kotsadm/objects/kotsadm_objects.go
  pkg/kotsadm/rqlite.go
Labels: type::bug, bug::normal

#3350 Update FOSSA API key
  .github/workflows/pr-license-scan.yaml
Labels: type::chore

#3343 Remove withRouter from UploadAirgapBundle
  web/src/components/UploadAirgapBundle.jsx
  web/src/components/UploadAirgapBundle.tsx
Labels: type::chore, team::orange

#3352 Rianfowler/sc 59398/remove withRouter from EditRedactor
  web/src/components/redactors/EditRedactor.jsx
  web/src/components/redactors/EditRedactor.tsx
  web/src/components/troubleshoot/TroubleshootContainer.tsx
  web/src/types/index.ts
Labels: type::chore, team::orange

#3365 Revert "Remove withRouter from UploadAirgapBundle"
  web/src/components/UploadAirgapBundle.jsx
  web/src/components/UploadAirgapBundle.tsx
Labels: type::bug, bug::regression, team::orange

#3366 No longer trigger kotsadm kurl package build as it is an external add-on
  .github/workflows/alpha.yaml
  .github/workflows/release.yaml
Labels: type::chore

#3348 Don't keep polling preflight status when preflights are not running
  cmd/kots/cli/install_test.go
  pkg/preflight/execute.go
  pkg/preflight/preflight.go
  pkg/preflight/preflight_test.go
  pkg/preflight/types/types.go
  pkg/updatechecker/updatechecker.go
  web/src/components/PreflightResultErrors.tsx
  web/src/components/PreflightResultPage.jsx
Labels: type::bug, bug::normal

#3354 clean up unused hostpath and nfs volumes
  .image.env
  Makefile
  pkg/image/constants.go
  pkg/snapshot/filesystem.go
  pkg/snapshot/store.go
Labels: type::bug, bug::normal

#3368 remove console log
  web/src/features/Dashboard/components/Dashboard.tsx
Labels: type::chore, team::orange

#3369 Sequence template function should return 0 for initial version
  pkg/handlers/config.go
Labels: type::bug, bug::normal

#3371 Update gorqlite connector to fix load balancing after scaling rqlite up to multiple replicas
  deploy/kurl/kotsadm/template/base/tmpl-secret-rqlite.yaml
  go.mod
  go.sum
  migrations/kustomize/overlays/dev/rqlite.yaml
  migrations/kustomize/overlays/okteto/rqlite.yaml
  pkg/kotsadm/objects/secrets_objects.go
Labels: type::bug, bug::normal

#3372 add unit test coverage for snapshot store
  pkg/snapshot/store.go
  pkg/snapshot/store_test.go
Labels: type::chore

#3377 change prometheus disk usage query
  pkg/version/metrics.go
Labels: type::bug, bug::normal
