Repository replicatedhq/kots, pull requests merged in 2023-03, with the labels that each got.

#3693 force removing app is implied when --undeploy is set
  .github/workflows/build-test.yaml
  pkg/handlers/app.go
Labels: type::feature, type::improvement

#3373 Automated Kots Image Dependency Tag Update
  .image.env
  Makefile
  migrations/Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#3698 add chore label to update-kubectl workflow
  .github/workflows/update-kubectl.yaml
Labels: type::chore

#3699 bump lvp to v0.5.1
  .image.env
  Makefile
  pkg/image/constants.go
Labels: type::security

#3686 Run private image checks concurrently to improve performance
  pkg/image/builder.go
Labels: type::feature, type::improvement

#3681 add actionlint and clean up deprecations [sc-70302]
  .github/actions/generate-support-bundle/action.yml
  .github/actions/kots-e2e/action.yml
  .github/actions/kurl-addon-kots-generate/action.yml
  .github/workflows/actionlint.yaml
  .github/workflows/alpha.yaml
  .github/workflows/build-test.yaml
  .github/workflows/e2e-infra-cleanup.yaml
  .github/workflows/e2e-workspace-cleanup.yaml
  .github/workflows/kurl-addon-kots-test.yaml
  .github/workflows/metrics.yml
  .github/workflows/regression.yaml
  .github/workflows/release.yaml
  .github/workflows/tag-helm-chart.yaml
  .github/workflows/update-kubectl.yaml
Labels: type::chore

#3687 Bug: add re-run button to preflight check
  web/src/components/PreflightResultPage.tsx
Labels: type::bug, bug::regression

#3705 stop using buildkite builder image for release web build
  .github/workflows/release.yaml
Labels: type::chore

#3711 fix cleanup workspace gather to address extra whitespace
  .github/workflows/e2e-infra-cleanup.yaml
Labels: type::chore

#3707 Rianfowler/sc 60124/investigate why eslint is not catching components
  web/package.json
  web/src/components/config_render/ConfigComponents.tsx
  web/src/components/hooks/index.ts
  web/src/components/layout/SidebarLayout/index.tsx
  web/src/components/shared/SideBar/index.tsx
  web/src/components/watches/WatchSidebarItem/index.tsx
  web/src/constants/rbac.ts
  web/src/features/AppConfig/styles/index.tsx
  web/src/features/AppVersionHistory/index.tsx
  web/src/features/Gitops/hooks/useApps.tsx
  web/src/hooks/usePrevious.tsx
  web/src/index.tsx
  web/src/stores/index.tsx
  web/src/styles/common.tsx
  web/webpack.config.dev.js
  web/webpack.config.dist.js
  web/yarn.lock
Labels: type::chore

#3712 fix accent color
  web/src/scss/variables.scss
Labels: type::bug, bug::regression

#3715 switch checkbox to using primary color css variable
  web/src/scss/components/apps/AppVersionHistory.scss
Labels: type::feature

#3721 Fix cleanup
  .github/workflows/e2e-infra-cleanup.yaml
Labels: type::chore

#3720 remove embedded-airgapped-install-k3s from cleanup list
  .github/workflows/e2e-workspace-cleanup.yaml
Labels: type::chore

#3719 remove accent color
  web/src/scss/components/forms/input.scss
  web/src/scss/components/forms/textarea.scss
  web/src/scss/components/shared/NavBar.scss
  web/src/scss/components/snapshots/AppSnapshots.scss
  web/src/scss/components/watches/WatchDetailPage.scss
  web/src/scss/utilities/colors.scss
  web/src/scss/utilities/forms.scss
  web/src/scss/variables.scss
Labels: type::feature

#3716 make file tree themeable
  web/src/scss/components/troubleshoot/FileTree.scss
  web/src/scss/variables.scss
Labels: type::feature

#3723 fix snapshot card styling
  web/src/features/Dashboard/components/DashboardSnapshotsCard.tsx
Labels: type::feature

#3713 break out build jobs [sc-70669]
  .github/workflows/build-test.yaml
  web/Makefile
Labels: type::chore

#3722 Rianfowler/sc 70719/cleanup various parts of custom branding make success warn failure themeable
  web/src/css/icon.css
  web/src/scss/components/PreflightCheckPage.scss
  web/src/scss/components/UploadLicenseFile.scss
  web/src/scss/components/apps/AppLicense.scss
  web/src/scss/components/apps/AppVersionHistory.scss
  web/src/scss/components/config-render/config-base-styles.scss
  web/src/scss/components/forms/input.scss
  web/src/scss/components/forms/select.scss
  web/src/scss/components/forms/textarea.scss
  web/src/scss/components/identity/IdentityManagement.scss
  web/src/scss/components/redactors/EditRedactor.scss
  web/src/scss/components/shared/MarkdownRenderer.scss
  web/src/scss/components/shared/NavBar.scss
  web/src/scss/components/shared/Warning.scss
  web/src/scss/components/snapshots/AppSnapshots.scss
  web/src/scss/components/state/StateFileViewer.scss
  web/src/scss/components/troubleshoot/GenerateSupportBundle.scss
  web/src/scss/components/troubleshoot/SupportBundleList.scss
  web/src/scss/components/troubleshoot/UploadSupportBundleModal.scss
  web/src/scss/components/watches/DashboardCard.scss
  web/src/scss/components/watches/WatchConfig.scss
  web/src/scss/utilities/base.scss
  web/src/scss/utilities/buttons.scss
  web/src/scss/utilities/colors.scss
  web/src/scss/utilities/overrides.scss
  web/src/scss/variables.scss
Labels: type::feature

#3726 Update troubleshoot to v0.58.0
  go.mod
  go.sum
Labels: type::chore

#3725 add csp headers to kurl_proxy
  kurl_proxy/cmd/main.go
  kurl_proxy/cmd/main_test.go
Labels: type::security

#3685 Miawong/sc 68585/refactor check for updates with hook
  web/src/features/Dashboard/api/getUpdates.ts
  web/src/features/Dashboard/components/Dashboard.tsx
Labels: type::chore

#3728 add typechecking to Loader
  web/src/components/shared/Loader.tsx
Labels: type::chore

#3731 make rollback button themeable
  web/src/features/AppVersionHistory/AppVersionHistoryRow.tsx
  web/src/scss/utilities/buttons.scss
Labels: type::feature

#3706 redesign preflight check
  web/src/components/PreflightResultErrors.tsx
  web/src/components/PreflightResultPage.tsx
Labels: type::feature

#3732 add type checking to Toggle and make it a functional component
  web/src/components/shared/Toggle.jsx
  web/src/components/shared/Toggle.tsx
Labels: type::chore

#3733 add typechecking to gitopsjsx
  web/src/Root.tsx
  web/src/components/Head/KotsPageTitle.tsx
  web/src/components/clusters/GitOps.tsx
Labels: type::chore

#3734 add typechecking to sidebarjsx
  web/src/components/shared/SideBar/SideBar.tsx
Labels: type::chore

#3737 bump helm v3 go mod to v3.11.2
  go.mod
  go.sum
Labels: type::security

#3742 KOTS CLI: when app port-forward port is not available, failure message are printed once and retry in silent
  pkg/k8sutil/portforward.go
Labels: type::feature

#3730 Automated Kots Image Dependency Tag Update
  .image.env
  Makefile
  migrations/Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#3754 use ed25519 keys for gitops configuration
  pkg/gitops/gitops.go
  pkg/gitops/gitops_test.go
  pkg/gitops/key.go
Labels: type::chore

#3758 bump load loader timeout to 2 minutes
  web/src/constants/timers.js
Labels: type::bug, bug::normal

#3755 remove hard coded nomad thing
  web/src/components/troubleshoot/SupportBundleAnalysis.jsx
Labels: type::bug, bug::normal

#3717 feat(support-bundle): simplify implementation handling the support bundle spec
  pkg/handlers/troubleshoot.go
  pkg/kotsadm/types/constants.go
  pkg/supportbundle/spec.go
  pkg/supportbundle/spec_test.go
  pkg/supportbundle/staticspecs/clusterspec.yaml
  pkg/supportbundle/staticspecs/defaultspec.yaml
  pkg/supportbundle/staticspecs/embed.go
  pkg/supportbundle/staticspecs/kurlspec.yaml
  pkg/supportbundle/staticspecs/vendorspec.yaml
  pkg/supportbundle/supportbundle.go
Labels: type::feature

#3760 migrate helm release version secrets to helm namespace
  .github/workflows/build-test.yaml
  pkg/helm/update_release.go
  pkg/helm/update_release_test.go
  pkg/operator/client/deploy.go
  pkg/operator/client/deploy_test.go
Labels: type::bug, bug::regression

#3764 update go mod golang.org/x/net to fix HIGH CVE-2022-41723
  .image.env
  Makefile
  kurl_proxy/go.mod
  kurl_proxy/go.sum
  migrations/Makefile
  pkg/image/constants.go
Labels: type::security

#3765 fix: use absolute path for kots.tar.gz kurl manifest asset
  .github/actions/kurl-addon-kots-generate/action.yml
  deploy/kurl/kotsadm/hack/Makefile
Labels: type::chore

#3768 chore: go fmt ./...
  pkg/base/helm.go
  pkg/base/helm_functions.go
  pkg/handlers/helm.go
  pkg/k8sutil/portforward.go
  web/webcontent.go
Labels: type::chore, skip-sc

#3750 Wrap log output
  web/src/components/modals/ShowLogsModal.jsx
Labels: type::feature, type::improvement

#3766 update kurl_proxy to use stronger cipher suites
  kurl_proxy/cmd/main.go
  kurl_proxy/go.mod
  kurl_proxy/go.sum
Labels: type::security

#3769 Fix: Preserve KOTS install ID on upgrades
  pkg/kotsadm/api.go
  pkg/kotsadm/main.go
  pkg/kotsadm/objects/configmaps_objects.go
Labels: type::bug, bug::normal

#3770 Fix json tags for app type
  pkg/app/types/app.go
Labels: type::chore

#3773 ignore secret already exists err when creating the helm release secret in release namespace
  pkg/helm/update_release.go
  pkg/helm/update_release_test.go
Labels: type::bug, bug::regression

#3775 install dependencies before running dev server
  web/okteto.yml
Labels: type::chore

#3776 change wording to include admin console
  web/src/features/Auth/components/SecureAdminConsole.tsx
Labels: type::feature

#3771 report when gitops is enabled/disabled
  pkg/api/reporting/types/types.go
  pkg/gitops/gitops.go
  pkg/gitops/gitops_test.go
  pkg/handlers/gitops.go
  pkg/reporting/app.go
  pkg/reporting/util.go
  web/src/features/Gitops/components/SetupProvider.jsx
Labels: type::feature
