Repository replicatedhq/kots, pull requests merged in 2023-04, with the labels that each got.

#3704 store helm release name with chart name secret
  pkg/helm/charts.go
Labels: type::bug, bug::normal

#3783 simplify airgap bundle upload text
  web/src/components/UploadAirgapBundle.jsx
Labels: type::feature

#3785 Miawong/sc 70876/convert info and snapshot get started to icon fonts
  web/src/components/selection.json
  web/src/components/snapshots/AppSnapshots.jsx
  web/src/components/snapshots/GettingStartedSnapshots.jsx
  web/src/components/snapshots/SnapshotSchedule.jsx
  web/src/features/AppConfig/components/ConfigInfo.jsx
Labels: type::feature

#3794 Sort multi app nav by createdBy date
  web/src/components/apps/AppDetailPage.tsx
  web/src/types/index.ts
Labels: type::feature, type::improvement

#3799 Rianfowler/sc 70387/improve spacing on config page to make it
  web/src/components/config_render/ConfigCheckbox.tsx
  web/src/components/config_render/ConfigFileInput.jsx
  web/src/components/config_render/ConfigGroup.jsx
  web/src/components/config_render/ConfigInput.jsx
  web/src/components/config_render/ConfigSelectOne.jsx
  web/src/components/config_render/ConfigTextarea.jsx
  web/src/scss/components/config-render/config-base-styles.scss
Labels: type::feature, type::improvement

#3791 Store instance reports in db for airgap installs
  migrations/tables/instance-report.yaml
  migrations/tables/preflight-report.yaml
  pkg/api/reporting/types/types.go
  pkg/handlers/deploy.go
  pkg/handlers/gitops.go
  pkg/handlers/mock/mock.go
  pkg/handlers/preflight.go
  pkg/online/online.go
  pkg/operator/client/client.go
  pkg/operator/operator.go
  pkg/preflight/preflight.go
  pkg/reporting/app.go
  pkg/reporting/app_airgap.go
  pkg/reporting/app_online.go
  pkg/reporting/preflight.go
  pkg/reporting/preflight_airgap.go
  pkg/reporting/preflight_online.go
  pkg/reporting/types.go
  pkg/reporting/util.go
  pkg/store/kotsstore/reporting_store.go
  pkg/store/mock/mock.go
  pkg/store/store_interface.go
  pkg/updatechecker/updatechecker.go
Labels: type::feature

#3796 update fossa config and workflow for faster/more reliable runs
  .fossa.yml
  .github/workflows/fossa.yaml
  .github/workflows/pr-license-scan.yaml
Labels: type::chore

#3804 Apply strict security contexts in OpenShift when specified
  pkg/identity/deploy/deploy.go
  pkg/k8sutil/openshift.go
  pkg/k8sutil/pod.go
  pkg/kotsadm/objects/distribution_objects.go
  pkg/kotsadm/objects/kotsadm_objects.go
  pkg/kotsadm/objects/minio_objects.go
  pkg/kotsadm/objects/rqlite_objects.go
  pkg/kotsadm/objects/shared_object_config.go
  pkg/kotsadmsnapshot/restore.go
  pkg/snapshot/restore.go
Labels: type::bug, bug::normal

#3793 upgrade to kustomize 5
  deploy/Dockerfile
  deploy/okteto/okteto-v2.Dockerfile
  deploy/okteto/okteto.Dockerfile
  hack/dev/skaffold.Dockerfile
  kustomize/overlays/dev/kustomization.yaml
  kustomize/overlays/kotsstore/kustomization.yaml
  kustomize/overlays/ocistore/kustomization.yaml
  pkg/base/write.go
  pkg/kotsutil/yaml.go
  pkg/kotsutil/yaml_test.go
  pkg/kustomize/app.go
  pkg/kustomize/helm.go
  pkg/tests/pull/cases/subchart-crds/upstream/my-chart-0.1.0.tgz
  pkg/tests/pull/cases/subchart-crds/wantResults/base/charts/my-chart-release/kustomization.yaml
  pkg/tests/pull/cases/subchart-crds/wantResults/base/charts/my-chart-release/templates/my-chart-pod.yaml
  pkg/tests/pull/cases/subchart-crds/wantResults/overlays/midstream/charts/my-chart-release/kustomization.yaml
  pkg/tests/pull/cases/subchart-crds/wantResults/overlays/midstream/charts/my-chart-release/pullsecrets.yaml
  pkg/tests/pull/cases/subchart-crds/wantResults/rendered/this-cluster/charts/my-chart-release/templates/my-app-my-chart-release-registry-secret.yaml
  pkg/tests/pull/cases/subchart-crds/wantResults/rendered/this-cluster/charts/my-chart-release/templates/my-chart-pod-pod.yaml
  pkg/tests/pull/cases/subchart-crds/wantResults/upstream/my-chart-0.1.0.tgz
Labels: type::security

#3812 bump helm binary to 3.11.3
  deploy/Dockerfile
  deploy/okteto/okteto-v2.Dockerfile
  deploy/okteto/okteto.Dockerfile
  hack/dev/skaffold.Dockerfile
Labels: type::security

#3790 Automated Kots Image Dependency Tag Update
  .image.env
  Makefile
  migrations/Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#3802 template namespace and helmUpgradeFlags
  pkg/kotsutil/kots.go
  pkg/operator/operator.go
  pkg/operator/operator_test.go
Labels: type::feature, type::improvement

#3814 calls to LoadKotsKindsFromPath use the "upstream" dir
  pkg/airgap/airgap.go
  pkg/airgap/update.go
  pkg/gitops/gitops.go
  pkg/handlers/config.go
  pkg/handlers/download.go
  pkg/handlers/identity.go
  pkg/handlers/preflight.go
  pkg/handlers/rendered_contents.go
  pkg/handlers/upload.go
  pkg/kotsadmconfig/config.go
  pkg/kotsadmlicense/license.go
  pkg/kotsadmsnapshot/backup.go
  pkg/kotsadmupstream/upstream.go
  pkg/online/online.go
  pkg/operator/operator.go
  pkg/preflight/preflight.go
  pkg/pull/pull.go
  pkg/registry/registry.go
  pkg/render/render.go
  pkg/reporting/app.go
  pkg/rewrite/rewrite.go
  pkg/store/kotsstore/migrations.go
  pkg/store/kotsstore/version_store.go
  pkg/supportbundle/supportbundle.go
  pkg/tests/base/render_test.go
  pkg/version/metrics.go
Labels: type::bug, bug::regression

#3809 Config Validation
  .github/workflows/build-test.yaml
  cmd/kots/cli/set-config.go
  e2e/e2e_test.go
  e2e/testim/inventory/inventory.go
  kotskinds/apis/kots/v1beta1/config_types.go
  kotskinds/apis/kots/v1beta1/zz_generated.deepcopy.go
  kotskinds/config/crds/kots.io_configs.yaml
  kotskinds/schemas/config-kots-v1beta1.json
  pkg/handlers/config.go
  pkg/kotsadmconfig/types/types.go
  pkg/kotsadmconfig/validation/config.go
  pkg/kotsadmconfig/validation/config_test.go
  pkg/kotsadmconfig/validation/interface.go
  pkg/kotsadmconfig/validation/regex.go
  pkg/kotsadmconfig/validation/regex_test.go
  pkg/kotsadmconfig/validation/validator.go
  pkg/kotsadmconfig/validation/validator_test.go
  pkg/print/config.go
  pkg/util/util.go
  web/src/components/config_render/ConfigFileInput.jsx
  web/src/components/config_render/ConfigGroup.jsx
  web/src/components/config_render/ConfigInput.jsx
  web/src/components/config_render/ConfigRender.jsx
  web/src/components/config_render/ConfigTextarea.jsx
  web/src/components/shared/forms/InputField.jsx
  web/src/features/AppConfig/components/AppConfig.tsx
  web/src/scss/components/config-render/config-base-styles.scss
  web/src/scss/components/shared/forms/InputField.scss
  web/src/scss/components/watches/WatchConfig.scss
Labels: type::chore

#3817 fix: loading kots kinds from airgap bundle
  pkg/pull/pull.go
Labels: type::bug, bug::regression

#3818 add check for when property at group and item level when determining required error state
  web/src/features/AppConfig/components/AppConfig.tsx
Labels: type::feature

#3819 ignore validation when group.when is false
  pkg/kotsadmconfig/validation/config.go
  pkg/kotsadmconfig/validation/config_test.go
  pkg/kotsadmconfig/validation/validator.go
  pkg/kotsadmconfig/validation/validator_test.go
Labels: type::bug, bug::normal

#3816 Fix reporting when app is not deployed
  pkg/store/kotsstore/reporting_store.go
Labels: type::bug, bug::normal

#3821 chore: modernize kurl testgrid spec
  deploy/kurl/kotsadm/template/testgrid/k8s-docker.yaml
Labels: type::chore

#3815 Update troubleshoot to v0.62.1
  go.mod
  go.sum
Labels: type::chore

#3824 ignore empty required value if there is a default value
  pkg/handlers/config.go
  pkg/kotsadmconfig/validation/config.go
  pkg/kotsadmconfig/validation/config_test.go
  pkg/kotsadmconfig/validation/validator_test.go
  web/src/features/AppConfig/components/AppConfig.tsx
Labels: type::bug, bug::regression

#3825 add warning if push-images airgap file doesn't exist
  cmd/kots/cli/admin-console-push-images.go
Labels: type::bug, bug::normal

#3827 Automated Kots Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#3831 Revert "add warning if push-images isn't given valid airgap file or u…
  cmd/kots/cli/admin-console-push-images.go
Labels: type::chore

#3749 change gke test to not use testim
  .github/workflows/build-test.yaml
Labels: type::chore, type::tests

#3833 fix: invalid kustomize for deeply nested subcharts
  pkg/base/helm.go
  pkg/tests/pull/cases/subchart-crds/upstream/my-chart-0.1.0.tgz
  pkg/tests/pull/cases/subchart-crds/wantResults/base/charts/my-chart-release/charts/my-sub-chart/charts/my-sub-sub-chart/Chart.yaml
  pkg/tests/pull/cases/subchart-crds/wantResults/base/charts/my-chart-release/charts/my-sub-chart/charts/my-sub-sub-chart/charts/my-sub-sub-sub-chart/Chart.yaml
  pkg/tests/pull/cases/subchart-crds/wantResults/base/charts/my-chart-release/charts/my-sub-chart/charts/my-sub-sub-chart/charts/my-sub-sub-sub-chart/kustomization.yaml
  pkg/tests/pull/cases/subchart-crds/wantResults/base/charts/my-chart-release/charts/my-sub-chart/charts/my-sub-sub-chart/charts/my-sub-sub-sub-chart/templates/my-subsubsubchart-pod.yaml
  pkg/tests/pull/cases/subchart-crds/wantResults/base/charts/my-chart-release/charts/my-sub-chart/charts/my-sub-sub-chart/kustomization.yaml
  pkg/tests/pull/cases/subchart-crds/wantResults/base/charts/my-chart-release/charts/my-sub-chart/charts/my-sub-sub-chart/templates/my-subsubchart-pod.yaml
  pkg/tests/pull/cases/subchart-crds/wantResults/base/charts/my-chart-release/values.yaml
  pkg/tests/pull/cases/subchart-crds/wantResults/overlays/downstreams/this-cluster/charts/my-chart-release/charts/my-sub-chart/charts/my-sub-sub-chart/charts/my-sub-sub-sub-chart/kustomization.yaml
  pkg/tests/pull/cases/subchart-crds/wantResults/overlays/downstreams/this-cluster/charts/my-chart-release/charts/my-sub-chart/charts/my-sub-sub-chart/kustomization.yaml
  pkg/tests/pull/cases/subchart-crds/wantResults/overlays/midstream/charts/my-chart-release/charts/my-sub-chart/charts/my-sub-sub-chart/backup-label-transformer.yaml
  pkg/tests/pull/cases/subchart-crds/wantResults/overlays/midstream/charts/my-chart-release/charts/my-sub-chart/charts/my-sub-sub-chart/charts/my-sub-sub-sub-chart/backup-label-transformer.yaml
  pkg/tests/pull/cases/subchart-crds/wantResults/overlays/midstream/charts/my-chart-release/charts/my-sub-chart/charts/my-sub-sub-chart/charts/my-sub-sub-sub-chart/kustomization.yaml
  pkg/tests/pull/cases/subchart-crds/wantResults/overlays/midstream/charts/my-chart-release/charts/my-sub-chart/charts/my-sub-sub-chart/charts/my-sub-sub-sub-chart/pullsecrets.yaml
  pkg/tests/pull/cases/subchart-crds/wantResults/overlays/midstream/charts/my-chart-release/charts/my-sub-chart/charts/my-sub-sub-chart/charts/my-sub-sub-sub-chart/secret.yaml
  pkg/tests/pull/cases/subchart-crds/wantResults/overlays/midstream/charts/my-chart-release/charts/my-sub-chart/charts/my-sub-sub-chart/kustomization.yaml
  pkg/tests/pull/cases/subchart-crds/wantResults/overlays/midstream/charts/my-chart-release/charts/my-sub-chart/charts/my-sub-sub-chart/pullsecrets.yaml
  pkg/tests/pull/cases/subchart-crds/wantResults/overlays/midstream/charts/my-chart-release/charts/my-sub-chart/charts/my-sub-sub-chart/secret.yaml
  pkg/tests/pull/cases/subchart-crds/wantResults/rendered/this-cluster/charts/my-chart-release/charts/my-sub-chart/charts/my-sub-sub-chart/Chart.yaml
  pkg/tests/pull/cases/subchart-crds/wantResults/rendered/this-cluster/charts/my-chart-release/charts/my-sub-chart/charts/my-sub-sub-chart/charts/my-sub-sub-sub-chart/Chart.yaml
  pkg/tests/pull/cases/subchart-crds/wantResults/rendered/this-cluster/charts/my-chart-release/charts/my-sub-chart/charts/my-sub-sub-chart/charts/my-sub-sub-sub-chart/templates/kotsadm-replicated-registry-secret.yaml
  pkg/tests/pull/cases/subchart-crds/wantResults/rendered/this-cluster/charts/my-chart-release/charts/my-sub-chart/charts/my-sub-sub-chart/charts/my-sub-sub-sub-chart/templates/my-app-my-sub-sub-sub-chart-registry-secret.yaml
  pkg/tests/pull/cases/subchart-crds/wantResults/rendered/this-cluster/charts/my-chart-release/charts/my-sub-chart/charts/my-sub-sub-chart/charts/my-sub-sub-sub-chart/templates/my-sub-sub-sub-chart-pod-pod.yaml
  pkg/tests/pull/cases/subchart-crds/wantResults/rendered/this-cluster/charts/my-chart-release/charts/my-sub-chart/charts/my-sub-sub-chart/templates/kotsadm-replicated-registry-secret.yaml
  pkg/tests/pull/cases/subchart-crds/wantResults/rendered/this-cluster/charts/my-chart-release/charts/my-sub-chart/charts/my-sub-sub-chart/templates/my-app-my-sub-sub-chart-registry-secret.yaml
  pkg/tests/pull/cases/subchart-crds/wantResults/rendered/this-cluster/charts/my-chart-release/charts/my-sub-chart/charts/my-sub-sub-chart/templates/my-sub-sub-chart-pod-pod.yaml
  pkg/tests/pull/cases/subchart-crds/wantResults/upstream/my-chart-0.1.0.tgz
Labels: type::bug, bug::regression

#3845 fix: process of uploading airgap bundle through the UI sometimes fails to get image layers
  integration/docker/registry/assets/manifests.yaml
  integration/docker/registry/temp_registry_test.go
  pkg/docker/registry/temp_registry.go
Labels: type::bug, bug::normal

#3836 Create sub-command 'admin-console copy-public-images'
  cmd/kots/cli/admin-console-copy-public-images.go
  cmd/kots/cli/admin-console-push-images.go
  cmd/kots/cli/admin-console.go
  deploy/assets/kots-upgrade.sh
  pkg/kotsadm/copy_images.go
Labels: type::bug, bug::normal

#3842 add back button to preflight
  web/src/components/PreflightResultPage.tsx
Labels: type::bug, bug::regression

#3846 updates to auth and session functions
  pkg/handlers/login.go
  pkg/handlers/session.go
Labels: type::chore

#3839 Miawong/sc 71608/UI feedback from installing schrodinger s
  web/src/components/apps/AppVersionHistory.tsx
  web/src/features/App/PreflightIcon.tsx
  web/src/features/AppVersionHistory/AppVersionHistoryRow.tsx
  web/src/features/VersionDiff/VersionDiff.tsx
  web/src/scss/components/apps/AppVersionHistory.scss
Labels: type::bug, bug::regression
