Repository replicatedhq/kots, pull requests merged in 2023-10, with the labels that each got.

#4055 bump helm to 3.13.0
  deploy/Dockerfile
  deploy/okteto/okteto-v2.Dockerfile
  deploy/okteto/okteto.Dockerfile
  hack/dev/skaffold.Dockerfile
Labels: type::security

#4056 Move HelmChartInterface to KotsKinds
  go.mod
  go.sum
  pkg/base/replicated.go
  pkg/kotsutil/kots.go
  pkg/operator/client/client.go
  pkg/operator/client/deploy.go
  pkg/operator/client/deploy_test.go
Labels: type::chore

#4059 Don't panic on nil values
  pkg/handlers/custom_metrics.go
  pkg/handlers/custom_metrics_test.go
Labels: type::bug, bug::normal

#4046 Log install preflight errors/warnings in both the CLI and kotsadm pod
  cmd/kots/cli/install.go
  cmd/kots/cli/install_test.go
  cmd/kots/cli/set-config.go
  pkg/handlers/preflight.go
  pkg/kotsutil/troubleshoot.go
  pkg/kurl/kurl_nodes.go
  pkg/preflight/execute.go
  pkg/preflight/preflight.go
  pkg/print/config.go
  pkg/reporting/distribution.go
Labels: type::feature, type::improvement

#4060 Add an endpoint to KOTS where application metrics can be retrieved adhoc
  pkg/apiserver/server.go
  pkg/handlers/handlers.go
  pkg/handlers/interface.go
  pkg/handlers/metrics.go
  pkg/handlers/metrics_test.go
  pkg/handlers/middleware.go
  pkg/handlers/mock/mock.go
  pkg/handlers/session.go
  pkg/policy/middleware.go
  pkg/replicatedapp/api.go
  pkg/reporting/util.go
Labels: type::feature

#4026 smoke test latest cmx versions
  .github/actions/cmx-versions/.gitignore
  .github/actions/cmx-versions/action.yaml
  .github/actions/cmx-versions/dist/index.js
  .github/actions/cmx-versions/index.js
  .github/actions/cmx-versions/package-lock.json
  .github/actions/cmx-versions/package.json
  .github/actions/kots-e2e/action.yml
  .github/workflows/build-test.yaml
  e2e/Makefile
  e2e/e2e_test.go
  e2e/kots/kots.go
  e2e/minio/install.go
  e2e/velero/cli.go
Labels: type::chore

#4068 upgrade tanstack query
  web/package.json
  web/src/Root.tsx
  web/src/components/hooks/useDownloadValues.test.jsx
  web/src/components/hooks/useIsHelmManaged.tsx
  web/src/components/hooks/useSaveConfig.js
  web/src/components/hooks/useSaveConfig.test.jsx
  web/src/components/snapshots/SnapshotStorageDestination.tsx
  web/src/features/AdminConsole/api/getAdminConsoleUpdateStatus.tsx
  web/src/features/AdminConsole/api/postUpdateAdminConsole.tsx
  web/src/features/App/api/getApps.test.jsx
  web/src/features/App/api/getApps.tsx
  web/src/features/App/api/getLicense.ts
  web/src/features/App/api/postDeployAppVersion.tsx
  web/src/features/App/api/postRedeployAppVersion.tsx
  web/src/features/AppVersionHistory/api/getDownloadAppVersionStatus.tsx
  web/src/features/AppVersionHistory/api/getVersions.tsx
  web/src/features/AppVersionHistory/api/postDownloadAppVersion.tsx
  web/src/features/Dashboard/api/createSnapshot.ts
  web/src/features/Dashboard/api/getAirgapConfig.ts
  web/src/features/Dashboard/api/getAppDownstream.ts
  web/src/features/Dashboard/api/getNextAppVersion.ts
  web/src/features/Dashboard/api/getSelectedAppClusterDashboard.ts
  web/src/features/Dashboard/api/getSnapshotSettings.ts
  web/src/features/Dashboard/api/getUpdateDownloadStatus.ts
  web/src/features/Dashboard/api/getUpdates.ts
  web/src/features/Gitops/hooks/useApps.tsx
  web/src/features/Gitops/hooks/useGitops.js
  web/src/features/PreflightChecks/api/getPreflightResult.tsx
  web/src/features/PreflightChecks/api/postIgnorePermissionErrors.tsx
  web/src/features/PreflightChecks/api/postPreflightRun.tsx
  web/src/stores/getMetadata.jsx
  web/webpack.config.dev.js
  web/webpack.config.js
  web/yarn.lock
Labels: type::chore

#4071 Revert 'Add an endpoint to KOTS where application metrics can be retrieved adhoc'
  pkg/apiserver/server.go
  pkg/handlers/handlers.go
  pkg/handlers/interface.go
  pkg/handlers/metrics.go
  pkg/handlers/middleware.go
  pkg/handlers/mock/mock.go
  pkg/handlers/session.go
Labels: type::chore

#4099 update kubectl, helm, and go.mod deps
  deploy/Dockerfile
  deploy/okteto/okteto-v2.Dockerfile
  deploy/okteto/okteto.Dockerfile
  go.mod
  go.sum
  hack/dev/skaffold.Dockerfile
Labels: type::security

#4076 Embedded cluster working group
  .github/actions/cmx-versions/dist/index.js
  migrations/tables/embeded_cluster_tokens.yaml
  pkg/embeddedcluster/delete_node.go
  pkg/embeddedcluster/drain_node.go
  pkg/embeddedcluster/exec.go
  pkg/embeddedcluster/helmvm_node.go
  pkg/embeddedcluster/helmvm_nodes.go
  pkg/embeddedcluster/node_join.go
  pkg/embeddedcluster/types/types.go
  pkg/embeddedcluster/util.go
  pkg/handlers/embedded_cluster_delete_node.go
  pkg/handlers/embedded_cluster_drain_node.go
  pkg/handlers/embedded_cluster_get.go
  pkg/handlers/embedded_cluster_node_join_command.go
  pkg/handlers/handlers.go
  pkg/handlers/handlers_test.go
  pkg/handlers/helmvm_get.go
  pkg/handlers/helmvm_node_join_command.go
  pkg/handlers/interface.go
  pkg/handlers/metadata.go
  pkg/handlers/mock/mock.go
  pkg/helmvm/helmvm_nodes.go
  pkg/helmvm/node_join.go
  pkg/helmvm/types/types.go
  pkg/helmvm/util.go
  pkg/kotsadm/metadata.go
  pkg/kotsadm/types/metadata.go
  pkg/store/kotsstore/embedded_cluster_store.go
  pkg/store/mock/mock.go
  pkg/store/store_interface.go
  pkg/store/types/constants.go
  pkg/util/image.go
  web/package.json
  web/src/Root.tsx
  web/src/components/UploadLicenseFile.tsx
  web/src/components/apps/AppDetailPage.tsx
  web/src/components/apps/AppVersionHistory.tsx
  web/src/components/apps/EmbeddedClusterManagement.tsx
  web/src/components/apps/EmbeddedClusterViewNode.jsx
  web/src/components/apps/EmbeddedClustrNodeRow.test.js
  web/src/components/apps/HelmVMClusterManagement.jsx
  web/src/components/apps/HelmVMNodeRow.jsx
  web/src/components/shared/CodeSnippet.jsx
  web/src/components/shared/NavBar.tsx
  web/src/features/AppVersionHistory/AppVersionHistoryRow.tsx
  web/src/features/Dashboard/components/DashboardVersionCard.tsx
  web/src/scss/components/apps/EmbeddedClusterManagement.scss
  web/src/types/index.ts
  web/tailwind.config.js
  web/yarn.lock
Labels: type::feature

#4103 Don't configure the SDK's user agent
  pkg/upstream/helm.go
  pkg/upstream/helm_test.go
Labels: type::chore

#4105 write instance and preflight reports to a secret
  pkg/api/reporting/types/types.go
  pkg/handlers/preflight.go
  pkg/reporting/app.go
  pkg/reporting/app_airgap.go
  pkg/reporting/instance_report.go
  pkg/reporting/preflight.go
  pkg/reporting/preflight_airgap.go
  pkg/reporting/preflight_report.go
  pkg/reporting/report.go
  pkg/reporting/report_test.go
  pkg/reporting/types.go
  pkg/store/kotsstore/reporting_store.go
  pkg/store/mock/mock.go
  pkg/store/store_interface.go
  pkg/supportbundle/spec.go
  pkg/util/compress.go
Labels: type::feature

#4109 revert to using ubuntu image to generate node join commands
  pkg/embeddedcluster/node_join.go
Labels: type::bug, bug::normal

#4111 update image dependencies
  .image.env
  Makefile
  migrations/Makefile
  pkg/image/constants.go
Labels: type::security

#4113 change troubleshoot.io to troubleshoot.sh
  pkg/kotsadm/types/constants.go
  pkg/kotsadm/types/constants_test.go
  pkg/supportbundle/spec_test.go
  pkg/tests/kotsutil/cases/multiple-preflights-in-helm-chart/rendered/this-cluster/helm/my-app/all.yaml
  pkg/tests/kotsutil/cases/preflights-in-helm-chart/rendered/this-cluster/helm/my-app/all.yaml
Labels: type::bug, bug::normal

#4114 remove yamlescape e2e test
  .github/workflows/build-test.yaml
Labels: type::chore

#4115 Handle race condition where events are reported out of order
  pkg/reporting/app_airgap.go
  pkg/reporting/app_online.go
Labels: type::bug, bug::normal
