Repository replicatedhq/kots, pull requests merged in 2023-01, with the labels that each got.

#3534 fix: 'Cluster Management' tab does not show up sometimes in kURL clusters
  pkg/kurl/configmap.go
Labels: type::bug, bug::regression

#3536 Grahamnscp patch 2023
  web/src/components/troubleshoot/GenerateSupportBundleModal.tsx
Labels: type::bug, bug::normal

#3537 Miawong/sc 45692/preflight checks pass with warnings breaks out of UI
  web/src/features/AppVersionHistory/AppVersionHistoryRow.jsx
  web/src/features/Dashboard/components/DashboardVersionCard.tsx
  web/src/scss/components/apps/AppVersionHistory.scss
Labels: type::bug, bug::normal

#3543 Rianfowler 2023 increase slowloading threshold
  web/src/constants/timers.js
  web/src/features/App/api/useLicense.ts
  web/src/features/Dashboard/api/useNextAppVersion.ts
  web/src/features/Dashboard/api/useSelectedAppClusterDashboard.ts
Labels: type::bug, bug::normal

#3545 fix dependabot safe-to-test label
  .github/dependabot.yml
Labels: type::chore

#3544 Adds an API endpoint for deleting support bundles
  pkg/filestore/blob_store.go
  pkg/filestore/s3_store.go
  pkg/filestore/store_interface.go
  pkg/handlers/handlers.go
  pkg/handlers/handlers_test.go
  pkg/handlers/interface.go
  pkg/handlers/mock/mock.go
  pkg/handlers/troubleshoot.go
  pkg/store/kotsstore/supportbundle_store.go
  pkg/store/mock/mock.go
  pkg/store/store_interface.go
Labels: type::feature

#3539 feat(support-bundle): add troubleshoot label for support-bundle spec secret
  pkg/kotsadm/types/constants.go
  pkg/kotsadm/types/constants_test.go
  pkg/supportbundle/spec.go
Labels: type::feature

#3546 Miawong/sc 65991/add show logs modal storybook
  web/src/scss/components/apps/AppVersionHistory.scss
  web/src/scss/index.scss
  web/src/stories/ShowLogsModal.stories.tsx
Labels: type::chore

#3547 Miawong/sc 65991/add show all modal to storybook
  web/src/components/snapshots/SnapshotDetails.jsx
  web/src/stories/ShowAllModal.stories.tsx
Labels: type::chore

#3549 read remaining bytes in pkcs12 certificates
  kurl_proxy/cmd/main.go
  kurl_proxy/cmd/main_test.go
Labels: type::bug, bug::normal

#3550 Miawong/sc 57763/add ability to delete support bundles from admin console
  pkg/handlers/handlers.go
  web/src/Root.tsx
  web/src/components/shared/Toast.tsx
  web/src/components/troubleshoot/SupportBundleList.tsx
  web/src/components/troubleshoot/SupportBundleRow.tsx
  web/src/context/ToastContext.tsx
  web/src/scss/components/troubleshoot/SupportBundleList.scss
  web/src/scss/utilities/base.scss
  web/src/stories/Toast.stories.tsx
Labels: type::feature

#3555 Miawong/sc 59049/auto expand and collapse the the config nav
  web/src/components/config_render/ConfigGroup.jsx
  web/src/features/AppConfig/components/AppConfig.tsx
  web/src/scss/components/watches/WatchConfig.scss
Labels: type::feature

#3561 upgrade helm for CVE-2022-27664 and CVE-2022-32149
  deploy/Dockerfile
Labels: type::security

#3560 Miawong/sc 59660/Do not show no snapshots if snapshots is in progress
  web/src/components/snapshots/AppSnapshots.jsx
  web/src/components/snapshots/Snapshots.jsx
Labels: type::bug, bug::normal

#3563 Return if a version is configurable or not
  pkg/api/downstream/types/types.go
  pkg/store/kotsstore/downstream_store.go
Labels: type::bug, bug::normal

#3564 delete private/public keys when gitops integration is disabled and keys are not in use by other applications
  pkg/gitops/gitops.go
  pkg/gitops/gitops_test.go
  pkg/handlers/gitops.go
Labels: type::bug, bug::normal

#3556 Miawong/sc 65991/add snapshot differences modal storybook
  web/src/components/modals/SnapshotDifferencesModal.tsx
  web/src/stories/SnapshotDifferencesModal.stories.tsx
Labels: type::chore

#3569 add --save-config flag when creating kotsadm-confg configmap(k8s declarative configuration)
  deploy/kurl/kotsadm/template/base/install.sh
Labels: type::bug, bug::normal

#3567 add showdetailsmodal to storybook
  web/src/stories/ShowDetailsModal.stories.tsx
Labels: type::chore

#3568 Do not show the config icon if a version does not have a config
  .github/workflows/build-test.yaml
  pkg/api/downstream/types/types.go
  pkg/handlers/app.go
  pkg/helm/helm.go
  pkg/store/kotsstore/downstream_store.go
  web/src/features/AppVersionHistory/AppVersionHistoryRow.jsx
Labels: type::bug, bug::normal

#3571 update velero install instructions
  pkg/print/fs-lvp-velero-config.go
  pkg/print/fs-minio-velero-config.go
  web/src/components/snapshots/ConfigureSnapshots.jsx
Labels: type::chore

#3573 update troubleshoot to v0.55.0 and add ipv4 redactor
  go.mod
  go.sum
  pkg/handlers/redact.go
  pkg/redact/app.go
  pkg/redact/default.go
  pkg/redact/default_test.go
  pkg/redact/redact.go
  pkg/supportbundle/supportbundle.go
Labels: type::chore

#3572 Update k3s version in e2e tests to avoid the port forward bug
  .github/actions/kots-e2e/action.yml
  .github/workflows/build-test.yaml
Labels: type::chore

#3553 Update cosign command in README to use double dash flags instead
  README.md
Labels: type::chore, type::docs

#3582 bump k3s version range to 1.23 - 1.26
  .github/workflows/build-test.yaml
Labels: type::chore

#3324 Automated Kubectl version update
  deploy/Dockerfile
Labels: automated-pr, type::chore, kubectl

#3574 Miawong/sc 65991/deletesnapshotmodal storybook
  web/.storybook/main.js
  web/src/components/modals/DeleteSnapshotModal.tsx
  web/src/stories/DeleteSnapshotModal.stories.tsx
  web/src/types/index.ts
Labels: type::chore

#3585 remove unused dependencies, upgrade typescript, clean up package.json metadata
  web/package.json
  web/yarn.lock
Labels: type::chore

#3565 Miawong/sc 62358/admin console config icon is shown for a
  web/src/components/shared/EditConfigIcon.tsx
  web/src/features/Dashboard/components/DashboardVersionCard.tsx
  web/src/types/index.ts
Labels: type::bug, bug::normal

#3587 remove unused openshift version check
  go.mod
  go.sum
  pkg/k8sutil/openshift.go
Labels: type::chore

#3588 Rianfowler/sc 45028/UI is broken when deploying a version in 2
  web/src/components/apps/AppDetailPage.tsx
  web/src/components/apps/AppVersionHistory.tsx
  web/src/components/modals/ErrorModal.jsx
Labels: type::bug, bug::normal

#3589 add delete redactor modal story
  web/src/stories/DeleteRedactorModal.stories.tsx
Labels: type::chore

#3576 add BackupRestoreModal to storybook
  web/src/stories/BackupRestoreModal.stories.tsx
Labels: type::chore

#3583 resolve CVE-2022-41721 in kurl_proxy
  kurl_proxy/go.mod
  kurl_proxy/go.sum
Labels: type::security

#3590 Miawong/sc 65991/changepasswordmodal to storybook
  web/src/stories/ChangePasswordModal.stories.tsx
Labels: type::chore
