Repository replicatedhq/kots, pull requests merged in 2023-08, with the labels that each got.

#3992 upgrade troubleshoot go mod to v0.70.2
  go.mod
  go.sum
  pkg/appstate/ingress.go
  pkg/appstate/ingress_test.go
  pkg/k8sutil/portforward.go
Labels: type::chore

#3979 Automated Kubectl version update
  deploy/Dockerfile
Labels: automated-pr, type::chore, kubectl

#3995 Surface errors when failing to parse KOTS kinds.
  pkg/base/base.go
  pkg/base/replicated.go
  pkg/kotsutil/kots.go
  pkg/kotsutil/kots_test.go
Labels: type::bug, bug::normal

#3996 upgrade to kustomize 5.1.1
  .github/workflows/alpha.yaml
  .github/workflows/build-test.yaml
  .github/workflows/release.yaml
  Makefile
  deploy/Dockerfile
  deploy/okteto/okteto-v2.Dockerfile
  deploy/okteto/okteto.Dockerfile
  hack/dev/skaffold.Dockerfile
  integration/replicated/tests/kitchen-sink/expected/base/kustomization.yaml
  integration/upload/tests/kitchen-sink/expected-archive/base/kustomization.yaml
  integration/upload/tests/kitchen-sink/input/base/kustomization.yaml
  pkg/base/write.go
  pkg/pull/pull.go
  pkg/rewrite/rewrite.go
  pkg/tests/pull/cases/configcontext/wantResults/base/charts/test-chart-2/kustomization.yaml
  pkg/tests/pull/cases/configcontext/wantResults/base/charts/test-chart/kustomization.yaml
  pkg/tests/pull/cases/configcontext/wantResults/base/kustomization.yaml
  pkg/tests/pull/cases/customhostnames/wantResults/base/kustomization.yaml
  pkg/tests/pull/cases/multidoc/wantResults/base/kustomization.yaml
  pkg/tests/pull/cases/samechartvariations/wantResults/base/charts/test-chart-release-1/kustomization.yaml
  pkg/tests/pull/cases/samechartvariations/wantResults/base/charts/test-chart-release-2/kustomization.yaml
  pkg/tests/pull/cases/samechartvariations/wantResults/base/charts/test-chart-variation-0/kustomization.yaml
  pkg/tests/pull/cases/samechartvariations/wantResults/base/kustomization.yaml
  pkg/tests/pull/cases/simple/wantResults/base/kustomization.yaml
  pkg/tests/pull/cases/subchart-alias/wantResults/base/charts/chart/charts/subchart-1/kustomization.yaml
  pkg/tests/pull/cases/subchart-alias/wantResults/base/charts/chart/charts/subchart-2/charts/subsubchart/kustomization.yaml
  pkg/tests/pull/cases/subchart-alias/wantResults/base/charts/chart/charts/subchart-2/kustomization.yaml
  pkg/tests/pull/cases/subchart-alias/wantResults/base/charts/chart/charts/subchart-3/kustomization.yaml
  pkg/tests/pull/cases/subchart-alias/wantResults/base/charts/chart/kustomization.yaml
  pkg/tests/pull/cases/subchart-alias/wantResults/base/kustomization.yaml
  pkg/tests/pull/cases/subchart-crds/wantResults/base/charts/my-chart-release/charts/my-sub-chart/charts/my-sub-sub-chart/charts/my-sub-sub-sub-chart/kustomization.yaml
  pkg/tests/pull/cases/subchart-crds/wantResults/base/charts/my-chart-release/charts/my-sub-chart/charts/my-sub-sub-chart/kustomization.yaml
  pkg/tests/pull/cases/subchart-crds/wantResults/base/charts/my-chart-release/charts/my-sub-chart/crds/kustomization.yaml
  pkg/tests/pull/cases/subchart-crds/wantResults/base/charts/my-chart-release/charts/my-sub-chart/kustomization.yaml
  pkg/tests/pull/cases/subchart-crds/wantResults/base/charts/my-chart-release/crds/kustomization.yaml
  pkg/tests/pull/cases/subchart-crds/wantResults/base/charts/my-chart-release/kustomization.yaml
  pkg/tests/pull/cases/subchart-crds/wantResults/base/kustomization.yaml
  pkg/tests/pull/cases/subcharts/wantResults/base/charts/chart/charts/subchart-1/kustomization.yaml
  pkg/tests/pull/cases/subcharts/wantResults/base/charts/chart/charts/subchart-2/charts/subsubchart/kustomization.yaml
  pkg/tests/pull/cases/subcharts/wantResults/base/charts/chart/charts/subchart-2/kustomization.yaml
  pkg/tests/pull/cases/subcharts/wantResults/base/charts/chart/kustomization.yaml
  pkg/tests/pull/cases/subcharts/wantResults/base/charts/fluent-bit/charts/fluent-bit/kustomization.yaml
  pkg/tests/pull/cases/subcharts/wantResults/base/charts/fluent-bit/kustomization.yaml
  pkg/tests/pull/cases/subcharts/wantResults/base/kustomization.yaml
  pkg/tests/pull/cases/v1beta2-charts/wantResults/base/kustomization.yaml
Labels: type::chore

#3999 prevent Replicated to Native Helm upgrade
  pkg/pull/pull.go
Labels: type::bug, bug::regression

#4001 remove gke autopilot distro reporting
  pkg/k8sutil/clientset.go
  pkg/reporting/app.go
  pkg/reporting/distribution.go
  pkg/reporting/distribution_test.go
Labels: type::bug, bug::normal

#4007 upgrade troubleshoot go mod to v0.70.3
  go.mod
  go.sum
Labels: type::chore

#4008 Automated Kots Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4006 replace windows line endings before splitting docs
  pkg/base/helm.go
  pkg/base/variadic.go
  pkg/image/builder.go
  pkg/kotsutil/yaml.go
  pkg/operator/client/delete.go
  pkg/operator/client/deploy.go
  pkg/operator/client/kots.go
  pkg/operator/client/resource.go
  pkg/operator/client/resource_test.go
  pkg/operator/helm.go
  pkg/operator/operator.go
  pkg/secrets/sealed_secrets.go
  pkg/secrets/secrets.go
  pkg/supportbundle/helm.go
  pkg/tests/pull/cases/multidoc/upstream/subdir/nginx-crlf.yaml
  pkg/tests/pull/cases/multidoc/wantResults/base/kustomization.yaml
  pkg/tests/pull/cases/multidoc/wantResults/base/subdir/nginx-crlf-2.yaml
  pkg/tests/pull/cases/multidoc/wantResults/base/subdir/nginx-crlf-3.yaml
  pkg/tests/pull/cases/multidoc/wantResults/base/subdir/nginx-crlf.yaml
  pkg/tests/pull/cases/multidoc/wantResults/kotsKinds/installation.yaml
  pkg/tests/pull/cases/multidoc/wantResults/overlays/midstream/kustomization.yaml
  pkg/tests/pull/cases/multidoc/wantResults/overlays/midstream/pullsecrets.yaml
  pkg/tests/pull/cases/multidoc/wantResults/rendered/this-cluster/nginx-deployment.yaml
  pkg/tests/pull/cases/multidoc/wantResults/rendered/this-cluster/nginx-service.yaml
  pkg/tests/pull/cases/multidoc/wantResults/rendered/this-cluster/nginx-serviceaccount.yaml
  pkg/tests/pull/cases/multidoc/wantResults/rendered/this-cluster/operator-image-pull-secret-secret-2.yaml
  pkg/tests/pull/cases/multidoc/wantResults/upstream/subdir/nginx-crlf.yaml
  pkg/tests/pull/cases/multidoc/wantResults/upstream/userdata/installation.yaml
  pkg/util/splitter.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: type::bug, bug::normal

#4011 reserve capacity for gke autopilot test
  .github/actions/kots-gke-create/reserve-capacity.yaml
  .github/workflows/build-test.yaml
Labels: type::chore

#3971 run tests on c11y matrix
  .github/actions/kots-e2e/action.yml
  .github/workflows/build-test.yaml
Labels: type::chore

#4015 Automated Kots Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4013 API to accept metrics from application
  pkg/apiserver/server.go
  pkg/handlers/custom_metrics.go
  pkg/handlers/custom_metrics_test.go
  pkg/handlers/handlers.go
  pkg/handlers/handlers_test.go
  pkg/handlers/interface.go
  pkg/handlers/middleware.go
  pkg/handlers/mock/mock.go
  pkg/handlers/session.go
  pkg/policy/middleware.go
  pkg/replicatedapp/api.go
  pkg/reporting/app.go
  pkg/session/middleware.go
  pkg/store/mock/mock.go
Labels: type::feature

#4020 Always cleanup c11y clusters because we generate support bundles
  .github/actions/kots-e2e/action.yml
  .github/workflows/build-test.yaml
Labels: type::chore
