Repository replicatedhq/kots, pull requests merged in 2023-12, with the labels that each got.

#4196 add gitops test to e2e suite
  .github/workflows/build-test.yaml
  e2e/e2e_test.go
  e2e/testim/inventory/inventory.go
Labels: type::chore

#4198 remove code associated with unused --set flag
  cmd/kots/cli/install.go
  pkg/base/helm.go
  pkg/base/helm_v2.go
  pkg/base/helm_v3.go
  pkg/base/render.go
Labels: type::chore

#4199 Build kurl-proxy image with Chainguard
  .github/actions/build-push-kurl-proxy-image/action.yml
  .github/workflows/alpha.yaml
  .github/workflows/build-test.yaml
  .github/workflows/release.yaml
  kurl_proxy/deploy/apko.yaml.tmpl
  kurl_proxy/deploy/melange.yaml.tmpl
Labels: type::security

#4200 Fix deploying dex for the identity service
  pkg/identity/deploy/deploy.go
Labels: type::security

#4203 runAsUser 1001 for dev env
  kustomize/base/deployment.yaml
  migrations/kustomize/overlays/dev/rqlite.yaml
  migrations/kustomize/overlays/okteto/rqlite.yaml
Labels: type::chore

#4212 don't fail loading troubleshoot kinds if directory doesn't exist
  pkg/kotsutil/troubleshoot.go
  pkg/preflight/preflight.go
  pkg/tests/kotsutil/troubleshoot_test.go
Labels: type::bug, bug::regression

#4218 Update LVP to v0.5.6
  .image.env
  Makefile
  pkg/image/constants.go
Labels: type::security

#4222 Improve updating image deps workflow
  .github/actions/build-push-image-with-apko/action.yml
  .github/workflows/alpha.yaml
  .github/workflows/build-test.yaml
  .github/workflows/image-deps-updater.yaml
  .github/workflows/release.yaml
  cmd/imagedeps/image-spec
  cmd/imagedeps/main.go
  cmd/imagedeps/main_test.go
  cmd/imagedeps/tag-finder.go
  cmd/imagedeps/testdata/dex/.image.env
  cmd/imagedeps/testdata/dex/constants.go
  cmd/imagedeps/testdata/dex/input-spec
  cmd/imagedeps/testdata/dex/replacers/expected/test.apko.yaml
  cmd/imagedeps/testdata/dex/replacers/input/test.apko.yaml
  cmd/imagedeps/testdata/minio/.image.env
  cmd/imagedeps/testdata/minio/constants.go
  cmd/imagedeps/testdata/minio/input-spec
  cmd/imagedeps/testdata/minio/replacers/expected/test.apko.yaml
  cmd/imagedeps/testdata/minio/replacers/input/test.apko.yaml
  cmd/imagedeps/testdata/rqlite/.image.env
  cmd/imagedeps/testdata/rqlite/constants.go
  cmd/imagedeps/testdata/rqlite/input-spec
  cmd/imagedeps/testdata/rqlite/replacers/expected/test.apko.yaml
  cmd/imagedeps/testdata/rqlite/replacers/input/test.apko.yaml
  cmd/imagedeps/testdata/schemahero/replacers/input/test.Dockerfile
  cmd/imagedeps/testdata/schemahero/replacers/input/test.mk
  kustomize/overlays/kotsstore/minio/statefulset.yaml
  migrations/kustomize/overlays/dev/rqlite.yaml
  migrations/kustomize/overlays/okteto/rqlite.yaml
Labels: type::security

#4223 Fix 3rd party image deps update workflow
  .github/actions/build-push-image-with-apko/action.yml
  .github/workflows/image-deps-updater.yaml
  cmd/imagedeps/image-spec
  cmd/imagedeps/main.go
  cmd/imagedeps/main_test.go
  cmd/imagedeps/tag-finder.go
  cmd/imagedeps/testdata/dex/.image.env
  cmd/imagedeps/testdata/dex/constants.go
  cmd/imagedeps/testdata/dex/input-spec
  cmd/imagedeps/testdata/dex/replacers/expected/test.apko.yaml
  cmd/imagedeps/testdata/minio/.image.env
  cmd/imagedeps/testdata/minio/constants.go
  cmd/imagedeps/testdata/minio/input-spec
  cmd/imagedeps/testdata/minio/replacers/expected/test.apko.yaml
  cmd/imagedeps/testdata/rqlite/.image.env
  cmd/imagedeps/testdata/rqlite/constants.go
  cmd/imagedeps/testdata/rqlite/input-spec
  cmd/imagedeps/testdata/rqlite/replacers/expected/test.apko.yaml
  cmd/imagedeps/testdata/rqlite/replacers/input/test.apko.yaml
  deploy/dex/apko.yaml.tmpl
  deploy/minio/apko.yaml
  deploy/minio/apko.yaml.tmpl
  deploy/rqlite/apko.yaml
  deploy/rqlite/apko.yaml.tmpl
Labels: type::security

#4225 Use NIGHTLY PAT to trigger image dep update
  .github/workflows/image-deps-updater.yaml
Labels: type::security

#4227 Use kotsadm/rqlite image in migrations test
  integration/database/rqlite_migration_test.go
Labels: type::security

#4234 node join commands should be generated properly
  pkg/embeddedcluster/node_join.go
  pkg/embeddedcluster/util.go
  pkg/k8sutil/cluster.go
Labels: type::feature

#4202 KOTS reporting to replicated-app
  integration/replicated/pull_test.go
  pkg/persistence/persistence.go
  pkg/replicatedapp/api.go
  pkg/store/store.go
Labels: type::feature

#4242 Fix image deps updater overwrite input
  .github/actions/build-push-image-with-apko/action.yml
Labels: type::security

#4226 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  migrations/Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4245 kotsadm NodePort service for dev env
  kustomize/base/deployment.yaml
  kustomize/base/service.yaml
  kustomize/overlays/dev/deployment.yaml
  kustomize/overlays/dev/dlv-service.yaml
  kustomize/overlays/dev/kustomization.yaml
  skaffold.yaml
  web/okteto.Dockerfile
  web/skaffold.Dockerfile
Labels: type::chore

#4244 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4246 add test namespace as resource to dev env
  kustomize/overlays/dev/kustomization.yaml
  kustomize/overlays/dev/namespace.yaml
Labels: type::chore

#4247 Combined dependabot PR
  .github/actions/copy-assets/go.mod
  .github/actions/copy-assets/go.sum
  .github/workflows/alpha.yaml
  .github/workflows/build-test.yaml
  .github/workflows/image-deps-updater.yaml
  .github/workflows/license.yaml
  .github/workflows/regression.yaml
  .github/workflows/release.yaml
  go.mod
  go.sum
  kurl_proxy/go.mod
  kurl_proxy/go.sum
  web/package.json
  web/yarn.lock
Labels: dependencies, github_actions, go, javascript, type::chore, dependabot

#4249 Migrate to skaffold v2 and kustomize v5 for the dev environment
  kurl_proxy/kustomize/base/kustomization.yaml
  kurl_proxy/kustomize/overlays/dev/kustomization.yaml
  kustomize/base/deployment.yaml
  kustomize/base/kustomization.yaml
  kustomize/overlays/dev/kustomization.yaml
  kustomize/overlays/kotsstore/kustomization.yaml
  kustomize/overlays/kotsstore/minio/kustomization.yaml
  kustomize/overlays/ocistore/kustomization.yaml
  kustomize/overlays/okteto/kustomization.yaml
  kustomize/overlays/rbac/kustomization.yaml
  migrations/kustomize/base/kustomization.yaml
  migrations/kustomize/overlays/dev/kustomization.yaml
  migrations/kustomize/overlays/okteto/kustomization.yaml
  skaffold.yaml
  web/kustomize/base/kustomization.yaml
  web/kustomize/overlays/dev/kustomization.yaml
  web/kustomize/overlays/kotsadm/kustomization.yaml
Labels: type::chore

#4248 Report the embedded cluster ID when available
  Makefile
  migrations/tables/instance-report.yaml
  pkg/api/reporting/types/types.go
  pkg/reporting/app.go
  pkg/reporting/app_airgap.go
  pkg/reporting/instance_report.go
  pkg/reporting/report_test.go
  pkg/reporting/util.go
Labels: type::feature

#4250 even more deps
  go.mod
  go.sum
  pkg/secrets/sealed_secrets.go
  web/package.json
  web/yarn.lock
Labels: type::chore

#4256 More dev env improvements
  kustomize/base/service.yaml
  kustomize/overlays/kotsstore/deployment.yaml
  kustomize/overlays/kotsstore/minio/secret.yaml
  kustomize/overlays/kotsstore/minio/service.yaml
  kustomize/overlays/kotsstore/minio/statefulset.yaml
  migrations/kustomize/overlays/dev/rqlite.yaml
  skaffold.yaml
Labels: type::chore

#4258 Use Github user as the current user when available
  Makefile
  cmd/imagedeps/testdata/schemahero/replacers/expected/test.mk
  cmd/imagedeps/testdata/schemahero/replacers/input/test.mk
  deploy/kurl/kotsadm/hack/Makefile
  hack/build-ttl.sh
  kurl_proxy/Makefile
  migrations/build-ttl.sh
Labels: type::chore
