Repository replicatedhq/kots, pull requests merged in 2023-09, with the labels that each got.

#4027 Use empty dir for tmp dir in embedded clusters as well
  deploy/kurl/kotsadm/template/base/deployment/kotsadm-deployment.yaml
  deploy/kurl/kotsadm/template/base/statefulset/kotsadm-statefulset.yaml
Labels: type::bug, bug::normal

#4024 replace FOSSA with Trivy
  .fossa.yml
  .github/workflows/fossa.yaml
  .github/workflows/license.yaml
  README.md
Labels: type::chore

#4028 Support Kubernetes 1.28
  .github/workflows/build-test.yaml
  deploy/Dockerfile
  deploy/okteto/okteto-v2.Dockerfile
  deploy/okteto/okteto.Dockerfile
  hack/dev/skaffold.Dockerfile
Labels: type::feature

#4036 fix: race condition when updating registry settings
  .github/actions/kots-gke-create/reserve-capacity.yaml
  pkg/handlers/registry.go
Labels: type::bug, bug::normal

#4019 feat: enable regression tests on top of helmvm
  .github/workflows/regression.yaml
Labels: type::chore

#4035 fix: handle empty kustomize bases
  go.mod
  go.sum
  pkg/apparchive/app.go
  pkg/apparchive/app_test.go
  pkg/apparchive/helm-v1beta1.go
  pkg/apparchive/helm-v1beta1_test.go
Labels: type::bug, bug::regression

#4040 Remove authorization header from custom metrics API
  pkg/apiserver/server.go
  pkg/handlers/custom_metrics.go
  pkg/handlers/custom_metrics_test.go
  pkg/handlers/handlers.go
  pkg/handlers/handlers_test.go
  pkg/handlers/interface.go
  pkg/handlers/middleware.go
  pkg/handlers/mock/mock.go
  pkg/handlers/session.go
Labels: type::bug, bug::normal

#4032 Add support for 'Lookup' template function
  pkg/template/static_context.go
Labels: type::feature

#4031 bump up the troubleshoot version to v0.72.x
  go.mod
  go.sum
Labels: type::chore

#4048 fix: clear v1beta2 helm directory before writing new charts
  .github/workflows/build-test.yaml
  pkg/apparchive/helm-v1beta2.go
Labels: type::bug, bug::regression

#4050 clarify that automatic update checks are in local server time
  .github/workflows/build-test.yaml
  web/src/components/modals/AutomaticUpdatesModal.tsx
Labels: type::feature, type::improvement

#4049 Ensure imagepullsecrets and hooks informer for dynamic namespaces even if API restarts
  pkg/apiserver/server.go
  pkg/operator/client/client.go
  pkg/operator/client/client_interface.go
  pkg/operator/client/deploy.go
  pkg/operator/client/hooks.go
  pkg/operator/client/mock/mock.go
  pkg/operator/client/namespaces.go
  pkg/operator/helm.go
  pkg/operator/image_pull_secrets.go
  pkg/operator/operator.go
  pkg/operator/operator_test.go
Labels: type::bug, bug::normal

#4052 Fix empty automatic partial snapshots dropdown
  web/src/Root.tsx
  web/src/components/shared/NavBar.tsx
  web/src/components/snapshots/SnapshotSettings.tsx
  web/src/components/snapshots/SnapshotStorageDestination.tsx
Labels: type::bug, bug::regression

#4053 resolve CVE-2023-29491 in minio deps
  .image.env
  Makefile
  pkg/image/constants.go
Labels: type::security
