Repository replicatedhq/kots, pull requests merged in 2023-05, with the labels that each got.

#3828 make default selected node type primary. force to secondary if no ha
  web/src/components/apps/ClusterNodes.jsx
Labels: type::feature

#3843 Fix snapshot restore cancellation when there are multiple apps installed
  .github/workflows/build-test.yaml
  e2e/e2e_test.go
  e2e/testim/inventory/inventory.go
  web/src/Root.tsx
  web/src/components/snapshots/SnapshotsWrapper.jsx
Labels: type::bug, bug::normal

#3852 show last updated in details modal
  web/src/features/Dashboard/components/Dashboard.tsx
Labels: type::feature, type::improvement

#3854 use configError over validationErrorMessage
  web/src/features/AppConfig/components/AppConfig.tsx
Labels: type::bug, bug::regression

#3855 Add customer email address to the license
  kotskinds/apis/kots/v1beta1/license_types.go
  kotskinds/config/crds/kots.io_licenses.yaml
  kotskinds/schemas/license-kots-v1beta1.json
  pkg/license/signature.go
Labels: type::chore

#3857 cleanup comment and console logs
  web/src/features/AppConfig/components/AppConfig.tsx
Labels: type::chore

#3859 check for current version to render "edit currently deployed version"
  web/src/features/AppConfig/components/ConfigInfo.jsx
Labels: type::bug, bug::normal

#3853 add validate-remove-app-with-ordered-kind test
  .github/workflows/build-test.yaml
Labels: type::bug, bug::regression

#3860 Miawong/sc 75508/improve padding for community edition banner
  web/src/components/apps/AppLicense.tsx
  web/src/css/icon.css
  web/src/features/Dashboard/components/DashboardLicenseCard.tsx
  web/src/scss/components/apps/AppLicense.scss
  web/src/scss/components/shared/NavBar.scss
  web/src/utilities/utilities.js
Labels: type::chore

#3851 Improvements to application resource management
  .github/workflows/build-test.yaml
  pkg/k8sutil/clientset.go
  pkg/operator/applier/kubectl.go
  pkg/operator/client/client.go
  pkg/operator/client/client_interface.go
  pkg/operator/client/delete.go
  pkg/operator/client/delete_test.go
  pkg/operator/client/deploy.go
  pkg/operator/client/deploy_test.go
  pkg/operator/client/doc.go
  pkg/operator/client/mock/mock.go
  pkg/operator/client/resource.go
  pkg/operator/client/resource_test.go
  pkg/operator/operator.go
  pkg/operator/types/types.go
  pkg/snapshot/store.go
Labels: type::feature, type::improvement

#3861 set httpOnly auth cookie when logging in through OIDC
  pkg/handlers/login.go
  web/src/features/Auth/components/SecureAdminConsole.tsx
Labels: type::bug, bug::normal

#3840 handle unauthorized error in IsKurl
  pkg/kurl/configmap.go
  pkg/kurl/configmap_test.go
Labels: type::bug, bug::normal

#3866 chore: use kurlkinds
  .github/workflows/build-test.yaml
  go.mod
  go.sum
  pkg/installers/installers.go
  pkg/kotsutil/kots.go
  pkg/preflight/preflight.go
  pkg/preflight/preflight_test.go
  pkg/template/kurl_context.go
  pkg/template/kurl_context_test.go
Labels: type::chore

#3869 Use the app slug as the registry namespace in air-gapped kURL clusters
  cmd/kots/cli/admin-console-generate-manifests.go
  cmd/kots/cli/identity.go
  cmd/kots/cli/install.go
  cmd/kots/cli/upstream-upgrade.go
  cmd/kots/cli/velero.go
  pkg/kotsadm/push_images.go
Labels: type::bug, bug::regression

#3871 fix: version status deploying and preflights running
  pkg/store/kotsstore/preflight_store.go
Labels: type::bug, bug::normal

#3865 remove containerName: rqlite from sb spec
  pkg/kotsadm/objects/rqlite_objects.go
  pkg/supportbundle/defaultspec/spec.yaml
  pkg/supportbundle/staticspecs/defaultspec.yaml
Labels: type::bug, bug::regression

#3873 Apply status informers before deploying the app
  pkg/operator/operator.go
Labels: type::feature, type::improvement

#3862 Miawong/sc 75115/improve layout for long strings
  web/src/components/apps/AppLicense.tsx
  web/src/components/config_render/ConfigItemTitle.jsx
  web/src/components/troubleshoot/GenerateSupportBundle.jsx
  web/src/components/watches/WatchSidebarItem/KotsSidebarItem.jsx
  web/src/features/AppConfig/components/AppConfig.tsx
  web/src/features/Auth/components/SecureAdminConsole.tsx
  web/src/features/Dashboard/components/Dashboard.tsx
  web/src/features/Dashboard/components/DashboardLicenseCard.tsx
  web/src/scss/components/watches/WatchConfig.scss
  web/src/scss/utilities/utilities.scss
  web/src/utilities/utilities.js
Labels: type::bug, bug::normal

#3841 Automated Kots Image Dependency Tag Update
  .image.env
  Makefile
  migrations/Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#3874 update sourcemap type to reduce bundle size
  web/webpack.config.dev.js
Labels: type::chore

#3879 add runtime check for HelmChartInterface
  pkg/kotsutil/kots.go
Labels: type::chore

#3880 fix license customer name when it's long
  web/src/features/Dashboard/components/DashboardLicenseCard.tsx
  web/src/scss/utilities/utilities.scss
Labels: type::bug, bug::regression

#3878 wrap forwardErr during port-forward
  pkg/k8sutil/portforward.go
Labels: type::chore

#3885 upgrade troubleshoot to v0.64.0
  go.mod
  go.sum
Labels: type::chore

#3886 improve ux of backup restore modal - replace call to action
  web/src/components/modals/BackupRestoreModal.jsx
Labels: type::feature, type::improvement

#3872 Add k3s 1.27.1 to PR tests
  .github/workflows/build-test.yaml
Labels: type::chore

#3803 Automated Kubectl version update
  deploy/Dockerfile
Labels: automated-pr, type::chore, kubectl

#3896 don't uninstall and reinstall helm charts when the version changes
  pkg/operator/client/deploy.go
  pkg/operator/client/deploy_test.go
Labels: type::bug, bug::regression

#3898 upgrade minio to RELEASE.2023-05-18T00-05-36Z
  .image.env
  Makefile
  pkg/image/constants.go
Labels: type::chore

#3900 log failed HelmChart contents
  pkg/base/replicated.go
Labels: type::chore

#3902 fix: add v1beta2 images to knownImages
  .gitignore
  pkg/apparchive/helm-v1beta2.go
  pkg/apparchive/installation.go
  pkg/kotsutil/kots.go
  pkg/midstream/write.go
  pkg/pull/pull.go
  pkg/rewrite/rewrite.go
  pkg/tests/pull/cases/v1beta2-charts/testcase.yaml
  pkg/tests/pull/cases/v1beta2-charts/upstream/my-chart-0.1.0.tgz
  pkg/tests/pull/cases/v1beta2-charts/upstream/my-other-chart-0.1.0.tgz
  pkg/tests/pull/cases/v1beta2-charts/wantResults/helm/my-chart-release/my-chart-0.1.0.tgz
  pkg/tests/pull/cases/v1beta2-charts/wantResults/helm/my-other-chart-release/my-other-chart-0.1.0.tgz
  pkg/tests/pull/cases/v1beta2-charts/wantResults/kotsKinds/installation.yaml
  pkg/tests/pull/cases/v1beta2-charts/wantResults/overlays/midstream/secret.yaml
  pkg/tests/pull/cases/v1beta2-charts/wantResults/rendered/this-cluster/helm/my-chart-release/all.yaml
  pkg/tests/pull/cases/v1beta2-charts/wantResults/rendered/this-cluster/helm/my-other-chart-release/all.yaml
  pkg/tests/pull/cases/v1beta2-charts/wantResults/rendered/this-cluster/kotsadm-replicated-registry-secret.yaml
  pkg/tests/pull/cases/v1beta2-charts/wantResults/rendered/this-cluster/my-app-registry-secret.yaml
  pkg/tests/pull/cases/v1beta2-charts/wantResults/upstream/my-chart-0.1.0.tgz
  pkg/tests/pull/cases/v1beta2-charts/wantResults/upstream/my-other-chart-0.1.0.tgz
  pkg/tests/pull/cases/v1beta2-charts/wantResults/upstream/userdata/installation.yaml
  pkg/upstream/write.go
Labels: type::bug, bug::normal

#3906 fix: bump helm to 3.12.0
  deploy/Dockerfile
  deploy/okteto/okteto-v2.Dockerfile
  deploy/okteto/okteto.Dockerfile
  hack/dev/skaffold.Dockerfile
Labels: type::bug, bug::regression

#3856 update CLI support bundle command
  pkg/handlers/troubleshoot.go
  pkg/supportbundle/supportbundle.go
  web/src/components/UploadAirgapBundle.jsx
Labels: type::chore

#3908 update base for web dev images
  web/okteto.Dockerfile
  web/skaffold.Dockerfile
Labels: type::chore

#3909 Revert "update CLI support bundle command"
  pkg/handlers/troubleshoot.go
  pkg/supportbundle/supportbundle.go
  web/src/components/UploadAirgapBundle.jsx
Labels: type::chore

#3911 chore: dependency updates
  go.mod
  go.sum
Labels: type::security

#3914 update CLI support bundle command
  pkg/handlers/troubleshoot.go
  pkg/supportbundle/supportbundle.go
  web/src/components/UploadAirgapBundle.jsx
Labels: type::chore

#3913 update dependency image tags
  .image.env
  Makefile
  migrations/Makefile
  pkg/image/constants.go
Labels: type::security
