Repository replicatedhq/kots, pull requests merged in 2023-02, with the labels that each got.

#3592 Rianfowler/sc 65991/add kots modals to storybook the rest
  web/src/stories/ConfigureRedactorsModal.stories.tsx
  web/src/stories/DeployWarningModal.stories.tsx
  web/src/stories/HelmDeployModal.stories.tsx
  web/src/stories/SkipPrelightsModal.stories.tsx
  web/src/stories/UploadSupportBundle.stories.tsx
  web/src/stories/ViewSnapshotLogsModal.stories.tsx
Labels: type::chore

#3591 add restore snapshot modal to storybook
  web/src/stories/RestoreSnapshotModal.stories.tsx
Labels: type::chore

#3586 Miawong/sc 67312/can t generate new support bundle after deleting
  web/src/components/troubleshoot/SupportBundleList.tsx
  web/src/components/troubleshoot/SupportBundleRow.tsx
  web/src/context/ToastContext.tsx
  web/src/css/icon.css
  web/src/scss/utilities/base.scss
Labels: type::bug, bug::normal

#3595 fix colors for status informers
  web/src/scss/utilities/base.scss
  web/src/scss/utilities/overrides.scss
Labels: type::bug, bug::regression

#3596 add start of preflights hook
  web/src/features/PreflightChecks/api/getPreflightResult.tsx
  web/src/features/PreflightChecks/types.ts
  web/webpack.config.js
Labels: type::chore

#3597 Don't limit support bundles in e2e tests to a single namespace
  .github/actions/generate-support-bundle/action.yml
  .github/actions/kots-e2e/action.yml
Labels: type::chore

#3593 improve velero installation experience for existing clusters
  cmd/kots/cli/velero.go
  e2e/hack/deps.sh
  e2e/velero/cli.go
  pkg/handlers/handlers.go
  pkg/handlers/handlers_test.go
  pkg/handlers/interface.go
  pkg/handlers/mock/mock.go
  pkg/handlers/snapshots.go
  pkg/k8sutil/util.go
  pkg/k8sutil/util_test.go
  pkg/print/fs-lvp-velero-config.go
  pkg/print/fs-minio-velero-config.go
  pkg/print/velero.go
  pkg/snapshot/store.go
  pkg/snapshot/store_test.go
  pkg/snapshot/types/types.go
  pkg/snapshot/velero.go
  web/src/components/snapshots/AppSnapshots.jsx
  web/src/components/snapshots/SnapshotStorageDestination.tsx
  web/src/components/snapshots/Snapshots.jsx
Labels: type::feature

#3594 use currentVersion iconURI to display app icons
  pkg/api/downstream/types/types.go
  pkg/apiserver/server.go
  pkg/operator/operator.go
  pkg/operator/operator_test.go
  pkg/store/kotsstore/downstream_store.go
  pkg/store/kotsstore/version_store.go
  web/src/components/apps/AppVersionHistory.tsx
  web/src/components/shared/NavBar.jsx
  web/src/components/troubleshoot/GenerateSupportBundle.jsx
  web/src/components/watches/WatchSidebarItem/KotsSidebarItem.jsx
  web/src/features/Dashboard/components/Dashboard.tsx
  web/src/features/Dashboard/components/DashboardVersionCard.tsx
  web/src/features/Gitops/utils.js
  web/src/types/index.ts
Labels: type::bug, bug::regression

#3598 chore: collect all pod logs running in the rook-ceph namespace
  pkg/supportbundle/defaultspec/spec.yaml
Labels: type::chore

#3603 update logfmt pkg and increase buffer size
  go.mod
  go.sum
  pkg/kotsadmsnapshot/backup.go
  pkg/kotsadmsnapshot/logparser.go
  pkg/kotsadmsnapshot/logparser_test.go
Labels: type::bug, bug::normal

#3600 Miawong/sc 67855/refactor dashboard fetch into hooks
  web/src/features/Dashboard/api/createSnapshot.ts
  web/src/features/Dashboard/api/getAirgapConfig.ts
  web/src/features/Dashboard/api/getAppDownstream.ts
  web/src/features/Dashboard/api/getUpdateDownloadStatus.ts
  web/src/features/Dashboard/api/getUpdates.ts
Labels: type::chore

#3604 Miawong/sc 52689/add icons to storybook
  web/.storybook/main.js
  web/package.json
  web/src/stories/Icons.stories.tsx
  web/yarn.lock
Labels: type::chore

#3607 Miawong/sc 68795/fix snapshot settings docs link
  web/src/components/snapshots/SnapshotStorageDestination.tsx
Labels: type::bug, bug::normal

#3606 Rianfowler/sc 68110/create hook for preflight endpoints 2
  web/src/Root.tsx
  web/src/components/PreflightRenderer.tsx
  web/src/components/PreflightResultErrors.tsx
  web/src/components/PreflightResultPage.tsx
  web/src/components/apps/AppDetailPage.tsx
  web/src/components/shared/modals/SkipPreflightsModal.tsx
  web/src/components/troubleshoot/PreflightsProgress.tsx
  web/src/features/PreflightChecks/api/getPreflightResult.tsx
  web/src/features/PreflightChecks/api/index.ts
  web/src/features/PreflightChecks/api/postDeployKotsDownstream.tsx
  web/src/features/PreflightChecks/api/postIgnorePermissionErrors.tsx
  web/src/features/PreflightChecks/api/postPreflightRun.tsx
  web/src/features/PreflightChecks/types.ts
  web/src/stories/SkipPrelightsModal.stories.tsx
  web/src/utilities/utilities.js
Labels: type::chore

#3611 Miawong/sc 68585/Refactor Dashboard.tsx to use useUpdateDownloadStatus hook
  web/src/features/Dashboard/api/getUpdateDownloadStatus.ts
  web/src/features/Dashboard/components/Dashboard.tsx
Labels: type::chore

#3614 Rianfowler/sc 68569/refactor version history api calls to use extract view diff
  web/src/components/apps/AppVersionHistory.tsx
  web/src/features/AppVersionHistory/AppVersionHistoryRow.jsx
  web/src/features/Dashboard/components/DashboardVersionCard.tsx
  web/src/features/VersionDiff/VersionDiff.tsx
  web/src/features/VersionDiff/ViewDiffButton.tsx
Labels: type::chore

#3613 flatten selected app
  web/src/components/PreflightResultErrors.tsx
  web/src/components/apps/AppDetailPage.tsx
  web/src/components/redactors/EditRedactor.tsx
  web/src/components/shared/EditConfigIcon.tsx
  web/src/features/App/api/getLicense.ts
  web/src/features/App/hooks/useSelectedApp.tsx
  web/src/features/Dashboard/api/createSnapshot.ts
  web/src/features/Dashboard/api/getAirgapConfig.ts
  web/src/features/Dashboard/api/getAppDownstream.ts
  web/src/features/Dashboard/api/getNextAppVersion.ts
  web/src/features/Dashboard/api/getSelectedAppClusterDashboard.ts
  web/src/features/Dashboard/api/getUpdateDownloadStatus.ts
  web/src/features/Dashboard/api/getUpdates.ts
  web/src/features/Dashboard/components/DashboardVersionCard.tsx
  web/src/features/VersionDiff/ViewDiffButton.tsx
Labels: type::chore

#3619 flatten isHelmManaged hook return value
  web/src/components/hooks/useIsHelmManaged.js
  web/src/components/hooks/useIsHelmManaged.test.jsx
  web/src/components/hooks/useIsHelmManaged.tsx
  web/src/components/shared/EditConfigIcon.tsx
  web/src/features/AppConfig/components/AppConfig.tsx
  web/src/features/AppVersionHistory/api/getVersions.jsx
  web/src/features/Dashboard/api/getSelectedAppClusterDashboard.ts
  web/src/features/Dashboard/components/DashboardVersionCard.tsx
  web/src/features/VersionDiff/ViewDiffButton.tsx
Labels: type::chore

#3620 sort props and state
  web/src/components/apps/AppVersionHistory.tsx
Labels: type::chore

#3621 Surface HelmChart custom resource decoding and rendering errors better
  pkg/base/replicated.go
  pkg/kotsutil/kots.go
Labels: type::bug, bug::normal

#3622 Add typechecking to AppVersionHistoryRow
  web/src/components/apps/AppVersionHistory.tsx
  web/src/features/AppVersionHistory/AppVersionHistoryRow.tsx
  web/src/types/index.ts
Labels: type::chore

#3623 extract renderVersionDownloadStatus
  web/src/components/apps/AppVersionHistory.tsx
  web/src/features/AppVersionHistory/AppVersionHistoryRow.tsx
Labels: type::chore

#3628 chore/security: update go mods
  Makefile
  go.mod
  go.sum
  kurl_proxy/go.mod
  kurl_proxy/go.sum
Labels: type::security

#3625 make AppVersionHistoryRow a functional component
  web/src/features/AppVersionHistory/AppVersionHistoryRow.tsx
Labels: type::chore

#3626 Add selectedApp and isHelmManaged hooks to AppVersionHistoryRow
  web/src/components/apps/AppVersionHistory.tsx
  web/src/features/AppVersionHistory/AppVersionHistoryRow.tsx
Labels: type::chore

#3629 Fix a few velero/node-agent related error messages
  pkg/snapshot/velero.go
Labels: type::chore

#3631 fix config item affix logic
  web/src/components/config_render/ConfigUtil.js
Labels: type::bug, bug::regression

#3633 fix rerun preflight button logic
  web/src/components/PreflightResultPage.tsx
  web/src/features/PreflightChecks/api/getPreflightResult.tsx
  web/src/features/PreflightChecks/types.ts
Labels: type::bug, bug::regression

#3548 feat(support-bundle): use labels to search spec secret
  pkg/secrets/secrets.go
  pkg/supportbundle/spec.go
  pkg/supportbundle/spec_test.go
Labels: type::feature

#3610 exclude shutdown pods from backup
  pkg/kotsadmsnapshot/backup.go
  pkg/kotsadmsnapshot/backup_test.go
Labels: type::bug, bug::normal

#3627 create hooks needed for renderVersionAction in VersionHistoryPage
  web/src/components/PreflightResultPage.tsx
  web/src/components/apps/AppVersionHistory.tsx
  web/src/features/AdminConsole/api/getAdminConsoleUpdateStatus.tsx
  web/src/features/AdminConsole/api/postUpdateAdminConsole.tsx
  web/src/features/App/api/index.ts
  web/src/features/App/api/postDeployAppVersion.tsx
  web/src/features/App/api/postRedeployAppVersion.tsx
  web/src/features/AppVersionHistory/AppVersionHistoryRow.tsx
  web/src/features/AppVersionHistory/VersionAction.tsx
  web/src/features/AppVersionHistory/api/getDownloadAppVersionStatus.tsx
  web/src/features/AppVersionHistory/api/getVersions.tsx
  web/src/features/AppVersionHistory/api/index.ts
  web/src/features/AppVersionHistory/api/postDownloadAppVersion.tsx
  web/src/features/PreflightChecks/api/index.ts
  web/src/types/index.ts
Labels: type::chore

#3616 Add GKE Autopilot tests
  .github/actions/kots-e2e/action.yml
  .github/actions/kots-gke-create/action.yml
  .github/actions/kots-gke-delete/action.yml
  .github/workflows/build-test.yaml
Labels: type::chore

#3637 remove language about app metadata
  web/src/components/modals/SnapshotDifferencesModal.tsx
  web/src/components/snapshots/AppSnapshots.jsx
Labels: type::chore, type::docs

#3642 feat(support-bundle): remove duplicated collectors and analyzers
  pkg/supportbundle/spec.go
Labels: type::bug, bug::normal

#3643 remove babel register
  web/package.json
  web/yarn.lock
Labels: type::chore

#3646 upgrade terser
  web/package.json
  web/yarn.lock
Labels: type::chore

#3648 Dependabot/npm and yarn/web/loader utils 1.4.2 b
  web/yarn.lock
Labels: type::chore

#3650 update grafana/data to latest minor version
  web/package.json
  web/yarn.lock
Labels: type::chore

#3651 remove favicon utils
  web/package.json
  web/yarn.lock
Labels: type::chore

#3654 Ability to completely un-deploy an application including its resources and not just the reference
  .github/workflows/build-test.yaml
  cmd/kots/cli/remove.go
  pkg/handlers/app.go
  pkg/operator/operator.go
Labels: type::feature

#3657 fix: namespace field in HelmChart custom resource does not work when useHelmInstall is set to true
  .github/workflows/build-test.yaml
  pkg/operator/client/deploy.go
Labels: type::bug, bug::normal

#3649 remove bugsnag
  web/package.json
  web/webpack.config.dist.js
  web/yarn.lock
Labels: type::chore

#3652 remove jsonwebtoken
  web/package.json
  web/yarn.lock
Labels: type::chore

#3666 Check whether the registry connection is valid before unpacking the airgap bundle
  .github/workflows/build-test.yaml
  cmd/kots/cli/admin-console-push-images.go
  cmd/kots/cli/install.go
  cmd/kots/cli/upstream-upgrade.go
  cmd/kots/cli/util.go
  pkg/docker/registry/auth.go
  pkg/upstream/upgrade.go
Labels: type::feature, type::improvement

#3660 force trim-newlines to latest
  web/package.json
  web/yarn.lock
Labels: type::chore

#3664 turn on dependabot for npm
  .github/dependabot.yml
Labels: type::chore

#3665 Dependabot/npm and yarn/web/markdown it 12.3.2 b
  web/package.json
  web/yarn.lock
Labels: type::chore

#3668 Add support for ACR registries
  pkg/docker/registry/auth.go
Labels: type::feature

#3656 refactor fetchappdownstream to use hook
  web/src/features/Dashboard/api/getAppDownstream.ts
  web/src/features/Dashboard/components/Dashboard.tsx
Labels: type::chore

#3678 fix missing dependency
  web/package.json
  web/yarn.lock
Labels: type::chore

#3676 Fix printed Velero docs links to point v1.10 instead of v1.9
  pkg/print/velero.go
Labels: type::bug, bug::normal

#3680 Fix shell syntax error in validate-registry-check test
  .github/workflows/build-test.yaml
Labels: type::chore

#3663 force moment-timezone to latest patch
  web/package.json
  web/yarn.lock
Labels: type::chore

#3682 Dependabot/npm and yarn/dot GitHub/actions/kurl addon kots publisher/json5 2.2.3 b
  .github/actions/kurl-addon-kots-publisher/package-lock.json
Labels: type::chore

#3683 replace usage of github-action-get-latest-release [sc-70357]
  .github/workflows/release.yaml
Labels: type::chore

#3679 Miawong/sc 68585/refactor dashboard snapshot card
  web/src/components/apps/AppDetailPage.tsx
  web/src/features/Dashboard/api/createSnapshot.ts
  web/src/features/Dashboard/api/getSnapshotSettings.ts
  web/src/features/Dashboard/components/Dashboard.tsx
  web/src/features/Dashboard/components/DashboardSnapshotsCard.tsx
  web/src/types/index.ts
Labels: type::chore

#3667 Change stateful set status informer updating calculation
  .github/workflows/build-test.yaml
  pkg/appstate/statefulsets.go
Labels: type::chore

#3636 Add daemonset status informer
  pkg/appstate/appstate.go
  pkg/appstate/daemonsets.go
  pkg/appstate/resource_test.go
Labels: type::feature

#3684 Miawong/sc 68585/refactor dashboard airgap config
  web/src/features/Dashboard/api/getAirgapConfig.ts
  web/src/features/Dashboard/components/Dashboard.tsx
Labels: type::chore

#3624 migrate to minio xl backend
  .github/workflows/build-test.yaml
  .image.env
  Makefile
  cmd/imagedeps/image-spec
  cmd/imagedeps/main.go
  cmd/imagedeps/tag-finder.go
  cmd/kots/cli/admin-console-generate-manifests.go
  cmd/kots/cli/identity.go
  cmd/kots/cli/install.go
  cmd/kots/cli/upstream-upgrade.go
  cmd/kots/cli/velero.go
  pkg/image/constants.go
  pkg/k8sutil/statefulset.go
  pkg/kotsadm/configmaps.go
  pkg/kotsadm/main.go
  pkg/kotsadm/minio.go
  pkg/kotsadm/minio_test.go
  pkg/kotsadm/objects/images.go
  pkg/kotsadm/objects/minio_objects.go
  pkg/kotsadm/objects/minio_objects_test.go
  pkg/kotsadm/objects/scripts/copy-minio-client.sh
  pkg/kotsadm/objects/scripts/export-minio-data.sh
  pkg/kotsadm/objects/scripts/import-minio-data.sh
  pkg/kotsadm/secrets.go
  pkg/kotsadm/types/deployoptions.go
  pkg/pull/pull.go
  pkg/rewrite/rewrite.go
  pkg/upstream/admin-console.go
  pkg/upstream/types/types.go
Labels: type::security

#3659 add collector for rqlite backup
  deploy/kurl/kotsadm/template/base/rqlite.yaml
  migrations/kustomize/overlays/dev/rqlite.yaml
  migrations/kustomize/overlays/okteto/rqlite.yaml
  pkg/kotsadm/objects/rqlite_objects.go
  pkg/supportbundle/defaultspec/spec.yaml
Labels: type::feature

#3677 Add css var overrides for primary and link colors
  web/package.json
  web/src/css/icon.css
  web/src/scss/components/PreflightCheckPage.scss
  web/src/scss/components/RestoreSnapshotRow.scss
  web/src/scss/components/apps/AppVersionHistory.scss
  web/src/scss/components/clusters/ClusterCard.scss
  web/src/scss/components/config-render/config-base-styles.scss
  web/src/scss/components/forms/input.scss
  web/src/scss/components/forms/textarea.scss
  web/src/scss/components/gitops/GitOpsDeploymentManager.scss
  web/src/scss/components/identity/IdentityManagement.scss
  web/src/scss/components/redactors/Redactor.scss
  web/src/scss/components/shared/CodeSnippet.scss
  web/src/scss/components/shared/InlineDropdown.scss
  web/src/scss/components/shared/MarkdownRenderer.scss
  web/src/scss/components/shared/NavBar.scss
  web/src/scss/components/shared/SideBar.scss
  web/src/scss/components/shared/SnapshotForm.scss
  web/src/scss/components/snapshots/AppSnapshots.scss
  web/src/scss/components/troubleshoot/FileTree.scss
  web/src/scss/components/troubleshoot/SupportBundleAnalysis.scss
  web/src/scss/components/troubleshoot/SupportBundleList.scss
  web/src/scss/components/watches/DashboardCard.scss
  web/src/scss/components/watches/DownstreamWatchVersionDiff.scss
  web/src/scss/components/watches/IntegrationCard.scss
  web/src/scss/components/watches/NotificationsModal.scss
  web/src/scss/components/watches/VersionCard.scss
  web/src/scss/components/watches/WatchCard.scss
  web/src/scss/components/watches/WatchConfig.scss
  web/src/scss/components/watches/WatchDetailPage.scss
  web/src/scss/utilities/base.scss
  web/src/scss/utilities/buttons.scss
  web/src/scss/utilities/colors.scss
  web/src/scss/utilities/forms.scss
  web/src/scss/utilities/tooltip.scss
  web/src/scss/variables.scss
  web/yarn.lock
Labels: type::feature

#3688 add scan for minio client
  .github/workflows/alpha.yaml
Labels: type::chore

#3689 add security label to automated image deps pr
  .github/workflows/release.yaml
Labels: type::chore
