Repository replicatedhq/kots, pull requests merged in 2023-06, with the labels that each got.

#3905 bug: setting https proxy to the right value
  deploy/kurl/kotsadm/template/base/deployment/tmpl-kotsadm-proxy.yaml
  deploy/kurl/kotsadm/template/base/install.sh
  deploy/kurl/kotsadm/template/base/statefulset/tmpl-kotsadm-proxy.yaml
Labels: type::bug, bug::normal

#3917 fix flaky test `validate-kots-helm-release-secret-migration`
  .github/workflows/build-test.yaml
Labels: type::chore, skip-sc

#3920 Use the custom domains from the installation spec instead of application spec
  kotskinds/apis/kots/v1beta1/installation_types.go
  kotskinds/client/kotsclientset/clientset.go
  kotskinds/client/kotsclientset/fake/clientset_generated.go
  kotskinds/client/kotsclientset/fake/register.go
  kotskinds/client/kotsclientset/typed/kots/v1beta2/doc.go
  kotskinds/client/kotsclientset/typed/kots/v1beta2/fake/doc.go
  kotskinds/client/kotsclientset/typed/kots/v1beta2/fake/fake_helmchart.go
  kotskinds/client/kotsclientset/typed/kots/v1beta2/fake/fake_kots_client.go
  kotskinds/client/kotsclientset/typed/kots/v1beta2/generated_expansion.go
  kotskinds/client/kotsclientset/typed/kots/v1beta2/helmchart.go
  kotskinds/client/kotsclientset/typed/kots/v1beta2/kots_client.go
  kotskinds/config/crds/kots.io_installations.yaml
  kotskinds/schemas/installation-kots-v1beta1.json
  pkg/base/replicated.go
  pkg/base/templates.go
  pkg/base/write_images_test.go
  pkg/config/config_test.go
  pkg/docker/registry/registry.go
  pkg/docker/registry/registry_test.go
  pkg/handlers/config.go
  pkg/image/builder.go
  pkg/kotsadmconfig/config.go
  pkg/midstream/write.go
  pkg/preflight/preflight.go
  pkg/pull/peek.go
  pkg/pull/pull.go
  pkg/registry/troubleshoot.go
  pkg/registry/troubleshoot_test.go
  pkg/render/render.go
  pkg/rewrite/rewrite.go
  pkg/store/kotsstore/version_store.go
  pkg/store/mock/mock.go
  pkg/store/store_interface.go
  pkg/supportbundle/spec.go
  pkg/template/builder.go
  pkg/template/config_context.go
  pkg/template/config_context_test.go
  pkg/template/license_context.go
  pkg/template/license_context_test.go
  pkg/template/version_context.go
  pkg/template/version_context_test.go
  pkg/updatechecker/updatechecker.go
  pkg/upstream/fetch.go
  pkg/upstream/replicated.go
  pkg/upstream/types/types.go
  pkg/upstream/write.go
Labels: type::feature, type::improvement

#3922 fix creation of config values for multi-doc releases
  pkg/base/replicated.go
  pkg/base/replicated_test.go
  pkg/base/templates.go
  pkg/upstream/replicated.go
  pkg/upstream/replicated_test.go
Labels: type::bug, bug::normal

#3921 Miawong/sc 78583/fix log in font size
  web/src/features/Auth/components/SecureAdminConsole.tsx
  web/src/utilities/utilities.js
Labels: type::bug, bug::regression

#3923 add disabled and readOnly attr to InputField component
  web/src/components/shared/forms/InputField.jsx
Labels: type::bug, bug::regression

#3918 Image Dependency Update
  .image.env
  Makefile
  migrations/Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::chore

#3925 Adding additional distribution detection mechanisms
  pkg/api/reporting/types/types.go
  pkg/reporting/app.go
  pkg/reporting/distribution.go
  pkg/reporting/types.go
  pkg/reporting/util.go
Labels: type::feature

#3929 Bump troubleshoot version to v0.68.0
  go.mod
  go.sum
Labels: type::chore

#3899 Miawong/sc 74983/upgrade to admin console react router 6
  web/package.json
  web/src/Root.tsx
  web/src/components/Home.jsx
  web/src/components/PreflightResultErrors.tsx
  web/src/components/PreflightResultPage.tsx
  web/src/components/UploadAirgapBundle.jsx
  web/src/components/UploadLicenseFile.tsx
  web/src/components/apps/AppDetailPage.tsx
  web/src/components/apps/AppLicense.tsx
  web/src/components/apps/AppVersionHistory.tsx
  web/src/components/identity/Access.tsx
  web/src/components/redactors/EditRedactor.tsx
  web/src/components/redactors/Redactors.jsx
  web/src/components/shared/AirgapRegistrySettings.tsx
  web/src/components/shared/NavBar.tsx
  web/src/components/shared/NavBarDropdown.jsx
  web/src/components/snapshots/AppSnapshotRestore.jsx
  web/src/components/snapshots/AppSnapshots.jsx
  web/src/components/snapshots/GettingStartedSnapshots.jsx
  web/src/components/snapshots/SnapshotDetails.jsx
  web/src/components/snapshots/SnapshotRestore.jsx
  web/src/components/snapshots/SnapshotRow.jsx
  web/src/components/snapshots/SnapshotSchedule.jsx
  web/src/components/snapshots/SnapshotSettings.jsx
  web/src/components/snapshots/SnapshotStorageDestination.tsx
  web/src/components/snapshots/Snapshots.jsx
  web/src/components/snapshots/SnapshotsWrapper.jsx
  web/src/components/tree/KotsApplicationTree.tsx
  web/src/components/troubleshoot/AnalyzerFileTree.jsx
  web/src/components/troubleshoot/AnalyzerInsights.jsx
  web/src/components/troubleshoot/AnalyzerRedactorReport.jsx
  web/src/components/troubleshoot/AnalyzerRedactorReportRow.jsx
  web/src/components/troubleshoot/GenerateSupportBundle.jsx
  web/src/components/troubleshoot/GenerateSupportBundleModal.tsx
  web/src/components/troubleshoot/SupportBundleAnalysis.jsx
  web/src/components/troubleshoot/SupportBundleList.tsx
  web/src/components/troubleshoot/SupportBundleRow.tsx
  web/src/components/troubleshoot/TroubleshootContainer.tsx
  web/src/features/AddNewApp/components/InstallWithHelm.tsx
  web/src/features/App/api/postDeployAppVersion.tsx
  web/src/features/AppConfig/components/AppConfig.tsx
  web/src/features/AppConfig/components/ConfigInfo.jsx
  web/src/features/AppVersionHistory/AppVersionHistoryRow.tsx
  web/src/features/Auth/components/SecureAdminConsole.tsx
  web/src/features/Dashboard/api/getUpdates.ts
  web/src/features/Dashboard/components/AppStatus.tsx
  web/src/features/Dashboard/components/Dashboard.tsx
  web/src/features/Dashboard/components/DashboardSnapshotsCard.tsx
  web/src/features/Dashboard/components/DashboardVersionCard.tsx
  web/src/features/Dashboard/components/DumbComponent.jsx
  web/src/features/Gitops/components/AppGitops.jsx
  web/src/features/Gitops/components/modals/ConnectionModal.jsx
  web/src/features/VersionDiff/VersionDiff.tsx
  web/src/index.tsx
  web/src/utilities/react-router-utilities.tsx
  web/yarn.lock
Labels: type::chore

#3932 fix `go.mod` CVEs
  .trivyignore
  Makefile
  go.mod
  go.sum
  kurl_proxy/go.mod
  kurl_proxy/go.sum
Labels: type::security

#3940 upgrade to go v1.20
  .github/actions/copy-assets/Dockerfile
  .github/workflows/alpha.yaml
  .github/workflows/build-test.yaml
  .github/workflows/release.yaml
  deploy/okteto/okteto-v2.Dockerfile
  deploy/okteto/okteto.Dockerfile
  go.mod
  go.sum
  hack/dev/skaffoldcache.Dockerfile
  kurl_proxy/go.mod
  kurl_proxy/go.sum
  kurl_proxy/okteto.Dockerfile
  kurl_proxy/skaffold.Dockerfile
Labels: type::chore

#3941 fix: repeatable config options ui
  web/src/components/config_render/ConfigRender.jsx
Labels: type::bug, bug::regression

#3942 kgrid has reached EOL and is no longer maintained
  .github/workflows/release.yaml
  hack/deploy-kgrid.sh
  hack/wait-kgrid.sh
Labels: type::chore

#3944 security: update image tags and go mod
  .image.env
  Makefile
  go.mod
  go.sum
  migrations/Makefile
  pkg/image/constants.go
Labels: type::security

#3945 Automated Kubectl version update
  deploy/Dockerfile
Labels: automated-pr, type::chore, kubectl
