Repository replicatedhq/kots, pull requests merged in 2023-07, with the labels that each got.

#3961 setup-kustomize in ci-test-kots
  .github/workflows/build-test.yaml
  .github/workflows/release.yaml
Labels: type::chore

#3958 upgrade dex to v2.37.0
  .image.env
  Makefile
  migrations/Makefile
  pkg/image/constants.go
Labels: type::security

#3964 Read Preflights from Helm Charts
  Makefile
  pkg/handlers/preflight.go
  pkg/kotsutil/troubleshoot.go
  pkg/preflight/execute.go
  pkg/preflight/preflight.go
  pkg/tests/kotsutil/cases/multiple-preflights-in-helm-chart/rendered/this-cluster/helm/my-app/all.yaml
  pkg/tests/kotsutil/cases/no-preflights-in-helm-chart/rendered/this-cluster/helm/my-app/all.yaml
  pkg/tests/kotsutil/cases/preflights-in-helm-chart/rendered/this-cluster/helm/my-app/all.yaml
  pkg/tests/kotsutil/troubleshoot_test.go
Labels: type::feature

#3969 fix alpha workflow kustomize
  .github/workflows/alpha.yaml
Labels: type::chore

#3972 add downstreams for airgap update
  pkg/airgap/update.go
Labels: type::bug, bug::regression

#3980 add default-http-backend ingress service when k8s version is < 1.22
  pkg/appstate/ingress.go
  pkg/appstate/ingress_test.go
  pkg/k8sutil/clientset.go
  pkg/k8sutil/clientset_test.go
Labels: type::bug, bug::regression

#3982 Fix skaffold after removing kotskinds directory
  hack/dev/skaffold.Dockerfile
  hack/dev/skaffoldcache.Dockerfile
Labels: type::chore

#3983 Use defaults for repeatable config items if values are not provided
  e2e/velero/cli.go
  pkg/template/config_context.go
  pkg/upstream/replicated.go
  pkg/upstream/replicated_test.go
Labels: type::bug, bug::normal

#3966 Automated Kots Image Dependency Tag Update
  .image.env
  Makefile
  migrations/Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#3991 Fix processing charts/subcharts that have '-charts/' as a suffix in the name
  pkg/base/helm.go
  pkg/base/helm_test.go
Labels: type::bug, bug::regression

#3993 upgrade to helm 3.12.2 to resolve CVE-2023-2253
  deploy/Dockerfile
  deploy/okteto/okteto-v2.Dockerfile
  deploy/okteto/okteto.Dockerfile
  hack/dev/skaffold.Dockerfile
Labels: type::security
