Repository replicatedhq/kots, pull requests merged in 2023-11, with the labels that each got.

#4119 Added OKE (Oracle Kubernetes Engine) to distribution support (#4117)
  go.mod
  go.sum
  pkg/reporting/distribution.go
  pkg/reporting/distribution_test.go
  pkg/reporting/types.go
  pkg/template/static_context_test.go
Labels: type::feature, type::improvement

#4120 Cap report secrets data at 1MB and improve tests
  pkg/handlers/metrics_test.go
  pkg/reporting/instance_report.go
  pkg/reporting/preflight_report.go
  pkg/reporting/report.go
  pkg/reporting/report_test.go
Labels: type::bug, bug::normal

#4118 validate-replicated-sdk test
  .github/workflows/build-test.yaml
Labels: type::chore

#4122 debian bookworm base image
  deploy/Dockerfile
  deploy/okteto/okteto.Dockerfile
  hack/dev/skaffold.Dockerfile
  kurl_proxy/deploy/Dockerfile
  migrations/deploy/Dockerfile
  web/okteto.Dockerfile
Labels: type::security

#4126 Use CLI to validate minimal RBAC tests instead of testim
  .github/workflows/build-test.yaml
  cmd/kots/cli/install.go
  e2e/e2e_test.go
  e2e/testim/inventory/inventory.go
  hack/build-ttl.sh
  migrations/build-ttl.sh
  pkg/preflight/preflight.go
  pkg/print/config.go
  pkg/print/preflight.go
Labels: type::feature, type::improvement

#4128 upgrade helm to 3.13.2
  deploy/Dockerfile
  deploy/okteto/okteto-v2.Dockerfile
  deploy/okteto/okteto.Dockerfile
  go.mod
  go.sum
  hack/dev/skaffold.Dockerfile
Labels: type::security

#4130 bump golang.org/x/net in kurl_proxy
  kurl_proxy/go.mod
  kurl_proxy/go.sum
Labels: type::security

#4134 fix pull secret check in pull tests
  pkg/tests/pull/pull_test.go
Labels: type::chore

#4132 upgrade minio and remove mc image dependency
  .github/workflows/alpha.yaml
  .github/workflows/build-test.yaml
  .github/workflows/release.yaml
  .image.env
  Makefile
  cmd/imagedeps/image-spec
  cmd/imagedeps/main.go
  cmd/imagedeps/tag-finder.go
  pkg/image/constants.go
  pkg/kotsadm/objects/images.go
  pkg/kotsadm/objects/minio_objects.go
  pkg/kotsadm/objects/scripts/copy-minio-client.sh
  pkg/kotsadm/objects/scripts/import-minio-data.sh
Labels: type::security

#4137 golang:1.21-bookworm for kurl_proxy dev env
  kurl_proxy/okteto.Dockerfile
  kurl_proxy/skaffold.Dockerfile
Labels: type::chore

#4138 snapshot reporting
  pkg/api/reporting/types/types.go
  pkg/handlers/snapshot_logs.go
  pkg/kotsadm/minio.go
  pkg/kotsadmsnapshot/backup.go
  pkg/kotsadmsnapshot/restore.go
  pkg/reporting/app.go
  pkg/reporting/app_airgap.go
  pkg/reporting/app_test.go
  pkg/reporting/instance_report.go
  pkg/reporting/report_test.go
  pkg/reporting/util.go
  pkg/snapshot/filesystem_lvp.go
  pkg/snapshot/store.go
  pkg/snapshot/store_test.go
  pkg/snapshot/velero.go
Labels: type::feature, type::improvement

#4173 update e2e nodejs install method
  e2e/hack/Dockerfile
  e2e/hack/deps.sh
Labels: type::chore

#4177 fix e2e-infra-cleanup workflow
  .github/workflows/e2e-infra-cleanup.yaml
  .github/workflows/regression.yaml
Labels: type::chore

#4178 clean up helmvm workspaces
  .github/workflows/e2e-workspace-cleanup.yaml
Labels: type::chore

#4135 Automated Kubectl version update
  deploy/Dockerfile
Labels: automated-pr, type::chore, kubectl

#4180 another mega dependabot
  .github/workflows/alpha.yaml
  .github/workflows/build-test.yaml
  .github/workflows/e2e-infra-cleanup.yaml
  .github/workflows/e2e-workspace-cleanup.yaml
  .github/workflows/license.yaml
  .github/workflows/release.yaml
  go.mod
  go.sum
  web/package.json
  web/yarn.lock
Labels: go, javascript, dependabot, github-actions

#4182 Generate join command based on selected node type when adding a node
  pkg/kurl/configmap.go
  web/src/components/apps/KurlClusterManagement.jsx
Labels: type::bug, bug::regression

#4184 add support-bundle tests to e2e suite
  .github/workflows/build-test.yaml
  e2e/e2e_test.go
  e2e/testim/inventory/inventory.go
Labels: type::chore

#4192 remove old build-push-kotsadm-image reference
  .github/workflows/build-test.yaml
Labels: type::chore

#4193 build-kots dependency
  .github/workflows/build-test.yaml
Labels: type::chore

#4185 fix: registry check strips port
  cmd/kots/cli/admin-console-push-images.go
  cmd/kots/cli/install.go
  cmd/kots/cli/upstream-upgrade.go
  cmd/kots/cli/util.go
  cmd/kots/cli/util_test.go
Labels: type::bug, bug::normal
