Repository replicatedhq/kots, pull requests merged in 2024-01, with the labels that each got.

#4262 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4265 Abiltiy to run tests in Dependabot PRs and auto approve/merge
  .github/dependabot.yml
  .github/workflows/build-test.yaml
Labels: type::security

#4266 Use PR author instead of actor for dependabot PRs
  .github/workflows/build-test.yaml
Labels: type::security

#4268 Fix dependabot job conditional
  .github/workflows/build-test.yaml
Labels: type::security

#4269 Consolidate dependabot PRs
  go.mod
  go.sum
  pkg/kotsadm/objects/distribution_objects.go
  pkg/kotsadm/objects/kotsadm_objects.go
  pkg/kotsadm/objects/minio_objects.go
  pkg/kotsadm/objects/rqlite_objects.go
  web/package.json
  web/yarn.lock
Labels: type::security

#4280 feat: propagate end user provided overrides
  go.mod
  go.sum
  pkg/embeddedcluster/util.go
Labels: type::feature

#4278 Automated PRs manager workflow
  .github/workflows/automated-prs-manager.yaml
  .github/workflows/build-test.yaml
Labels: type::security

#4282 Run image deps updater at 9am UTC
  .github/workflows/image-deps-updater.yaml
Labels: type::security

#4281 feat: provide overrides for embedded cluster join
  pkg/handlers/embedded_cluster_node_join_command.go
Labels: type::feature

#4291 Create a single dependabot PR per package manager / project
  .github/dependabot.yml
  .github/workflows/automated-prs-manager.yaml
Labels: type::security

#4293 Test removing PR limit for npm
  .github/dependabot.yml
Labels: type::security

#4294 Customize main dir dependabot rules
  .github/dependabot.yml
Labels: type::security

#4304 Group npm using semver
  .github/dependabot.yml
Labels: type::security

#4310 Allow all npm dependency types
  .github/dependabot.yml
Labels: type::security

#4313 Group npm updates using minor,patch only
  .github/dependabot.yml
Labels: type::security

#4314 remove pr limit
  .github/dependabot.yml
Labels: type::security

#4315 allow major version updates in npm
  .github/dependabot.yml
Labels: type::security

#4316 Run dependabot gomod job at 11am UTC
  .github/dependabot.yml
Labels: type::security

#4317 group dependabot prs by patch
  .github/dependabot.yml
Labels: type::security

#4327 Organize automated PRs run times
  .github/dependabot.yml
  .github/workflows/image-deps-updater.yaml
Labels: type::security

#4283 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4331 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4332 fix: use rendered KOTS kinds to create version even when configuration is needed
  pkg/pull/pull.go
  pkg/tests/pull/cases/needsconfig/testcase.yaml
  pkg/tests/pull/cases/needsconfig/upstream/app/configmap.yaml
  pkg/tests/pull/cases/needsconfig/upstream/kots-app.yaml
  pkg/tests/pull/cases/needsconfig/upstream/kots-config.yaml
  pkg/tests/pull/cases/needsconfig/upstream/kots-preflight.yaml
  pkg/tests/pull/cases/needsconfig/upstream/my-chart-0.1.0.tgz
  pkg/tests/pull/cases/needsconfig/upstream/my-excluded-chart.yaml
  pkg/tests/pull/cases/needsconfig/upstream/userdata/license.yaml
  pkg/tests/pull/cases/needsconfig/wantResults/kotsKinds/kots-app.yaml
  pkg/tests/pull/cases/needsconfig/wantResults/kotsKinds/kots-config.yaml
  pkg/tests/pull/cases/needsconfig/wantResults/kotsKinds/kots-preflight.yaml
  pkg/tests/pull/cases/needsconfig/wantResults/kotsKinds/my-excluded-chart.yaml
  pkg/tests/pull/cases/needsconfig/wantResults/kotsKinds/userdata/config.yaml
  pkg/tests/pull/cases/needsconfig/wantResults/kotsKinds/userdata/installation.yaml
  pkg/tests/pull/cases/needsconfig/wantResults/kotsKinds/userdata/license.yaml
  pkg/tests/pull/cases/needsconfig/wantResults/upstream/app/configmap.yaml
  pkg/tests/pull/cases/needsconfig/wantResults/upstream/kots-app.yaml
  pkg/tests/pull/cases/needsconfig/wantResults/upstream/kots-config.yaml
  pkg/tests/pull/cases/needsconfig/wantResults/upstream/kots-preflight.yaml
  pkg/tests/pull/cases/needsconfig/wantResults/upstream/my-chart-0.1.0.tgz
  pkg/tests/pull/cases/needsconfig/wantResults/upstream/my-excluded-chart.yaml
  pkg/tests/pull/cases/needsconfig/wantResults/upstream/userdata/config.yaml
  pkg/tests/pull/cases/needsconfig/wantResults/upstream/userdata/installation.yaml
  pkg/tests/pull/cases/needsconfig/wantResults/upstream/userdata/license.yaml
  pkg/tests/pull/pull_test.go
Labels: type::bug, bug::normal

#4333 Use GITHUB_TOKEN for Automated PRs Manager github action
  .github/workflows/automated-prs-manager.yaml
Labels: type::security

#4334 add kubectl 1.29
  deploy/Dockerfile
  deploy/apko.yaml.tmpl
  deploy/melange.yaml.tmpl
  deploy/okteto/okteto-v2.Dockerfile
  deploy/okteto/okteto.Dockerfile
  hack/dev/skaffold.Dockerfile
Labels: type::chore

#4335 revert network-timeout for web deps
  web/Makefile
Labels: type::chore

#4337 Add default node affinity rules to rqlite and minio
  pkg/kotsadm/objects/minio_objects.go
  pkg/kotsadm/objects/rqlite_objects.go
Labels: type::bug, bug::normal

#4338 Use REPLICATED_GH_PAT for the Automated PRs Manager workflow
  .github/workflows/automated-prs-manager.yaml
  .github/workflows/image-deps-updater.yaml
Labels: type::security

#4339 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4340 Ensure that KOTS resources only get scheduled on amd64 nodes
  pkg/kotsadm/objects/affinity_objects.go
Labels: type::bug, bug::normal

#4341 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4342 chore: add new ec operator statuses
  web/src/utilities/utilities.js
Labels: type::chore

#4345 Fix kots build
  cmd/kots/cli/admin-console-upgrade.go
Labels: type::chore

#4346 Fix kots build - again
  pkg/version/metrics_test.go
Labels: type::chore

#4344 improvement: set acceptAnonymousUploads=1 for initial kotsadm-tls cert
  kurl_proxy/cmd/main.go
  kurl_proxy/cmd/main_test.go
  kurl_proxy/go.mod
  kurl_proxy/go.sum
Labels: type::chore, type::improvement

#4349 Detect MinIO image from the 'ha-minio' StatefulSet if exists
  pkg/image/minio.go
  pkg/image/minio_test.go
  pkg/kurl/configmap.go
  pkg/kurl/configmap_test.go
Labels: type::bug, bug::normal

#4360 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4362 bug: do not fail to install if no embedded cluster installation
  pkg/embeddedcluster/monitor.go
  pkg/embeddedcluster/util.go
Labels: type::bug, bug::normal

#4365 use kurl-proxy-kotsadm nodeport in embedded-cluster installations
  pkg/embeddedcluster/node_join.go
Labels: type::bug, bug::regression

#4367 embedded cluster state display should not split up application state
  web/src/features/Dashboard/components/AppStatus.tsx
Labels: type::bug, bug::normal

#4368 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4369 add namespace to locked password command
  pkg/handlers/login.go
Labels: type::feature, type::improvement

#4371 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4370 Automated Kubectl version update
  deploy/Dockerfile
Labels: automated-pr, type::chore, type::security, kubectl

#4372 pass expires-on date for regression tests
  .github/workflows/regression.yaml
Labels: type::chore

#4374 update embedded-cluster-operator to v0.20.0
  go.mod
  go.sum
Labels: type::chore

#4375 fix expires-on date command
  .github/workflows/regression.yaml
Labels: type::chore

#4389 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4376 get expiration in separate job
  .github/workflows/regression.yaml
Labels: type::chore

#4391 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4392 Only run tests against k3s and openshift
  .github/actions/cmx-versions/action.yaml
  .github/actions/cmx-versions/dist/index.js
  .github/actions/cmx-versions/index.js
  .github/dependabot.yml
  .github/workflows/build-test.yaml
Labels: type::chore, type::tests

#4396 fix AddonsInstalling constant
  web/src/utilities/utilities.js
Labels: type::chore

#4400 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4398 embedded cluster upgrade modal
  Makefile
  pkg/api/handlers/types/types.go
  pkg/handlers/app.go
  pkg/store/kotsstore/version_store.go
  pkg/store/mock/mock.go
  pkg/store/store_interface.go
  web/src/Root.tsx
  web/src/components/apps/AppDetailPage.tsx
  web/src/components/clusters/EmbeddedClusterUpgrading.tsx
  web/src/types/index.ts
  web/src/utilities/utilities.js
  web/src/utilities/utilities.test.js
Labels: type::feature, type::improvement

#4401 update embedded cluster check in apps handler
  pkg/handlers/app.go
Labels: type::chore

#4406 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4408 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4410 Fix building kotsadm bundle
  .github/workflows/release.yaml
  pkg/image/airgap.go
  pkg/imageutil/image.go
  pkg/imageutil/image_test.go
Labels: type::feature

#4411 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4412 Fix downloading kubectl binary for skaffold
  hack/dev/skaffold.Dockerfile
Labels: type::chore

#4413 fix skaffold minio image
  kustomize/overlays/kotsstore/minio/statefulset.yaml
Labels: type::chore

#4414 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  migrations/Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security
