Repository replicatedhq/kots, pull requests merged in 2024-03, with the labels that each got.

#4487 fix license upload page flash when logged out
  web/src/components/apps/AppDetailPage.tsx
Labels: type::bug, bug::normal

#4492 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4488 fix cluster upgrade modal not showing intermittently
  pkg/api/handlers/types/types.go
  pkg/embeddedcluster/util.go
  pkg/handlers/app.go
  web/src/utilities/utilities.js
  web/src/utilities/utilities.test.js
Labels: type::bug, bug::normal

#4486 Improvements to get/set config CLI commands
  .github/workflows/build-test.yaml
  cmd/kots/cli/get-config.go
  cmd/kots/cli/set-config.go
  pkg/handlers/config.go
  web/src/features/AppConfig/components/AppConfig.tsx
  web/src/features/AppVersionHistory/AppVersionHistoryRow.tsx
Labels: type::feature

#4493 disable rolling back the app on embedded cluster
  pkg/store/kotsstore/version_store.go
Labels: type::feature

#4494 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4507 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4513 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4514 allow embedded cluster node labels with dns prefix
  pkg/embeddedcluster/roles.go
  pkg/embeddedcluster/roles_test.go
Labels: type::bug, bug::normal

#4515 push embedded-cluster oci artifacts
  go.mod
  go.sum
  pkg/image/airgap.go
  pkg/image/airgap_test.go
  pkg/image/types/types.go
  pkg/imageutil/image.go
  pkg/imageutil/image_test.go
Labels: type::feature

#4517 Add exclude-admin-console flag to KOTS install command to support EC installs
  cmd/kots/cli/install.go
Labels: type::feature

#4518 process embedded-cluster airgap artifacts during install and upgrade
  cmd/kots/cli/install.go
  pkg/airgap/airgap.go
  pkg/automation/automation.go
  pkg/handlers/airgap.go
  pkg/image/airgap.go
  pkg/image/types/types.go
  pkg/kotsadm/configmaps.go
  pkg/kotsadm/main.go
  pkg/kotsadm/types/deployoptions.go
  pkg/pull/pull.go
  pkg/rewrite/rewrite.go
  pkg/upstream/upgrade.go
Labels: type::feature

#4519 Add support for embedded cluster registry
  cmd/kots/cli/install.go
  pkg/handlers/airgap.go
  pkg/handlers/app.go
  pkg/handlers/license.go
  pkg/kotsadmsnapshot/backup.go
  pkg/kotsutil/embedded.go
  pkg/kotsutil/embedded_test.go
  pkg/registry/images.go
  pkg/registry/registry.go
Labels: type::feature

#4520 fix: don't deploy app if pending_cluster_management in airgap
  pkg/airgap/airgap.go
Labels: type::bug, bug::normal

#4523 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4525 use plain http for embedded artifact push
  pkg/image/airgap.go
  pkg/image/airgap_test.go
Labels: type::bug, bug::normal

#4526 Automated KOTS Image Dependency Tag Update
  .image.env
  migrations/Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security
