Repository replicatedhq/kots, pull requests merged in 2024-08, with the labels that each got.

#4797 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4798 Fix typo
  e2e/playwright/tests/smoke-test/test.spec.ts
  pkg/license/signature.go
Labels: type::chore

#4795 Fix error in Cluster Management page when clicking continue
  pkg/handlers/embedded_cluster_confirm_cluster_management.go
  web/src/components/PreflightResultPage.tsx
  web/src/components/upgrade_service/ConfirmAndDeploy.tsx
  web/src/components/upgrade_service/PreflightChecks.tsx
  web/src/features/AppConfig/components/AppConfig.tsx
  web/src/features/PreflightChecks/api/getPreflightResult.tsx
Labels: type::bug, bug::normal

#4805 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4806 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4807 docs: update e2e readme with pw instructions
  e2e/README.md
Labels: type::chore, type::docs

#4799 Embedded Cluster: Improve UX for license installation process
  web/src/Root.tsx
  web/src/components/UploadLicenseFile.tsx
  web/src/components/apps/AppDetailPage.tsx
  web/src/components/apps/AppLoading.tsx
Labels: type::bug, bug::normal

#4808 Add uri field to the default support bundle spec
  pkg/supportbundle/staticspecs/defaultspec.yaml
Labels: type::chore

#4809 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  migrations/Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4810 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4812 Revert uri field in default support bundle spec
  pkg/supportbundle/staticspecs/defaultspec.yaml
Labels: type::chore

#4813 Add dropdown and radio config item types
  e2e/playwright/tests/smoke-test/test.spec.ts
  pkg/kotsadmconfig/types/types.go
  pkg/template/config_context.go
  web/src/components/config_render/ConfigDropdown.tsx
  web/src/components/config_render/ConfigGroup.jsx
Labels: type::feature

#4820 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4821 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4816 Add uri field to the default support bundle spec
  pkg/supportbundle/spec.go
  pkg/supportbundle/staticspecs/defaultspec.yaml
  pkg/supportbundle/staticspecs/embed.go
Labels: type::chore

#4815 Display node join command during initial install
  web/src/components/apps/EmbeddedClusterManagement.tsx
  web/src/components/apps/EmbeddedClusterViewNode.jsx
  web/src/components/modals/AddANodeModal.tsx
  web/src/components/selection.json
Labels: type::feature

#4825 Add check for updates button for newly available versions
  web/src/components/apps/AppVersionHistory.tsx
  web/src/components/apps/AvailableUpdatesComponent.tsx
Labels: type::feature

#4824 Update default and kurl support bundles specs
  pkg/supportbundle/staticspecs/defaultspec.yaml
  pkg/supportbundle/staticspecs/kurlspec.yaml
Labels: type::chore

#4827 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4835 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4834 fix: GetLatestLicense includes `licenseSequence` query param
  pkg/replicatedapp/api.go
  pkg/replicatedapp/api_test.go
Labels: type::bug, bug::normal

#4841 Add class for role management buttons
  web/src/components/apps/EmbeddedClusterManagement.tsx
Labels: type::feature

#4840 Align loader spinner when the upgrade service is starting
  web/src/components/modals/UpgradeServiceModal.tsx
  web/src/components/upgrade_service/AppConfig.tsx
Labels: type::bug, bug::normal

#4839 Hide commands to download application archive in embedded cluster
  web/src/Root.tsx
  web/src/components/tree/KotsApplicationTree.tsx
Labels: type::feature

#4779 chore: Update troubleshoot version to v0.99.0
  go.mod
  go.sum
Labels: type::chore

#4828 Show available updates in Dashboard
  web/src/components/apps/AvailableUpdatesComponent.tsx
  web/src/features/Dashboard/components/AvailableUpdateCard.tsx
  web/src/features/Dashboard/components/DashboardVersionCard.tsx
Labels: type::feature

#4849 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type::chore

#4848 feat: Print runPod collector name in failed error logs
  pkg/supportbundle/staticspecs/kurlspec.yaml
Labels: type::feature

#4847 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4826 Show join command during restore in Embedded Cluster
  web/src/Root.tsx
  web/src/components/apps/EmbeddedClusterManagement.tsx
  web/src/components/shared/NavBar.tsx
Labels: type::feature

#4853 add PriorityClass to resource creation/deletion order
  pkg/operator/client/resource.go
Labels: type::chore
