Repository replicatedhq/kots, pull requests merged in 2024-11, with the labels that each got.

#4977 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4978 Revert "feat: enable remote host collector in KOTS (#4958)"
  pkg/supportbundle/execute.go
  pkg/supportbundle/spec.go
  pkg/supportbundle/spec_test.go
  pkg/supportbundle/supportbundle.go
Labels: type::bug, bug::regression

#4979 Revert "chore: Add check for replicated.app to support bundle specs missing the check"
  pkg/supportbundle/defaultspec/spec.yaml
  pkg/supportbundle/staticspecs/defaultspec.yaml
Labels: type::bug, bug::regression

#4980 Fix 404 in Admin Console
  kurl_proxy/assets/tls-warning.html
  kurl_proxy/assets/welcome.html
  kurl_proxy/cmd/main.go
Labels: type::feature

#4971 Allow embedded cluster installs to complete if config values are passed in
  pkg/airgap/airgap.go
  pkg/kotsadmconfig/config.go
  pkg/online/online.go
  pkg/util/util.go
Labels: type::feature

#4983 fix: unable to upgrade EC when introducing a required config item w/o default or value
  Makefile
  pkg/upgradeservice/bootstrap.go
Labels: type::bug, bug::regression

#4985 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4986 Add timeout to replicated.app health check collector
  pkg/supportbundle/staticspecs/kurlspec.yaml
Labels: type::bug, bug::regression

#4988 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4987 Consolidate the logic for determining downstream version status
  e2e/playwright/tests/@change-license/test.spec.ts
  e2e/playwright/tests/@multi-app-backup-and-restore/test.spec.ts
  e2e/playwright/tests/@multi-app-install/test.spec.ts
  e2e/playwright/tests/@no-required-config/test.spec.ts
  pkg/airgap/airgap.go
  pkg/airgap/update.go
  pkg/handlers/config.go
  pkg/handlers/identity.go
  pkg/handlers/registry.go
  pkg/handlers/upload.go
  pkg/kotsadmupstream/upstream.go
  pkg/kotsutil/kots.go
  pkg/kotsutil/kots_test.go
  pkg/online/online.go
  pkg/operator/operator.go
  pkg/preflight/preflight.go
  pkg/pull/pull.go
  pkg/rewrite/rewrite.go
  pkg/store/kotsstore/license_store.go
  pkg/store/kotsstore/version_store.go
  pkg/store/kotsstore/version_store_test.go
  pkg/store/mock/mock.go
  pkg/store/store_interface.go
  pkg/upgradeservice/preflight/preflight.go
Labels: type::feature

#4990 Bug: Copy button for validating cert and FE error on Config page
  kurl_proxy/assets/tls-warning.html
  web/src/Root.tsx
Labels: type::bug, bug::normal

#4991 Update TLS warning steps for different browsers
  kurl_proxy/assets/tls-warning.html
Labels: type::feature

#4993 Fix: Use IE TLS warn image too
  kurl_proxy/assets/tls-warning.html
Labels: type::feature

#4992 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  migrations/Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4998 Ability to download the application archive of any version including the currently deployed one
  .github/actions/cmx-versions/action.yaml
  .github/actions/kurl-addon-kots-publisher/action.yml
  .github/actions/version-tag/action.yml
  .github/workflows/build-test.yaml
  cmd/kots/cli/download.go
  pkg/download/download.go
  pkg/handlers/download.go
Labels: type::feature

#5001 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#5000 Use OpenShift 4.15.0-okd
  .github/actions/cmx-versions/dist/index.js
  .github/actions/cmx-versions/index.js
  .github/workflows/build-test.yaml
Labels: type::chore

#5009 Pin melange version to v0.14.10
  .github/actions/build-custom-melange-package/action.yml
Labels: type::chore

#5005 fix(frontend): do not refetch join command on window focus
  web/src/components/apps/EmbeddedClusterManagement.tsx
Labels: type::bug, bug::normal

#5002 chore(local-dev): add node affinity on the patches for local dev with EC
  Makefile
  README.md
  dev/patches/kotsadm-up.yaml
  dev/patches/kotsadm-web-up.yaml
  dev/patches/kurl-proxy-up.yaml
  dev/scripts/common.sh
  dev/scripts/dev-deps.sh
Labels: type::chore

#5003 bug: account for etcd leader changes error
  pkg/handlers/middleware.go
  pkg/handlers/session.go
  pkg/handlers/session_test.go
Labels: type::bug, bug::normal

#5021 use .<namespace>.svc for HA-rqlite
  pkg/ha/ha_test.go
  pkg/kotsadm/objects/rqlite_objects.go
Labels: type::bug, bug::normal

#5004 feat(ec_join): update handler to return tcp connections required
  pkg/apiserver/server.go
  pkg/embeddedcluster/node_join.go
  pkg/embeddedcluster/node_join_test.go
  pkg/handlers/app.go
  pkg/handlers/dashboard.go
  pkg/handlers/embedded_cluster_get.go
  pkg/handlers/embedded_cluster_node_join_command.go
  pkg/handlers/embedded_cluster_node_join_command_test.go
  pkg/handlers/handlers.go
  pkg/handlers/kubeclient/kubeclient.go
Labels: type::feature

#5017 chore(ec): send upgrade events instead of the operator
  e2e/playwright/tests/@smoke-test/test.spec.ts
  pkg/embeddedcluster/metrics.go
  pkg/embeddedcluster/upgrade.go
  pkg/embeddedcluster/util.go
  pkg/operator/operator.go
  pkg/upgradeservice/deploy/deploy.go
Labels: type::bug, bug::normal

#5015 feat: embedded cluster manager websocket
  pkg/apiserver/server.go
  pkg/handlers/debug.go
  pkg/handlers/handlers.go
  pkg/handlers/handlers_test.go
  pkg/handlers/interface.go
  pkg/handlers/mock/mock.go
  pkg/handlers/websocket.go
  pkg/websocket/types/types.go
  pkg/websocket/websocket.go
  web/src/Root.tsx
  web/src/components/DebugInfo.jsx
  web/src/scss/components/DebugInfo.scss
Labels: type::feature
