Repository replicatedhq/kots, pull requests merged in 2024-02, with the labels that each got.

#4417 Remove rqlite dump from support bundles
  pkg/supportbundle/defaultspec/spec.yaml
  pkg/supportbundle/staticspecs/defaultspec.yaml
Labels: type::feature, type::improvement

#4419 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  migrations/Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4402 show initial preflight page for helm chart preflights
  pkg/kotsutil/kots.go
  pkg/pull/pull.go
  pkg/rewrite/rewrite.go
  pkg/tests/pull/cases/kotskinds/upstream/my-preflight-chart-0.1.0.tgz
  pkg/tests/pull/cases/kotskinds/upstream/my-preflight-chart.yaml
  pkg/tests/pull/cases/kotskinds/wantResults/helm/my-preflight-chart/my-preflight-chart-0.1.0.tgz
  pkg/tests/pull/cases/kotskinds/wantResults/helm/my-preflight-chart/values.yaml
  pkg/tests/pull/cases/kotskinds/wantResults/kotsKinds/helm-preflight.yaml
  pkg/tests/pull/cases/kotskinds/wantResults/kotsKinds/my-preflight-chart.yaml
  pkg/tests/pull/cases/kotskinds/wantResults/rendered/this-cluster/helm/my-preflight-chart/all.yaml
  pkg/tests/pull/cases/kotskinds/wantResults/upstream/my-preflight-chart-0.1.0.tgz
  pkg/tests/pull/cases/kotskinds/wantResults/upstream/my-preflight-chart.yaml
  web/src/features/AppConfig/components/AppConfig.tsx
Labels: type::bug, bug::normal

#4422 add PendingChartCreation as a state case for embedded-cluster
  web/src/utilities/utilities.js
Labels: type::chore

#4420 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4430 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4431 fix okteto deployment
  okteto-v2.yml
Labels: type::chore

#4433 fix okteto deployment
  okteto-pipeline.yml
Labels: type::chore

#4432 show intermediate cluster upgrade status
  pkg/api/handlers/types/types.go
  pkg/embeddedcluster/monitor.go
  pkg/handlers/app.go
  pkg/operator/operator.go
  web/src/features/AppVersionHistory/AppVersionHistoryRow.tsx
  web/src/features/Dashboard/components/Dashboard.tsx
  web/src/features/Dashboard/components/DashboardVersionCard.tsx
  web/src/types/index.ts
  web/src/utilities/utilities.js
Labels: type::feature, type::improvement

#4435 bump troubleshoot to v0.83.0
  go.mod
  go.sum
  pkg/kotsadmsnapshot/download.go
Labels: type::chore

#4437 embedded cluster management UI cleanup
  web/src/components/apps/EmbeddedClusterManagement.tsx
  web/src/components/apps/EmbeddedClusterViewNode.jsx
  web/src/components/shared/NavBar.tsx
Labels: type::feature, type::improvement

#4439 bump github.com/replicatedhq/kotskinds
  go.mod
  go.sum
Labels: type::chore

#4438 ci: use openshift 4.14
  .github/actions/cmx-versions/dist/index.js
  .github/actions/cmx-versions/index.js
  .github/workflows/build-test.yaml
Labels: type::chore

#4443 Return metrics base URL with the embedded cluster join command response
  pkg/handlers/embedded_cluster_node_join_command.go
Labels: type::feature

#4444 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4446 fix the wording of the kurl-proxy tls page
  kurl_proxy/assets/tls.html
Labels: type::chore

#4447 Report embedded cluster version
  migrations/tables/instance-report.yaml
  pkg/api/reporting/types/types.go
  pkg/reporting/app.go
  pkg/reporting/app_airgap.go
  pkg/reporting/instance_report.go
  pkg/reporting/report_test.go
  pkg/reporting/util.go
Labels: type::feature

#4448 Automated KOTS Image Dependency Tag Update
  .image.env
  migrations/Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4449 Do not process online images in airgap mode for v1beta2 Helm charts
  pkg/airgap/airgap.go
  pkg/airgap/update.go
  pkg/apparchive/helm-v1beta2.go
  pkg/image/airgap.go
  pkg/midstream/write.go
  pkg/pull/pull.go
  pkg/tests/pull/cases/configcontext/testcase.yaml
  pkg/tests/pull/cases/customhostnames/testcase.yaml
  pkg/tests/pull/cases/kotskinds/testcase.yaml
  pkg/tests/pull/cases/multidoc/testcase.yaml
  pkg/tests/pull/cases/needsconfig/testcase.yaml
  pkg/tests/pull/cases/replicatedhelm/testcase.yaml
  pkg/tests/pull/cases/samechartvariations/testcase.yaml
  pkg/tests/pull/cases/simple/testcase.yaml
  pkg/tests/pull/cases/subchart-alias/testcase.yaml
  pkg/tests/pull/cases/subchart-crds/testcase.yaml
  pkg/tests/pull/cases/subcharts/testcase.yaml
  pkg/tests/pull/cases/taganddigest-norewrite/testcase.yaml
  pkg/tests/pull/cases/taganddigest-rewrite/testcase.yaml
  pkg/tests/pull/cases/v1beta2-charts/testcase.yaml
Labels: type::bug, bug::regression

#4455 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4456 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4459 don't show airgap upload page if embedded cluster
  pkg/handlers/license.go
Labels: type::feature, type::improvement

#4461 add pending_cluster_management status for embedded clusters
  pkg/handlers/embedded_cluster_confirm_cluster_management.go
  pkg/handlers/embedded_cluster_delete_node.go
  pkg/handlers/embedded_cluster_drain_node.go
  pkg/handlers/embedded_cluster_get.go
  pkg/handlers/embedded_cluster_node_join_command.go
  pkg/handlers/handlers.go
  pkg/handlers/handlers_test.go
  pkg/handlers/interface.go
  pkg/handlers/mock/mock.go
  pkg/online/online.go
  pkg/store/kotsstore/version_store.go
  pkg/store/types/constants.go
  web/src/components/apps/AppDetailPage.tsx
  web/src/components/apps/EmbeddedClusterManagement.tsx
  web/src/types/index.ts
Labels: type::bug, bug::normal

#4466 do not taint controller nodes joining embedded-cluster clusters
  pkg/embeddedcluster/node_join.go
Labels: type::bug, bug::normal

#4463 use non-node join command for embedded-cluster
  pkg/embeddedcluster/node_join.go
Labels: type::feature

#4465 Hide / disable monitoring graphs for embedded clusters
  web/src/components/apps/AppDetailPage.tsx
  web/src/features/Dashboard/components/Dashboard.tsx
  web/src/features/Dashboard/components/DashboardLicenseCard.tsx
Labels: type::feature

#4462 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4467 fix hidden ignore preflights option
  web/src/components/PreflightResultPage.tsx
Labels: type::bug, bug::normal

#4468 Fix templating LicenseFieldValue on license sync
  .gitignore
  pkg/handlers/config.go
  pkg/handlers/identity.go
  pkg/handlers/registry.go
  pkg/handlers/upload.go
  pkg/operator/operator.go
  pkg/preflight/preflight.go
  pkg/registry/registry.go
  pkg/render/helper/appfile.go
  pkg/render/render.go
  pkg/render/types/interface.go
  pkg/store/kotsstore/license_store.go
  pkg/store/kotsstore/version_store.go
  pkg/store/store.go
  pkg/tests/renderdir/cases/outdated-kotskinds/archiveDir/base/kustomization.yaml
  pkg/tests/renderdir/cases/outdated-kotskinds/archiveDir/base/subdir/configmap.yaml
  pkg/tests/renderdir/cases/outdated-kotskinds/archiveDir/kotsKinds/config.yaml
  pkg/tests/renderdir/cases/outdated-kotskinds/archiveDir/kotsKinds/userdata/config.yaml
  pkg/tests/renderdir/cases/outdated-kotskinds/archiveDir/kotsKinds/userdata/installation.yaml
  pkg/tests/renderdir/cases/outdated-kotskinds/archiveDir/kotsKinds/userdata/license.yaml
  pkg/tests/renderdir/cases/outdated-kotskinds/archiveDir/overlays/downstreams/this-cluster/kustomization.yaml
  pkg/tests/renderdir/cases/outdated-kotskinds/archiveDir/overlays/midstream/backup-label-transformer.yaml
  pkg/tests/renderdir/cases/outdated-kotskinds/archiveDir/overlays/midstream/kustomization.yaml
  pkg/tests/renderdir/cases/outdated-kotskinds/archiveDir/overlays/midstream/secret.yaml
  pkg/tests/renderdir/cases/outdated-kotskinds/archiveDir/rendered/this-cluster/kotsadm-replicated-registry-secret.yaml
  pkg/tests/renderdir/cases/outdated-kotskinds/archiveDir/rendered/this-cluster/my-app-registry-secret.yaml
  pkg/tests/renderdir/cases/outdated-kotskinds/archiveDir/rendered/this-cluster/test-licenseinfo-configmap.yaml
  pkg/tests/renderdir/cases/outdated-kotskinds/archiveDir/upstream/config.yaml
  pkg/tests/renderdir/cases/outdated-kotskinds/archiveDir/upstream/subdir/configmap.yaml
  pkg/tests/renderdir/cases/outdated-kotskinds/archiveDir/upstream/userdata/config.yaml
  pkg/tests/renderdir/cases/outdated-kotskinds/archiveDir/upstream/userdata/installation.yaml
  pkg/tests/renderdir/cases/outdated-kotskinds/archiveDir/upstream/userdata/license.yaml
  pkg/tests/renderdir/cases/outdated-kotskinds/testcase.yaml
  pkg/tests/renderdir/cases/outdated-kotskinds/wantResults/base/kustomization.yaml
  pkg/tests/renderdir/cases/outdated-kotskinds/wantResults/base/subdir/configmap.yaml
  pkg/tests/renderdir/cases/outdated-kotskinds/wantResults/kotsKinds/config.yaml
  pkg/tests/renderdir/cases/outdated-kotskinds/wantResults/kotsKinds/userdata/config.yaml
  pkg/tests/renderdir/cases/outdated-kotskinds/wantResults/kotsKinds/userdata/installation.yaml
  pkg/tests/renderdir/cases/outdated-kotskinds/wantResults/kotsKinds/userdata/license.yaml
  pkg/tests/renderdir/cases/outdated-kotskinds/wantResults/overlays/downstreams/this-cluster/kustomization.yaml
  pkg/tests/renderdir/cases/outdated-kotskinds/wantResults/overlays/midstream/backup-label-transformer.yaml
  pkg/tests/renderdir/cases/outdated-kotskinds/wantResults/overlays/midstream/kustomization.yaml
  pkg/tests/renderdir/cases/outdated-kotskinds/wantResults/overlays/midstream/secret.yaml
  pkg/tests/renderdir/cases/outdated-kotskinds/wantResults/rendered/this-cluster/kotsadm-replicated-registry-secret.yaml
  pkg/tests/renderdir/cases/outdated-kotskinds/wantResults/rendered/this-cluster/my-app-registry-secret.yaml
  pkg/tests/renderdir/cases/outdated-kotskinds/wantResults/rendered/this-cluster/test-licenseinfo-configmap.yaml
  pkg/tests/renderdir/cases/outdated-kotskinds/wantResults/upstream/config.yaml
  pkg/tests/renderdir/cases/outdated-kotskinds/wantResults/upstream/subdir/configmap.yaml
  pkg/tests/renderdir/cases/outdated-kotskinds/wantResults/upstream/userdata/config.yaml
  pkg/tests/renderdir/cases/outdated-kotskinds/wantResults/upstream/userdata/installation.yaml
  pkg/tests/renderdir/cases/outdated-kotskinds/wantResults/upstream/userdata/license.yaml
  pkg/tests/renderdir/renderdir_test.go
  pkg/version/metrics.go
Labels: type::bug, bug::regression

#4471 Update development instructions
  README.md
Labels: type::chore

#4475 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4476 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4477 Import necessary types from Dex and remove it from the dependencies
  .github/dependabot.yml
  .trivyignore
  go.mod
  go.sum
  pkg/dex/types/config.go
  pkg/dex/types/kubernetes.go
  pkg/dex/types/logger.go
  pkg/dex/types/oidc.go
  pkg/dex/types/server.go
  pkg/dex/types/storage.go
  pkg/handlers/identity.go
  pkg/identity/config.go
  pkg/identity/deploy/dex.go
  pkg/identity/dex.go
Labels: type::security

#4479 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4470 return the embedded cluster version with the node join response
  pkg/handlers/embedded_cluster_node_join_command.go
Labels: type::chore

#4481 Add delay between approving and merging PR in the automated PRs manager
  .github/workflows/automated-prs-manager.yaml
Labels: type::security

#4482 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4483 Print scan reports
  .github/workflows/alpha.yaml
Labels: type::security

#4485 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security
