Repository replicatedhq/kots, pull requests merged in 2024-04, with the labels that each got.

#4524 trigger embedded airgap upgrade
  cmd/kots/cli/admin-console-push-images.go
  go.mod
  go.sum
  pkg/embeddedcluster/monitor.go
  pkg/embeddedcluster/roles.go
  pkg/embeddedcluster/roles_test.go
  pkg/embeddedcluster/util.go
  pkg/embeddedcluster/util_test.go
  pkg/handlers/app.go
  pkg/image/airgap.go
  pkg/image/airgap_test.go
  pkg/image/online.go
  pkg/image/types/types.go
  pkg/kotsadm/main.go
  pkg/kotsutil/kots.go
  pkg/midstream/write.go
  pkg/operator/operator.go
  pkg/pull/pull.go
  pkg/store/kotsstore/version_store.go
  pkg/store/mock/mock.go
  pkg/store/store_interface.go
  pkg/upstream/upgrade.go
Labels: type::feature

#4536 update embedded-cluster-kinds to include a new BinaryName field
  go.mod
  go.sum
  pkg/embeddedcluster/util.go
Labels: type::chore

#4534 only push from images directory for docker archive bundles
  pkg/image/airgap.go
  pkg/image/airgap_test.go
Labels: type::bug, bug::normal

#4535 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4539 feat(troubleshoot): support for distribution kind
  go.mod
  go.sum
  pkg/base/rewrite.go
  pkg/docker/registry/auth.go
  pkg/docker/registry/challenge/addr.go
  pkg/docker/registry/challenge/authchallenge.go
  pkg/docker/registry/challenge/authchallenge_test.go
  pkg/docker/registry/temp_registry.go
  pkg/image/online.go
  pkg/kotsadm/copy_images.go
  pkg/kotsadm/version/kotsadm_version.go
Labels: type::feature

#4540 add mapping for CopyingArtifacts installation state
  web/src/utilities/utilities.js
Labels: type::bug, bug::normal

#4541 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4542 bump troubleshoot to 0.87.0
  go.mod
  go.sum
Labels: type::chore

#4544 consider PendingChartCreation state during upgrade ui
  web/src/utilities/utilities.js
  web/src/utilities/utilities.test.js
Labels: type::bug, bug::normal

#4545 feat: print x/y progress to the stdout
  pkg/image/airgap.go
Labels: type::feature

#4550 Include airgap-bundle flag to node join command in airgap mode
  pkg/embeddedcluster/node_join.go
  pkg/embeddedcluster/node_join_test.go
  pkg/handlers/embedded_cluster_node_join_command.go
Labels: type::feature

#4552 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4553 include the airgap registry cluster IP in the node join response
  pkg/handlers/embedded_cluster_node_join_command.go
Labels: type::feature

#4560 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4562 Experiment testing with Playwright instead of testIM
  .github/actions/kots-e2e/action.yml
  .github/workflows/build-test.yaml
  e2e/Dockerfile
  e2e/Makefile
  e2e/e2e_test.go
  e2e/inventory/inventory.go
  e2e/inventory/test.go
  e2e/kots/kots.go
  e2e/playwright/.gitignore
  e2e/playwright/package-lock.json
  e2e/playwright/package.json
  e2e/playwright/playwright.config.ts
  e2e/playwright/playwright.go
  e2e/playwright/tests/no-required-config/license.yaml
  e2e/playwright/tests/no-required-config/test.spec.ts
  e2e/scripts/deps.sh
  e2e/testim/client.go
Labels: type::chore, type::tests

#4564 fix edit config link on dashboard
  web/src/features/Dashboard/components/AppStatus.tsx
  web/src/features/Dashboard/components/Dashboard.tsx
Labels: type::bug, bug::normal

#4563 Move config validation test to Playwright
  .github/workflows/build-test.yaml
  e2e/inventory/inventory.go
  e2e/inventory/test.go
  e2e/playwright/playwright.go
  e2e/playwright/tests/config-validation/invalid-jwt.txt
  e2e/playwright/tests/config-validation/license.yaml
  e2e/playwright/tests/config-validation/test.spec.ts
  e2e/playwright/tests/config-validation/valid-jwt.txt
  e2e/playwright/tests/no-required-config/test.spec.ts
  e2e/playwright/tests/shared/index.ts
  e2e/playwright/tests/shared/login.ts
  e2e/playwright/tests/shared/upload-license.ts
  e2e/testim/client.go
Labels: type::chore, type::tests

#4565 Move backup and restore test to playwright
  .github/workflows/build-test.yaml
  e2e/inventory/inventory.go
  e2e/playwright/package-lock.json
  e2e/playwright/package.json
  e2e/playwright/tests/backup-and-restore/license.yaml
  e2e/playwright/tests/backup-and-restore/test.spec.ts
Labels: type::chore, type::tests

#4568 Update troubleshoot to v0.88.0 to resolve CVE-2024-3817
  go.mod
  go.sum
Labels: type::security

#4566 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4567 Move online smoke test to playwright
  .github/workflows/build-test.yaml
  e2e/inventory/inventory.go
  e2e/playwright/tests/shared/index.ts
  e2e/playwright/tests/shared/validate-deploy-logs.ts
  e2e/playwright/tests/smoke-test/license.yaml
  e2e/playwright/tests/smoke-test/test.spec.ts
Labels: type::chore, type::tests

#4569 set whether snapshots are supported when updating the EC installation
  go.mod
  go.sum
  pkg/embeddedcluster/monitor.go
  pkg/embeddedcluster/util.go
  pkg/handlers/metadata_test.go
Labels: type::feature

#4571 treat every embedded cluster app as if it has a backup object
  pkg/handlers/app.go
  pkg/kotsutil/kots.go
  pkg/kotsutil/kots_test.go
Labels: type::feature

#4570 disaster recovery UI for embedded cluster
  hack/dev/skaffoldcache.Dockerfile
  pkg/handlers/backup.go
  pkg/snapshot/store.go
  pkg/snapshot/velero.go
  web/src/Root.tsx
  web/src/components/apps/AppDetailPage.tsx
  web/src/components/modals/DeleteSnapshotModal.tsx
  web/src/components/shared/NavBar.tsx
  web/src/components/shared/NavBarDropdown.jsx
  web/src/components/shared/SubNavBar/SubNavBar.jsx
  web/src/components/snapshots/AppSnapshots.jsx
  web/src/components/snapshots/GettingStartedSnapshots.jsx
  web/src/components/snapshots/SnapshotDetails.jsx
  web/src/components/snapshots/SnapshotRow.jsx
  web/src/components/snapshots/SnapshotSchedule.jsx
  web/src/components/snapshots/SnapshotSettings.tsx
  web/src/components/snapshots/SnapshotStorageDestination.data.jsx
  web/src/components/snapshots/SnapshotStorageDestination.tsx
  web/src/components/snapshots/Snapshots.jsx
  web/src/components/snapshots/SnapshotsWrapper.jsx
  web/src/config-ui/subNavConfig.js
  web/src/features/Dashboard/components/Dashboard.tsx
  web/src/features/Dashboard/components/DashboardSnapshotsCard.tsx
  web/src/stories/DeleteSnapshotModal.stories.tsx
  web/src/utilities/utilities.js
Labels: type::feature

#4574 Fix flakiness in no-required-config and smoke-test tests
  e2e/playwright/playwright.config.ts
  e2e/playwright/tests/no-required-config/test.spec.ts
  e2e/playwright/tests/shared/index.ts
  e2e/playwright/tests/shared/validate-deploy-logs.ts
  e2e/playwright/tests/smoke-test/test.spec.ts
Labels: type::chore, type::tests

#4575 Print instructions to view Playwright test report
  .github/actions/kots-e2e/action.yml
Labels: type::chore, type::tests

#4580 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  migrations/Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4581 Update troubleshoot to v0.90.0 to resolve helm collector issue
  .gitignore
  go.mod
  go.sum
Labels: type::bug, bug::normal
