Repository replicatedhq/kots, pull requests merged in 2024-06, with the labels that each got.

#4659 Include the disaster recovery chart label for dynamic resources
  pkg/kotsadm/types/constants.go
  pkg/kotsadm/types/constants_test.go
Labels: type::feature

#4660 backup seaweedfs label and namespace in disaster recovery
  pkg/kotsadmsnapshot/backup.go
  pkg/kotsadmsnapshot/backup_test.go
Labels: type::feature

#4662 Remove usage of embedded-cluster-config configmap
  go.mod
  pkg/embeddedcluster/monitor.go
  pkg/embeddedcluster/node_join.go
  pkg/embeddedcluster/node_join_test.go
  pkg/embeddedcluster/roles.go
  pkg/embeddedcluster/util.go
  pkg/handlers/app.go
  pkg/handlers/embedded_cluster_get.go
  pkg/handlers/embedded_cluster_node_join_command.go
  pkg/k8sutil/clientset.go
  pkg/k8sutil/cluster.go
  pkg/kotsadmsnapshot/backup.go
  pkg/reporting/app.go
  pkg/util/util.go
Labels: type::feature

#4650 remove decimal percentage and capitalize units
  web/src/components/AirgapUploadProgress.jsx
  web/src/features/Dashboard/components/AirgapUploadProgress.jsx
  web/src/utilities/utilities.js
Labels: type::feature

#4666 Add HA annotation to embedded cluster backups
  pkg/kotsadmsnapshot/backup.go
Labels: type::feature

#4663 Display updated node status once it's updated
  web/src/components/apps/EmbeddedClusterManagement.tsx
Labels: type::feature

#4661 ignore failing non strict preflights if skipped
  .github/workflows/build-test.yaml
  cmd/kots/cli/install.go
  cmd/kots/cli/install_test.go
  pkg/airgap/airgap.go
  pkg/airgap/update.go
  pkg/handlers/config.go
  pkg/handlers/embedded_cluster_confirm_cluster_management.go
  pkg/handlers/identity.go
  pkg/handlers/preflight.go
  pkg/handlers/registry.go
  pkg/handlers/upload.go
  pkg/kotsadmlicense/license.go
  pkg/kotsadmupstream/upstream.go
  pkg/online/online.go
  pkg/preflight/preflight.go
  pkg/preflight/preflight_test.go
  pkg/store/kotsstore/preflight_store.go
  pkg/store/kotsstore/preflight_store_test.go
  pkg/updatechecker/updatechecker.go
Labels: type::bug, bug::normal

#4664 expose proxy for embedded cluster
  pkg/handlers/embedded_cluster_node_join_command.go
  pkg/util/util.go
Labels: type::feature

#4668 fix airgap version check when semver is not enabled
  pkg/airgap/update.go
  pkg/airgap/update_test.go
Labels: type::bug, bug::normal

#4669 Add SeaweedFS S3 service IP to backup annotations
  pkg/embeddedcluster/util.go
  pkg/kotsadmsnapshot/backup.go
Labels: type::feature

#4657 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4674 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4676 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4677 add available updates api endpoint
  pkg/handlers/handlers.go
  pkg/handlers/interface.go
  pkg/handlers/mock/mock.go
  pkg/handlers/update.go
  pkg/updatechecker/updatechecker.go
  pkg/updatechecker/updatechecker_test.go
  pkg/upstream/replicated.go
  pkg/upstream/types/types.go
Labels: type::feature

#4680 Embedded Cluster: Show available updates in the UI
  web/src/components/apps/AppVersionHistory.tsx
Labels: type::feature

#4682 allow kurl proxy iframe from same origin
  kurl_proxy/cmd/main.go
  kurl_proxy/cmd/main_test.go
Labels: type::chore

#4681 save config api for upgrade service
  pkg/handlers/config.go
  pkg/handlers/identity.go
  pkg/handlers/upload.go
  pkg/kotsadmconfig/config.go
  pkg/kotsadmlicense/license.go
  pkg/preflight/execute.go
  pkg/preflight/preflight.go
  pkg/render/render.go
  pkg/render/types/interface.go
  pkg/reporting/app_online.go
  pkg/rewrite/rewrite.go
  pkg/store/kotsstore/license_store.go
  pkg/store/kotsstore/version_store.go
  pkg/store/mock/mock.go
  pkg/store/store_interface.go
  pkg/tests/renderdir/renderdir_test.go
  pkg/upgradeservice/handlers/config.go
  pkg/upgradeservice/handlers/handlers.go
  pkg/upgradeservice/handlers/interface.go
  pkg/upgradeservice/preflight/preflight.go
Labels: type::feature

#4689 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4691 download config file
  pkg/upgradeservice/handlers/config.go
  pkg/upgradeservice/handlers/handlers.go
  pkg/upgradeservice/handlers/interface.go
  web/src/components/AppConfigRenderer.jsx
  web/src/components/apps/AppVersionHistory.tsx
  web/src/components/config_render/ConfigFileInput.jsx
  web/src/components/config_render/ConfigGroup.jsx
  web/src/components/config_render/ConfigGroups.jsx
  web/src/components/config_render/ConfigRender.jsx
  web/src/components/upgrade_service/AppConfig.tsx
  web/src/features/AppConfig/components/AppConfig.tsx
Labels: type::feature

#4695 bug: fix concurrent map read and map write
  pkg/k8sutil/clientset.go
Labels: type::bug, bug::normal

#4693 upgrade service preflights api
  pkg/upgradeservice/handlers/handlers.go
  pkg/upgradeservice/handlers/interface.go
  pkg/upgradeservice/handlers/preflight.go
  pkg/upgradeservice/preflight/preflight.go
Labels: type::feature

#4697 Remove unused Dex fields/types
  pkg/dex/types/config.go
  pkg/dex/types/logger.go
  pkg/dex/types/storage.go
Labels: type::chore

#4698 upgrade service airgap preflight reporting
  pkg/upgradeservice/handlers/config.go
  pkg/upgradeservice/handlers/preflight.go
  pkg/upgradeservice/preflight/preflight.go
  pkg/upgradeservice/reporting/reporting.go
Labels: type::feature

#4700 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4683 feat: push lam image to the embedded cluster registry
  go.mod
  go.sum
  pkg/image/airgap.go
  pkg/image/airgap_test.go
Labels: type::feature

#4692 Push additional embedded cluster airgap artifacts
  go.mod
  go.sum
  pkg/embeddedcluster/util.go
  pkg/embeddedcluster/util_test.go
  pkg/image/airgap.go
  pkg/image/airgap_test.go
  pkg/tests/pull/cases/airgap/upstream/userdata/installation.yaml
  pkg/tests/pull/cases/airgap/wantResults/kotsKinds/userdata/installation.yaml
  pkg/tests/pull/cases/airgap/wantResults/upstream/userdata/installation.yaml
  pkg/upstream/fetch.go
Labels: type::feature

#4699 skip required versions if channel is different
  pkg/airgap/update.go
  pkg/airgap/update_test.go
Labels: type::bug, bug::normal

#4702 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  migrations/Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4703 feat(user feedback): count lam as an embedded cluster artifact
  go.mod
  go.sum
  pkg/image/airgap.go
Labels: type::feature

#4713 Airgap upgrade service
  cmd/kots/cli/admin-console-push-images.go
  cmd/kots/cli/airgap-update.go
  cmd/kots/cli/install.go
  cmd/kots/cli/root.go
  cmd/kots/cli/util.go
  pkg/airgap/airgap.go
  pkg/airgap/update.go
  pkg/airgap/update_test.go
  pkg/apiserver/server.go
  pkg/archives/airgap.go
  pkg/archives/airgap_test.go
  pkg/archives/archives.go
  pkg/handlers/airgap.go
  pkg/handlers/app.go
  pkg/handlers/handlers.go
  pkg/handlers/interface.go
  pkg/handlers/metadata.go
  pkg/handlers/mock/mock.go
  pkg/handlers/update.go
  pkg/handlers/upgrade_service.go
  pkg/image/airgap.go
  pkg/image/airgap_test.go
  pkg/imageutil/image.go
  pkg/imageutil/image_test.go
  pkg/kotsadm/main.go
  pkg/kotsutil/kots.go
  pkg/operator/operator.go
  pkg/pull/pull.go
  pkg/update/required.go
  pkg/update/required_test.go
  pkg/update/types/types.go
  pkg/update/update.go
  pkg/update/update_test.go
  pkg/updatechecker/types/types.go
  pkg/updatechecker/updatechecker.go
  pkg/updatechecker/updatechecker_test.go
  pkg/upgradeservice/bootstrap.go
  pkg/upgradeservice/preflight/preflight.go
  pkg/upgradeservice/process.go
  pkg/upgradeservice/server.go
  pkg/upgradeservice/types/types.go
  pkg/upstream/upgrade.go
Labels: type::feature

#4714 temporarily disable EKS 1.30 testing
  .github/actions/cmx-versions/dist/index.js
  .github/actions/cmx-versions/index.js
  .github/workflows/arm64-arc-runner-set.yaml
Labels: type::chore

#4717 Update arm64-arc-runner-set.yaml to 100G disk
  .github/workflows/arm64-arc-runner-set.yaml
Labels: type::chore

#4710 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4722 Allow specifying custom storage class
  .github/actions/kots-e2e/action.yml
  .github/workflows/build-test.yaml
  cmd/kots/cli/admin-console-generate-manifests.go
  cmd/kots/cli/install.go
  cmd/kots/cli/pull.go
  e2e/Makefile
  e2e/e2e_test.go
  e2e/kots/kots.go
  pkg/kotsadm/objects/kotsadm_objects.go
  pkg/kotsadm/objects/minio_objects.go
  pkg/kotsadm/objects/rqlite_objects.go
  pkg/kotsadm/types/deployoptions.go
  pkg/pull/pull.go
  pkg/upstream/admin-console.go
  pkg/upstream/types/types.go
Labels: type::feature

#4724 Fix release permissions
  .github/workflows/release.yaml
Labels: type::chore

#4725 EC upgrade: close modal bug, preflight polling issue, error message for available updates
  web/src/components/apps/AppVersionHistory.tsx
  web/src/components/upgrade_service/AppConfig.tsx
  web/src/components/upgrade_service/hooks/getPreflightResult.tsx
Labels: type::feature

#4726 UI improvements to available updates
  web/src/components/apps/AppVersionHistory.tsx
  web/src/types/index.ts
Labels: type::feature

#4727 Add released at timestamp
  web/src/components/apps/AppVersionHistory.tsx
Labels: type::feature

#4732 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security
