Repository replicatedhq/kots, pull requests merged in 2024-07, with the labels that each got.

#4719 include networking information with node join responses
  pkg/embeddedcluster/util.go
  pkg/handlers/embedded_cluster_node_join_command.go
Labels: type::chore

#4734 EC upgrades UI: loading state for start upgrade service & minor UI polish
  web/src/components/apps/AppVersionHistory.tsx
  web/src/components/upgrade_service/ConfirmAndDeploy.tsx
  web/src/components/upgrade_service/PreflightChecks.tsx
Labels: type::feature

#4735 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4712 fix: use correct url to navigate to troubleshoot from Troubleshoot button
  web/src/features/Dashboard/components/Dashboard.tsx
Labels: type::bug, bug::normal

#4736 include pod and service CIDRs as annotations on embedded cluster snapshots
  pkg/kotsadmsnapshot/backup.go
Labels: type::feature

#4738 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4737 EC upgrade UI: address pr feedback & refactor AppVersionHistory
  web/src/components/apps/AppVersionHistory.tsx
  web/src/components/apps/AvailableUpdatesComponent.tsx
  web/src/components/modals/ConfirmDeploymentModal.tsx
  web/src/components/modals/DiffErrorModal.tsx
  web/src/components/modals/DisplayKotsUpdateModal.tsx
  web/src/components/modals/NoChangesModal.tsx
  web/src/components/modals/ReleaseNotesModal.tsx
  web/src/components/modals/UpgradeServiceModal.tsx
Labels: type::feature

#4723 disable update checker in EC installations
  pkg/updatechecker/updatechecker.go
  web/src/Root.tsx
  web/src/components/apps/AppVersionHistory.tsx
  web/src/features/Dashboard/components/Dashboard.tsx
  web/src/features/Dashboard/components/DashboardVersionCard.tsx
Labels: type::chore

#4739 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4740 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4741 do not run automatic update checks on EC
  pkg/updatechecker/updatechecker.go
Labels: type::feature

#4743 Upgrade service confirm and deploy UX
  pkg/api/handlers/types/types.go
  pkg/embeddedcluster/monitor.go
  pkg/embeddedcluster/util.go
  pkg/handlers/app.go
  pkg/handlers/upgrade_service.go
  pkg/operator/operator.go
  pkg/store/kotsstore/version_store.go
  pkg/upgradeservice/bootstrap.go
  pkg/upgradeservice/deploy/deploy.go
  pkg/upgradeservice/handlers/deploy.go
  pkg/upgradeservice/handlers/spa.go
  pkg/upgradeservice/task/task.go
  pkg/upgradeservice/types/types.go
  web/src/Root.tsx
  web/src/components/apps/AppDetailPage.tsx
  web/src/components/apps/AppVersionHistory.tsx
  web/src/components/clusters/EmbeddedClusterUpgrading.tsx
  web/src/components/upgrade_service/ConfirmAndDeploy.tsx
  web/src/components/upgrade_service/PreflightChecks.tsx
  web/src/features/AppVersionHistory/AppVersionHistoryRow.tsx
  web/src/features/Dashboard/components/AppStatus.tsx
  web/src/features/Dashboard/components/Dashboard.tsx
  web/src/features/Dashboard/components/DashboardVersionCard.tsx
  web/src/types/index.ts
  web/src/utilities/utilities.js
  web/src/utilities/utilities.test.js
Labels: type::feature

#4748 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4749 EC upgrade UI: Iframe loading state, disable Preparing and Deploying buttons
  web/src/components/apps/AppVersionHistory.tsx
  web/src/components/apps/AvailableUpdatesComponent.tsx
  web/src/components/modals/UpgradeServiceModal.tsx
  web/src/components/upgrade_service/ConfirmAndDeploy.tsx
  web/src/components/upgrade_service/PreflightChecks.tsx
Labels: type::feature

#4733 Add analyzer to check for default storage class
  pkg/supportbundle/defaultspec/spec.yaml
Labels: type::feature

#4753 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4754 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4752 EC upgrade UI: add KOTS version to upgrade wizard, fix ignore preflights workflow
  web/src/components/modals/UpgradeServiceModal.tsx
  web/src/components/shared/modals/SkipPreflightsModal.tsx
  web/src/components/upgrade_service/ConfirmAndDeploy.tsx
  web/src/components/upgrade_service/PreflightChecks.tsx
  web/src/components/upgrade_service/StepIndicator.tsx
  web/src/components/upgrade_service/UpgradeServiceContext.tsx
Labels: type::feature

#4757 Upgrade service integration test
  pkg/handlers/handlers_test.go
  pkg/handlers/upgrade_service.go
  pkg/handlers/upgrade_service_test.go
  pkg/upgradeservice/process.go
Labels: type::feature

#4758 EC upgrade UI: Fix type errors
  web/src/components/UploadLicenseFile.tsx
  web/src/components/snapshots/SnapshotStorageDestination.tsx
Labels: type::feature

#4763 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4765 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4770 fix: Remove extra double quotes in all-ttl.sh make cmd
  Makefile
  README.md
Labels: type::bug, bug::normal

#4771 Remove unnecessary melange packages
  deploy/dex/apko.yaml.tmpl
  deploy/minio/apko.yaml.tmpl
  deploy/rqlite/apko.yaml.tmpl
Labels: type::security

#4780 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  deploy/dex/apko.yaml.tmpl
  deploy/minio/apko.yaml.tmpl
  deploy/rqlite/apko.yaml.tmpl
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4778 feat: update default support bundle spec with PVC check
  hack/dev/entrypoint.sh
  hack/dev/skaffoldcache.Dockerfile
  kustomize/base/deployment.yaml
  kustomize/base/service.yaml
  pkg/supportbundle/staticspecs/defaultspec.yaml
Labels: type::feature

#4782 Add support for Velero 1.14
  pkg/embeddedcluster/util.go
  pkg/kotsadmsnapshot/backup.go
  pkg/kotsadmsnapshot/backup_test.go
Labels: type::feature

#4783 Init Helm capabilities in upgrade service
  pkg/upgradeservice/bootstrap.go
  pkg/upgradeservice/server.go
Labels: type::bug, bug::regression

#4788 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4781 Fetch available updates after uploading a new airgap version
  web/src/components/apps/AppVersionHistory.tsx
Labels: type::feature

#4789 Direct to app if user tries to upload license
  web/src/components/UploadLicenseFile.tsx
Labels: type::bug, bug::normal

#4790 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4791 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4792 fix: [sc-98355] KubernetesMinorVersion | ParseInt cannot handle eks minor version with no integer string
  pkg/k8sutil/clientset.go
  pkg/k8sutil/clientset_test.go
Labels: type::bug, bug::normal

#4794 Embedded Cluster upgrade: Rerun preflights when config has changed
  web/src/components/upgrade_service/AppConfig.tsx
  web/src/components/upgrade_service/PreflightChecks.tsx
  web/src/components/upgrade_service/UpgradeServiceContext.tsx
Labels: type::feature

#4796 Fix the admin-console upgrade CLI command help text
  cmd/kots/cli/admin-console-upgrade.go
Labels: type::bug, bug::normal
