Repository replicatedhq/kots, pull requests merged in 2024-10, with the labels that each got.

#4932 fix(ec): new kinds to fix registry upgrade failure
  go.mod
  go.sum
Labels: type::bug, bug::normal

#4933 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4935 feat(ec): consolidate data directories
  go.mod
  go.sum
  pkg/kotsadmsnapshot/backup.go
Labels: type::feature

#4934 chore: Add check for replicated.app to support bundle specs missing the check
  pkg/supportbundle/defaultspec/spec.yaml
  pkg/supportbundle/staticspecs/defaultspec.yaml
Labels: type::chore

#4941 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4936 remove clusterResources from the default SupportBundle Spec
  pkg/supportbundle/spec.go
  pkg/supportbundle/staticspecs/defaultspec.yaml
Labels: type::feature

#4946 Move change-license test to Playwright
  .github/workflows/build-test.yaml
  dev/dockerfiles/kotsadm/Dockerfile.local
  e2e/inventory/inventory.go
  e2e/playwright/tests/@change-license/community-license.yaml
  e2e/playwright/tests/@change-license/different-app-license.yaml
  e2e/playwright/tests/@change-license/expired-license.yaml
  e2e/playwright/tests/@change-license/paid-license.yaml
  e2e/playwright/tests/@change-license/test.spec.ts
Labels: type::chore

#4943 fix(ec): solve make kotsadm-up-ec fail
  dev/scripts/common.sh
  dev/scripts/down-ec.sh
  dev/scripts/up-ec.sh
Labels: type::bug, bug::normal

#4950 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4945 bug: stop fetching support bundle uri on airgap
  pkg/supportbundle/defaultspec/embed.go
  pkg/supportbundle/spec.go
  pkg/supportbundle/staticspecs/embed.go
  pkg/supportbundle/supportbundle.go
Labels: type::bug, bug::normal

#4953 Copy custom CA config map to additional namespaces
  pkg/operator/client/client.go
  pkg/operator/client/deploy.go
  pkg/operator/client/namespaces.go
Labels: type::bug, bug::normal

#4952 Use cluster role for the SDK deployment when running in EC
  pkg/upstream/helm.go
Labels: type::bug, bug::normal

#4961 specify git commit and repo url for melange github action
  .github/actions/build-custom-melange-package/action.yml
Labels: type::chore

#4962 fix: persist http proxy settings and security context on upgrades
  cmd/kots/cli/admin-console-upgrade.go
  pkg/kotsadm/api.go
  pkg/kotsadm/api_test.go
  pkg/kotsadm/main.go
  pkg/kotsadm/secrets.go
  pkg/kotsadm/types/upgradeoptions.go
Labels: type::bug, bug::normal

#4959 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4951 Unboxing the embedded cluster
  e2e/playwright/tests/@smoke-test/test.spec.ts
  kurl_proxy/.gitignore
  kurl_proxy/assets/images/check.svg
  kurl_proxy/assets/images/down_arrow.svg
  kurl_proxy/assets/images/up_arrow.svg
  kurl_proxy/assets/input.css
  kurl_proxy/assets/insecure.html
  kurl_proxy/assets/output.css
  kurl_proxy/assets/tls-custom.css
  kurl_proxy/assets/tls.html
  kurl_proxy/assets/tls.js
  kurl_proxy/assets/welcome.html
  kurl_proxy/cmd/main.go
  kurl_proxy/tailwind.config.js
  web/src/Root.tsx
  web/src/components/PreflightResultPage.tsx
  web/src/components/apps/EmbeddedClusterManagement.tsx
  web/src/components/identity/ConfigureIngress.jsx
  web/src/components/modals/BackupRestoreModal.jsx
  web/src/components/modals/RestoreSnapshotModal.jsx
  web/src/components/selection.json
  web/src/components/snapshots/AppSnapshotRestore.jsx
  web/src/components/snapshots/SnapshotRestore.jsx
  web/src/components/snapshots/SnapshotSchedule.jsx
  web/src/components/snapshots/Snapshots.jsx
  web/src/components/troubleshoot/GenerateSupportBundleModal.tsx
  web/src/components/upgrade_service/PreflightChecks.tsx
  web/src/features/AddNewApp/components/InstallWithHelm.tsx
  web/src/features/AdminConsole/api/getAdminConsoleUpdateStatus.tsx
  web/src/features/AdminConsole/api/postUpdateAdminConsole.tsx
  web/src/features/AppConfig/components/AppConfig.tsx
  web/src/features/AppVersionHistory/api/getDownloadAppVersionStatus.tsx
  web/src/features/Auth/components/SecureAdminConsole.tsx
  web/src/features/Dashboard/components/DashboardGitOpsCard.jsx
  web/src/features/Gitops/components/AppGitops.jsx
  web/src/features/Gitops/components/SetupProvider.jsx
  web/src/features/Gitops/components/modals/DisableModal.jsx
  web/src/scss/components/watches/WatchConfig.scss
Labels: type::feature

#4964 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4958 feat: enable remote host collector in KOTS
  go.mod
  go.sum
  pkg/supportbundle/execute.go
  pkg/supportbundle/spec.go
  pkg/supportbundle/spec_test.go
  pkg/supportbundle/supportbundle.go
Labels: type::feature

#4966 feat(support-bundle): bump troubleshoot version
  go.mod
  go.sum
Labels: type::feature

#4972 feat(ec): allow rollbacks for embedded cluster
  cmd/kotsadm/cli/root.go
  pkg/apparchive/helm-v1beta1.go
  pkg/store/kotsstore/downstream_store.go
  pkg/store/kotsstore/downstream_store_test.go
  pkg/store/kotsstore/kots_store.go
  pkg/store/kotsstore/version_store.go
  pkg/store/store.go
  pkg/supportbundle/spec.go
  pkg/updatechecker/updatechecker.go
  pkg/util/util.go
Labels: type::feature

#4974 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4975 Ignore host env vars as they may override the registry config
  pkg/docker/registry/temp_registry.go
Labels: type::bug, bug::normal
