Repository replicatedhq/kots, pull requests merged in 2024-12, with the labels that each got.

#5031 feat(ec): dr use label for backup name, change terminology
  pkg/kotsadmsnapshot/backup.go
  pkg/kotsadmsnapshot/backup_test.go
Labels: type::feature

#5026 add kubernetes system namespaces to generated support bundles
  pkg/supportbundle/staticspecs/kurlspec.yaml
Labels: type::chore

#5028 feat(ec): improved disaster recovery - take multiple backups
  migrations/tables/app_version.yaml
  pkg/handlers/backup.go
  pkg/handlers/restore.go
  pkg/k8sutil/kotsadm.go
  pkg/kotsadmsnapshot/backup.go
  pkg/kotsadmsnapshot/backup_test.go
  pkg/kotsadmsnapshot/restore.go
  pkg/kotsadmsnapshot/types/types.go
  pkg/kotsutil/kots.go
  pkg/kotsutil/kots_test.go
  pkg/operator/operator.go
  pkg/snapshot/backup.go
  pkg/snapshot/restore.go
  pkg/snapshotscheduler/snapshotscheduler.go
  pkg/store/kotsstore/version_store.go
Labels: type::feature

#5033 feat(ec): change `ListInstanceBackups` handler to return `ReplicatedBackups`
  pkg/handlers/backup.go
  pkg/kotsadmsnapshot/backup.go
  pkg/kotsadmsnapshot/backup_test.go
  pkg/kotsadmsnapshot/k8sclient/k8sclient.go
  pkg/kotsadmsnapshot/types/types.go
  pkg/kotsadmsnapshot/veleroclient/veleroclient.go
  web/src/components/snapshots/Snapshots.jsx
Labels: type::feature

#5037 feat: [sc-117029] Add keep annotation to KOTS
  Makefile
  dev/dockerfiles/kotsadm/Dockerfile.local
  dev/manifests/kotsadm/minio.yaml
  pkg/operator/client/delete.go
  pkg/operator/client/gvkn.go
Labels: type::feature

#5039 feat(snapshots): support for orLabelSelectors
  pkg/kotsadmsnapshot/backup.go
  pkg/kotsadmsnapshot/backup_test.go
Labels: type::feature

#5038 feat(ec): fixes for restore in new improved dr
  migrations/Makefile
  pkg/docker/registry/registry.go
  pkg/docker/registry/registry_test.go
  pkg/k8sutil/clientset.go
  pkg/kotsadmsnapshot/backup.go
  pkg/kotsadmsnapshot/backup_test.go
  pkg/kotsadmsnapshot/download.go
  pkg/snapshot/velero.go
Labels: type::feature

#5041 fix(ec): always enable snapshots
  pkg/store/kotsstore/version_store.go
Labels: type::feature

#5042 feat(snapshots): encode restore spec in backup cr for restore
  pkg/kotsadmsnapshot/backup.go
  pkg/kotsadmsnapshot/backup_test.go
  pkg/kotsadmsnapshot/types/types.go
Labels: type::feature

#5036 feat: remove quiet flag in Minio
  pkg/kotsadm/objects/minio_objects.go
  pkg/snapshot/filesystem_minio.go
  pkg/supportbundle/staticspecs/defaultspec.yaml
Labels: type::feature

#5043 Detect EC installations from configmaps
  pkg/embeddedcluster/util.go
Labels: type::feature

#5045 feat(snapshots): add new replicated.com/disaster-recovery-version annotation
  pkg/handlers/restore.go
  pkg/kotsadmsnapshot/backup.go
  pkg/kotsadmsnapshot/backup_test.go
  pkg/kotsadmsnapshot/restore.go
  pkg/kotsadmsnapshot/types/types.go
  pkg/operator/operator.go
  pkg/snapshot/backup.go
  pkg/snapshot/restore.go
Labels: type::feature

#5044 feat(ec): `DeleteBackup` supports deleting new Replicated Backups
  pkg/kotsadmsnapshot/backup.go
  pkg/kotsadmsnapshot/backup_test.go
Labels: type::feature

#5055 Use dev migrations image for EC dev
  dev/patches/kotsadm-up.yaml
  dev/scripts/up-ec.sh
Labels: type::chore

#5057 fix(ci): chainguard build is broken
  deploy/melange.yaml.tmpl
  kurl_proxy/deploy/melange.yaml.tmpl
  migrations/deploy/melange.yaml.tmpl
Labels: type::chore

#5056 chore(backup): cleanup volume annotations
  pkg/kotsadmsnapshot/backup.go
  pkg/kotsadmsnapshot/backup_test.go
  pkg/kotsadmsnapshot/types/types.go
Labels: type::chore

#5047 Ingress will only have an IP address when type is LoadBalancer
  pkg/appstate/ingress.go
  pkg/appstate/ingress_test.go
Labels: type::bug, bug::normal

#5058 feat(snapshots): GetBackup details endpoint should support new dr
  .github/actions/build-custom-image-with-apko/action.yml
  .github/actions/build-dep-image-with-apko/action.yml
  pkg/handlers/backup.go
  pkg/kotsadmsnapshot/backup.go
  pkg/kotsadmsnapshot/backup_test.go
  pkg/kotsadmsnapshot/types/types.go
  web/src/components/RestoreSnapshotRow.jsx
  web/src/components/snapshots/SnapshotDetails.jsx
Labels: type::feature

#5061 feat(backups): change list instance backups response payload
  pkg/handlers/backup.go
  pkg/kotsadmsnapshot/backup.go
  pkg/kotsadmsnapshot/backup_test.go
  pkg/kotsadmsnapshot/types/types.go
  pkg/kotsadmsnapshot/types/types_test.go
  web/src/components/snapshots/Snapshots.jsx
Labels: type::feature

#5060 EC v2 to v2 upgrades
  cmd/imagedeps/tag-finder.go
  dev/scripts/common.sh
  dev/scripts/up-ec.sh
  go.mod
  go.sum
  migrations/tables/plan.yaml
  pkg/apiserver/server.go
  pkg/embeddedcluster/monitor.go
  pkg/embeddedcluster/util.go
  pkg/embeddedcluster/util_test.go
  pkg/handlers/deploy_ec2.go
  pkg/handlers/handlers.go
  pkg/handlers/handlers_test.go
  pkg/handlers/interface.go
  pkg/handlers/metadata.go
  pkg/handlers/mock/mock.go
  pkg/kotsadmsnapshot/backup_test.go
  pkg/kotsutil/kots.go
  pkg/plan/app.go
  pkg/plan/cluster.go
  pkg/plan/extensions.go
  pkg/plan/plan.go
  pkg/plan/types/types.go
  pkg/plan/util.go
  pkg/replicatedapp/api_test.go
  pkg/replicatedapp/upstream.go
  pkg/store/kotsstore/plan_store.go
  pkg/store/mock/mock.go
  pkg/store/store_interface.go
  pkg/upgradeservice/bootstrap.go
  pkg/upgradeservice/deploy/deploy_ec2.go
  pkg/upgradeservice/handlers/deploy_ec2.go
  pkg/upgradeservice/handlers/handlers.go
  pkg/upgradeservice/handlers/info.go
  pkg/upgradeservice/handlers/interface.go
  pkg/upgradeservice/plan/plan.go
  pkg/upgradeservice/types/types.go
  pkg/upstream/replicated.go
  pkg/util/util.go
  pkg/websocket/upgrade.go
  web/src/Root.tsx
  web/src/components/apps/AppVersionHistory.tsx
  web/src/components/modals/UpgradeStatusModal.tsx
  web/src/components/upgrade_service/ConfirmAndDeploy.tsx
  web/src/components/upgrade_service/UpgradeService.tsx
  web/src/components/upgrade_service/hooks/getUpgradeInfo.tsx
  web/src/components/upgrade_service/hooks/postDeployAppVersion.tsx
  web/src/types/index.ts
Labels: type::feature
