Repository replicatedhq/kots, pull requests merged in 2024-09, with the labels that each got.

#4860 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4852 feat: add OOMKilled and Default Storage Class analysers
  pkg/supportbundle/staticspecs/defaultspec.yaml
Labels: type::feature

#4854 chore(embedded-cluster): kinds repo moved
  go.mod
  go.sum
  pkg/embeddedcluster/node_join_test.go
  pkg/embeddedcluster/roles.go
  pkg/embeddedcluster/roles_test.go
  pkg/embeddedcluster/upgrade.go
  pkg/embeddedcluster/util.go
  pkg/embeddedcluster/util_test.go
  pkg/handlers/embedded_cluster_node_join_command.go
  pkg/k8sutil/clientset.go
  pkg/kotsadmsnapshot/backup.go
  pkg/kotsadmsnapshot/backup_test.go
  pkg/kotsutil/kots.go
  pkg/kotsutil/kots_test.go
  pkg/store/kotsstore/version_store.go
  pkg/store/mock/mock.go
  pkg/store/store_interface.go
  pkg/upgradeservice/deploy/deploy.go
Labels: type::chore

#4842 Improved messaging when requested channel slug not allowed by license
  cmd/kots/cli/install.go
  cmd/kots/cli/pull.go
  cmd/kots/cli/util.go
  cmd/kots/cli/util_test.go
  pkg/license/multichannel.go
Labels: type::feature

#4862 Pass-through PROXY environment to Replicated SDK deployment
  pkg/rewrite/rewrite.go
  pkg/upstream/helm.go
  pkg/upstream/helm_test.go
Labels: type::feature

#4863 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4865 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4864 begin adding labels and annotations
  .github/workflows/build-test.yaml
  cmd/kots/cli/install.go
  pkg/kotsadm/objects/configmaps_objects.go
  pkg/kotsadm/objects/distribution_objects.go
  pkg/kotsadm/objects/kotsadm_objects.go
  pkg/kotsadm/objects/minio_objects.go
  pkg/kotsadm/objects/rqlite_objects.go
  pkg/kotsadm/types/deployoptions.go
Labels: type::feature

#4866 supply additional labels and annotations to fs-minio pods
  pkg/kotsutil/kots.go
  pkg/kotsutil/kots_test.go
  pkg/snapshot/filesystem_minio.go
  pkg/snapshot/filesystem_minio_test.go
Labels: type::feature

#4872 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4873 run integration tests with ubuntu-latest to match embedded-cluster
  .github/workflows/regression.yaml
Labels: type::chore

#4874 fix(proxy): use fqdn for kotsadm-rqlite and kotsadm-minio addresses
  deploy/kurl/kotsadm/template/base/tmpl-secret-rqlite.yaml
  pkg/kotsadm/objects/kotsadm_objects.go
  pkg/kotsadm/objects/secrets_objects.go
  pkg/supportbundle/staticspecs/kurlspec.yaml
Labels: type::bug, bug::normal

#4875 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4876 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4877 chore(ec): add binaryOverrideUrl and metadataOverrideUrl
  go.mod
  go.sum
Labels: type::chore

#4882 Bootstrapping pact tests for replicated.app
  .github/workflows/release.yaml
  .gitignore
  Makefile
  contracts/replicated-app/init_test.go
  contracts/replicated-app/root_test.go
  go.mod
  go.sum
Labels: type::feature

#4883 Fix Dropdown logic for when field
  web/src/components/config_render/ConfigDropdown.tsx
Labels: type::bug, bug::normal

#4878 add PrivateCACert template function
  pkg/template/static_context.go
Labels: type::chore

#4885 Rename pact provider replicated-app -> market-api
  contracts/market-api/init_test.go
  contracts/market-api/root_test.go
Labels: type::chore

#4886 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4888 preserve ec proxy config on cluster upgrade
  pkg/embeddedcluster/upgrade.go
Labels: type::bug, bug::normal

#4884 allow end users to configure additional trusted certificate authorities
  .github/workflows/build-test.yaml
  cmd/kots/cli/admin-console-generate-manifests.go
  cmd/kots/cli/install.go
  pkg/kotsadm/objects/kotsadm_objects.go
  pkg/kotsadm/types/deployoptions.go
  pkg/upstream/admin-console.go
  pkg/upstream/types/types.go
Labels: type::feature

#4897 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4898 automatically copy all non-overridden fields in EC installation object
  pkg/embeddedcluster/upgrade.go
Labels: type::chore

#4902 Separate command blocks for dev README
  README.md
Labels: type::chore

#4903 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4900 Run record-release command for pact
  .github/workflows/release.yaml
  Makefile
Labels: type::chore

#4906 Dev env - always patch even if up & cache yarn packages
  .gitignore
  dev/scripts/common.sh
  dev/scripts/up-ec.sh
  dev/scripts/up.sh
Labels: type::chore

#4901 fix: EC - unable to upgrade if version label has special characters
  pkg/embeddedcluster/upgrade.go
  pkg/replicatedapp/embeddedcluster.go
Labels: type::bug, bug::normal

#4909 feat(ec): support for custom admin console and lam ports
  go.mod
  go.sum
  pkg/handlers/embedded_cluster_node_join_command.go
  pkg/kotsadmsnapshot/backup.go
Labels: type::feature

#4913 Fix change-channel e2e test
  e2e/playwright/tests/change-channel/test.spec.ts
Labels: type::chore

#4907 Fix pact publish command
  Makefile
Labels: type::bug, bug::normal

#4890 disable helmvm integration test with failing curl arguments
  .github/workflows/regression.yaml
Labels: type::chore

#4911 return the entire installation spec object in a EC join struct
  pkg/handlers/embedded_cluster_node_join_command.go
Labels: type::chore

#4918 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4887 feat(admin console): save bundle of last run preflight in Admin Console
  go.mod
  go.sum
  pkg/preflight/execute.go
  pkg/preflight/preflight.go
  pkg/supportbundle/defaultspec/spec.yaml
  pkg/supportbundle/staticspecs/defaultspec.yaml
  pkg/supportbundle/staticspecs/kurlspec.yaml
Labels: type::feature

#4914 Add custom CA when deploying replicated-sdk
  cmd/kots/cli/pull.go
  pkg/kotsadmupstream/upstream.go
  pkg/online/online.go
  pkg/pull/pull.go
  pkg/registry/registry.go
  pkg/render/render.go
  pkg/rewrite/rewrite.go
  pkg/upstream/admin-console.go
  pkg/upstream/helm.go
  pkg/upstream/helm_test.go
Labels: type::feature

#4920 Move multi app install test to Playwright
  .github/workflows/build-test.yaml
  e2e/Makefile
  e2e/README.md
  e2e/inventory/inventory.go
  e2e/playwright/tests/multi-app-install/app1-license.yaml
  e2e/playwright/tests/multi-app-install/app2-license.yaml
  e2e/playwright/tests/multi-app-install/test.spec.ts
  e2e/playwright/tests/shared/upload-license.ts
Labels: type::chore

#4919 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4921 Ability to manage npm packages in dev env
  README.md
  dev/patches/kotsadm-web-up.yaml
  dev/scripts/common.sh
  dev/scripts/down-ec.sh
  dev/scripts/down.sh
  dev/scripts/up-ec.sh
  dev/scripts/up.sh
Labels: type::chore

#4923 Move multi-app-backup-and-restore test to Playwright
  .github/actions/kots-e2e/action.yml
  .github/workflows/build-test.yaml
  e2e/README.md
  e2e/e2e_test.go
  e2e/inventory/inventory.go
  e2e/inventory/test.go
  e2e/playwright/tests/@backup-and-restore/license.yaml
  e2e/playwright/tests/@backup-and-restore/test.spec.ts
  e2e/playwright/tests/@change-channel/license.yaml
  e2e/playwright/tests/@change-channel/test.spec.ts
  e2e/playwright/tests/@config-validation/invalid-jwt.txt
  e2e/playwright/tests/@config-validation/license.yaml
  e2e/playwright/tests/@config-validation/test.spec.ts
  e2e/playwright/tests/@config-validation/valid-jwt.txt
  e2e/playwright/tests/@multi-app-backup-and-restore/app1-license.yaml
  e2e/playwright/tests/@multi-app-backup-and-restore/app2-license.yaml
  e2e/playwright/tests/@multi-app-backup-and-restore/test.spec.ts
  e2e/playwright/tests/@multi-app-install/app1-license.yaml
  e2e/playwright/tests/@multi-app-install/app2-license.yaml
  e2e/playwright/tests/@multi-app-install/test.spec.ts
  e2e/playwright/tests/@no-required-config/license.yaml
  e2e/playwright/tests/@no-required-config/test.spec.ts
  e2e/playwright/tests/@smoke-test/license.yaml
  e2e/playwright/tests/@smoke-test/test.spec.ts
  kurl_proxy/Makefile
Labels: type::chore

#4924 Adding OKE 1.30.1
  .github/actions/cmx-versions/dist/index.js
  .github/actions/cmx-versions/index.js
Labels: type::feature

#4925 fix(dev): make build-ttl.sh should respect OS and ARCH
  Makefile
Labels: type::chore

#4929 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4930 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4931 Ability to recognize Embedded Clusters in kurl proxy
  kurl_proxy/cmd/main.go
Labels: type::chore
