Repository replicatedhq/kots, pull requests merged in 2024-05, with the labels that each got.

#4584 Update troubleshoot to v0.91.0 to resolve ReplicaSetStatus analyzer nil result issue
  go.mod
  go.sum
Labels: type::bug, bug::normal

#4583 backup more namespaces in Embedded Cluster
  pkg/embeddedcluster/util.go
  pkg/kotsadmsnapshot/backup.go
  pkg/kotsadmsnapshot/backup_test.go
  pkg/util/util.go
Labels: type::feature

#4585 update okteto golang version
  deploy/okteto/okteto-v2.Dockerfile
  deploy/okteto/okteto.Dockerfile
  kurl_proxy/okteto.Dockerfile
Labels: type::chore

#4588 sort installations by name, not creation timestamp
  pkg/embeddedcluster/util.go
Labels: type::bug, bug::normal

#4587 include app and embedded cluster version as backup annotation
  pkg/kotsadmsnapshot/backup.go
Labels: type::feature

#4589 redirect to cluster mgmt if EC restore in progress
  pkg/handlers/metadata.go
  pkg/handlers/metadata_test.go
  web/src/Root.tsx
  web/src/features/Auth/components/SecureAdminConsole.tsx
Labels: type::feature, type::improvement

#4586 chore: Update troubleshoot to a version with a regression fix
  Makefile
  go.mod
  go.sum
Labels: type::chore

#4591 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4590 remove extra slash in snapshot bucket path
  web/src/features/Dashboard/components/DashboardSnapshotsCard.tsx
  web/src/utilities/utilities.js
  web/src/utilities/utilities.test.js
Labels: type::bug, bug::normal

#4593 add replicated.com/disaster-recovery=infra label to kotsadm resources
  pkg/kotsadm/types/constants.go
  pkg/kotsadm/types/constants_test.go
Labels: type::feature, type::improvement

#4594 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4592 Split boxes for snapshot schedule and retention
  pkg/handlers/handlers.go
  pkg/handlers/handlers_test.go
  pkg/handlers/interface.go
  pkg/handlers/mock/mock.go
  pkg/handlers/snapshots.go
  web/src/components/snapshots/SnapshotSchedule.jsx
Labels: type::feature

#4599 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4600 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4603 Fix installing playwright
  e2e/scripts/deps.sh
Labels: type::chore, type::tests

#4602 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4601 add backup annotations for air gap specific embedded cluster infra
  pkg/kotsadmsnapshot/backup.go
  pkg/kotsadmsnapshot/backup_test.go
Labels: type::feature

#4605 feat(kots): add embedded cluster distribution
  pkg/reporting/distribution.go
  pkg/reporting/distribution_test.go
  pkg/reporting/types.go
Labels: type::bug, bug::normal

#4606 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4607 annotate backups with airgap status
  pkg/kotsadmsnapshot/backup.go
Labels: type::feature

#4608 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4604 display the namespace, podname and volumename of snapshotted volumes
  pkg/kotsadmsnapshot/backup.go
  pkg/kotsadmsnapshot/types/types.go
  web/src/components/snapshots/SnapshotDetails.jsx
  web/src/stories/ShowAllModal.stories.tsx
Labels: type::feature

#4614 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4616 fix config and view files tab underlines
  .github/actions/build-custom-image-with-apko/action.yml
  .github/actions/build-dep-image-with-apko/action.yml
  .github/actions/kurl-addon-kots-generate/action.yml
  .github/actions/kurl-addon-kots-publish/action.yml
  .github/actions/kurl-addon-kots-test/action.yml
  web/src/components/apps/AppDetailPage.tsx
  web/src/utilities/utilities.js
  web/src/utilities/utilities.test.js
Labels: type::bug, bug::normal

#4617 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4618 Use new EC restore state ConfigMap name
  pkg/handlers/metadata.go
  pkg/handlers/metadata_test.go
Labels: type::feature

#4619 remove apko-image input for chainguard action
  .github/actions/build-custom-image-with-apko/action.yml
  .github/actions/build-dep-image-with-apko/action.yml
Labels: type::chore

#4620 Fix processing v1beta2 Helm charts that include required values
  pkg/apparchive/helm-v1beta2.go
  pkg/pull/pull.go
  pkg/tests/pull/cases/required-helm-values/testcase.yaml
  pkg/tests/pull/cases/required-helm-values/upstream/kots-app.yaml
  pkg/tests/pull/cases/required-helm-values/upstream/my-required-chart-0.1.0.tgz
  pkg/tests/pull/cases/required-helm-values/upstream/my-required-chart.yaml
  pkg/tests/pull/cases/required-helm-values/upstream/userdata/config.yaml
  pkg/tests/pull/cases/required-helm-values/upstream/userdata/license.yaml
  pkg/tests/pull/cases/required-helm-values/wantResults/base/kustomization.yaml
  pkg/tests/pull/cases/required-helm-values/wantResults/helm/my-required-chart-release/my-required-chart-0.1.0.tgz
  pkg/tests/pull/cases/required-helm-values/wantResults/helm/my-required-chart-release/values.yaml
  pkg/tests/pull/cases/required-helm-values/wantResults/kotsKinds/kots-app.yaml
  pkg/tests/pull/cases/required-helm-values/wantResults/kotsKinds/my-required-chart.yaml
  pkg/tests/pull/cases/required-helm-values/wantResults/kotsKinds/userdata/config.yaml
  pkg/tests/pull/cases/required-helm-values/wantResults/kotsKinds/userdata/installation.yaml
  pkg/tests/pull/cases/required-helm-values/wantResults/kotsKinds/userdata/license.yaml
  pkg/tests/pull/cases/required-helm-values/wantResults/overlays/downstreams/this-cluster/kustomization.yaml
  pkg/tests/pull/cases/required-helm-values/wantResults/overlays/midstream/backup-label-transformer.yaml
  pkg/tests/pull/cases/required-helm-values/wantResults/overlays/midstream/kustomization.yaml
  pkg/tests/pull/cases/required-helm-values/wantResults/overlays/midstream/secret.yaml
  pkg/tests/pull/cases/required-helm-values/wantResults/rendered/this-cluster/helm/my-required-chart-release/all.yaml
  pkg/tests/pull/cases/required-helm-values/wantResults/rendered/this-cluster/kotsadm-replicated-registry-secret.yaml
  pkg/tests/pull/cases/required-helm-values/wantResults/rendered/this-cluster/my-app-registry-secret.yaml
  pkg/tests/pull/cases/required-helm-values/wantResults/upstream/kots-app.yaml
  pkg/tests/pull/cases/required-helm-values/wantResults/upstream/my-required-chart-0.1.0.tgz
  pkg/tests/pull/cases/required-helm-values/wantResults/upstream/my-required-chart.yaml
  pkg/tests/pull/cases/required-helm-values/wantResults/upstream/userdata/config.yaml
  pkg/tests/pull/cases/required-helm-values/wantResults/upstream/userdata/installation.yaml
  pkg/tests/pull/cases/required-helm-values/wantResults/upstream/userdata/license.yaml
Labels: type::bug, bug::regression

#4623 Overwrite image deps tags by default to automatically patch CVEs
  .github/workflows/image-deps-updater.yaml
  .image.env
  Makefile
  migrations/Makefile
  pkg/image/constants.go
Labels: type::security

#4622 chore: Update troubleshoot to v0.92.1
  go.mod
  go.sum
Labels: type::chore

#4624 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4625 add application disaster recovery labels for injected pull secrets
  pkg/docker/registry/registry.go
  pkg/docker/registry/registry_test.go
  pkg/kotsadm/types/constants.go
Labels: type::feature, type::improvement

#4632 fix: cli port-forward fails with high network latency
  pkg/k8sutil/portforward.go
Labels: type::bug, bug::normal

#4635 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4636 Use golang 1.22 to fix dev env
  .github/actions/copy-assets/Dockerfile
  kurl_proxy/skaffold.Dockerfile
Labels: type::chore

#4633 feat: oras using tls registry
  pkg/image/airgap.go
  pkg/image/airgap_test.go
Labels: type::feature

#4637 Use DR license field to enable DR
  go.mod
  go.sum
  pkg/embeddedcluster/util.go
  pkg/handlers/app.go
  pkg/handlers/license.go
  pkg/license/signature.go
  pkg/template/license_context.go
  pkg/template/license_context_test.go
  web/src/Root.tsx
  web/src/components/apps/AppLicense.tsx
  web/src/types/index.ts
Labels: type::feature

#4638 return better errors when license contents don't match signed contents
  pkg/license/signature.go
  pkg/license/signature_test.go
Labels: type::chore

#4644 rename path to prefix for object store snapshot destinations
  web/src/components/snapshots/SnapshotStorageDestination.tsx
Labels: type::feature, type::improvement

#4645 preserve isHighAvailability field in ec installation object
  go.mod
  go.sum
  pkg/embeddedcluster/util.go
Labels: type::feature

#4646 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#4651 rqlite object store
  cmd/kotsadm/cli/migrate.go
  cmd/kotsadm/cli/root.go
  migrations/tables/object_store.yaml
  pkg/filestore/blob_store.go
  pkg/filestore/migrate.go
  pkg/filestore/rqlite_store.go
  pkg/filestore/store.go
  pkg/store/kotsstore/kots_store.go
Labels: type::feature

#4647 hide generate support bundle cli command for embedded cluster
  web/src/Root.tsx
  web/src/components/troubleshoot/GenerateSupportBundle.jsx
  web/src/components/troubleshoot/GenerateSupportBundleModal.tsx
  web/src/components/troubleshoot/SupportBundleList.tsx
Labels: type::feature
