Repository replicatedhq/kots, pull requests merged in 2025-03, with the labels that each got.

#5163 chore: update go version to 1.24
  .github/actions/copy-assets/Dockerfile
  dev/dockerfiles/kotsadm/Dockerfile.local
  dev/dockerfiles/kurl-proxy/Dockerfile.local
  dev/scripts/common.sh
  kurl_proxy/go.mod
Labels: type::chore

#5164 Move min-kots-version test to Playwright
  .github/actions/kots-e2e/action.yml
  .github/workflows/build-test.yaml
  dev/patches/kotsadm-up.yaml
  e2e/Makefile
  e2e/e2e_test.go
  e2e/inventory/inventory.go
  e2e/playwright/package-lock.json
  e2e/playwright/package.json
  e2e/playwright/tests/@backup-and-restore/test.spec.ts
  e2e/playwright/tests/@config-validation/test.spec.ts
  e2e/playwright/tests/@min-kots-version-airgap/constants.ts
  e2e/playwright/tests/@min-kots-version-airgap/license.yaml
  e2e/playwright/tests/@min-kots-version-airgap/test.spec.ts
  e2e/playwright/tests/@min-kots-version-online/constants.ts
  e2e/playwright/tests/@min-kots-version-online/license.yaml
  e2e/playwright/tests/@min-kots-version-online/test.spec.ts
  e2e/playwright/tests/@multi-app-install/test.spec.ts
  e2e/playwright/tests/@no-required-config/test.spec.ts
  e2e/playwright/tests/@smoke-test/test.spec.ts
  e2e/playwright/tests/shared/airgap.ts
  e2e/playwright/tests/shared/api.ts
  e2e/playwright/tests/shared/app.ts
  e2e/playwright/tests/shared/index.ts
  e2e/playwright/tests/shared/login.ts
  e2e/playwright/tests/shared/online.ts
  e2e/playwright/tests/shared/upload-license.ts
  e2e/playwright/tsconfig.json
  web/src/components/UploadAirgapBundle.jsx
  web/src/components/apps/AppVersionHistory.tsx
  web/src/components/shared/AirgapRegistrySettings.tsx
  web/src/components/shared/MountAware.jsx
  web/src/components/shared/SubNavBar/SubNavBar.jsx
  web/src/components/shared/forms/InputField.jsx
  web/src/features/AppVersionHistory/AppVersionHistoryRow.tsx
  web/src/features/Dashboard/components/AppStatus.tsx
  web/src/features/Dashboard/components/Dashboard.tsx
Labels: type::chore

#5166 chore(ci): move target-kots-version test to playwright
  .github/workflows/build-test.yaml
  e2e/e2e_test.go
  e2e/inventory/inventory.go
  e2e/playwright/tests/@min-kots-version-online/test.spec.ts
  e2e/playwright/tests/@target-kots-version-airgap/constants.ts
  e2e/playwright/tests/@target-kots-version-airgap/license.yaml
  e2e/playwright/tests/@target-kots-version-airgap/test.spec.ts
  e2e/playwright/tests/@target-kots-version-online/constants.ts
  e2e/playwright/tests/@target-kots-version-online/license.yaml
  e2e/playwright/tests/@target-kots-version-online/test.spec.ts
  e2e/playwright/tests/shared/api.ts
  web/src/components/shared/Footer.jsx
Labels: type::chore

#5165 migrate validate gitops from testim to playwright
  .github/actions/kots-e2e/action.yml
  .github/workflows/build-test.yaml
  Makefile
  e2e/Makefile
  e2e/playwright/tests/@gitops/gitops.yaml
  e2e/playwright/tests/@gitops/test.spec.ts
  web/src/features/Gitops/utils.js
Labels: type::chore

#5157 Update README.md
  README.md
Labels: type::chore

#5169 move version history pagination test to playwright
  .github/workflows/build-test.yaml
  e2e/playwright/tests/@gitops/test.spec.ts
  e2e/playwright/tests/@version-history-pagination/constants.ts
  e2e/playwright/tests/@version-history-pagination/test.spec.ts
  e2e/playwright/tests/@version-history-pagination/version-history-pagination.yaml
  web/src/components/shared/Pager.jsx
Labels: type::chore

#5173 Move existing-online-install-minimal regression test to playwright
  e2e/playwright/regression/@existing-online-install-minimal/constants.ts
  e2e/playwright/regression/@existing-online-install-minimal/license.yaml
  e2e/playwright/regression/@existing-online-install-minimal/test.spec.ts
  e2e/playwright/regression/shared/api.ts
  e2e/playwright/regression/shared/index.ts
  e2e/playwright/regression/shared/license.ts
  e2e/playwright/regression/shared/preflights.ts
  e2e/playwright/regression/shared/version-history.ts
Labels: type::chore

#5174 Fix flakiness in playwright regression tests
  e2e/playwright/regression/@existing-online-install-admin/test.spec.ts
  e2e/playwright/regression/@existing-online-install-minimal/test.spec.ts
  e2e/playwright/regression/shared/registry-settings.ts
  e2e/playwright/regression/shared/version-history.ts
  e2e/playwright/regression/shared/view-files.ts
  e2e/playwright/tests/@min-kots-version-online/test.spec.ts
  e2e/playwright/tests/@range-kots-version-online/test.spec.ts
Labels: type::chore

#5176 Move checking for updates earlier in the regression test
  e2e/playwright/regression/@existing-online-install-admin/test.spec.ts
  e2e/playwright/regression/@existing-online-install-minimal/test.spec.ts
  e2e/playwright/regression/shared/registry-settings.ts
  e2e/playwright/regression/shared/version-history.ts
Labels: type::chore

#5168 chore(ci): move support-bundle test to playwright
  .github/dependabot.yml
  .github/workflows/build-test.yaml
  e2e/inventory/inventory.go
  e2e/playwright/package-lock.json
  e2e/playwright/package.json
  e2e/playwright/regression/shared/cli.ts
  e2e/playwright/tests/@backup-and-restore/test.spec.ts
  e2e/playwright/tests/@gitops/test.spec.ts
  e2e/playwright/tests/@support-bundle/license.yaml
  e2e/playwright/tests/@support-bundle/test.spec.ts
  e2e/playwright/tests/@version-history-pagination/test.spec.ts
  pkg/handlers/troubleshoot.go
  web/src/components/shared/CodeSnippet.jsx
  web/src/components/shared/Loader.tsx
  web/src/components/shared/Toast.tsx
  web/src/components/troubleshoot/AnalyzerFileTree.jsx
  web/src/components/troubleshoot/AnalyzerInsights.jsx
  web/src/components/troubleshoot/AnalyzerRedactorReport.jsx
  web/src/components/troubleshoot/AnalyzerRedactorReportRow.jsx
  web/src/components/troubleshoot/ConfigureRedactorsModal.jsx
  web/src/components/troubleshoot/GenerateSupportBundle.jsx
  web/src/components/troubleshoot/GenerateSupportBundleModal.tsx
  web/src/components/troubleshoot/SupportBundleAnalysis.jsx
  web/src/components/troubleshoot/SupportBundleList.tsx
  web/src/components/troubleshoot/SupportBundleRow.tsx
Labels: type::chore

#5179 Updating regression tests config can take more than 5 seconds
  e2e/playwright/regression/shared/config.ts
Labels: type::chore

#5181 Fix sequences in regression tests
  e2e/playwright/regression/@existing-online-install-admin/test.spec.ts
  e2e/playwright/regression/@existing-online-install-minimal/test.spec.ts
  e2e/playwright/regression/shared/license.ts
  e2e/playwright/regression/shared/version-history.ts
Labels: type::chore

#5182 Add snapshots RBAC before validating dashboard
  e2e/playwright/regression/@existing-online-install-minimal/test.spec.ts
Labels: type::chore

#5175 chore(ci): move smoke-test-airgap test to playwright
  .github/workflows/build-test.yaml
  e2e/e2e_test.go
  e2e/inventory/inventory.go
  e2e/playwright/playwright.go
  e2e/playwright/tests/@smoke-test-airgap/constants.ts
  e2e/playwright/tests/@smoke-test-airgap/license.yaml
  e2e/playwright/tests/@smoke-test-airgap/test.spec.ts
  e2e/playwright/tests/@smoke-test-online/license.yaml
  e2e/playwright/tests/@smoke-test-online/test.spec.ts
  e2e/playwright/tests/shared/filetree.ts
  e2e/playwright/tests/shared/index.ts
  e2e/playwright/tests/shared/login.ts
  web/src/components/apps/AppVersionHistory.tsx
  web/src/components/config_render/ConfigGroup.jsx
  web/src/components/config_render/ConfigInput.jsx
  web/src/features/AppConfig/components/AppConfig.tsx
  web/src/features/AppVersionHistory/AppVersionHistoryRow.tsx
  web/src/features/Dashboard/components/DashboardVersionCard.tsx
Labels: type::chore

#5185 Fix validating release notes in regression tests
  e2e/playwright/regression/@existing-online-install-admin/test.spec.ts
  e2e/playwright/regression/@existing-online-install-minimal/test.spec.ts
  e2e/playwright/regression/shared/version-history.ts
Labels: type::chore

#5186 Fix expected restore sequence for regression tests
  e2e/playwright/regression/@existing-online-install-minimal/test.spec.ts
Labels: type::chore

#5187 Fix validating deploy logs for regression tests
  e2e/playwright/regression/shared/version-history.ts
Labels: type::chore

#5188 Fix 3rd row index in regression tests
  e2e/playwright/regression/shared/version-history.ts
Labels: type::chore

#5189 Fix checking version history rows for regression tests
  e2e/playwright/regression/shared/version-history.ts
Labels: type::chore

#5193 fix flaky airgap smoke test
  e2e/playwright/tests/@smoke-test-airgap/test.spec.ts
  e2e/playwright/tests/@version-history-pagination/test.spec.ts
Labels: type::chore

#5192 feat(ec): add env vars for custom domains
  cmd/kots/cli/install.go
  integration/replicated/pull_test.go
  pkg/base/rewrite.go
  pkg/docker/registry/registry.go
  pkg/docker/registry/registry_test.go
  pkg/handlers/embedded_cluster_node_join_command_test.go
  pkg/handlers/platform_license.go
  pkg/image/online.go
  pkg/kotsutil/kots_test.go
  pkg/metrics/install.go
  pkg/midstream/write.go
  pkg/pull/pull.go
  pkg/registry/troubleshoot.go
  pkg/replicatedapp/upstream.go
  pkg/replicatedapp/upstream_test.go
  pkg/template/config_context.go
  pkg/template/config_context_test.go
  pkg/template/license_context.go
  pkg/template/license_context_test.go
  pkg/upstream/replicated.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: type::feature

#5195 Disable OKE CMX tests due to DockerHub rate limits issue
  .github/actions/cmx-versions/dist/index.js
  .github/actions/cmx-versions/index.js
Labels: type::chore

#5201 update embedded cluster types
  go.mod
  go.sum
  pkg/embeddedcluster/upgrade.go
Labels: type::chore

#5204 chore: do not pin go modules
  go.mod
  go.sum
  pkg/k8sutil/portforward_test.go
Labels: type::chore

#5190 Remove the hard coding of the cosign release [sc-77445]
  .github/workflows/release.yaml
Labels: type::chore

#5206 Running e2e in more current and relevant kind versions
  .github/workflows/build-test.yaml
Labels: type::chore

#5211 Fix workspace cleanup
  .github/workflows/e2e-workspace-cleanup.yaml
Labels: type::chore

#5216 info log where we're downloading the kots binary from
  pkg/replicatedapp/embeddedcluster.go
Labels: type::chore

#5156 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  migrations/Makefile
  pkg/image/constants.go
  pkg/kotsadm/minio.go
Labels: automated-pr, images, type::security

#5213 Move existing-online-install-minimal PR test to Playwright
  .github/actions/generate-support-bundle/action.yml
  .github/actions/kots-e2e/action.yml
  .github/workflows/build-test.yaml
  cmd/kots/cli/install.go
  e2e/Makefile
  e2e/README.md
  e2e/e2e_test.go
  e2e/inventory/inventory.go
  e2e/inventory/test.go
  e2e/kots/kots.go
  e2e/playwright/playwright.go
  e2e/playwright/regression/@existing-online-install-minimal/license.yaml
  e2e/playwright/regression/@existing-online-install-minimal/test.spec.ts
  e2e/playwright/shared-core/support-bundle.ts
  e2e/playwright/tests/@change-license/test.spec.ts
  e2e/playwright/tests/@version-history-pagination/test.spec.ts
  e2e/scripts/deps.sh
  e2e/testim/client.go
  e2e/testim/client_test.go
  e2e/testim/run.go
  pkg/kotsadm/objects/kotsadm_objects.go
Labels: type::chore

#5221 Wait for Velero in kurl-airgap-install regression test
  e2e/playwright/regression/@embedded-airgapped-install/test.spec.ts
Labels: type::chore

#5220 Use registry service cluster IP for PR regression tests
  .github/actions/kots-e2e/action.yml
  e2e/inventory/inventory.go
  e2e/playwright/regression/shared/snapshots.ts
  web/src/components/snapshots/SnapshotSchedule.jsx
Labels: type::chore

#5223 Use domain provided by EC rather than license endpoint
  pkg/embeddedcluster/monitor.go
  pkg/embeddedcluster/upgrade.go
  pkg/handlers/troubleshoot.go
  pkg/handlers/update.go
  pkg/metrics/install.go
  pkg/operator/operator.go
  pkg/pull/pull.go
  pkg/replicatedapp/api.go
  pkg/replicatedapp/embeddedcluster.go
  pkg/replicatedapp/upstream.go
  pkg/replicatedapp/upstream_test.go
  pkg/reporting/app_online.go
  pkg/reporting/preflight_online.go
  pkg/template/license_context.go
  pkg/upgradeservice/deploy/deploy.go
  pkg/upstream/replicated.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: type::feature

#5226 adds new image scanning process
  .github/workflows/daily-container-scans.yml
  .github/workflows/scan-container-image.yml
Labels: type::chore

#5228 Ability to push kots binary to ttl.sh
  Makefile
Labels: type::chore

#5227 Ability to update custom domains in EC installs
  pkg/docker/registry/registry.go
  pkg/docker/registry/registry_test.go
  pkg/replicatedapp/api_test.go
  pkg/replicatedapp/upstream.go
  pkg/upstream/replicated.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: type::feature

#5233 Various tests improvements
  .github/workflows/build-test.yaml
  e2e/playwright/regression/@embedded-airgapped-install/test.spec.ts
  e2e/playwright/regression/@embedded-online-install/test.spec.ts
  e2e/playwright/regression/shared/cluster-management.ts
  pkg/replicatedapp/api_test.go
Labels: type::chore

#5239 update golang-jwt/jwt
  go.mod
  go.sum
  pkg/session/session.go
Labels: type::chore

#5240 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#5241 Overwrite existing files when untarring
  integration/replicated/generate.go
  integration/replicated/pull_test.go
  integration/upload/generate.go
  pkg/apparchive/app.go
  pkg/apparchive/helm-v1beta1_test.go
  pkg/download/download.go
  pkg/embeddedcluster/upgrade.go
  pkg/handlers/download.go
  pkg/image/airgap.go
  pkg/operator/client/client.go
  pkg/operator/client/deploy.go
  pkg/operator/client/deploy_test.go
  pkg/pull/archive.go
  pkg/store/kotsstore/version_store.go
  pkg/supportbundle/backup.go
  pkg/supportbundle/filetree.go
  pkg/supportbundle/supportbundle.go
  pkg/upload/archive.go
  pkg/util/tar.go
Labels: type::bug, bug::normal

#5234 return to using the latest EKS version in CI
  .github/actions/cmx-versions/dist/index.js
  .github/actions/cmx-versions/index.js
  .github/actions/copy-assets/go.mod
  .github/workflows/build-test.yaml
Labels: type::chore

#5238 include any readable string in the error message when failing to decompress a tarball pulled from the web
  pkg/pull/pull.go
  pkg/upstream/replicated.go
  pkg/upstream/replicated_test.go
  pkg/util/caching-reader.go
  pkg/util/caching-reader_test.go
  pkg/util/extract.go
  pkg/util/extract_test.go
Labels: type::chore

#5243 Fix support-bundle test flakiness
  e2e/playwright/shared-core/support-bundle.ts
Labels: type::chore

#5246 Reporting for multi-node EC installations
  pkg/api/reporting/types/types.go
  pkg/apiserver/server.go
  pkg/embeddedcluster/node.go
  pkg/embeddedcluster/nodes.go
  pkg/embeddedcluster/types/types.go
  pkg/informers/informers.go
  pkg/operator/operator.go
  pkg/reporting/app.go
  pkg/reporting/app_airgap.go
  pkg/reporting/instance_report.go
  pkg/reporting/report_test.go
  pkg/reporting/util.go
  pkg/supportbundle/backup.go
  pkg/watchers/watchers.go
  web/src/components/apps/EmbeddedClusterManagement.tsx
Labels: type::feature

#5245 remove unused npm imports
  web/package.json
  web/yarn.lock
Labels: type::chore

#5247 Chore - refactor image scanning process
  .github/workflows/daily-image-scans.yml
  .github/workflows/scan-container-image.yml
  .github/workflows/scan-image-grype.yml
Labels: type::chore
