Repository replicatedhq/kots, pull requests merged in 2025-05, with the labels that each got.

#5305 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  migrations/Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#5310 Automated KOTS Image Dependency Tag Update
  .image.env
  migrations/Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#5312 chore: fix stack trace
  pkg/tasks/tasks.go
  pkg/upgradeservice/deploy/deploy.go
Labels: type::chore

#5314 Use .tgz instead of .tar.gz for join instructions
  cmd/kots/cli/get-joincommand_test.go
  pkg/embeddedcluster/node_join.go
  pkg/embeddedcluster/node_join_test.go
Labels: type::chore

#5315 fix: use retryable http client
  go.mod
  go.sum
  pkg/embeddedcluster/upgrade.go
  pkg/handlers/troubleshoot.go
  pkg/handlers/update.go
  pkg/kotsadmlicense/platform_license.go
  pkg/metrics/install.go
  pkg/replicatedapp/api.go
  pkg/replicatedapp/embeddedcluster.go
  pkg/replicatedapp/upstream.go
  pkg/reporting/app_online.go
  pkg/reporting/preflight_online.go
  pkg/reporting/util.go
  pkg/reporting/util_test.go
  pkg/upstream/replicated.go
  pkg/upstream/upgrade.go
  pkg/util/http.go
  pkg/util/request.go
Labels: type::bug, bug::normal

#5317 update upgrade task status timestamp safely
  pkg/tasks/tasks.go
Labels: type::bug, bug::normal

#5321 Surface embedded cluster upgrade failures on panics
  pkg/upgradeservice/deploy/deploy.go
Labels: type::bug, bug::normal

#5313 feat(ec): do not allow upgrading more than 1 k8s minor
  pkg/upgradeservice/bootstrap.go
  pkg/upgradeservice/bootstrap_test.go
Labels: type::feature

#5322 Automated KOTS Image Dependency Tag Update
  .image.env
  migrations/Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#5327 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#5329 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#5330 feat(ec): HostCABundlePath in RuntimeConfigSpec for improved CA support
  go.mod
  go.sum
Labels: type::feature

#5344 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security
