Repository replicatedhq/kots, pull requests merged in 2025-01, with the labels that each got.

#5075 Add --tolerations option to kots cli
  .github/workflows/build-test.yaml
  cmd/kots/cli/install.go
  cmd/kots/cli/install_inpackage_test.go
  pkg/kotsadm/objects/distribution_objects.go
  pkg/kotsadm/objects/kotsadm_objects.go
  pkg/kotsadm/objects/minio_objects.go
  pkg/kotsadm/objects/rqlite_objects.go
  pkg/kotsadm/types/deployoptions.go
Labels: type::feature

#5076 improve usage strings for additional annotations, labels, and tolerations flags
  cmd/kots/cli/install.go
Labels: type::chore

#5063 chore(local-dev): fix backups in local dev
  deploy/kurl/kotsadm/template/base/deployment/kotsadm-deployment.yaml
  deploy/kurl/kotsadm/template/base/statefulset/kotsadm-statefulset.yaml
  deploy/kurl/kotsadm/template/base/statefulset/patches/s3-migration.yaml
  deploy/melange.yaml.tmpl
  dev/dockerfiles/kotsadm/Dockerfile.ttlsh
  dev/patches/kotsadm-up.yaml
  pkg/kotsadm/objects/kotsadm_objects.go
  pkg/kotsadm/updates.go
  pkg/s3/s3.go
  pkg/snapshot/filesystem_minio.go
Labels: type::chore

#5077 [chore] update config types link
  web/src/components/config_render/ConfigGroup.jsx
Labels: type::chore

#5066 chore(velero): bump velero client to latest 1.15.0
  go.mod
  go.sum
  pkg/handlers/handlers.go
  pkg/handlers/snapshot_logs.go
  pkg/informers/informers.go
  pkg/k8sutil/clientset.go
  pkg/kotsadm/minio.go
  pkg/kotsadmsnapshot/backup.go
  pkg/kotsadmsnapshot/backup_test.go
  pkg/kotsadmsnapshot/download.go
  pkg/kotsadmsnapshot/k8sclient/k8sclient.go
  pkg/kotsadmsnapshot/restore.go
  pkg/kotsadmsnapshot/snapshot.go
  pkg/kotsadmsnapshot/veleroclient/veleroclient.go
  pkg/kotsutil/kots_test.go
  pkg/reporting/app.go
  pkg/snapshot/backup.go
  pkg/snapshot/filesystem_lvp.go
  pkg/snapshot/restore.go
  pkg/snapshot/snapshot.go
  pkg/snapshot/store.go
  pkg/snapshot/store_test.go
  pkg/snapshot/velero.go
  pkg/store/kotsstore/kots_store.go
  pkg/upgradeservice/handlers/handlers.go
Labels: type::chore

#5083 update the velero backup annotation when updating kotsadm
  pkg/kotsadm/objects/kotsadm_objects.go
Labels: type::bug, bug::normal

#5085 fix: update spec with new scripts dir when updating kotsadm
  pkg/kotsadm/objects/kotsadm_objects.go
  pkg/kotsadm/objects/kotsadm_objects_test.go
Labels: type::bug, bug::normal

#5089 alternate config navbar fix
  web/src/features/AppConfig/components/AppConfig.tsx
Labels: type::bug, bug::normal

#5087 return information about combined backup on backup page
  pkg/handlers/backup.go
  pkg/kotsadmsnapshot/backup.go
Labels: type::feature

#5094 improve comments for the app config sidebar logic and backup api
  pkg/handlers/backup.go
  web/src/features/AppConfig/components/AppConfig.tsx
Labels: type::chore

#5095 update cosign to the latest v1 release, v1.13.6
  .github/workflows/release.yaml
Labels: type::chore

#5070 Miawong/sc 116932/improved disaster recovery for ec ux
  e2e/playwright/tests/@smoke-test/test.spec.ts
  web/src/components/snapshots/SnapshotDetails.jsx
  web/src/components/snapshots/SnapshotRow.jsx
  web/src/scss/utilities/base.scss
Labels: type::feature

#5006 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  migrations/Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#5100 feat(ec): migration from v1 to v2
  pkg/embeddedcluster/upgrade.go
  pkg/embeddedcluster/util.go
  pkg/reporting/distribution.go
  pkg/upgradeservice/deploy/deploy.go
Labels: type::feature

#5109 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#5046 feat: allow migrate from HelmChart v1beta1 to v1beta2 if Helm --take-ownership is set
  dev/dockerfiles/kotsadm/Dockerfile.local
  pkg/pull/pull.go
Labels: type::feature

#5110 Push EC manager binary in airgap bundle to registry
  pkg/embeddedcluster/util_test.go
  pkg/image/airgap_test.go
  pkg/tests/pull/cases/airgap/upstream/userdata/installation.yaml
  pkg/tests/pull/cases/airgap/wantResults/kotsKinds/userdata/installation.yaml
  pkg/tests/pull/cases/airgap/wantResults/upstream/userdata/installation.yaml
  pkg/upstream/fetch.go
Labels: type::feature

#5111 feat(ec): migration from v1 to v2 - fixes
  go.mod
  go.sum
  pkg/embeddedcluster/upgrade.go
  pkg/operator/operator.go
  web/src/components/modals/UpgradeStatusModal.tsx
  web/src/utilities/utilities.js
Labels: type::feature

#5113 fix(ui): missing pre snapshot scripts show more button
  web/src/components/snapshots/SnapshotDetails.jsx
Labels: type::bug, bug::normal

#5114 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#5112 chore: remove unnecessary concurrency
  pkg/apiserver/server.go
  pkg/handlers/debug.go
  pkg/handlers/deploy_ec2.go
  pkg/handlers/handlers.go
  pkg/handlers/websocket.go
  pkg/plan/app.go
  pkg/plan/cluster.go
  pkg/plan/extensions.go
  pkg/plan/manager.go
  pkg/plan/manager_test.go
  pkg/plan/plan.go
  pkg/websocket/upgrade.go
  pkg/websocket/websocket.go
Labels: type::chore

#5120 chore: Only collect the latest kURL k8s-audit API server log
  pkg/supportbundle/staticspecs/kurlspec.yaml
Labels: type::chore

#5123 EC upgrades without a manager
  migrations/tables/plan.yaml
  pkg/apiserver/server.go
  pkg/embeddedcluster/util_test.go
  pkg/handlers/debug.go
  pkg/handlers/deploy_ec2.go
  pkg/handlers/handlers.go
  pkg/handlers/handlers_test.go
  pkg/handlers/interface.go
  pkg/handlers/metadata.go
  pkg/handlers/mock/mock.go
  pkg/handlers/upgrade_service.go
  pkg/handlers/websocket.go
  pkg/image/airgap_test.go
  pkg/kotsutil/kots.go
  pkg/plan/app.go
  pkg/plan/cluster.go
  pkg/plan/extensions.go
  pkg/plan/manager.go
  pkg/plan/manager_test.go
  pkg/plan/plan.go
  pkg/plan/types/types.go
  pkg/plan/util.go
  pkg/store/kotsstore/plan_store.go
  pkg/store/mock/mock.go
  pkg/store/store_interface.go
  pkg/tests/pull/cases/airgap/upstream/userdata/installation.yaml
  pkg/tests/pull/cases/airgap/wantResults/kotsKinds/userdata/installation.yaml
  pkg/tests/pull/cases/airgap/wantResults/upstream/userdata/installation.yaml
  pkg/upgradeservice/bootstrap.go
  pkg/upgradeservice/deploy/deploy_ec2.go
  pkg/upgradeservice/handlers/deploy_ec2.go
  pkg/upgradeservice/handlers/handlers.go
  pkg/upgradeservice/handlers/info.go
  pkg/upgradeservice/handlers/interface.go
  pkg/upgradeservice/plan/plan.go
  pkg/upgradeservice/types/types.go
  pkg/upstream/fetch.go
  pkg/util/util.go
  pkg/websocket/types/types.go
  pkg/websocket/upgrade.go
  pkg/websocket/websocket.go
  web/src/Root.tsx
  web/src/components/DebugInfo.jsx
  web/src/components/apps/AppVersionHistory.tsx
  web/src/components/modals/UpgradeStatusModal.tsx
  web/src/components/upgrade_service/ConfirmAndDeploy.tsx
  web/src/components/upgrade_service/UpgradeService.tsx
  web/src/components/upgrade_service/hooks/getUpgradeInfo.tsx
  web/src/components/upgrade_service/hooks/postDeployAppVersion.tsx
  web/src/types/index.ts
Labels: type::feature

#5125 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#5122 quote the image name in image check failure errors to make it clear it is empty
  pkg/image/online.go
Labels: type::chore
