Repository replicatedhq/kots, pull requests merged in 2025-07, with the labels that each got.

#5353 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  migrations/Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#5374 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#5390 chore(ci): update to go 1.24.4
  .github/actions/copy-assets/Dockerfile
  .github/actions/copy-assets/go.mod
  dev/dockerfiles/kotsadm/Dockerfile.local
  dev/dockerfiles/kurl-proxy/Dockerfile.local
  dev/scripts/common.sh
  go.mod
  kurl_proxy/go.mod
Labels: type::chore

#5411 chore(ci): consolidate deps for e2e validate tests
  .github/workflows/build-test.yaml
Labels: type::chore

#5409 Fix skopeo copy flakiness in CI
  .github/workflows/build-test.yaml
Labels: type::chore

#5412 chore(ci): fix test flake - slow test
  e2e/playwright/tests/@no-required-config/test.spec.ts
Labels: type::chore

#5364 allow updating service account token
  pkg/handlers/handlers.go
  pkg/handlers/handlers_test.go
  pkg/handlers/interface.go
  pkg/handlers/mock/mock.go
  pkg/handlers/serviceaccount.go
  pkg/kotsadmlicense/license.go
  pkg/kotsadmlicense/serviceaccount.go
  pkg/kotsadmlicense/serviceaccount_test.go
  pkg/kotsutil/kots.go
  pkg/util/auth.go
  web/src/components/apps/AppLicense.tsx
  web/src/features/Dashboard/components/DashboardLicenseCard.tsx
  web/src/utilities/utilities.js
Labels: type::feature

#5363 lint CONTRIBUTING.md
  CONTRIBUTING.md
Labels: type::chore

#5422 chore(web): remove storybook
  web/.storybook/main.js
  web/.storybook/preview.js
  web/babel.config.js
  web/package.json
  web/src/stories/AutomaticUpdatesModal.stories.tsx
  web/src/stories/BackupRestoreModal.stories.tsx
  web/src/stories/ChangePasswordModal.stories.tsx
  web/src/stories/CodeSnippet.stories.tsx
  web/src/stories/ConfigureRedactorsModal.stories.tsx
  web/src/stories/DeleteRedactorModal.stories.tsx
  web/src/stories/DeleteSnapshotModal.stories.tsx
  web/src/stories/DeployWarningModal.stories.tsx
  web/src/stories/ErrorModal.stories.tsx
  web/src/stories/Icons.stories.tsx
  web/src/stories/RestoreSnapshotModal.stories.tsx
  web/src/stories/ShowAllModal.stories.tsx
  web/src/stories/ShowDetailsModal.stories.tsx
  web/src/stories/ShowLogsModal.stories.tsx
  web/src/stories/SkipPrelightsModal.stories.tsx
  web/src/stories/SnapshotDifferencesModal.stories.tsx
  web/src/stories/Toast.stories.tsx
  web/src/stories/UploadSupportBundle.stories.tsx
  web/src/stories/ViewSnapshotLogsModal.stories.tsx
  web/yarn.lock
Labels: type::chore

#5435 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#5437 feat: update embedded cluster kinds
  go.mod
  go.sum
Labels: type::feature
