Repository replicatedhq/kots, pull requests merged in 2025-02, with the labels that each got.

#5128 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  migrations/Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#5134 Fix image deps slack notification
  .github/workflows/image-deps-updater.yaml
Labels: type::chore

#5135 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#5136 fix updating image deps
  .image.env
  Makefile
  cmd/imagedeps/image-spec
  cmd/imagedeps/main_test.go
  cmd/imagedeps/testdata/lvp/.image.env
  cmd/imagedeps/testdata/lvp/constants.go
  cmd/imagedeps/testdata/lvp/input-spec
  pkg/image/constants.go
Labels: type::chore

#5139 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#5140 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#5142 Surface upgrade service errors to the UI
  pkg/embeddedcluster/upgrade.go
  pkg/upgradeservice/process.go
  web/src/components/apps/AvailableUpdatesComponent.tsx
Labels: type::feature, type::improvement

#5143 fix: pull application metadata from custom domain
  cmd/kots/cli/install.go
  pkg/pull/pull.go
  pkg/replicatedapp/api.go
Labels: type::bug, bug::normal

#5149 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#5150 update go to 1.24+
  .github/workflows/build-test.yaml
  .github/workflows/release.yaml
  cmd/kots/cli/backup.go
  cmd/kots/cli/download.go
  cmd/kots/cli/install.go
  cmd/kots/cli/restore.go
  cmd/kots/cli/upload.go
  cmd/kots/cli/upstream-download.go
  cmd/kots/cli/upstream-upgrade.go
  cmd/kots/cli/velero.go
  go.mod
  pkg/print/config.go
  pkg/snapshot/backup.go
  pkg/snapshot/restore.go
  pkg/upstream/upgrade.go
Labels: type::chore
