Repository replicatedhq/kots, pull requests merged in 2025-09, with the labels that each got.

#5521 chore(e2e): address flakiness in deployment check
  e2e/playwright/regression/shared/version-history.ts
Labels: type::chore

#5517 chore(deps): upgrade jest
  web/jest.config.js
  web/package.json
  web/src/components/upgrade_service/UpgradeService.test.tsx
  web/src/features/App/api/getApps.test.jsx
  web/src/jest-setup.ts
  web/yarn.lock
Labels: type::chore

#5526 fix(e2e): regression test flakiness
  e2e/playwright/regression/@embedded-airgapped-install/test.spec.ts
  e2e/playwright/regression/shared/version-history.ts
Labels: type::chore

#5541 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#5550 chore(ci): fix regression test flake
  e2e/playwright/regression/shared/version-history.ts
  pkg/operator/operator.go
  pkg/version/version.go
Labels: type::chore

#5552 chore(ci): fix regression test flakes
  e2e/playwright/regression/shared/version-history.ts
  pkg/kotsadmsnapshot/backup.go
  pkg/kotsadmsnapshot/restore.go
  pkg/operator/operator.go
  pkg/snapshot/backup.go
  pkg/snapshot/restore.go
  web/src/components/snapshots/AppSnapshotRestore.jsx
  web/src/components/snapshots/SnapshotRestore.jsx
  web/src/scss/utilities/base.scss
  web/src/utilities/utilities.js
Labels: type::chore

#5553 Include channel ID and sequence in get versions command
  cmd/kots/cli/get-versions.go
  pkg/print/versions.go
Labels: type::feature

#5562 New hidden KOTS command for V3 EC to sync license, download update, update config and deploy in a single operation
  .github/workflows/build-test.yaml
  cmd/kots/cli/deploy.go
  cmd/kots/cli/root.go
  e2e/scripts/deps.sh
  go.mod
  pkg/airgap/update.go
  pkg/airgap/update_test.go
  pkg/handlers/download.go
  pkg/handlers/handlers.go
  pkg/handlers/handlers_test.go
  pkg/handlers/interface.go
  pkg/handlers/mock/mock.go
  pkg/handlers/update.go
  pkg/kotsadmupstream/upstream.go
  pkg/store/mock/mock.go
  pkg/update/required.go
  pkg/update/required_test.go
  pkg/upstream/upgrade.go
Labels: type::feature

#5573 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#5586 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#5590 chore: remove cpu resource limits from k8s objects
  .github/workflows/build-test.yaml
  deploy/kurl/kotsadm/template/base/deployment/kotsadm-deployment.yaml
  deploy/kurl/kotsadm/template/base/kurl-proxy/tmpl-deployment.yaml
  deploy/kurl/kotsadm/template/base/rqlite.yaml
  deploy/kurl/kotsadm/template/base/statefulset/kotsadm-statefulset.yaml
  deploy/kurl/kotsadm/template/base/statefulset/patches/s3-migration.yaml
  dev/manifests/kotsadm/deployment.yaml
  dev/manifests/kotsadm/rqlite.yaml
  pkg/identity/deploy/deploy.go
  pkg/kotsadm/objects/kotsadm_objects.go
  pkg/kotsadm/objects/minio_objects.go
  pkg/kotsadm/objects/minio_objects_test.go
  pkg/kotsadm/objects/rqlite_objects.go
  pkg/s3/s3.go
  pkg/snapshot/filesystem_minio.go
Labels: type::chore

#5591 fix(ci): use bitnamilegacy for regression tests
  e2e/playwright/regression/@embedded-online-install/constants.ts
  e2e/playwright/regression/@embedded-online-install/license.yaml
  e2e/playwright/regression/@existing-online-install-admin/constants.ts
  e2e/playwright/regression/@existing-online-install-admin/license.yaml
  e2e/playwright/regression/@existing-online-install-minimal/constants.ts
  e2e/playwright/regression/@existing-online-install-minimal/license.yaml
  e2e/playwright/regression/@existing-online-upgrade-admin/constants.ts
  e2e/playwright/regression/@existing-online-upgrade-admin/license.yaml
  e2e/playwright/regression/@existing-online-upgrade-minimal/constants.ts
  e2e/playwright/regression/@existing-online-upgrade-minimal/license.yaml
Labels: type::chore

#5593 chore(deps): bump the security group across 1 directory with 4 updates
  web/jest.config.js
  web/package.json
  web/yarn.lock
Labels: type::chore
