Repository replicatedhq/kots, pull requests merged in 2025-08, with the labels that each got.

#5447 chore(ci): update actions deps
  .github/actions/cmx-versions/dist/101.index.js
  .github/actions/cmx-versions/dist/index.js
  .github/actions/cmx-versions/dist/package.json
  .github/actions/cmx-versions/index.js
  .github/actions/cmx-versions/package-lock.json
  .github/actions/cmx-versions/package.json
  .github/actions/kurl-addon-kots-publisher/dist/index.js
  .github/actions/kurl-addon-kots-publisher/index.js
  .github/actions/kurl-addon-kots-publisher/package-lock.json
  .github/actions/kurl-addon-kots-publisher/package.json
  .github/actions/kurl-addon-kots-publisher/publisher.js
  .github/actions/version-tag/dist/index.js
  .github/actions/version-tag/index.js
  .github/actions/version-tag/package-lock.json
  .github/actions/version-tag/package.json
Labels: type::chore

#5448 chore(ci): fix dependabot pr labels and missing built package
  .github/actions/kurl-addon-kots-publisher/dist/index.js
  .github/actions/kurl-addon-kots-publisher/dist/package.json
  .github/actions/version-tag/dist/package.json
  .github/dependabot.yml
Labels: type::chore

#5450 chore(deps): update react-router, remove react-remarkable, upgrade node
  .github/workflows/build-test.yaml
  .github/workflows/release.yaml
  dev/dockerfiles/kotsadm-web/Dockerfile.local
  dev/scripts/common.sh
  web/.nvmrc
  web/package.json
  web/src/components/PreflightRenderer.tsx
  web/src/components/config_render/ConfigCheckbox.tsx
  web/src/components/config_render/ConfigDropdown.tsx
  web/src/components/config_render/ConfigFileInput.jsx
  web/src/components/config_render/ConfigGroup.jsx
  web/src/components/config_render/ConfigInput.jsx
  web/src/components/config_render/ConfigItemTitle.jsx
  web/src/components/config_render/ConfigSelectOne.jsx
  web/src/components/config_render/ConfigTextarea.jsx
  web/src/components/shared/Markdown.tsx
  web/src/components/upgrade_service/ConfirmAndDeploy.tsx
  web/src/features/Auth/components/SecureAdminConsole.tsx
  web/tsconfig.json
  web/yarn.lock
Labels: type::chore

#5471 feat(ec-updates): don't allow updates of >1 minor kube versions
  pkg/update/required.go
  pkg/update/update.go
  pkg/update/update_test.go
  pkg/upgradeservice/bootstrap.go
  pkg/upgradeservice/bootstrap_test.go
  pkg/upstream/replicated.go
  pkg/upstream/types/types.go
  pkg/util/kube_version.go
  pkg/util/kube_version_test.go
Labels: type::feature

#5473 feat(ec-updates): don't allow updates of >1 minor kube versions for airgap
  go.mod
  go.sum
  pkg/airgap/update.go
  pkg/handlers/app.go
  pkg/handlers/upgrade_service.go
  pkg/update/required.go
  pkg/update/required_test.go
  pkg/update/update.go
Labels: type::feature

#5476 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#5503 Revert "feat(updates): hide/show demoted/un-demoted releases when updated upstream"
  migrations/tables/app_version.yaml
  pkg/api/downstream/types/types.go
  pkg/store/kotsstore/downstream_store.go
  pkg/store/kotsstore/downstream_store_test.go
  pkg/store/kotsstore/version_store.go
  pkg/store/mock/mock.go
  pkg/store/store_interface.go
  pkg/updatechecker/updatechecker.go
  pkg/updatechecker/updatechecker_test.go
  web/src/components/apps/AppVersionHistory.tsx
  web/src/types/index.ts
Labels: type::bug, bug::normal

#5505 feat(updates): hide/show demoted/un-demoted releases when updated upstream
  migrations/tables/app_version.yaml
  pkg/store/kotsstore/downstream_store.go
  pkg/store/kotsstore/version_store.go
  pkg/store/mock/mock.go
  pkg/store/store_interface.go
  pkg/updatechecker/updatechecker.go
  pkg/updatechecker/updatechecker_test.go
Labels: type::feature

#5514 chore(deps): upgrade typescript-eslint
  .github/dependabot.yml
  web/package.json
  web/yarn.lock
Labels: type::chore

#5513 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security
