Repository replicatedhq/kots, pull requests merged in 2025-04, with the labels that each got.

#5252 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#5251 Migrate scans to reusable workflow using Grype
  .github/workflows/alpha.yaml
  .github/workflows/scan-image-grype.yml
Labels: type::chore

#5255 Remove .rli file filter for licenses
  e2e/playwright/regression/shared/license.ts
  e2e/playwright/tests/shared/upload-license.ts
  web/src/components/UploadLicenseFile.tsx
Labels: type::bug, bug::normal

#5257 Respect the EC multi-node license option
  go.mod
  go.sum
  kurl_proxy/assets/tls-warning.html
  kurl_proxy/assets/tls.html
  kurl_proxy/assets/welcome.html
  kurl_proxy/cmd/main.go
  pkg/airgap/airgap.go
  pkg/airgap/update.go
  pkg/api/handlers/types/types.go
  pkg/automation/automation.go
  pkg/embeddedcluster/upgrade.go
  pkg/handlers/app.go
  pkg/handlers/config.go
  pkg/handlers/identity.go
  pkg/handlers/license.go
  pkg/handlers/registry.go
  pkg/handlers/upload.go
  pkg/kotsadmupstream/upstream.go
  pkg/kotsutil/kots.go
  pkg/license/signature.go
  pkg/online/online.go
  pkg/operator/operator.go
  pkg/store/kotsstore/license_store.go
  pkg/store/kotsstore/version_store.go
  pkg/store/kotsstore/version_store_test.go
  pkg/store/mock/mock.go
  pkg/store/store_interface.go
  pkg/template/license_context.go
  pkg/template/license_context_test.go
  web/src/Root.tsx
  web/src/components/PreflightResultPage.tsx
  web/src/components/apps/AppLicense.tsx
  web/src/components/apps/EmbeddedClusterManagement.tsx
  web/src/features/AppConfig/components/AppConfig.tsx
  web/src/images/main_spritesheet.svg
  web/src/scss/utilities/icons.scss
  web/src/types/index.ts
Labels: type::feature

#5253 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#5260 Remove prettier
  web/.eslintrc
  web/Makefile
  web/package.json
Labels: type::chore

#5262 Fix uploading license file in regression tests
  e2e/playwright/regression/shared/license.ts
  e2e/playwright/tests/shared/upload-license.ts
Labels: type::chore

#5265 use ubuntu-latest instead of ubuntu-20.04
  .github/workflows/alpha.yaml
  .github/workflows/image-deps-updater.yaml
  .github/workflows/kurl-addon-kots-publish.yaml
  .github/workflows/kurl-addon-kots-test.yaml
  .github/workflows/regression.yaml
  .github/workflows/release.yaml
  .github/workflows/tag-helm-chart.yaml
  .github/workflows/update-kubectl.yaml
Labels: type::chore

#5266 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#5268 Fix processing config values in EC automated installs
  pkg/airgap/airgap.go
  pkg/automation/automation.go
  pkg/online/online.go
Labels: type::feature

#5267 add grype scan action. enable for 1 scan job in alpha build for testing
  .github/actions/scan-image/action.yml
  .github/workflows/alpha.yaml
  .github/workflows/daily-image-scans.yml
  .github/workflows/scan-image-grype.yml
  .grype.yaml
Labels: type::chore

#5271 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#5272 rename isEmbeddedClusterMultinodeEnabled to isEmbeddedClusterMultiNodeEnabled
  go.mod
  go.sum
  kurl_proxy/assets/tls-warning.html
  kurl_proxy/assets/tls.html
  kurl_proxy/assets/welcome.html
  kurl_proxy/cmd/main.go
  pkg/api/handlers/types/types.go
  pkg/embeddedcluster/upgrade.go
  pkg/handlers/app.go
  pkg/handlers/license.go
  pkg/kotsutil/kots.go
  pkg/license/signature.go
  pkg/store/kotsstore/version_store.go
  pkg/store/kotsstore/version_store_test.go
  pkg/template/license_context.go
  pkg/template/license_context_test.go
  web/src/Root.tsx
  web/src/components/apps/AppLicense.tsx
  web/src/components/apps/EmbeddedClusterManagement.tsx
  web/src/scss/utilities/icons.scss
  web/src/types/index.ts
Labels: type::feature

#5276 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#5275 Preserve license on automated air gapped installs
  cmd/kots/cli/install.go
  cmd/kots/cli/pull.go
  pkg/kotsadm/license.go
  pkg/kotsadm/types/deployoptions.go
  pkg/license/signature.go
  pkg/license/signature_test.go
Labels: type::feature

#5278 Add support for EC release tags
  .github/workflows/release-for-ec.yaml
Labels: type::feature

#5277 Update Dashboard.tsx
  web/src/features/Dashboard/components/Dashboard.tsx
Labels: type::chore

#5256 Prepend Kubernetes API path, if present
  pkg/k8sutil/portforward.go
Labels: type::bug, bug::normal

#5274 use EC kinds for the EC node join response, and include the app version
  go.mod
  go.sum
  pkg/handlers/embedded_cluster_node_join_command.go
  pkg/handlers/embedded_cluster_node_join_command_test.go
Labels: type::feature

#5280 add hidden 'get join-command' command for embedded-cluster
  cmd/kots/cli/get-joincommand.go
  cmd/kots/cli/get-joincommand_test.go
  cmd/kots/cli/get.go
  pkg/api/handlers/types/types.go
  pkg/embeddedcluster/roles.go
  pkg/handlers/embedded_cluster_get.go
  pkg/handlers/embedded_cluster_node_join_command.go
Labels: type::feature

#5287 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#5290 Add endpoint that returns the EC binary from the EC data directory
  .github/actions/copy-assets/Dockerfile
  dev/dockerfiles/kotsadm/Dockerfile.local
  dev/dockerfiles/kurl-proxy/Dockerfile.local
  dev/scripts/common.sh
  e2e/playwright/tests/@target-kots-version-online/test.spec.ts
  go.mod
  kurl_proxy/go.mod
  pkg/handlers/embedded_cluster_artifacts.go
  pkg/handlers/handlers.go
Labels: type::feature

#5288 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#5291 feat(multinode): online distribute artifacts on upgrade
  pkg/embeddedcluster/upgrade.go
  pkg/embeddedcluster/upgrade_test.go
  pkg/handlers/upgrade_service_test.go
  pkg/kotsutil/kots.go
  pkg/template/config_context.go
Labels: type::feature

#5293 Add endpoint that returns the EC infra images from the k0s directory
  pkg/handlers/embedded_cluster_artifacts.go
  pkg/handlers/handlers.go
  pkg/util/util.go
  web/src/features/AppConfig/components/AppConfig.tsx
Labels: type::feature

#5294 Automated KOTS Image Dependency Tag Update
  .image.env
  migrations/Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#5296 Add safe_image_name to help github better track scan findings over time
  .github/actions/scan-image/action.yml
Labels: type::chore

#5297 Remove airgap bundle flag from join command
  pkg/embeddedcluster/node_join.go
  pkg/embeddedcluster/node_join_test.go
  pkg/handlers/embedded_cluster_artifacts.go
  pkg/handlers/handlers.go
Labels: type::feature

#5304 feat(ec): update node join instructions for improved join experience
  cmd/kots/cli/get-joincommand.go
  cmd/kots/cli/get-joincommand_test.go
  cmd/kots/cli/get.go
  pkg/api/handlers/types/types.go
  pkg/embeddedcluster/node_join.go
  pkg/embeddedcluster/node_join_test.go
  pkg/handlers/embedded_cluster_node_join_command.go
  web/src/components/apps/EmbeddedClusterManagement.tsx
  web/src/components/modals/AddANodeModal.tsx
Labels: type::feature

#5301 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security
