Repository replicatedhq/kots, pull requests merged in 2025-06, with the labels that each got.

#5352 Automated KOTS Image Dependency Tag Update
  .image.env
  Makefile
  pkg/image/constants.go
Labels: automated-pr, images, type::security

#5349 chore: CVE-2024-0406 remove github.com/mholt/archiver/v3 dependency
  go.mod
  go.sum
Labels: type::security

#5355 chore(ec): update kinds
  go.mod
  go.sum
  pkg/kotsadmsnapshot/backup.go
  pkg/kotsadmsnapshot/backup_test.go
Labels: type::feature

#5368 chore(ci): fix melange build
  .github/actions/build-custom-image-with-apko/action.yml
  .github/actions/build-custom-melange-package/action.yml
  .github/actions/build-dep-image-with-apko/action.yml
  .github/dependabot.yml
  .github/workflows/build-test.yaml
  e2e/playwright/tests/@change-license/test.spec.ts
  e2e/playwright/tests/@gitops/test.spec.ts
  e2e/playwright/tests/@multi-app-backup-and-restore/test.spec.ts
  e2e/playwright/tests/@multi-app-install/test.spec.ts
Labels: type::chore
